/**
 * This software was developed and / or modified by Raytheon Company,
 * pursuant to Contract DG133W-05-CQ-1067 with the US Government.
 * 
 * U.S. EXPORT CONTROLLED TECHNICAL DATA
 * This software product contains export-restricted data whose
 * export/transfer/disclosure is restricted by U.S. law. Dissemination
 * to non-U.S. persons whether in the United States or abroad requires
 * an export license or other authorization.
 * 
 * Contractor Name:        Raytheon Company
 * Contractor Address:     6825 Pine Street, Suite 340
 *                         Mail Stop B8
 *                         Omaha, NE 68106
 *                         402.291.0100
 * 
 * See the AWIPS II Master Rights File ("Master Rights File.pdf") for
 * further licensing information.
 **/

package oasis.names.tc.ebxml.regrep.wsdl.registry.services.v4;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * 
 * A service providing SOAP endpoints for Cataloger interface.
 * 
 * 
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.6 in JDK 6 Generated
 * source version: 2.1
 * 
 */
@WebServiceClient(name = "CatalogerSOAPService", targetNamespace = "urn:oasis:names:tc:ebxml-regrep:wsdl:registry:services:4.0", wsdlLocation = "file:/common/bphillip/DataDelivery_FILES/ebXML/regrep/wsdl/1.1/regrep-server-service.wsdl")
public class CatalogerSOAPService extends Service {

    private final static URL CATALOGERSOAPSERVICE_WSDL_LOCATION;

    private final static Logger logger = Logger
            .getLogger(oasis.names.tc.ebxml.regrep.wsdl.registry.services.v4.CatalogerSOAPService.class
                    .getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = oasis.names.tc.ebxml.regrep.wsdl.registry.services.v4.CatalogerSOAPService.class
                    .getResource(".");
            url = new URL(
                    baseUrl,
                    "file:/common/bphillip/DataDelivery_FILES/ebXML/regrep/wsdl/1.1/regrep-server-service.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/common/bphillip/DataDelivery_FILES/ebXML/regrep/wsdl/1.1/regrep-server-service.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CATALOGERSOAPSERVICE_WSDL_LOCATION = url;
    }

    public CatalogerSOAPService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CatalogerSOAPService() {
        super(CATALOGERSOAPSERVICE_WSDL_LOCATION, new QName(
                "urn:oasis:names:tc:ebxml-regrep:wsdl:registry:services:4.0",
                "CatalogerSOAPService"));
    }

    /**
     * 
     * A template SOAP endpoints for ebXML RegRep Cataloger interface.
     * 
     * 
     * @return returns Cataloger
     */
    @WebEndpoint(name = "CatalogerPort")
    public Cataloger getCatalogerPort() {
        return super.getPort(new QName(
                "urn:oasis:names:tc:ebxml-regrep:wsdl:registry:services:4.0",
                "CatalogerPort"), Cataloger.class);
    }

    /**
     * 
     * A template SOAP endpoints for ebXML RegRep Cataloger interface.
     * 
     * 
     * @param features
     *            A list of {@link javax.xml.ws.WebServiceFeature} to configure
     *            on the proxy. Supported features not in the
     *            <code>features</code> parameter will have their default
     *            values.
     * @return returns Cataloger
     */
    @WebEndpoint(name = "CatalogerPort")
    public Cataloger getCatalogerPort(WebServiceFeature... features) {
        return super.getPort(new QName(
                "urn:oasis:names:tc:ebxml-regrep:wsdl:registry:services:4.0",
                "CatalogerPort"), Cataloger.class, features);
    }

}
