C MEMBER FCHKCO
C  (from old member FCFCHKCO)
C
C.....................................................................
C
C  SUBROUTINE FCHKCO CHECKS TO SEE IF ANY USER ASSIGNED CARRYOVER DATES
C   EITHER MATCH OR PRECEDE THE INITIAL FORECAST RUN DATE AND TIME, OR
C   EXCEED THE ENDING RUN DATE AND TIME.
C
C  IF A USER ASSIGNED DATE PRECEDES THE INITIAL RUN DATE, THAT DATE IS
C  REMOVED FROM THE LIST OF CARRYOVER SAVE DATES, AND THE TOTAL NUMBER
C  OF CARRYOVER DATES IS REDUCED BY THE NUMBER OF VIOLATIONS.
C
C  IF A MATCH IS FOUND, THAT DATE IS REMOVED FROM THE LIST OF
C  THE REQUESTED DATES, AND THE NUMBER OF REQUESTED DATES IS REDUCED
C  BY ONE.
C
C  INPUT -- NO INPUT NEEDED
C
C....................................................................
C
      SUBROUTINE FCHKCO
C
C.....................................................................
C
C  SUBROUTINE ORIGINALLY WRITTEN BY --
C          JOE OSTROWSKI -- HRL -- 791106
C
C.....................................................................
C
      INCLUDE 'common/fccgd1'
      INCLUDE 'common/fcary'
      INCLUDE 'common/fctim2'
      INCLUDE 'common/fctime'
      INCLUDE 'common/where'
      INCLUDE 'common/errdat'
      INCLUDE 'common/fdbug'
      INCLUDE 'common/sysbug'
      INCLUDE 'common/ionum'
C
      DIMENSION SUBRNM(2),OLDSUB(2),KDAY(20),KHR(20)
C
C    ================================= RCS keyword statements ==========
      CHARACTER*68     RCSKW1,RCSKW2
      DATA             RCSKW1,RCSKW2 /                                 '
     .$Source: /fs/hseb/ob72/rfc/ofs/src/fcst_top/RCS/fchkco.f,v $
     . $',                                                             '
     .$Id: fchkco.f,v 1.1 1995/09/17 19:08:10 dws Exp $
     . $' /
C    ===================================================================
C
      DATA COTR/4HCOTR/,COBG/4HCOBG/
      DATA SUBRNM/4HFCHK,4HCO  /
      DATA IEQ,ILT,IGT/2HEQ,2HLT,2HGT/
C
      DO 200 I=1,2
      OLDSUB(I)=OPNAME(I)
  200 OPNAME(I)=SUBRNM(I)
      IOPNUM=0
C
      IBUG=0
      IF (IFBUG(COTR).EQ.1.OR.IFBUG(COBG).EQ.1) IBUG=1
C
      IF (IBUG.GE.1) WRITE(IODBUG,600)
  600 FORMAT(23H   *** ENTER FCHKCO ***)
C
      NDAY=IDARUN
      NHR=IHRRUN
      NOUSE=0
C
      IANTE=0
      IPOST=0
C
C  ** CHECK TO SEE IF ANY USER ASSIGNED CARRYOVER DATES PRECEDE THE
C     INITIAL FORECAST RUN DATE AND TIME.
C
    1 DO 100 J=1,NCSTOR
C
      CALL FDATCK(ICDAY(J),ICHOUR(J),NDAY,NHR,ILT,IPRE)
      IF (IPRE.EQ.0) GO TO 100
C
C  ** IF ANY USER ASSIGNED CARRYOVER DATE PRECEDES THE INITIAL FORECAST
C     DATE, IGNORE THAT DATE.
C
      CALL MDYH2(ICDAY(J),ICHOUR(J),MM,MD,MY,MH,NDUMZ,NDUMDS,INPTZC)
      WRITE (IPR,1601) MM,MD,MY,MH,INPTZC
 1601 FORMAT(1H0,11X,'**WARNING** ',34HTHE USER DEFINED CARRYOVER DATE -
     * ,I2,01H/,I2,01H/,I4,01H-,I2,A4,30H - IS BEFORE THE START OF THE ,
     *      13HFORECAST RUN./23X,35HTHAT DATE IS IGNORED FOR CARRYOVER.)
      CALL WARN
C
      ICDAY(J)=0
      ICHOUR(J)=0
      IANTE=1
C
  100 CONTINUE
C
C  ** CHECK TO FIND IF ANY USER ASSIGNED CARRYOVER DATE MATCHES THE
C     INITIAL FORECAST RUN DATE AND TIME.
C
C  ** IGNORE THAT DATE IF A MATCH IS FOUND.
C
    5 DO 10 I=1,NCSTOR
      IF (ICDAY(I).EQ.0.AND.ICHOUR(I).EQ.0) GO TO 10
      CALL FDATCK(ICDAY(I),ICHOUR(I),NDAY,NHR,IEQ,ITSW)
C
      IF (ITSW.EQ.0) GO TO 10
      NOUSE=I
      GO TO 20
   10 CONTINUE
C
      GO TO 60
C
   20 CONTINUE
C
      WRITE(IPR,1600)
 1600 FORMAT(1H0,11X,'**WARNING** ',40HONE OF THE USER ASSIGNED CARRYOVE
     *R DATES,55H MATCHES THE INITIAL DATE AND TIME OF THE FORECAST RUN.
     */23X,54HNO NEW CARRYOVER WILL BE SAVED FOR THAT DATE AND TIME.)
      CALL WARN
C
      ICDAY(NOUSE)=0
      ICHOUR(NOUSE)=0
C
C ** CHECK TO SEE IF ANY USER ASSIGNED CARRYOVER DATE EXCEEDS
C    THE ENDING RUN DATE AND TIME.
C
   60 DO 65 J=1,NCSTOR
      IF (ICDAY(J).EQ.0.AND.ICHOUR(J).EQ.0) GO TO 65
C
      CALL FDATCK(ICDAY(J),ICHOUR(J),LDARUN,LHRRUN,IGT,IAFT)
      IF (IAFT.EQ.0) GO TO 65
C ** IGNORE DATE FOR SAVING CARRYOVER IF IT EXCEEDS THE END RUN DATE.
C
      CALL MDYH2(ICDAY(J),ICHOUR(J),MM,MD,MY,MH,NDUMZ,NDUMDS,INPTZC)
      WRITE(IPR,1602) MM,MD,MY,MH,INPTZC
C
 1602 FORMAT(1H0,11X,'**WARNING** ',34HTHE USER DEFINED CARRYOVER DATE -
     * ,I2,01H/,I2,01H/,I4,01H-,I2,A4,27H - IS AFTER THE END OF THE ,
     *13HFORECAST RUN./23X,35HTHAT DATE IS IGNORED FOR CARRYOVER.)
      CALL WARN
C
      ICDAY(J)=0
      ICHOUR(J)=0
      IPOST=0
   65 CONTINUE
C
C ** CHECK THAT SAVE CO HOUR IS DIVISIBLE BY MINDTC (THE MINIMUM
C    DELTA T FOR THE CARRYOVER GROUP)
C
      DO 80 I=1,NCSTOR
      ICHTMP=ICHOUR(I)
      IF(ICDAY(I).EQ.0.AND.ICHTMP.EQ.0)GO TO 80
      IF(ICHTMP.EQ.24.OR.ICHTMP.EQ.0)GO TO 80
      IF((ICHTMP/MINDTC)*MINDTC.EQ.ICHTMP)GO TO 80
C
C ** DELETE CO SAVE DATE - HOUR NOT COMPATIBLE
C
      CALL MDYH2(ICDAY(I),ICHOUR(I),MM,MD,MY,MH,NDUMZ,NDUMDS,INPTZC)
      WRITE (IPR,1603) MM,MD,MY,MH,INPTZC,MINDTC
 1603 FORMAT(1H0,11X,'**WARNING** ',34HTHE USER DEFINED CARRYOVER DATE -
     * ,I2,01H/,I2,01H/,I4,01H-,I2,A4/5X,'HAS AN INTERNAL HOUR NOT ',
     *  'DIVISIBLE BY THE MINIMUM DT FOR THE CARRYOVER GROUP (',
     *  I2,' HOURS).'/23X,35HTHAT DATE IS IGNORED FOR CARRYOVER.)
      CALL WARN
C
      ICDAY(I)=0
      ICHOUR(I)=0
C
   80 CONTINUE
C
      NT=0
C
C ** REMOVE THOSE PRECEEDING, MATCHING, EXCEEDING OR INVALID DATES.
C
      DO 30 I=1,NCSTOR
      IF (ICDAY(I).EQ.0.AND.ICHOUR(I).EQ.0) GO TO 30
C
      NT=NT+1
      KDAY(NT)=ICDAY(I)
      KHR(NT)=ICHOUR(I)
C
   30 CONTINUE
C
C
C  ** RESET THE NUMBER OF SAVE DATES (NCSTOR) AND REMOVE ANY PRECEDING
C     AND/OR MATCHING DATES.
C
      NCSTOR=NT
      IF (NCSTOR.EQ.0) GO TO 9999
      DO 40 I=1,NT
      ICDAY(I)=KDAY(I)
      ICHOUR(I)=KHR(I)
   40 CONTINUE
C
 9999 CONTINUE
C
      DO 210 I=1,2
      OPNAME(I)=OLDSUB(I)
  210 CONTINUE
C
      IF (IBUG.GE.1) WRITE(IODBUG,605)
  605 FORMAT(23H    *** EXIT FCHKCO ***)
      RETURN
      END
