#!/bin/ksh

# File name: run_pdc_pp
# This allows you to run this script from outside of ./bin
RUN_FROM_DIR=`dirname $0`

# set up SOME environment variables for WHFS applications
. $RUN_FROM_DIR/../../set_hydro_env


export CONNECTION_STRING=$JDBCURL

#get java dir
export SYS_JAVA_DIR=$($GAD_DIR/get_apps_defaults$OS_SUFFIX sys_java_dir)
export SYS_JAVA_BIN_DIR=$SYS_JAVA_DIR/bin

# set java classpath

export CLASSPATH=.:$SYS_JAVA_DIR\
:$SYS_JAVA_BIN_DIR\
:$DB_DRIVER_PATH\
:$WHFS_BIN_DIR/pdc_pp.jar

# set up an X Terminal window to write stdout and run the DamCrest 
# application using java
$SYS_JAVA_BIN_DIR/java ohd.hseb.pdc_pp.sample_data_set.PDCPreProcessorTest $CONNECTION_STRING $PDC_PP_LOG_DIR