#!/bin/ksh
# file name: run_SSHP_Databasepopulater
# Created: 12/15/2003

# This allows you to run this script from outside of ./bin
RUN_FROM_DIR=`dirname $0`

# set up SOME environment variables for WHFS applications
. $RUN_FROM_DIR/../../set_hydro_env

# set initial lid to the first command line argument passed into the script
LID_PASSED_IN=$1

export CLASSPATH=.
CLASSPATH=$CLASSPATH:$DB_DRIVER_PATH
# need to add a path to the jar file for this application
CLASSPATH=$CLASSPATH:/fs/hseb/pda/users/lix/devl/bin/Var.jar

# Java bin directory(/usr/local/java/bin)
JBINDIR=$SYS_JAVA_DIR/bin

export LID=BLUO2
export VAR_LOG_DIR=/fs/shared/home/lix/eclipse_workspace/Var

# run Databasepopulater
$JBINDIR/java ohd.hseb.sshp.var.DatabasePopulater $LID $VAR_LOG_DIR
     

