#!/bin/ksh

# File name: start_fcstservice
# Author   : Ram Varma

# This allows you to run this script from outside of ./bin
RUN_FROM_DIR=`dirname $0`

# set up SOME environment variables for WHFS
. $RUN_FROM_DIR/../../set_hydro_env

#LHVM_LOG=$LHVM_LOG_DIR/fcstservice

# set java classpath
export CLASSPATH=$DB_DRIVER_PATH
CLASSPATH=$CLASSPATH:$WHFS_BIN_DIR/fcstservice.jar

#Execute Lhvm
xterm -T "fcstservice" -iconic \
-e $SYS_JAVA_DIR/bin/java ohd.hseb.fcstservice.LhvmApplicationWindow $JDBCURL &
