#!/bin/bash
##############################################################################
# Provides a simple wrapper to the mhsAckNotify Python module allowing that module
# to be executed as a command line tool without requiring the .py extension.
#
#     SOFTWARE HISTORY
#    
#    Date            Ticket#       Engineer       Description
#    ------------    ----------    -----------    --------------------------
#    04/06/2012		 10388		   mhuang		  Initial creation
#    10/09/12        DR 13901      D. Friedman    Add logging
#    02/20/13        DR 15836      D. Friedman    Append to log
##############################################################################

# this allows you to run this script from outside of ./bin
path_to_script=`readlink -f $0`
RUN_FROM_DIR=`dirname $path_to_script`

BASE_AWIPS_DIR=`dirname $RUN_FROM_DIR`

# source the env
source ${RUN_FROM_DIR}/setup.env

# setup the environment needed to run the the Python
export LD_LIBRARY_PATH=${BASE_AWIPS_DIR}/src/lib:${PYTHON_INSTALL}/lib
export PYTHONPATH=${RUN_FROM_DIR}/src:$PYTHONPATH

# execute the Python module
_PYTHON="${PYTHON_INSTALL}/bin/python"
_MODULE="${RUN_FROM_DIR}/src/qpidNotify/mhsAckNotify.py"

log_file=${LOG_DIR:-/data/logs/fxa}/$(date -u +%Y%m%d)/mhsAckNotify
if touch "$log_file"; then
    exec >>"$log_file" 2>&1
fi

# quoting of '$@' is used to prevent command line interpretation 
$_PYTHON $_MODULE "$@"
