#!/bin/bash
##
# This software was developed and / or modified by Raytheon Company,
# pursuant to Contract DG133W-05-CQ-1067 with the US Government.
# 
# U.S. EXPORT CONTROLLED TECHNICAL DATA
# This software product contains export-restricted data whose
# export/transfer/disclosure is restricted by U.S. law. Dissemination
# to non-U.S. persons whether in the United States or abroad requires
# an export license or other authorization.
# 
# Contractor Name:        Raytheon Company
# Contractor Address:     6825 Pine Street, Suite 340
#                         Mail Stop B8
#                         Omaha, NE 68106
#                         402.291.0100
# 
# See the AWIPS II Master Rights File ("Master Rights File.pdf") for
# further licensing information.
##
##############################################################################
# Provides a simple wrapper around the UEngine Python module allowing that
# module to be executed as a command line tool without requiring the .py file
# extension. In addition, the maintenance mode flag (-m maintain) is set.
# This provides a command line interface similar to the textdb and uengine
# tools. The bulk of the functionality is provided by the UEngine.py module.
#
# Critical: the first line of this file must point to a valid AWIPS II
#           provided installation of Python.
#
#     SOFTWARE HISTORY
#    
#    Date            Ticket#       Engineer       Description
#    ------------    ----------    -----------    --------------------------
#    11/07/08        1709          mfegan         Initial Creation.
#    01/14/09        1652          mfegan         Converted to BASH script.
#    06/05/09        2453          mfegan         Remove "./" paths.
#    12/21/09        2493          mfegan         Remove export of LD_PRELOAD.
#    12/15/10		 7656		   cjeanbap		  Replaced "%" with "$"
##############################################################################

# this allows you to run this script from outside of ./bin
path_to_script=`readlink -f $0`
RUN_FROM_DIR=`dirname $path_to_script`

BASE_AWIPS_DIR=`dirname $RUN_FROM_DIR`

# source the env
source ${RUN_FROM_DIR}/setup.env

# setup the environment needed to run the the Python
export LD_LIBRARY_PATH=${BASE_AWIPS_DIR}/src/lib:${PYTHON_INSTALL}/lib
export PYTHONPATH=${RUN_FROM_DIR}/src:$PYTHONPATH

# execute the textdb Python module
_PYTHON="${PYTHON_INSTALL}/bin/python"
_MODULE="${RUN_FROM_DIR}/src/subscription/SubscriptionManager.py"

# quoting of '$@' is used to prevent command line interpretation 
$_PYTHON $_MODULE "$@"

