#!/bin/ksh
# file name: run_SSHP_data_transfer
# Created: 12/15/2003

# This allows you to run this script from outside of ./bin
RUN_FROM_DIR=`dirname $0`

# set up SOME environment variables for WHFS applications
. $RUN_FROM_DIR/../../set_hydro_env

# set initial lid to the first command line argument passed into the script
LID_PASSED_IN=$1

export CLASSPATH=$CLASSPATH:$DB_DRIVER_PATH
# need to add a path to the jar file for this application
CLASSPATH=$CLASSPATH:$WHFS_BIN_DIR/SiteSpecific.jar

# Java bin directory
JBINDIR=$SYS_JAVA_DIR/bin

export CONTROL_FILE=$SSHP_CONTROL_DIR/SSHPTransfer.xml

# Keeps the last 1200 lines of the log file

LOGFILE=$SSHP_LOG_DIR/SshpDataTransferMgr.log
STDLOGFILE=$SSHP_LOG_DIR/SshpDataTransferMgr.stdout.log
TMPFILE=$SSHP_LOG_DIR/SshpDataTransferMgr.tmp

tail -1200 $LOGFILE > $TMPFILE
mv $TMPFILE $LOGFILE

tail -1200 $STDLOGFILE > $TMPFILE
mv $TMPFILE $STDLOGFILE

if [[ `uname` = "Linux" ]]
then
     $JBINDIR/java ohd.hseb.sshp.messaging.SshpDataTransferMgr $CONTROL_FILE $SSHP_OFS_EXTRACT_TEXT_DIR $SSHP_OFS_EXTRACT_XML_DIR $SSHP_LOG_DIR >>$STDLOGFILE 2>>$STDLOGFILE
elif [[ `uname` = "HP-UX" ]]
then
     ssh -oBatchMode=yes $SSHP_JAVA_PROCESS_HOST $WHFS_BIN_DIR/run_SSHP_data_transfer >>$STDLOGFILE 2>>$STDLOGFILE
fi