C MODULE SFMARO
C-----------------------------------------------------------------------
C
C  ROUTINE TO DEFINE MEAN REAL RUNOFF PARAMETERS.
C
      SUBROUTINE SFMARO (LARRAY,ARRAY,DISP,PRPARM,PRNOTE,PLOT,NFLD,
     *   IRUNCK,IERR)
C
      REAL XMARO/4HMARO/
      REAL XENGL/4HENGL/
      REAL XNO/4HNO  /
      REAL BLNK/4H    /
      REAL XNEW/4HNEW /,XOLD/4HOLD /,QUES/4H????/
      REAL SLASH/4H/   /,CKNULL(2)/4H,,  ,4HNULL/
      REAL LPAREN/4H(    /,RPAREN/4H)   /
      REAL XMAPI/4HMAPI/,XMAPG/4HMAPG/
      REAL*8 FTSID
      REAL*8 BLNK8/8H        /
      REAL*8 OPTN(4)
      INTEGER*2 NMDRGP(42,89)
C
      DIMENSION CHAR(5),CHK(5),ARRAY(LARRAY)
      DIMENSION IRFRO(1000)
      DIMENSION TSTYPE(3),ITSIND(3),TSUNIT(3),ITSINT(3)
      DIMENSION IHEAD(22)
C
      INCLUDE 'scommon/dimmaro'
      INCLUDE 'scommon/dimstan'
C
      INCLUDE 'uio'
      INCLUDE 'common/udtypc'
      INCLUDE 'scommon/sudbgx'
      INCLUDE 'scommon/sugnlx'
      INCLUDE 'scommon/sgboxx'
      INCLUDE 'scommon/sworkx'
C
C    ================================= RCS keyword statements ==========
      CHARACTER*68     RCSKW1,RCSKW2
      DATA             RCSKW1,RCSKW2 /                                 '
     .$Source: /fs/hseb/ob72/rfc/ofs/src/ppinit_define/RCS/sfmaro.f,v $
     . $',                                                             '
     .$Id: sfmaro.f,v 1.3 1999/05/06 10:32:46 page Exp $
     . $' /
C    ===================================================================
C
C
      DATA NOPTN/4/
      DATA OPTN/8HGPA     ,8HRRN     ,8HMDR     ,8HNOTS    /
C
C
      IF (ISTRCE.GT.0) THEN
         WRITE (IOSDBG,1670)
         CALL SULINE (IOSDBG,1)
         ENDIF
C
C  SET DEBUG LEVEL
      LDEBUG=ISBUG(XMARO)
C
      ISTAT=0
C
      LCHAR=5
      LCHK=5
      TDISP=DISP
C
C  SET VALUE FOR MISSING PARAMETER
      UNSD=-999.
      UNDEF=-997.
      IUNDEF=-997
C
      MRFRO=1000
      NUMERR=0
      NUMWRN=0
      ILPFND=0
      IRPFND=0
      ISTRT=-1
      NUMFLD=0
      MINFLD=9
      MAXFLD=10
      INWIND=0
      NOPFLD=0
      NXTFLD=0
      NPIFLD=0
      NPCFLD=NFLD
      IENDIN=0
C
      IOFLD1=0
      IOFLD2=0
      IOFLD3=0
      IOFLD4=0
C
      MXGPA=200
      DO 10 I=1,MXGPA
         NMGPA(I)=IUNDEF
10       CONTINUE
      MXRRN=200
      DO 20 I=1,MXRRN
         NMRFRO(I)=IUNDEF
20       CONTINUE
      NGPA=0
      NRRN=0
      NUMMDR=0
      MAXMDR=3
      DO 30 I=1,MAXMDR
         MMDRBX(I)=IUNDEF
         MDRGPA(I)=IUNDEF
30       CONTINUE
      NUMTSG=0
      NTSTYP=3
C
C  TSTYPE STORES THE TIME SERIES DATA TYPES
      TSTYPE(1)=XMARO
      TSTYPE(2)=XMAPG
      TSTYPE(3)=XMAPI
C
C  ITSIND INDICATES STATUS OF EACH TIME SERIES DATA TYPE
C     -1 = OLD AND UNCHANGED
C      0 = OLD AND CHANGED
C      1 = NEW
      DO 40 I=1,NTSTYP
         TSUNIT(I)=QUES
         ITSIND(I)=1
         IF (I.LE.2) ITSREC(I)=0
40       CONTINUE
C
C  ITSINT STORES THE TIME SERIES DATA TIME INTERVAL
      ITSINT(1)=6
      ITSINT(2)=6
      ITSINT(3)=24
C
C  CHECK NUMBER OF LINES LEFT ON PAGE
      IF (ISLEFT(5).GT.0) CALL SUPAGE
C
C  PRINT CARD
      CALL SUPCRD
C
C  PRINT HEADER LINE
      WRITE (LP,1680)
      CALL SULINE (LP,2)
      WRITE (LP,1690)
      CALL SULINE (LP,2)
C
      IF (LDEBUG.EQ.0) GO TO 50
C
C  PRINT OPTIONS
      WRITE (LP,1700) TDISP,PRPARM,PRNOTE
      CALL SULINE (LP,2)
C
C- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
C
C  CHECK IF PREPROCESSOR PARAMETRIC DATA BASE ALLOCATED
C
50    IDPPP=1
      CALL SUDALC (0,0,0,0,IDPPP,0,0,0,0,0,NUMERR,IERR)
      IF (IERR.EQ.0) GO TO 60
         WRITE (LP,1740)
         CALL SUERRS (LP,2,NUMERR)
C
C- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
C
C  CHECK IF GENERAL USER PARAMETER COMMON BLOCK FILLED
C
60    IF (IUGFIL.GT.0) GO TO 80
C
C  READ USER DEFINED DEFAULTS
      CALL SUGTUG (LARRAY,ARRAY,IERR)
      IF (IERR.NE.0) GO TO 70
         IUGFIL=1
         GO TO 80
70    WRITE (LP,1750)
      CALL SUERRS (LP,2,NUMERR)
C
C- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
C
C  CHECK IF GRID BOX COMMON BLOCK FILLED
C
80    IF (IBXFIL.GT.0) GO TO 90
C
C  READ GRID BOX PARAMETER ARRAYS
      CALL SUGTBX (LARRAY,ARRAY,IERR)
C
C- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
C
C  GET RAINFALL-RUNOFF RELATIONSHIP NUMBERS CURRENTLY DEFINED
C
90    CALL SUGTRR (LARRAY,ARRAY,MRFRO,IRFRO,NRFRO,IERR)
C
C- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
C
C  GET GRID POINT ADDRESS OF GRID POINT LOCATED NEAREST TO THE CENTROID
C  OF EACH MDR BOX
C
      IPTR=0
      IPRERR=0
      IRGMDR=1
      INCLUDE 'scommon/callsrgmdr'
      IF (IERR.EQ.0) GO TO 120
         IF (IERR.EQ.2) GO TO 100
            WRITE (LP,1760) IERR
            CALL SUERRS (LP,2,NUMERR)
            GO TO 110
100      WRITE (LP,1770)
         CALL SUERRS (LP,2,NUMERR)
110      IRGMDR=0
         GO TO 130
C
120   IF (LDEBUG.EQ.0) GO TO 130
      INCLUDE 'scommon/callspgmdr'
C
C- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
C
130    IF (ICFULL.GT.0) GO TO 160
C
C  READ FILE AND LOAD DATA TYPE COMMON BLOCK UDTYPC
C
      IPRC=-99
      CALL UDTYPE ('FCST',MTYPE,NTYPE,TYPE,DIMN,UNIT,MISS,NVAL,
     *   TIME,NADD,IPRC,IERR)
      IF (LDEBUG.GT.0) THEN
         WRITE (IOSDBG,1810) NTYPE
         CALL SULINE (IOSDBG,1)
         ENDIF
      IF (IERR.EQ.0) GO TO 140
         WRITE (LP,1780) IERR
         CALL SUERRS (LP,2,NUMERR)
         GO TO 160
C
140   ICFULL=1
C
      IF (NTYPE.GT.0) THEN
         IF (LDEBUG.LT.2) GO TO 160
            WRITE (IOSDBG,1790)
            CALL SULINE (IOSDBG,2)
            DO 150 I=1,NTYPE
               WRITE (IOSDBG,1800) TYPE(I),DIMN(I),UNIT(I),MISS(I),
     *             NVAL(I),TIME(I),NADD(I)
               CALL SULINE (IOSDBG,1)
150            CONTINUE
         ENDIF
C
C- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
C
C  CHECK FIELDS FOR DEFINE AREA MARO OPTIONS
160   IF (INWIND.EQ.0) GO TO 170
         INULL=1
         GO TO 240
170   INULL=0
      NULREP=0
      CALL UFIELD (NFLD,ISTRT,LENGTH,ITYPE,NREP,INTEGR,REAL,LCHAR,CHAR,
     *   LLPAR,LRPAR,LASK,LATSGN,LAMPS,LEQUAL,IERR)
      IF (NFLD.NE.-1) GO TO 180
         IENDIN=1
         GO TO 220
180   IF (LDEBUG.GT.0)
     * CALL UPRFLD (NFLD,ISTRT,LENGTH,ITYPE,NREP,INTEGR,REAL,LCHAR,
     *   CHAR,LLPAR,LRPAR,LASK,LATSGN,LAMPS,LEQUAL,IERR)
C
C  CHECK FOR NULL FIELD
      IF (IERR.NE.1) GO TO 200
         IF (LDEBUG.GT.0) WRITE (IOSDBG,1890) NFLD
         IF (LDEBUG.GT.0) CALL SULINE (IOSDBG,1)
         IF (TDISP.EQ.XNEW) GO TO 190
            NUMFLD=NUMFLD+1
            IF (NFLD.EQ.1) CALL SUPCRD
            GO TO 160
190      INULL=1
         GO TO 340
C
200   IF (LDEBUG.GT.0) WRITE (IOSDBG,1910) CHAR
      IF (LDEBUG.GT.0) CALL SULINE (IOSDBG,1)
C
C  CHECK FOR DEBUG
      CALL SUIDCK ('CMDS',CHAR,NFLD,0,ICMD,IERR)
      IF (ICMD.NE.1) GO TO 210
         CALL SBDBUG (NFLD,ISTRT,IERR)
         LDEBUG=ISBUG(XMARO)
         GO TO 170
C
210   IF (NXTFLD.GT.0) GO TO 230
C
C  CHECK FOR PAIRED PARENTHESES
220   CALL SUPFND (ILPFND,IRPFND,NPIFLD,NPCFLD)
C
230   IF (IENDIN.EQ.1) GO TO 310
C
C  CHECK IF DISP IS NEW AND ALL FIELDS FOUND
240   IF (INWIND.EQ.0) GO TO 250
         IF (NUMFLD.NE.MINFLD) GO TO 330
            INWIND=0
            IF (IENDIN.EQ.1) GO TO 1450
            GO TO 160
C
C  CHECK FOR REPEATED NULL FIELD
250   IF (CHAR(1).NE.CKNULL(1).AND.CHAR(1).NE.CKNULL(2)) GO TO 280
         IF (LDEBUG.GT.0) WRITE (LP,1850) NREP
         IF (LDEBUG.GT.0) CALL SULINE (IOSDBG,1)
         IF (NREP.GT.0.AND.NREP+NUMFLD.LE.MINFLD) GO TO 260
            WRITE (LP,1860) NREP,NUMFLD,MINFLD
            CALL SUERRS (LP,2,NUMERR)
            NREP=MAXFLD-NUMFLD
260      IF (TDISP.EQ.XOLD) GO TO 270
            NULREP=NREP
            INWIND=1
            NOPFLD=0
            NXTFLD=0
            INULL=1
            GO TO 330
270      NUMFLD=NUMFLD+NREP
         GO TO 160
C
C  CHECK FOR COMMAND
280   IF (LATSGN.NE.1) GO TO 290
         IENDIN=1
         GO TO 220
C
C  CHECK FOR PARENTHESIS IN FIELD
290   IF (CHAR(1).EQ.LPAREN.AND.LENGTH.EQ.1) GO TO 330
      IF (CHAR(1).EQ.RPAREN.AND.LENGTH.EQ.1) GO TO 330
      IF (LLPAR.GT.0) CALL UFPACK (LCHK,CHK,ISTRT,1,LLPAR-1,IERR)
      IF (LLPAR.EQ.0) CALL UFPACK (LCHK,CHK,ISTRT,1,LENGTH,IERR)
C
C  CHECK FOR END OF INPUT
      IF (CHK(1).NE.SLASH) GO TO 300
         IENDIN=1
         GO TO 220
C
C  IF FIRST FIELD, CONTENTS HAS BEEN CHECKED FOR KEYWORD
300   IF (NUMFLD.EQ.0) GO TO 330
C
C  CHECK FOR KEYWORD
      CALL SUIDCK ('DEFN',CHK,NFLD,0,IKEYWD,IERR)
      IF (IERR.NE.2) GO TO 330
310      CALL SUPFND (ILPFND,IRPFND,NPIFLD,NPCFLD)
         IF (TDISP.EQ.XNEW.AND.NUMFLD.LT.MINFLD) GO TO 320
            GO TO 1450
320      INWIND=1
         NOPFLD=0
         NXTFLD=0
         IENDIN=1
         IF (PRNOTE.EQ.XNO) GO TO 160
            WRITE (LP,1920)
            CALL SULINE (LP,2)
            GO TO 160
C
C  PRINT CARD
330   IF (NFLD.EQ.1.AND.NUMFLD.GT.0.AND.INWIND.EQ.0) CALL SUPCRD
C
340   IF (NUMFLD.LE.MINFLD-1) GO TO 380
C
C  CHECK FOR OPTIONAL FIELDS
      IF (NUMFLD.GT.MAXFLD) GO TO 370
         IF (NOPFLD.GT.0.AND.CHAR(1).EQ.LPAREN.AND.LENGTH.EQ.1)
     *      GO TO 380
         IF (NOPFLD.GT.0.AND.CHAR(1).EQ.RPAREN.AND.LENGTH.EQ.1)
     *      GO TO 380
            DO 350 IOPTN=1,NOPTN
               CALL SUCOMP (2,CHK,OPTN(IOPTN),IMATCH)
               IF (IMATCH.EQ.1) GO TO 360
350            CONTINUE
         IF (NXTFLD.GT.0) GO TO 380
            WRITE (LP,1820) NUMFLD,NFLD,CHAR
            CALL SUERRS (LP,2,NUMERR)
            GO TO 160
360      NOPFLD=0
         NXTFLD=0
         CALL SUPFND (ILPFND,IRPFND,NPIFLD,NPCFLD)
         GO TO (590,790,1120,1280),IOPTN
            WRITE (LP,1970) IOPTN
            CALL SUERRS (LP,2,NUMERR)
            GO TO 160
C
370      WRITE (LP,1840) NUMFLD,MAXFLD
         CALL SUERRS (LP,2,NUMERR)
         GO TO 160
C
C  CHECK FOR PARENTHESES IN FIELD
380   IF (NOPFLD.EQ.0) CALL SUPFND (ILPFND,IRPFND,NPIFLD,NPCFLD)
      IF (LLPAR.GT.0) ILPFND=1
      IF (LRPAR.GT.0) IRPFND=1
C
      IF (LDEBUG.GT.0) WRITE (IOSDBG,1710) NUMFLD,MINFLD,MAXFLD,NUMERR,
     *   NOPFLD,NXTFLD,CHK
      IF (LDEBUG.GT.0) CALL SULINE (IOSDBG,1)
C
C  CHECK IF FIELD WITH MORE THAN ONE POSSIBLE PARAMETER
      IF (NOPFLD.GT.0) GO TO (590,790,1120,1280),NOPFLD
C
C  CHECK IF MAXIMUM NUMBER OF FIELDS EXPECTED EXCEEDED
390   NUMFLD=NUMFLD+1
      IF (TDISP.EQ.XOLD.AND.INULL.EQ.1) GO TO 160
C
      GO TO (400,430,500,520,550,590,790,1000,1120),NUMFLD
         WRITE (LP,1830) CHAR
         CALL SUERRS (LP,2,NUMERR)
         GO TO 1430
C
C- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
C
C    CHECK PARAMETER TYPE
400   IF (CHK(1).EQ.XMARO) GO TO 410
         WRITE (LP,1950) CHK(1)
         CALL SUERRS (LP,2,NUMERR)
         GO TO 160
410   PTYPE=CHK(1)
      IF (LDEBUG.GT.0) THEN
         WRITE (IOSDBG,1870) PTYPE
         CALL SULINE (IOSDBG,1)
         ENDIF
C
C  CHECK IF UNITS SPECIFIED
      IF (LLPAR.EQ.0) GO TO 160
      IEND=LRPAR-1
      IF (LRPAR.GT.0) GO TO 420
         WRITE (LP,1900) NUMFLD,NFLD
         CALL SULINE (LP,2)
         LRPAR=LENGTH-1
420   CALL UFPACK (LCHK,CHK,ISTRT,LLPAR+1,IEND,IERR)
      WRITE (LP,1880) CHK(1),NFLD
      CALL SULINE (LP,2)
      GO TO 160
C
C- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
C
C  AREA IDENTIFIER

430   IF (LENGTH.LE.8) GO TO 440
         WRITE (LP,1980) LENGTH
         CALL SUWRNS (LP,2,NUMERR)
C
C  SET AREA IDENTIFIER
440   CALL SUBSTR (CHAR,1,8,XMAROI,1)
      IF (LDEBUG.GT.0) WRITE (IOSDBG,2380) XMAROI
      IF (LDEBUG.GT.0) CALL SULINE (IOSDBG,1)
C
C  CHECK IF AREA EXISTS
      IPRERR=0
      IPTR=0
      INCLUDE 'scommon/callsrmaro'
      IRMARO=IERR
      IF (LDEBUG.EQ.0.OR.IRMARO.GT.0) GO TO 450
      INCLUDE 'scommon/callspmaro'
C
C  AREA EXIST AND DISP IS NEW
450   IF (IRMARO.EQ.0.AND.TDISP.EQ.XNEW) GO TO 460
         GO TO 470
460   WRITE (LP,1720) XMAROI
      CALL SUERRS (LP,2,NUMERR)
      TDISP=XOLD
      GO TO 490
C
C  AREA DOES NOT EXIST AND DISP IS OLD
470   IF (IRMARO.GT.0.AND.TDISP.EQ.XOLD) GO TO 480
         GO TO 490
480   WRITE (LP,1730) XMAROI
      CALL SUWRNS (LP,2,NUMWRN)
      TDISP=XNEW
C
490   GO TO 1430
C
C- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
C
C  AREA DESCRIPTION

500   IF (LENGTH.LE.20) GO TO 510
         WRITE (LP,1990) LENGTH
         CALL SUWRNS (LP,2,NUMERR)
C
C  SET AREA DESCRIPTION
510   CALL SUBSTR (CHAR,1,20,XDESCR,1)
      IF (LDEBUG.GT.0) WRITE (IOSDBG,2390) XDESCR
      IF (LDEBUG.GT.0) CALL SULINE (IOSDBG,1)
      GO TO 1430
C
C- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
C
C  AREA LATITUDE - INPUT AS DECIMAL DEGREES OR DEGREES AND MINUTES
C
520   IF (TDISP.EQ.XNEW) CENTRD(1)=UNDEF
      IF (INULL.EQ.0) GO TO 530
         IF (TDISP.EQ.XOLD) GO TO 1430
         WRITE (LP,2000) NUMFLD,NFLD
         CALL SUERRS (LP,2,NUMERR)
         GO TO 1430
530   SUNITS=BLNK
      CALL SUCDEG (NFLD,ISTRT,LENGTH,ITYPE,REAL,CHAR,LCHAR,
     *   DEG,XMIN,DEGMIN,SUNITS,NUMFLD,NUMERR,IERR)
      IF (IUGFIL.EQ.0) GO TO 540
         IF (DEGMIN.GE.ULLMTS(2).AND.DEGMIN.LE.ULLMTS(1)) GO TO 540
            WRITE (LP,2010) DEGMIN,ULLMTS(2),ULLMTS(1)
            CALL SUERRS (LP,2,NUMERR)
            GO TO 1430
C
540   CENTRD(1)=DEGMIN
      IF (LDEBUG.GT.0) WRITE (IOSDBG,2400) CENTRD(1)
      IF (LDEBUG.GT.0) CALL SULINE (IOSDBG,1)
      GO TO 1430
C
C- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
C
C  AREA LONGITUDE - INPUT AS DECIMAL DEGREES OR DEGREES AND MINUTES
C
550   IF (TDISP.EQ.XNEW) CENTRD(2)=UNDEF
      IF (INULL.EQ.0) GO TO 560
         IF (TDISP.EQ.XOLD) GO TO 580
         WRITE (LP,2000) NUMFLD,NFLD
         CALL SUERRS (LP,2,NUMERR)
         GO TO 1430
560   SUNITS=BLNK
      CALL SUCDEG (NFLD,ISTRT,LENGTH,ITYPE,REAL,CHAR,LCHAR,
     *   DEG,XMIN,DEGMIN,SUNITS,NUMFLD,NUMERR,IERR)
      IF (IUGFIL.EQ.0) GO TO 570
         IF (DEGMIN.GE.ULLMTS(3).AND.DEGMIN.LE.ULLMTS(4)) GO TO 570
            WRITE (LP,2020) DEGMIN,ULLMTS(3),ULLMTS(4)
            CALL SUERRS (LP,2,NUMERR)
            GO TO 1430
C
570   CENTRD(2)=DEGMIN
      IF (LDEBUG.GT.0) WRITE (IOSDBG,2410) CENTRD(2)
      IF (LDEBUG.GT.0) CALL SULINE (IOSDBG,1)
C
580   GO TO 1430
C
C- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
C
C  CHECK IF RAINFALL-RUNOFF RELATIONSHIP INDICATOR FOUND
590   CALL SUCOMP (2,CHK,OPTN(2),IMATCH)
      IF (IMATCH.EQ.0) GO TO 600
         IF (NOPFLD.GT.0) NUMFLD=NUMFLD+1
         NXTFLD=0
         GO TO 800
C
C  GRID POINT ADDRESSES
C
C  CHECK WHICH FIELD TO BE PROCESSED
600   NGOTO=NXTFLD+1
      GO TO (610,670),NGOTO
C
C  CHECK IF OPTIONAL FIELD ALREADY SPECIFIED
610   IF (IOFLD1.EQ.0) GO TO 620
         WRITE (LP,2180)
         CALL SUWRNS (LP,2,NUMWRN)
         NGPA=0
C
620   IOFLD1=1
      IF (NOPFLD.GT.0) CALL SUPFND (ILPFND,IRPFND,NUMFLD,0)
C
C  CHECK FOR NULL FIELD
      IF (INULL.EQ.0) GO TO 630
         WRITE (LP,1930) NUMFLD,NFLD
         CALL SUERRS (LP,2,NUMERR)
         GO TO 1430
C
C  CHECK IF CHARACTER DATA
630   IF (ITYPE.EQ.2) GO TO 640
         WRITE (LP,1960) NUMFLD,NFLD
         CALL SUERRS (LP,2,NUMERR)
         GO TO 1430
C
C  CHECK FOR PARENTHESES IN FIELD
640   IF (CHAR(1).NE.RPAREN) GO TO 650
         NOPFLD=0
         NXTFLD=0
         WRITE (LP,2190) NUMFLD,NFLD
         CALL SUERRS (LP,2,NUMERR)
         GO TO 1430
650   IF (LLPAR.EQ.0) CHK(1)=CHAR(1)
      IF (LLPAR.GT.0) CALL SUBSTR (CHAR,1,LLPAR-1,CHK,1)
      CALL SUCOMP (2,CHK,OPTN(1),IMATCH)
      IF (IMATCH.EQ.1) GO TO 660
         WRITE (LP,2220) CHK(1),NUMFLD,NFLD
         CALL SUERRS (LP,2,NUMERR)
         GO TO 1430
660   NOPFLD=1
      NXTFLD=1
      IF (LLPAR.EQ.0.OR.LLPAR.EQ.LENGTH) GO TO 1430
C
C  CHECK FOR SPECIAL CHARACTERS
670   IF (CHAR(1).EQ.LPAREN.AND.LENGTH.EQ.1) GO TO 1430
      IF (ITYPE.NE.2) GO TO 700
         IF (LRPAR.NE.1) GO TO 690
            IF (NGPA.EQ.0) GO TO 680
               NOPFLD=0
               NXTFLD=0
               GO TO 1430
680         WRITE (LP,2280)
            CALL SUERRS (LP,2,NUMERR)
            NOPFLD=0
            NXTFLD=0
            GO TO 1430
690      IF (LRPAR.EQ.0.OR.LRPAR.EQ.LENGTH) GO TO 700
            WRITE (LP,1960) NUMFLD,NFLD
            CALL SUERRS (LP,2,NUMERR)
            NXTFLD=1
            GO TO 1430
700   IF (LLPAR.EQ.0) IBEG=1
      IF (LLPAR.GT.0) IBEG=LLPAR+1
      IF (LASK.GT.0) IBEG=LASK+1
      IEND=LENGTH
      IF (LRPAR.EQ.0) GO TO 710
         IEND=LRPAR-1
         NOPFLD=0
         NXTFLD=0
C
C  CHECK FOR MAXIMUM NUMBER OF CHARACTERS
710   NCHAR=IEND-IBEG+1
      IF (NCHAR.EQ.3.OR.NCHAR.EQ.4) GO TO 720
         WRITE (LP,2240) NFLD,NCHAR
         CALL SUERRS (LP,2,NUMERR)
         GO TO 770
C
C  GET GRID POINT ADDRESS
720   CALL UFINFX (IGPA,ISTRT,IBEG,IEND,IERR)
      IF (IERR.EQ.0) GO TO 730
         WRITE (LP,2230) NFLD
         CALL SUERRS (LP,2,NUMERR)
         GO TO 770
C
C  CHECK FOR MAXIMUM NUMBER OF VALUES
730   NGPA=NGPA+1
      IF (NGPA.LE.MXGPA) GO TO 740
         IF (NGPA.GT.MXGPA+1) GO TO 770
            WRITE (LP,2250) MXGPA,NUMFLD,NFLD
            CALL SUERRS (LP,2,NUMERR)
            GO TO 770
C
C  CHECK FOR VALID GRID POINT BOX
740   IF (NCHAR.EQ.3) IEND=IBEG
      IF (NCHAR.EQ.4) IEND=IBEG+1
      CALL UFINFX (IBOX,ISTRT,IBEG,IEND,IERR)
      IF (IBOX.GT.0.AND.IBOX.LT.100) GO TO 750
         WRITE (LP,2300) NGPA,IBOX
         CALL SUERRS (LP,2,NUMERR)
         GO TO 770
C
C  CHECK IF GRID BOX DEFINED
750   IF (IGBOX(IBOX).EQ.1) GO TO 760
         WRITE (LP,2310) IBOX
         CALL SUERRS (LP,2,NUMERR)
         GO TO 770
C
C  SET GRID POINT ADDRESS
760   NMGPA(NGPA)=IGPA
      IF (LDEBUG.GT.0) WRITE (IOSDBG,2490) NGPA,NMGPA(NGPA)
      IF (LDEBUG.GT.0) CALL SULINE (IOSDBG,1)
C
C  CHECK FOR REPEATED VALUES
770   IF (NREP.LE.1) GO TO 780
         NREP=NREP-1
         GO TO 730
C
780   NXTFLD=1
      IF (LRPAR.EQ.0) GO TO 1430
         NOPFLD=0
         NXTFLD=0
         GO TO 1430
C
C- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
C
C  CHECK IF RAINFALL-RUNOFF RELATIONSHIP INDICATOR FOUND
790   CALL SUCOMP (2,CHK,OPTN(1),IMATCH)
      IF (IMATCH.EQ.0) GO TO 800
         IF (NOPFLD.GT.0) NUMFLD=NUMFLD+1
         NXTFLD=0
         GO TO 600
C
C  RAINFALL-RUNOFF RELATIONSHIP NUMBER
C
C  CHECK WHICH FIELD TO BE PROCESSED
800   NGOTO=NXTFLD+1
      GO TO (810,870),NGOTO
C
C  CHECK IF OPTIONAL FIELD ALREADY SPECIFIED
810   IF (IOFLD2.EQ.0) GO TO 820
         WRITE (LP,2210)
         CALL SUWRNS (LP,2,NUMWRN)
         NGPA=0
C
820   IOFLD2=1
      IF (NOPFLD.GT.0) CALL SUPFND (ILPFND,IRPFND,NUMFLD,0)
C
C  CHECK FOR NULL FIELD
      IF (INULL.EQ.0) GO TO 830
         WRITE (LP,1930) NUMFLD,NFLD
         CALL SUERRS (LP,2,NUMERR)
         GO TO 1430
C
C  CHECK IF CHARACTER DATA
830   IF (ITYPE.EQ.2) GO TO 840
         WRITE (LP,1960) NUMFLD,NFLD
         CALL SUERRS (LP,2,NUMERR)
         GO TO 1430
C
C  CHECK FOR PARENTHESES IN FIELD
840   IF (CHAR(1).NE.RPAREN) GO TO 850
         NOPFLD=0
         NXTFLD=0
         WRITE (LP,2200) NUMFLD,NFLD
         CALL SUERRS (LP,2,NUMERR)
         GO TO 1430
850   IF (LLPAR.EQ.0) CHK(1)=CHAR(1)
      IF (LLPAR.GT.0) CALL SUBSTR (CHAR,1,LLPAR-1,CHK,1)
      CALL SUCOMP (2,CHK,OPTN(2),IMATCH)
      IF (IMATCH.EQ.1) GO TO 860
         WRITE (LP,2220) CHK(1),NUMFLD,NFLD
         CALL SUERRS (LP,2,NUMERR)
         GO TO 1430
860   NOPFLD=2
      NXTFLD=1
      IF (LLPAR.EQ.0.OR.LLPAR.EQ.LENGTH) GO TO 1430
C
C  CHECK FOR SPECIAL CHARACTERS
870   IF (CHAR(1).EQ.LPAREN.AND.LENGTH.EQ.1) GO TO 1430
      IF (ITYPE.NE.2) GO TO 900
         IF (LRPAR.NE.1) GO TO 890
            IF (NRRN.EQ.0) GO TO 880
               NOPFLD=0
               NXTFLD=0
               GO TO 1430
880         WRITE (LP,2290)
            CALL SUERRS (LP,2,NUMERR)
            NOPFLD=0
            NXTFLD=0
            GO TO 1430
890      IF (LRPAR.EQ.0.OR.LRPAR.EQ.LENGTH) GO TO 900
            WRITE (LP,1960) NUMFLD,NFLD
            CALL SUERRS (LP,2,NUMERR)
            NXTFLD=1
            GO TO 1430
900   IF (LLPAR.EQ.0) IBEG=1
      IF (LLPAR.GT.0) IBEG=LLPAR+1
      IF (LASK.GT.0) IBEG=LASK+1
      IEND=LENGTH
      IF (LRPAR.EQ.0) GO TO 910
         IEND=LRPAR-1
         NOPFLD=0
         NXTFLD=0
910   CALL UFINFX (IRRN,ISTRT,IBEG,IEND,IERR)
      IF (IERR.EQ.0) GO TO 920
         WRITE (LP,2230) NFLD
         CALL SUERRS (LP,2,NUMERR)
         GO TO 980
C
C  CHECK FOR ZERO VALUE
920   IF (IRRN.GT.0) GO TO 930
         WRITE (LP,2260)
         CALL SUERRS (LP,2,NUMERR)
         GO TO 980
C
C  CHECK FOR MAXIMUM NUMBER OF VALUES
930   NRRN=NRRN+1
      IF (NRRN.LE.MXRRN) GO TO 940
         IF (NRRN.GT.MXRRN+1) GO TO 980
            WRITE (LP,2270) MXRRN,NUMFLD,NFLD
            CALL SUERRS (LP,2,NUMERR)
            GO TO 980
C
C  CHECK IF RAINFALL-RUNOFF RELATIONSHIP IS DEFINED
940   IF (NRFRO.GT.0) GO TO 950
         WRITE (LP,2320)
         CALL SUERRS (LP,2,NUMERR)
         GO TO 980
950   DO 960 I=1,NRFRO
         IF (IRFRO(I).EQ.IRRN) GO TO 970
960      CONTINUE
         WRITE (LP,2330) IRRN
         CALL SUERRS (LP,2,NUMERR)
         GO TO 980
C
C  SET RAINFALL-RUNOFF RELATIONSHIP NUMBER
970   NMRFRO(NRRN)=IRRN
      IF (LDEBUG.GT.0) WRITE (IOSDBG,2500) NRRN,NMRFRO(NRRN)
      IF (LDEBUG.GT.0) CALL SULINE (IOSDBG,1)
C
C  CHECK FOR REPEATED VALUES
980   IF (NREP.LE.1) GO TO 990
         NREP=NREP-1
         GO TO 920
C
990   NXTFLD=1
      IF (LRPAR.EQ.0) GO TO 1430
         NOPFLD=0
         NXTFLD=0
         GO TO 1430
C
C- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
C
C  FIRST ORDER STATION IDENTIFIER
C
1000  IF (NOPFLD.GT.0) CALL SUPFND (ILPFND,IRPFND,NUMFLD,0)
      NOPFLD=0
C
C  CHECK FOR NULL FIELD
      IF (INULL.EQ.0) GO TO 1010
         IF (TDISP.EQ.XOLD) GO TO 1430
            WRITE (LP,1930) NUMFLD,NPCFLD
            CALL SUERRS (LP,2,NUMERR)
            GO TO 1430
C
C  CHECK IF CHARACTER DATA
1010  IF (ITYPE.EQ.2) GO TO 1020
         WRITE (LP,1960) NUMFLD,NFLD
         CALL SUERRS (LP,2,NUMERR)
         GO TO 1430
C
C  CHECK LENGTH
1020  IF (LENGTH.LE.8) GO TO 1030
         WRITE (LP,2030) LENGTH
         CALL SUWRNS (LP,2,NUMWRN)
C
C  SET STATION IDENTIFIER
1030  CALL SUBSTR (CHAR,1,8,XSTAID,1)
      IF (LDEBUG.GT.0) WRITE (IOSDBG,2420) XSTAID
      IF (LDEBUG.GT.0) CALL SULINE (IOSDBG,1)
C
C  CHECK IF STATION EXISTS
      CALL SUBSTR (XSTAID,1,8,STAID,1)
      IPTR=0
      IPRERR=0
      RDISP=XOLD
      INCLUDE 'scommon/callsrstan'
      IRSTAN=IERR
      IF (LDEBUG.EQ.0.OR.IERR.GT.0) GO TO 1040
         IPRNT=1
         UNITS=XENGL
      INCLUDE 'scommon/callspstan'
1040  IF (IRSTAN.EQ.0) GO TO 1050
         WRITE (LP,2040) XSTAID
         CALL SUERRS (LP,2,NUMERR)
         GO TO 1430
C
C  CHECK STATION STATUS
1050  IF (ICSTAN.EQ.0) GO TO 1060
         WRITE (LP,2050) XSTAID
         CALL SUERRS (LP,2,NUMERR)
         GO TO 1430
C
C  CHECK IF STATION HAS PCPN DATA
1060  DO 1070 I=1,NGPS
         IF (GPS(I).EQ.'PCPN') GO TO 1080
1070     CONTINUE
         WRITE (LP,2060) XSTAID,'PCPN'
         CALL SUERRS (LP,2,NUMERR)
         GO TO 1430
C
C  CHECK IF STATION AS 6-HR DATA
1080  IF (ITPPVR.EQ.6) GO TO 1090
         WRITE (LP,2070) XSTAID,ITPPVR
         CALL SUERRS (LP,2,NUMERR)
         GO TO 1430
C
C  CHECK PARAMETER ARRAY VERSION NUMBER
1090  IF (IVSTAN.GE.4) GO TO 1100
         WRITE (LP,2080) XSTAID,IVSTAN
         CALL SUERRS (LP,2,NUMERR)
         GO TO 1430
C
C  CHECK IF GRID POINT ADDRESS IS DEFINED
1100  IF (NUGPA.GT.0) GO TO 1110
         WRITE (LP,2090) XSTAID,NUGPA
         CALL SUERRS (LP,2,NUMERR)
         GO TO 1430
C
C  SET STATION GRID POINT ADDRESS
1110  NMSGPA=NUGPA
      IF (LDEBUG.GT.0) WRITE (IOSDBG,2430) NMSGPA
      IF (LDEBUG.GT.0) CALL SULINE (IOSDBG,1)
      GO TO 1430
C
C- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
C
C  MDR BOXES
C
C  CHECK WHICH FIELD TO BE PROCESSED
1120  NGOTO=NXTFLD+1
      GO TO (1130,1190),NGOTO
C
C  CHECK IF OPTIONAL FIELD PREVIOUSLY PROCESSED
1130  IF (IOFLD3.EQ.0) GO TO 1140
         WRITE (LP,2130)
         CALL SUWRNS (LP,2,NUMWRN)
         NUMMDR=0
C
1140  IOFLD3=1
      IF (NOPFLD.GT.0) CALL SUPFND (ILPFND,IRPFND,NUMFLD,0)
C
C  CHECK FOR NULL FIELD
      IF (INULL.EQ.0) GO TO 1150
         WRITE (LP,1940) NUMFLD,NFLD
         CALL SUERRS (LP,2,NUMERR)
         GO TO 1430
C
C  CHECK FOR CHARACTER DATA
1150  IF (ITYPE.EQ.2) GO TO 1160
         WRITE (LP,1960) NUMFLD,NFLD
         CALL SUERRS (LP,2,NUMERR)
         GO TO 1430
C
C  CHECK FOR PARENTHESES IN FIELD
1160  IF (CHAR(1).NE.RPAREN) GO TO 1170
         NOPFLD=0
         NXTFLD=0
         WRITE (LP,2140) NUMFLD,NFLD
         CALL SUERRS (LP,2,NUMERR)
         GO TO 1430
1170  IF (LLPAR.EQ.0) CHK(1)=CHAR(1)
      IF (LLPAR.GT.0) CALL SUBSTR (CHAR,1,LLPAR-1,CHK,1)
      CALL SUCOMP (2,CHK,OPTN(3),IMATCH)
      IF (IMATCH.EQ.1) GO TO 1180
         WRITE (LP,2150) CHK(1),NUMFLD,NFLD
         CALL SUERRS (LP,2,NUMERR)
         GO TO 1430
1180  NOPFLD=3
      NXTFLD=1
      IF (LLPAR.EQ.0.OR.LLPAR.EQ.LENGTH) GO TO 1430
      NROW=0
      NCOL=0
C
C  CHECK FOR SPECIAL CHARACTERS
1190  IF (CHAR(1).EQ.LPAREN.AND.LENGTH.EQ.1) GO TO 1430
      IF (ITYPE.NE.2) GO TO 1210
         IF (LRPAR.NE.1) GO TO 1200
         IF (NUMMDR.GT.0) GO TO 1430
            WRITE (LP,2160)
            CALL SUERRS (LP,2,NUMERR)
            NOPFLD=0
            NXTFLD=0
            GO TO 1430
1200     IF (LRPAR.EQ.0.OR.LRPAR.EQ.LENGTH) GO TO 1210
            WRITE (LP,1960) NUMFLD,NFLD
            CALL SUERRS (LP,2,NUMERR)
            NXTFLD=1
            GO TO 1430
1210  IF (LLPAR.EQ.0) IBEG=1
      IF (LLPAR.GT.0) IBEG=LLPAR+1
      IF (LASK.GT.0) IBEG=LASK+1
      IEND=LENGTH
      IF (LRPAR.EQ.0) GO TO 1220
         IEND=LRPAR-1
         NOPFLD=0
         NXTFLD=0
1220  CALL UFINFX (IVALUE,ISTRT,IBEG,IEND,IERR)
C
C  CHECK FOR MAXIMUM MDR BOXES
1230  NUMMDR=NUMMDR+1
      IF (NUMMDR.LE.MAXMDR*2) GO TO 1240
         WRITE (LP,2100) NUMFLD,NFLD
         CALL SUERRS (LP,2,NUMERR)
         GO TO 1430
C
C  SET ROW OR COLUMN VALUE
1240  IF (NUMMDR/2*2.NE.NUMMDR) NROW=IVALUE
      IF (NUMMDR/2*2.EQ.NUMMDR) NCOL=IVALUE
      IF (LDEBUG.GT.0) WRITE (IOSDBG,2440) NUMMDR,NROW,NCOL
      IF (LDEBUG.GT.0) CALL SULINE (IOSDBG,1)
      IF (NUMMDR/2*2.NE.NUMMDR) GO TO 1260
C
C  SET MDR BOX NUMBER
      NMDR=NUMMDR/2
      CALL SBMNUM (NCOL,NROW,NBOX,IERR)
      MMDRBX(NMDR)=NBOX
      IF (LDEBUG.GT.0) WRITE (IOSDBG,2450) NMDR,MMDRBX(NMDR)
      IF (LDEBUG.GT.0) CALL SULINE (IOSDBG,1)
C
C  CHECK IF GMDR PARAMETERS SUCCESSFULLY READ
      IF (IRGMDR.EQ.0) GO TO 1260
C
C  GET GRID POINT ADDRESS OF CENTROID OF MDR BOX
      ICOL=NCOL-MDRWCL+1
      IMDRGP=NMDRGP(ICOL,NROW)
      IMDRGP=IABS(IMDRGP)
      IF (LDEBUG.GT.0) WRITE (IOSDBG,2460) IMDRGP
      IF (LDEBUG.GT.0) CALL SULINE (IOSDBG,1)
C
C  CHECK IF ADDRESS IS ZERO
      IF (IMDRGP.GT.0) GO TO 1250
         WRITE (LP,2470) NMDR,NROW,NCOL
         CALL SUERRS (LP,2,NUMERR)
         GO TO 1430
C
C  SET GRID POINT ADDRESS OF CENTROID OF MDR BOX
1250  MDRGPA(NMDR)=IMDRGP
      IF (LDEBUG.GT.0) WRITE (IOSDBG,2480) NMDR,MDRGPA(NMDR)
      IF (LDEBUG.GT.0) CALL SULINE (IOSDBG,1)
C
C  CHECK FOR REPEATED VALUES
1260  IF (NREP.LE.1) GO TO 1270
         NREP=NREP-1
         GO TO 1230
C
1270  NXTFLD=1
      IF (LRPAR.EQ.0) GO TO 1430
         NOPFLD=0
         NXTFLD=0
         GO TO 1430
C
C- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
C
C  OPTION TO NOT GENERATE MAPG AND/OR MAPI TIME SERIES
C
C  CHECK WHICH FIELD TO BE PROCESSED
1280  NGOTO=NXTFLD+1
      GO TO (1290,1360),NGOTO
C
C  CHECK IF OPTIONAL FIELD PREVIOUSLY PROCESSED
1290  IF (IOFLD4.EQ.0) GO TO 1310
         WRITE (LP,2360)
         CALL SUWRNS (LP,2,NUMWRN)
         DO 1300 I=1,NTSTYP
            ITSIND(I)=1
1300        CONTINUE
         NUMTSG=0
C
1310  IOFLD4=1
      IF (NOPFLD.GT.0) CALL SUPFND (ILPFND,IRPFND,NUMFLD,0)
C
C  CHECK FOR NULL FIELD
      IF (INULL.EQ.0) GO TO 1320
         WRITE (LP,1940) NUMFLD,NFLD
         CALL SUERRS (LP,2,NUMERR)
         GO TO 1430
C
C  CHECK FOR CHARACTER DATA
1320  IF (ITYPE.EQ.2) GO TO 1330
         WRITE (LP,1960) NUMFLD,NFLD
         CALL SUERRS (LP,2,NUMERR)
         GO TO 1430
C
C  CHECK FOR PARENTHESES IN FIELD
1330  IF (CHAR(1).NE.RPAREN) GO TO 1340
         NOPFLD=0
         NXTFLD=0
         WRITE (LP,2340) NUMFLD,NFLD
         CALL SUERRS (LP,2,NUMERR)
         GO TO 1430
1340  IF (LLPAR.EQ.0) CHK(1)=CHAR(1)
      IF (LLPAR.GT.0) CALL SUBSTR (CHAR,1,LLPAR-1,CHK,1)
      CALL SUCOMP (2,CHK,OPTN(4),IMATCH)
      IF (IMATCH.EQ.1) GO TO 1350
         WRITE (LP,2350) CHK(1),NUMFLD,NFLD
         CALL SUERRS (LP,2,NUMERR)
         GO TO 1430
1350  NOPFLD=4
      NXTFLD=1
      IF (LLPAR.EQ.0.OR.LLPAR.EQ.LENGTH) GO TO 1430
C
C  CHECK FOR SPECIAL CHARACTERS
1360  IF (CHAR(1).EQ.LPAREN.AND.LENGTH.EQ.1) GO TO 1430
      IF (ITYPE.NE.2) GO TO 1380
         IF (LRPAR.NE.1) GO TO 1370
         IF (NUMTSG.GT.0) GO TO 1430
            WRITE (LP,2170)
            CALL SUERRS (LP,2,NUMERR)
            NOPFLD=0
            NXTFLD=0
            GO TO 1430
1370     IF (LRPAR.EQ.0.OR.LRPAR.EQ.LENGTH) GO TO 1380
            WRITE (LP,1960) NUMFLD,NFLD
            CALL SUERRS (LP,2,NUMERR)
            NXTFLD=1
            GO TO 1430
1380  IF (LLPAR.EQ.0) IBEG=1
      IF (LLPAR.GT.0) IBEG=LLPAR+1
      IF (LASK.GT.0) IBEG=LASK+1
      IEND=LENGTH
      IF (LRPAR.EQ.0) GO TO 1390
         IEND=LRPAR-1
         NOPFLD=0
         NXTFLD=0
1390  CALL UFPACK (LCHK,CHK,ISTRT,IBEG,IEND,IERR)
C
C  CHECK FOR VALID OPTION
1400  IF (CHK(1).EQ.XMAPG.OR.CHK(1).EQ.XMAPI) GO TO 1410
         WRITE (LP,2370) CHK
         CALL SUERRS (LP,2,NUMERR)
         NXTFLD=1
         GO TO 1430
C
C  SET TIME SERIES OUTPUT INDICATOR
1410  IF (CHK(1).EQ.XMAPG) ITSIND(2)=-1
      IF (CHK(1).EQ.XMAPI) ITSIND(3)=-1
      IF (LDEBUG.GT.0) WRITE (IOSDBG,2510) CHK(1),ITSIND
      IF (LDEBUG.GT.0) CALL SULINE (IOSDBG,1)
      NUMTSG=NUMTSG+1
C
C  CHECK FOR REPEATED VALUES
      IF (NREP.LE.1) GO TO 1420
         NREP=NREP-1
         GO TO 1400
C
1420  NXTFLD=1
      IF (LRPAR.EQ.0) GO TO 1430
         NOPFLD=0
         NXTFLD=0
         GO TO 1430
C
C- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
C
C  CHECK FOR REPEATED NULL FIELDS
C
1430  IF (NULREP.EQ.0) GO TO 1440
         NULREP=NULREP-1
         IF (NULREP.NE.0) GO TO 390
            INWIND=0
C
1440  NPIFLD=NUMFLD
      NPCFLD=NFLD
C
C  CHECK FOR END OF INPUT
      IF (INWIND.EQ.1) GO TO 160
      IF (IENDIN.EQ.1) GO TO 1450
         GO TO 160
C
C- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
C
C  CHECK NUMBER OF FIELDS PROCESSED
1450  IF (NUMFLD.GE.1) GO TO 1460
         WRITE (LP,2530)
         CALL SUWRNS (LP,2,NUMWRN)
         GO TO 1660
C
C  CHECK NUMBER OF GRID POINT ADDRESSES AND RAINFALL-RUNOFF
C  RELATIONSHIPS PROCESSED
1460  IF (NGPA.EQ.NRRN) GO TO 1470
         WRITE (LP,2110) NGPA,NRRN
         CALL SUERRS (LP,2,NUMERR)
C
C  CHECK NUMBER OF MDR BOXES PROCESSED
1470  IF (NMDR.EQ.3) GO TO 1480
         WRITE (LP,2120) NMDR
         CALL SUERRS (LP,2,NUMERR)
C
C  WRITE MARO PARAMETERS IF NO ERRORS ENCOUNTERED
1480  IF (NUMERR.EQ.0) GO TO 1490
         WRITE (LP,2520) XMAROI,NUMERR
         CALL SULINE (LP,2)
         ISTAT=1
         GO TO 1660
C
C  CHECK IF RUNCHECK OPTION SPECIFIED
1490  IF (IRUNCK.EQ.1) GO TO 1660
C
C- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
C
C  DEFINE TIME SERIES IN PROCESSED DATA BASE
C
      NPRERR=0
C
C  GET STANDARD INTERNAL DATA UNITS FOR EACH TYPE
      DO 1520 I=1,NTSTYP
         DO 1500 J=1,NTYPE
            IF (TSTYPE(I).EQ.TYPE(J)) GO TO 1510
1500        CONTINUE
            WRITE (LP,2540) TSTYPE(I)
            CALL SUERRS (LP,2,NUMERR)
            NPRERR=NPRERR+1
            GO TO 1520
1510     TSUNIT(I)=UNIT(J)
1520     CONTINUE
C
      IF (LDEBUG.EQ.0) GO TO 1540
         WRITE (IOSDBG,2550)
         CALL SULINE (IOSDBG,1)
         DO 1530 I=1,NTSTYP
            WRITE (IOSDBG,2560) TSTYPE(I),ITSIND(I),TSUNIT(I),ITSINT(I)
            CALL SULINE (IOSDBG,1)
1530        CONTINUE
C
C  CHECK IF TIME SERIES EXISTS
1540  CALL SUDOPN (1,'PRD ',IERR)
      IF (IERR.EQ.0) GO TO 1550
         NPRERR=NPRERR+1
         GO TO 1630
1550  MAXX=1
      DO 1560 I=1,NTSTYP
         IF (ITSIND(I).LE.0) GO TO 1560
            LXBUF=1
            CALL RPRDH (XMAROI,TSTYPE(I),MAXX,IHEAD,LXBUF,XBUF,FTSID,
     *         IERR)
            IF (IERR.EQ.1) GO TO 1560
               WRITE (LP,2570) TSTYPE(I)
               CALL SUWRNS (LP,2,NUMWRN)
               ITSIND(I)=0
1560     CONTINUE
      IF (NPRERR.GT.0) GO TO 1630
C
C  WRITE OR UDPATE TIME SERIES HEADER
      LXBUF=0
      NPDT=1
      FTSID=BLNK8
      IPRERR=1
      DO 1590 I=1,NTSTYP
         IF (ITSIND(I).EQ.-1.OR.ITSIND(I).EQ.0) GO TO 1590
         CALL SUPRDW (TSTYPE(I),LSWORK,ITSINT(I),NPDT,LXBUF,IPRERR,
     *      LPRDW,NUMERR,IERR)
         IF (IERR.GT.0) GO TO 1570
         CALL WPRDH (XMAROI,TSTYPE(I),ITSINT(I),TSUNIT(I),NPDT,CENTRD,
     *      FTSID,XDESCR,LXBUF,XBUF,LSWORK,SWORK,IREC,IERR)
         IF (IERR.EQ.0) GO TO 1580
            CALL SWPRST (8HWPRDH   ,XMAROI,TSTYPE(I),ITSINT(I),
     *         TSUNIT(I),FTSID,LSWORK,NPDT,IERR)
1570        WRITE (LP,2580) TSTYPE(I),XMAROI
            CALL SUERRS (LP,2,NPRERR)
            GO TO 1590
1580     CALL SUDWRT (1,'PRD ',IERR)
         WRITE (LP,2600) TSTYPE(I),XMAROI
         CALL SULINE (LP,2)
         IF (I.GT.1) ITSREC(I-1)=IREC
1590     CONTINUE
C
C  UPDATE TIME SERIES
      DO 1620 I=1,NTSTYP
         IF (ITSIND(I).EQ.-1.OR.ITSIND(I).EQ.1) GO TO 1620
         CALL SUPRDW (TSTYPE(I),LSWORK,ITSINT(I),NPDT,LXBUF,IPRERR,
     *      LPRDW,NUMERR,IERR)
         IF (IERR.GT.0) GO TO 1600
         CALL WPRDC (XMAROI,TSTYPE(I),TSUNIT(I),CENTRD,
     *      XDESCR,FTSID,LXBUF,XBUF,LSWORK,SWORK,IREC,IERR)
         IF (IERR.EQ.0) GO TO 1610
            CALL SWPRST (8HWPRDC   ,XMAROI,TSTYPE(I),ITSINT(I),
     *         TSUNIT(I),FTSID,LSWORK,NPDT,IERR)
            IF (IERR.EQ.8) GO TO 1620
1600        WRITE (LP,2590) TSTYPE(I),XMAROI
            CALL SUERRS (LP,2,NPRERR)
            GO TO 1620
1610     CALL SUDWRT (1,'PRD ',IERR)
         WRITE (LP,2610) TSTYPE(I),XMAROI
         CALL SULINE (LP,2)
         IF (I.GT.1) ITSREC(I-1)=IREC
1620     CONTINUE
C
1630  IF (NPRERR.EQ.0) GO TO 1640
         WRITE (LP,2620) NPRERR
         CALL SULINE (LP,2)
         ISTAT=1
         GO TO 1660
C
C- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
C
C  WRITE MARO PARAMETERS TO FILE
C
1640  IVMARO=1
      NGRID=NGPA
      IF (LDEBUG.GT.0) WRITE (IOSDBG,2630) MDRGPA
      IF (LDEBUG.GT.0) CALL SULINE (IOSDBG,1)
      CALL SWMARO (IVMARO,XMAROI,XDESCR,CENTRD,NGRID,
     *   ITSREC,NMSGPA,XSTAID,MMDRBX,MDRGPA,NMGPA,NMRFRO,UNSD,
     *   LARRAY,ARRAY,IPTR,DISP,IERR)
      IF (IERR.EQ.0) GO TO 1650
         ISTAT=1
         GO TO 1660
C
1650  IF (PRPARM.EQ.XNO) GO TO 1660
C
C  READ MARO PARAMETERS
      IPTR=0
      IPRERR=1
      INCLUDE 'scommon/callsrmaro'
      IF (IERR.GT.0) GO TO 1660
C
C  PRINT MARO PARAMETERS
      IPRNT=1
      INCLUDE 'scommon/callspmaro'
C
1660  IF (ISTRCE.GT.0) THEN
         WRITE (IOSDBG,2640)
         CALL SULINE (IOSDBG,1)
         ENDIF
C
      RETURN
C
C- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
C
1670  FORMAT (' *** ENTER SFMARO')
1680  FORMAT (1H )
1690  FORMAT ('0*--> DEFINE MEAN AREAL RUNOFF PARAMETERS')
1700  FORMAT ('0DEFINE OPTIONS IN EFFECT :  DISP=',A4,3X,'PRPARM=',A4,
     *   3X,'PRNOTE=',A4)
1710  FORMAT (' NUMFLD=',I2,3X,'MINFLD=',I2,3X,'MAXFLD=',I2,3X,
     *   'NUMERR=',I2,3X,'NOPFLD=',I2,3X,'NXTFLD=',I2,3X,'CHK=',5A4)
1720  FORMAT ('0*** ERROR - DISPOSITION OF NEW WAS SPECIFIED FOR ',
     *   'AREA ',2A4,' BUT MARO PARAMETERS ALREADY EXIST.')
1730  FORMAT ('0*** WARNING - MARO PARAMETERS FOR AREA ',2A4,
     *   ' DO NOT EXIST. DISP ASSUMED TO BE NEW FOR THIS DATA GROUP.')
1740  FORMAT ('0*** ERROR - PREPROCESSOR PARAMETRIC DATA BASE FILES ',
     *   'ARE NOT ALLOCATED. INPUT DATA WILL BE CHECKED FOR ERRORS.')
1750  FORMAT ('0*** ERROR - MARO PARAMETERS CANNOT BE DEFINED BECAUSE ',
     *   'GENERAL USER PARAMETERS NOT DEFINED.')
1760  FORMAT ('0*** ERROR - GMDR PARAMETERS NOT SUCCESSFULLY ',
     *   'READ. STATUS CODE RETURNED FROM SRGMDR = ',I2)
1770  FORMAT ('0*** ERROR - GMDR PARAMETERS ARE NOT DEFINED. @MDRGRID ',
     *   'COMMAND HAS NOT BEEN RUN.')
1780  FORMAT ('0*** ERROR - DATA TYPE FILE NOT SUCCESSFULLY ',
     *   'READ. STATUS CODE RETURNED FROM UDTYPE = ',I2)
1790  FORMAT ('0TYPE DIMN UNIT MISS NVAL TIME NADD')
1800  FORMAT (1H ,3(A4,1X),2(I4,1X),A4,1X,I4)
1810  FORMAT (' UDTYPE CALLED : NTYPE=',I2)
1820  FORMAT ('0*** ERROR - INVALID DEFINE MARO AREA OPTION ',
     *   'IN INPUT FIELD ',I2,' (CARD FIELD ',I2,') : ',5A4)
1830  FORMAT ('0*** ERROR - PROCESSING OPTION : ',5A4)
1840  FORMAT ('0*** ERROR - FIELD ',I2,' EXCEEDS MAXIMUM ALLOWABLE ',
     *   'FIELDS (',I2,').')
1850  FORMAT (' NUMBER OF NULL FIELDS TO BE REPEATED = ',I2)
1860  FORMAT ('0*** ERROR - ',I3,' IS AN INVALID NUMBER OF NULL ',
     *   'TO BE REPEATED. CURRENT FIELD IS ',I2,'. MAXIMUM REQUIRED ',
     *   'FIELDS ALLOWED IS ',I2,'.')
1870  FORMAT (' PTYPE=',A4)
1880  FORMAT ('0*** NOTE - UNITS CODE (',A4,') FOUND IN CARD FIELD ',
     *   I2,' NOT USED FOR DEFINING MARO PARAMETERS.')
1890  FORMAT (' BLANK STRING FOUND IN FIELD ',I2)
1900  FORMAT ('0*** NOTE - RIGHT PARENTHESES ASSUMED IN INPUT FIELD ',
     *   I2,' (CARD FIELD ' ,I2,').')
1910  FORMAT (' INPUT FIELD = ',5A4)
1920  FORMAT ('0*** NOTE - REMAINING AREA MARO PARAMETERS WILL ',
     *   'BE FILLED WITH DEFAULT VALUES.')
1930  FORMAT ('0*** ERROR - NO VALUE FOUND FOR REQUIRED INPUT FIELD ',
     *   I2,' (CARD FIELD ',I2,').')
1940  FORMAT ('0*** ERROR - NO VALUE FOUND FOR OPTIONAL INPUT FIELD ',
     *   I2,' (CARD FIELD ',I2,').')
1950  FORMAT ('0*** ERROR - INVALID DEFINE MARO PARAMETER TYPE : ',A4)
1960  FORMAT ('0*** ERROR - NON-CHARACTER DATA EXPECTED IN INPUT ',
     *   'FIELD ',I2,' (CARD FIELD ',I2,').')
1970  FORMAT ('0*** ERROR - PROCESSING DEFINE AREA MARO OPTION ',
     *   'NUMBER ',I2,'.')
1980  FORMAT ('0*** WARNING - LENGTH OF AREA IDENTIFIER (',I2,
     *   ') EXCEEDS MAXIMUM CHARACTERS. LENGTH SET TO 8 CHARACTERS.')
1990  FORMAT ('0*** WARNING - LENGTH OF AREA DESCRIPTION (',I2,
     *   ') EXCEEDS MAXIMUM CHARACTERS. LENGTH SET TO 20 CHARACTERS.')
2000  FORMAT ('0*** ERROR - NO VALUE FOUND FOR REQUIRED INPUT FIELD ',
     *   I2,' (CARD FIELD ',I2,').')
2010  FORMAT ('0*** ERROR - MARO AREA LATITUDE (',F9.2,') DOES NOT ',
     *   'FALL WITHIN USER DEFINED LIMITS (',F9.2,' TO ',F9.2,').')
2020  FORMAT ('0*** ERROR - MARO AREA LONGITUDE (',F9.2,') DOES NOT ',
     *   'FALL WITHIN USER DEFINED LIMITS (',F9.2,' TO ',F9.2,').')
2030  FORMAT ('0*** WARNING - LENGTH OF STATION IDENTIFIER (',I2,
     *   ') EXCEEDS MAXIMUM CHARACTERS. LENGTH SET TO 8 CHARACTERS.')
2040  FORMAT ('0*** ERROR - STATION ',2A4,' IS NOT DEFINED.')
2050  FORMAT ('0*** ERROR - STATION ',2A4,' IS DEFINED BUT HAS A ',
     *   'STATUS OF INCOMPLETE.')
2060  FORMAT ('0*** ERROR - STATION ',2A4,' IS DEFINED BUT DOES ',
     *   'HAVE ',A4,' DATA.')
2070  FORMAT ('0*** ERROR - STATION ',2A4,' IS DEFINED BUT HAS A ',
     *   'PCPN TIME INTERVAL OF ',I2,' HOURS. TIME INTERVAL MUST BE ',
     *   '6 HOURS.')
2080  FORMAT ('0*** ERROR - STATION ',2A4,' IS DEFINED BUT PARAMETER ',
     *   'ARRAY VERSION NUMBER (',I2,') INDICATES GRID POINT ADDRESS ',
     *   'IS NOT DEFINED.')
2090  FORMAT ('0*** ERROR - STATION ',2A4,' IS DEFINED BUT GRID POINT ',
     *   'ADDRESS (',I4,') IS NOT DEFINED.')
2100  FORMAT ('0*** ERROR - MAXIMUM NUMBER OF MDR BOXES ',
     *   '(3) EXCEEDED IN INPUT FIELD ',I2,'+ (CARD FIELD ',I2,').')
2110  FORMAT ('0*** ERROR - NUMBER OF GRID POINT ADDRESSES (',I4,
     *   ') DOES NOT EQUAL NUMBER OF RAINFALL-RUNOFF RELATIONSHIPS (',
     *   I4,').')
2120  FORMAT ('0*** ERROR - NUMBER OF MDR BOXES ',
     *   '(',I2,') DOES NOT EQUAL 3.')
2130  FORMAT ('0*** WARNING - MARO MDR BOXES HAVE ',
     *   'ALREADY BEEN DEFINED.')
2140  FORMAT ('0*** ERROR - NO MARO MDR BOXES ',
     *   'FOUND IN INPUT FIELD ',I2,' (CARD FIELD ',I2,').')
2150  FORMAT ('0*** ERROR - PROCESSING MDR BOX NUMBERS ',
     *   'INDICATOR (',A4,') IN INPUT FIELD ',I2,' (CARD FIELD ',
     *   I2,').')
2160  FORMAT ('0*** ERROR - NO MDR BOXES FOUND.')
2170  FORMAT ('0*** ERROR - NO INDICATORS TO NOT GENERATE TIME SERIES ',
     *   'FOUND.')
2180  FORMAT ('0*** WARNING - GRID POINT ADDRESSES HAVE ',
     *   'ALREADY BEEN DEFINED.')
2190  FORMAT ('0*** ERROR - NO GRID POINT ADDRESSES ',
     *   'FOUND IN INPUT FIELD ',I2,' (CARD FIELD ',I2,').')
2200  FORMAT ('0*** ERROR - NO RAINFALL-RUNOFF RELATIONSHIP NUMBERS ',
     *   'FOUND IN INPUT FIELD ',I2,' (CARD FIELD ',I2,').')
2210  FORMAT ('0*** WARNING - RAINFALL-RUNOFF RELATIONSHIPS HAVE ',
     *   'ALREADY BEEN DEFINED.')
2220  FORMAT ('0*** ERROR - PROCESSING RAINFALL-RUNOFF RELATIONSHIP ',
     *   'INDICATOR (',A4,') IN INPUT FIELD ',I2,' (CARD FIELD ',
     *   I2,').')
2230  FORMAT ('0*** ERROR - CONTENTS OF CARD FIELD ',I2,' COULD NOT ',
     *   'BE CONVERTED TO AN INTEGER VALUE.')
2240  FORMAT ('0*** ERROR - GRID POINT ADDRESS MUST BE 3 OR 4 DIGITS. ',
     *   'VALUE FOUND IN CARD FIELD ',I2,' HAS ',I2,' CHARACTERS.')
2250  FORMAT ('0*** ERROR - MAXIMUM NUMBER OF GRID POINT ADDRESSES (',
     *   I3,') EXCEEDED IN INPUT FIELD ',I2,
     *   ' (CARD FIELD ',I2,').')
2260  FORMAT ('0*** ERROR - RAINFALL RUNOFF NUMBER MUST BE GREATER ',
     *   'THAN ZERO.')
2270  FORMAT ('0*** ERROR - MAXIMUM NUMBER OF RAINFALL-RUNOFF ',
     *   'RELATIONSHIP NUMBERS (',I3,') EXCEEDED IN INPUT FIELD ',I2,
     *   ' (CARD FIELD ',I2,').')
2280  FORMAT ('0*** ERROR - NO GRID POINT ADDRESSES FOUND.')
2290  FORMAT ('0*** ERROR - NO RAINFALL-RUNOFF RELATIONSHIP NUMBERS ',
     *   'FOUND.')
2300  FORMAT ('0*** ERROR - GRID POINT BOX ',I2,' MUST BE ',
     *   'GREATER THAN 0 AND LESS THAN 100. VALUE INPUT IS ',I4,'.')
2310  FORMAT ('0*** ERROR - GRID BOX ',I4,' IS NOT DEFINED.')
2320  FORMAT ('0*** ERROR - NO RAINFALL-RUNOFF RELATIONSHIPS ',
     *  'ARE DEFINED.')
2330  FORMAT ('0*** ERROR - RAINFALL-RUNOFF RELATIONSHIP ',I4,
     *   ' IS NOT DEFINED.')
2340  FORMAT ('0*** ERROR - NO TIME SERIES GENERATE OPTION ',
     *   'FOUND IN INPUT FIELD ',I2,' (CARD FIELD ',I2,').')
2350  FORMAT ('0*** ERROR - PROCESSING TIME SERIES GENERATE ',
     *   'INDICATOR (',A4,') IN INPUT FIELD ',I2,' (CARD FIELD ',
     *   I2,').')
2360  FORMAT ('0*** WARNING - INDICATOR TO NOT GENERATE TIME SERIES ',
     *   'HAS ALREADY BEEN DEFINED.')
2370  FORMAT ('0*** ERROR - INVALID TIME SERIES TYPE NOT TO BE ',
     *   'GENERATED : ',5A4)
2380  FORMAT (' MARO AREA IDENTIFIER SET TO : ',2A4)
2390  FORMAT (' MARO AREA DESCRIPTION SET TO : ',5A4)
2400  FORMAT (' MARO AREA LATITUDE SET TO : ',F9.2)
2410  FORMAT (' MARO AREA LONGITUDE SET TO : ',F9.2)
2420  FORMAT (' FIRST ORDER STATION IDENTIFIER SET TO : ',2A4)
2430  FORMAT (' FIRST ORDER STATION GRID POINT ADDRESS SET TO : ',I4)
2440  FORMAT (' NUMMDR=',I2,3X,'NROW=',I4,3X,'NCOL=',I4)
2450  FORMAT (' MDR BOX ',I1,' SET TO : ',I5)
2460  FORMAT (' IMDRGP=',I5)
2470  FORMAT ('0*** ERROR - CENTROID OF MDR BOX NUMBER ',I2,
     *   ' (ROW=',I3,1X,'COL=',I3,') DOES NOT ',
     *   'FALL WITHIN THE GRID SYSTEM.')
2480  FORMAT (' MDR BOX GRID POINT ADDRESS ',I1,' SET TO : ',I5)
2490  FORMAT (' GRID POINT ADDRESS ',I2,' SET TO : ',I5)
2500  FORMAT (' RAINFALL-RUNOFF RELATIONSHIP ',I2,' SET TO : ',I5)
2510  FORMAT (' TIME SERIES GENERATE INDICATOR=',A4,3X,
     *   'ITSIND SET TO : ',3(I2,1X))
2520  FORMAT ('0*** NOTE - AREA MARO PARAMETERS FOR AREA ',2A4,
     *   ' NOT WRITTEN BECAUSE ',I2,' ERRORS ENCOUNTERED.')
2530  FORMAT ('0*** WARNING - NO MARO PARAMETER VALUES FOUND.')
2540  FORMAT ('0*** ERROR - DATA TYPE ',A4,' NOT FOUND IN DATA TYPE ',
     *   'COMMON BLOCK.')
2550  FORMAT (' TSTYPE',3X,'ITSIND',3X,'TSUNIT',3X,'ITSINT')
2560  FORMAT (1H ,A4,2X,3X,I6,3X,A4,2X,3X,I6)
2570  FORMAT ('0*** WARNING - TIME SERIES FOR DATA TYPE ',A4,
     *   ' ALREADY EXISTS AND WILL BE UPDATED.')
2580  FORMAT ('0*** ERROR - ',A4,' TIME SERIES FOR AREA ',2A4,
     *   ' NOT DEFINED BECAUSE ERRORS ENCOUNTERED.')
2590  FORMAT ('0*** ERROR - ',A4,' TIME SERIES FOR AREA ',2A4,
     *   ' NOT REDEFINED BECAUSE ERRORS ENCOUNTERED.')
2600  FORMAT ('0*** NOTE - ',A4,' TIME SERIES SUCCESSFULLY WRITTEN ',
     *   'FOR AREA ',2A4,'.')
2610  FORMAT ('0*** NOTE - ',A4,' TIME SERIES SUCCESSFULLY UPDATED ',
     *   'FOR AREA ',2A4,'.')
2620  FORMAT ('0*** NOTE - MARO PARAMETERS NOT WRITTEN BECAUSE ',I2,
     *   ' ERRORS ENCOUNERED WRITING TO PROCESSED DATA BASE.')
2630   FORMAT (' MDRGPA=',3(I5,1X))
2640  FORMAT (' *** EXIT SFMARO')
C
      END
