C MODULE SFSTBN
C-----------------------------------------------------------------------
C
C  ROUTINE TO DEFINE STATE BOUNDARY (STBN) PARAMETERS.
C
      SUBROUTINE SFSTBN (LARRAY,ARRAY,DISP,NFLD,
     *   IRUNCK,ISTAT)
C
      CHARACTER*4 DISP
      CHARACTER*4 TDISP,WDISP,TYPE,UNITS
      CHARACTER*20 CHAR/' '/,CHK/' '/
      CHARACTER*4 IBNPT
      CHARACTER*4 IQUOTE/'''   '/,IDOT/'.   '/
      CHARACTER*4 IBLNK/'    '/,IDOLR/'$   '/
      CHARACTER*4 ISTBNP(89,42)
C
      DIMENSION ARRAY(LARRAY)
      DIMENSION MDRBND(4)
C
      INCLUDE 'uio'
      INCLUDE 'scommon/sudbgx'
      INCLUDE 'ufreex'
      INCLUDE 'scommon/sugnlx'
C
C    ================================= RCS keyword statements ==========
      CHARACTER*68     RCSKW1,RCSKW2
      DATA             RCSKW1,RCSKW2 /                                 '
     .$Source: /fs/hseb/ob72/rfc/ofs/src/ppinit_define/RCS/sfstbn.f,v $
     . $',                                                             '
     .$Id: sfstbn.f,v 1.3 1998/07/06 12:28:40 page Exp $
     . $' /
C    ===================================================================
C
C
C
      IF (ISTRCE.GT.0) THEN
         WRITE (IOSDBG,570)
         CALL SULINE (IOSDBG,1)
         ENDIF
C
C  SET DEBUG LEVEL
      LDEBUG=ISBUG('DEFN')
C
      ISTAT=0
C
      LCHAR=LEN(CHAR)/4
      LCHK=LEN(CHK)/4
C
      ILPFND=0
      IRPFND=0
      ISTRT=-1
C
      NUMFLD=0
      MINFLD=6
      MAXREP=4
      DO 15 I=1,89
         DO 10 J=1,42
            ISTBNP(I,J)=IBLNK
10          CONTINUE
15       CONTINUE
C
      MAXCOL=42
      NUMERR=0
      NUMWRN=0
C
C  CHECK NUMBER OF LINES LEFT ON PAGE
      IF (ISLEFT(10).GT.0) CALL SUPAGE
C
C  PRINT CARD
      CALL SUPCRD
C
C  PRINT HEADER LINE
      WRITE (LP,590)
      CALL SULINE (LP,2)
      WRITE (LP,580)
      CALL SULINE (LP,2)
C
C  PRINT OPTIONS
      TDISP=DISP
      WRITE (LP,610) TDISP
      CALL SULINE (LP,2)
C
C  SET VALUE FOR MISSING PARAMETER
      UNUSD=-999.
      IUNDEF=-997
C
C  STORE INDICATOR TO PRINT ERROR IF QUOTES NOT IN PAIRS
      ICDQTO=ICDQTE
C
C- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
C
C  CHECK IF PREPROCESSOR PARAMETRIC DATA BASE ALLOCATED
      IDPPP=1
      CALL SUDALC (0,0,0,0,IDPPP,0,0,0,0,0,NUMERR,IERR)
      IF (IERR.NE.0) THEN
         WRITE (LP,660)
         CALL SUERRS (LP,2,NUMERR)
         GO TO 90
         ENDIF
C
C- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
C
      IF (IUGFIL.EQ.0) THEN
C     READ USER GENERAL PARAMETERS
         IPRERR=0
         INCLUDE 'scommon/callsrugnl'
         IF (IERR.EQ.2) THEN
            WRITE (LP,620)
            CALL SUERRS (LP,2,NUMERR)
            DO 25 I=1,4
               MDRSUB(I)=IUNDEF
25             CONTINUE
            GO TO 40
            ENDIF
         IF (LDEBUG.GT.0) THEN
C        PRINT UGNL PARAMETERS
            UNITS='ENGL'
            INCLUDE 'scommon/callspugnl'
            ENDIF
         ENDIF
C
C  CHECK IF MDR SUBSET DEFINED
      IF (MDRSUB(1).EQ.-997) THEN
         WRITE (LP,630)
         CALL SUERRS (LP,2,NUMERR)
         ENDIF
C
C- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
C
C  READ STBN PARAMETER RECORD
40    IPRERR=0
      CALL SRSTBN (IVSTBN,UNUSED,MDRBND,ISTBNP,LARRAY,ARRAY,IPRERR,
     *   IERR)
C
C  PARAMETERS EXIST AND DISP IS NEW
      IF (IERR.EQ.0.AND.TDISP.EQ.'NEW') THEN
         WRITE (LP,640)
         CALL SUERRS (LP,2,NUMERR)
         GO TO 90
         ENDIF
C
C  PARAMETERS DO NOT EXIST AND DISP IS OLD
      IF (IERR.GT.0.AND.TDISP.EQ.'OLD') THEN
         TDISP='NEW'
         WRITE (LP,650) TDISP
         CALL SUWRNS (LP,2,NUMWRN)
         ENDIF
C
C  PRINT STBN PARAMETERS
      IF (LDEBUG.GT.0.AND.IERR.EQ.0) THEN
         CALL SPSTBN (IVSTBN,UNUSED,MDRBND,ISTBNP,IERR)
         ENDIF
C
C- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
C
C  CHECK FIELDS FOR DEFINE STBN OPTIONS
C
90    INULL=0
      NULREP=0
      CALL UFIELD (NFLD,ISTRT,LENGTH,ITYPE,NREP,INTEGR,REAL,LCHAR,CHAR,
     *   LLPAR,LRPAR,LASK,LATSGN,LAMPS,LEQUAL,IFIELD)
      IF (NFLD.EQ.-1) GO TO 530
      IF (LDEBUG.GT.0) THEN
         CALL UPRFLD (NFLD,ISTRT,LENGTH,ITYPE,NREP,INTEGR,REAL,
     *      LCHAR,CHAR,LLPAR,LRPAR,LASK,LATSGN,LAMPS,LEQUAL,IFIELD)
         ENDIF
C
C  CHECK FOR PAIRED PARENTHESES
      IF (ILPFND.GT.0.AND.IRPFND.EQ.0) THEN
         WRITE (LP,700) NFLD
         CALL SULINE (LP,2)
         ILPFND=0
         IRPFND=0
         ENDIF
      IF (LLPAR.GT.0) ILPFND=1
      IF (LRPAR.GT.0) IRPFND=1
C
C  CHECK FOR NULL FIELD
      IF (IFIELD.NE.1) GO TO 140
         IF (LDEBUG.GT.0) THEN
            WRITE (IOSDBG,690) NFLD
            CALL SULINE (IOSDBG,1)
            ENDIF
         INULL=1
         GO TO 210
C
C  CHECK FOR REPEATED NULL FIELD
140   IF (CHAR.EQ.',,'.OR.CHAR.EQ.'NULL') THEN
         IF (LDEBUG.GT.0) THEN
            WRITE (IOSDBG,*) 'NREP=',NREP
            CALL SULINE (LP,1)
            ENDIF
         IF (NREP.GT.0.AND.NREP.LE.MAXREP) GO TO 150
            WRITE (LP,720) NREP,MAXREP
            CALL SUERRS (LP,2,NUMERR)
150      NREP=MAXREP-NUMFLD
         NULREP=NREP-1
         INULL=1
         GO TO 200
         ENDIF
C
C  CHECK FOR COMMAND
      IF (LATSGN.EQ.1) GO TO 530
C
C  CHECK FOR PARENTHESIS IN FIELD
      IF (LLPAR.GT.0) CALL UFPACK (LCHK,CHK,ISTRT,1,LLPAR-1,IERR)
      IF (LLPAR.EQ.0) CALL UFPACK (LCHK,CHK,ISTRT,1,LENGTH,IERR)
C
C  CHECK FOR END OF INPUT
      IF (CHK.EQ.'/') GO TO 530
C
C  IF FIRST FIELD, CONTENTS HAS BEEN CHECK FOR KEYWORD
      IF (NUMFLD.EQ.0) GO TO 200
C
C  CHECK FOR KEYWORD
      CALL SUIDCK ('DEFN',CHK,NFLD,0,IKEYWD,IUIDCK)
      IF (LDEBUG.GT.0) THEN
         WRITE (IOSDBG,*) 'CHK=',CHK
         CALL SULINE (IOSDBG,1)
         ENDIF
      IF (IUIDCK.EQ.2) THEN
         IF (TDISP.EQ.'NEW'.AND.NUMFLD.LT.MINFLD) THEN
            WRITE (LP,740) CHK(1:LENSTR(CHK))
            CALL SUERRS (LP,2,NUMERR)
            GO TO 510
            ENDIF
         GO TO 530
         ENDIF
C
C  PRINT CARD
200   IF (NUMFLD.GT.0.AND.NFLD.EQ.1) CALL SUPCRD
C
C  CHECK IF MAXIMUM NUMBER OF FIELD EXPECTED EXCEEDED
210   NUMFLD=NUMFLD+1
      IF (NUMFLD.GT.MINFLD-1) GO TO 410
C
      IF (LDEBUG.GT.0) THEN
         WRITE (IOSDBG,600) NUMFLD,NUMERR
         CALL SULINE (LP,1)
         ENDIF
C         
      GO TO (220,240,280,330,370),NUMFLD
      WRITE (LP,670) NUMFLD
      CALL SULINE (LP,2)
      GO TO 90
C
C- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
C
C  CHECK PARAMETER TYPE
C
220   IF (CHK.NE.'STBN') THEN
         WRITE (LP,760) CHK(1:LENSTR(CHK))
         CALL SUERRS (LP,2,NUMERR)
         GO TO 90
         ENDIF
      TYPE=CHK
      IF (LDEBUG.GT.0) THEN
         WRITE (IOSDBG,*) 'TYPE=',TYPE
         CALL SULINE (IOSDBG,1)
         ENDIF
      GO TO 90
C
C- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
C
C  WESTERN MOST MDR COLUMN
C
240   NSUB=1
      IF (INULL.EQ.0) GO TO 250
         WRITE (LP,750) NSUB,NFLD
         CALL SUERRS (LP,2,NUMERR)
         GO TO 500
250   IF (ITYPE.EQ.0) GO TO 260
         WRITE (LP,770) NFLD
         CALL SUERRS (LP,2,NUMERR)
         GO TO 500
260   MDRBND(NSUB)=INTEGR
      IF (MDRBND(NSUB).EQ.MDRSUB(NSUB)) GO TO 270
         IF (MDRSUB(NSUB).EQ.IUNDEF) GO TO 500
            WRITE (LP,780) MDRBND(NSUB),MDRSUB(NSUB)
            CALL SUERRS (LP,2,NUMERR)
            GO TO 500
270   IF (LDEBUG.GT.0) THEN
         WRITE (IOSDBG,790) MDRBND(NSUB)
         CALL SULINE (IOSDBG,1)
         ENDIF
      GO TO 500
C
C- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
C
C  NUMBER OF MDR COLUMNS
C
280   NSUB=2
      IF (INULL.EQ.0) GO TO 290
         WRITE (LP,750) NSUB,NFLD
         CALL SUERRS (LP,2,NUMERR)
         GO TO 500
290   IF (ITYPE.EQ.0) GO TO 300
         WRITE (LP,770) NFLD
         CALL SUERRS (LP,2,NUMERR)
         GO TO 500
300   MDRBND(NSUB)=INTEGR
      IF (MDRBND(NSUB).EQ.MDRSUB(NSUB)) GO TO 310
         IF (MDRSUB(2).EQ.IUNDEF) GO TO 500
            WRITE (LP,800) MDRBND(NSUB),MDRSUB(NSUB)
            CALL SUERRS (LP,2,NUMERR)
            GO TO 500
310   IF (MDRBND(NSUB).LE.MAXCOL) GO TO 320
         WRITE (LP,810) MDRBND(NSUB),MAXCOL
         CALL SUERRS (LP,2,NUMERR)
         GO TO 500
320   IF (LDEBUG.GT.0) THEN
         WRITE (IOSDBG,820) MDRBND(NSUB)
         CALL SULINE (IOSDBG,1)
         ENDIF
      GO TO 500
C
C- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
C
C  SOUTHERN MOST MDR ROW
C
330   NSUB=3
      IF (INULL.EQ.0) GO TO 340
         WRITE (LP,750) NSUB,NFLD
         CALL SUERRS (LP,2,NUMERR)
         GO TO 500
340   IF (ITYPE.EQ.0) GO TO 350
         WRITE (LP,770) NFLD
         CALL SUERRS (LP,2,NUMERR)
         GO TO 500
350   MDRBND(NSUB)=INTEGR
      IF (MDRBND(NSUB).EQ.MDRSUB(NSUB)) GO TO 360
         IF (MDRSUB(3).EQ.IUNDEF) GO TO 500
            WRITE (LP,830) MDRBND(NSUB),MDRSUB(NSUB)
            CALL SUERRS (LP,2,NUMERR)
            GO TO 500
360   IF (LDEBUG.GT.0) THEN
         WRITE (IOSDBG,840) MDRBND(NSUB)
         CALL SULINE (IOSDBG,1)
         ENDIF
      GO TO 500
C
C- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
C
C  NUMBER OF MDR ROWS
C
370   NSUB=4
      IF (INULL.EQ.0) GO TO 380
         WRITE (LP,750) NSUB,NFLD
         CALL SUERRS (LP,2,NUMERR)
         GO TO 405
380   IF (ITYPE.EQ.0) GO TO 390
         WRITE (LP,770) NFLD
         CALL SUERRS (LP,2,NUMERR)
         GO TO 405
390   MDRBND(4)=INTEGR
      IF (MDRBND(NSUB).EQ.MDRSUB(NSUB)) GO TO 400
         IF (MDRSUB(NSUB).EQ.IUNDEF) GO TO 405
            WRITE (LP,850) MDRBND(NSUB),MDRSUB(NSUB)
            CALL SUERRS (LP,2,NUMERR)
            GO TO 405
400   IF (LDEBUG.GT.0) THEN
         WRITE (IOSDBG,860) MDRBND(NSUB)
         CALL SULINE (IOSDBG,1)
         ENDIF
C
C  SET INDICATOR TO NOT PRINT ERROR IF QUOTES NOT IN PAIRS
405   ICDQTE=0
      GO TO 500
C
C- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
C
C  STATE BOUNDARY DEFINITION
C
410   IF (ITYPE.EQ.0) GO TO 420
         WRITE (LP,770) NFLD
         CALL SUERRS (LP,2,NUMERR)
         GO TO 490
420   IROW=INTEGR
C
C  CHECK IF ROW FALLS IN SUBSET
      MROW=MDRBND(3)+MDRBND(4)-1
      IF (IROW.GE.MDRBND(3).AND.IROW.LE.MROW) GO TO 430
         WRITE (LP,870) IROW,MDRBND(3),MROW
         CALL SUERRS (LP,2,NUMERR)
         GO TO 490
430   IF (LDEBUG.GT.0) THEN
         WRITE (LP,880) IROW
         CALL SULINE (LP,1)
         ENDIF
C
      IBEG=ISTRT+LENGTH+1
      NUMCOL=MDRBND(2)
      IEND=IBEG+NUMCOL
      IF (IEND.LE.ICDSTP) GO TO 440
         WRITE (LP,890) IEND,ICDSTP
         CALL SUWRNS (LP,2,NUMWRN)
         NUMCOL=ICDSTP-IBEG+1
440   IF (NUMCOL.GT.MAXCOL) NUMCOL=MAXCOL
C
C  CHECK FOR CHARACTERS AFTER LAST STATE BOUNDARY POINT
      ICOL=IBEG+NUMCOL
      NFND=0
      DO 450 I=ICOL,ICDSTP
         IF (ICDBUF(I:I).EQ.IDOLR) GO TO 470
         IF (ICDBUF(I:I).EQ.IBLNK) GO TO 450
         NFND=NFND+1
         IF (NFND.GT.1) GO TO 450
            WRITE (LP,900) NUMCOL
            CALL SUWRNS (LP,2,NUMWRN)
450      CONTINUE
C
C  CHECK FOR INVALID CHARACTERS
      DO 460 I=1,NUMCOL
         IPOS=IBEG+I-1
         IF (ICDBUF(IPOS:IPOS).EQ.IDOT.OR.
     *       ICDBUF(IPOS:IPOS).EQ.IQUOTE.OR.
     *       ICDBUF(IPOS:IPOS).EQ.IBLNK) GO TO 460
         WRITE (LP,910) ICDBUF(IPOS:IPOS),IPOS,IROW
         CALL SULINE (LP,2)
460   CONTINUE
C
C  STORE STATE BOUNDARY POINTS
470   DO 480 ICOL=1,NUMCOL
         IBNPT=IBLNK
         CALL SUBSTR (ICDBUF(IBEG+ICOL-1:IBEG+ICOL-1),1,1,IBNPT,2)
         ISTBNP(IROW,ICOL)=IBNPT
         IF (LDEBUG.GT.0) THEN
            WRITE (IOSDBG,920) IROW,ICOL,IBNPT
            CALL SULINE (IOSDBG,1)
            ENDIF
480      CONTINUE
      IF (LDEBUG.GT.0) THEN
         WRITE (LP,930) (ISTBNP(IROW,I),I=1,NUMCOL)
         CALL SULINE (LP,1)
         ENDIF
490   NFLD=0
      GO TO 500
C
C- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
C
C  CHECK FOR REPEATED NULL FIELDS
500   IF (NULREP.EQ.0) GO TO 90
         NULREP=NULREP-1
         GO TO 200
C
C- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
C
C  MAXIMUM FIELDS PROCESSED BUT NO KEYWORD FOUND - SEARCH FOR
C  NEXT KEYWORD
510   ISTRT=-1
520   CALL UFIELD (NFLD,ISTRT,LENGTH,ITYPE,NREP,INTEGR,REAL,LCHAR,CHAR,
     *   LLPAR,LRPAR,LASK,LATSGN,LAMPS,LEQUAL,IFIELD)
      IF (LATSGN.EQ.1) GO TO 530
      IF (LLPAR.GT.0) CALL UFPACK (LCHK,CHK,ISTRT,1,LLPAR-1,IERR)
      IF (LLPAR.EQ.0) CALL UFPACK (LCHK,CHK,ISTRT,1,LENGTH,IERR)
      IF (CHK.EQ.'/') GO TO 530
      CALL SUIDCK ('DEFN',CHK,NFLD,0,IKEYWD,IUIDCK)
      IF (IUIDCK.EQ.2) GO TO 530
         WRITE (LP,950) NFLD,CHAR
         CALL SUWRNS (LP,2,NUMWRN)
         GO TO 520
C
C  RESET INDICATOR TO PRINT ERROR IF QUOTES NOT IN PAIRS
530   ICDQTE=ICDQTO
C
C  CHECK NUMBER OF FIELDS PROCESSED
      IF (NUMFLD.LT.MINFLD) THEN
         WRITE (LP,960)
         CALL SULINE (LP,2)
         GO TO 560
         ENDIF
C
C  CHECK IF RUNCHECK OPTION SPECIFIED
      IF (IRUNCK.EQ.1) GO TO 560
C
C  WRITE PARAMETERS IF NO ERRORS ENCOUNTERED
      IF (NUMERR.GT.0) THEN
         WRITE (LP,940) NUMERR
         CALL SULINE (LP,2)
         ISTAT=1
         GO TO 560
         ENDIF
C
C  WRITE PARAMETERS TO FILE
      IVSTBN=1
      WDISP=TDISP
      CALL SWSTBN (IVSTBN,UNUSD,MDRBND,ISTBNP,LARRAY,ARRAY,WDISP,IERR)
      IF (IERR.GT.0) GO TO 560
C
C  READ PARAMETERS
      IPRERR=1
      CALL SRSTBN (IVSTBN,UNUSED,MDRBND,ISTBNP,LARRAY,ARRAY,IPRERR,
     *   IERR)
      IF (IERR.GT.0) GO TO 560
C
C  PRINT PARAMETERS
      CALL SPSTBN (IVSTBN,UNUSED,MDRBND,ISTBNP,IERR)
C
560   IF (ISTRCE.GT.0) THEN
         WRITE (IOSDBG,970)
         CALL SULINE (IOSDBG,1)
         ENDIF
C
      RETURN
C
C- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
C
570   FORMAT (' *** ENTER SFSTBN')
580   FORMAT ('0*--> DEFINE STATE BOUNDARY PARAMETERS')
590   FORMAT (' ')
600   FORMAT (' NUMFLD=',I2,3X,'NUMERR=',I2)
610   FORMAT ('0DEFINE OPTIONS IN EFFECT :  ',
     *   'DISP=',A4)
620   FORMAT ('0*** ERROR - UGNL PARAMETERS ARE NOT DEFINED.')
630   FORMAT ('0*** ERROR - MDR SUBSET NOT DEFINED IN UGNL ',
     *   'PARAMETERS. STBN PARAMETERS CANNOT BE DEFINED.')
640   FORMAT ('0*** ERROR - DISPOSITION OF NEW WAS SPECIFIED FOR ',
     *   'STBN PARAMETERS BUT PARAMETERS ALREADY EXIST.')
650   FORMAT ('0*** WARNING - STBN PARAMETER RECORD DOES NOT EXIST. ',
     *   'DISP ASSUMED TO BE ',A,'.')
660   FORMAT ('0*** ERROR - PREPROCESSOR PARAMETRIC DATA BASE FILES ',
     *   'ARE NOT ALLOCATED. INPUT DATA WILL BE CHECKED FOR ERRORS.')
670   FORMAT ('0*** ERROR - FIELD ',I2,' EXCEEDS MAXIMUM ALLOWABLE ',
     *   'FIELDS (4).')
690   FORMAT (' NULL FIELD FOUND IN INPUT FIELD ',I2)
700   FORMAT ('0*** NOTE - RIGHT PARENTHESES ASSUMED. IN CARD FIELD ',
     *   I2,'.')
720   FORMAT ('0*** ERROR - ',I3,' IS AN INVALID NUMBER OF NULL ',
     *   'FIELDS TO BE REPEATED. MAXIMUM REPEAT FIELDS ALLOWED IS ',I2,
     *   '.')
740   FORMAT ('0*** NOTE - THE KEYWORD ',A,' WAS FOUND WHEN ',
     *   'ANOTHER STBN FIELD WAS EXPECTED.')
750   FORMAT ('0*** ERROR - MDR SUBSET PARAMETER NUMBER ',I2,
     *   ' IN CARD FIELD ',I2,' CANNOT BE A NULL FIELD.')
760   FORMAT ('0*** ERROR - INVALID GENERAL PARAMETER TYPE : ',A4)
770   FORMAT ('0*** ERROR - INTEGER DATA EXPECTED IN CARD FIELD ',I2,
     *   '.')
780   FORMAT ('0*** ERROR - WESTERN MOST MDR COLUMN (',I4,
     *   ') DOES NOT EQUAL USER DEFINED WESTERN MOST MDR COLUMN (',
     *   I4,').')
790   FORMAT (' WESTERN MDR COLUMN SET TO ',I4)
800   FORMAT ('0*** ERROR - NUMBER OF MDR COLUMNS (',I4,
     *   ') DOES NOT EQUAL USER DEFINED NUMBER OF MDR COLUMNS (',
     *   I4,').')
810   FORMAT ('0*** ERROR - NUMBER OF MDR COLUMNS (',I4,') EXCEEDS ',
     *   'MAXIMUM NUMBER OF MDR COLUMNS ALLOWED (',I2,').')
820   FORMAT (' NUMBER OF MDR COLUMNS SET TO ',I4)
830   FORMAT ('0*** ERROR - SOUTHERN MOST MDR ROW (',I4,
     *   ') DOES NOT EQUAL USER DEFINED SOUTHERN MOST MDR ROW (',
     *   I4,').')
840   FORMAT (' SOUTHERN MDR ROW SET TO ',I4)
850   FORMAT ('0*** ERROR - NUMBER OF MDR ROWS (',I4,
     *   ') DOES NOT EQUAL USER DEFINED NUMBER OF MDR ROWS (',
     *   I4,').')
860   FORMAT (' NUMBER OF MDR ROWS SET TO ',I4)
870   FORMAT ('0*** ERROR - ROW NUMBER (',I3,') IS LESS THAN THE ',
     *   'SOUTHERN MOST ROW SPECIFIED (',I3,
     *   ') OR GREATER THAN NORTHERN MOST ROW SPECIFIED (',I3,').')
880   FORMAT (' MDR ROW NUMBER = ',I2)
890   FORMAT ('0*** WARNING - LAST STATE BOUNARY POINT IS IN COLUMN ',
     *   I2,'. ONLY THE FIRST ',I2,' COLUMNS OF THE CARD ARE ',
     *   'PROCESSED.')
900   FORMAT ('0*** WARNING - NON-BLANK CHARACTERS FOUND AFTER ',
     *   'USER SPECIFIED NUMBER OF COLUMNS (',I2,') PROCESSED.')
910   FORMAT ('0*** NOTE - A CHARACTER (',A1,') OTHER THAN A ',
     *   'PERIOD, QUOTE OR BLANK FOUND IN COLUMN ',I2,' OF ROW ',
     *   I2,'.')
920   FORMAT (' IROW=',I3,3X,'ICOL=',I3,3X,'IBNPT=',A4)
930   FORMAT (' POINTS : ',42A3)
940   FORMAT ('0*** NOTE - STBN PARAMETERS NOT WRITTEN TO ',
     *   'BECAUSE ',I2,' ERRORS ENCOUNTERED.')
950   FORMAT ('0*** WARNING - CONTENTS OF FIELD ',I2,' IS NOT A ',
     *   'KEYWORD : ',A)
960   FORMAT ('0*** NOTE - NO PARAMETER VALUES FOUND.')
970   FORMAT (' *** EXIT SFSTBN')
C
      END
