# ----------------------------------------------------------------------------
#
# SOFTWARE HISTORY
#
# Date          Ticket#  Engineer  Description
# ------------- -------- --------- --------------------------------------------
# Oct 22, 2015  17873    lshi      remove quotes from default SVCBU_USER_ID
# Nov 14, 2020  8143     randerso  Change SVCBU_HOST for vm
# Jun 29, 2021  8572     randerso  Removed unused variables. 
#                                  Moved path definitions to serviceBackupUtil.sh
# Sep 20, 2023  2036191  jkelmer   Re-added the ability for a site to specify
#                                  SCVBU_SENDAREA for export_grids
#################################################################


#Variables used by service backup:
#
# SVCBU_HOST:           Server where the service backup scripts will be
#                       executed.
#
# MSG_SEND_COMMAND:     The command executed to send a message via the message handling
#                       system.  This value will usually be msg_send.  But, it can be
#                       changed to a different command in a test environment.
#
# CDSPORT:              This is the port on which the Thrift Client listens
#                       for script execution events.
#
# SVCBU_DB:             Defines which database to use for exporting
#                       grids to central server for service backup.
#                       VALID VALUES: Fcst
#                                     Official (default)
#
# SVCBU_TRIM_ELEMS:     Indication of whether ifpnetCDF needs to trim
#                       off elements while exporting grids to central
#                       server.
#                       VALID VALUES: 1 - To do element trimming
#                                     0 - To disable element trimming
#                       Note: ${IFPS_DATA}/svcbu_export_elements.ccc
#                       file has to be present for this to work. This file
#                       will contain list of elements to include in the
#                       netcdf file that's being sent over to central srv.
#
# SVCBU_GRIDAREA:       The name of the edit area used when exporting grids
#                       to the central server for service backup
#                       DEFAULT VALUE: ISC_Send_Area
#
# SVCBU_ADDRESSEE:      The name of the msg_send addressee. Will be used to
#                       pass with -a flag of msg_send. (NCF use only).
#
# SVCBU_WMO_HEADER:     The WMO header that will be used to pass in calls to
#                       msg_send with -i argument. This will be empty to
#                       begin with. Should not be changed. (NCF use only)
#
# EXPORT_GRID           Indicate the ways of grid being exported
#                       VALID VALUES: 0 = do not export grids
#                                     1 = grids are exported by quartz timer
#                                         at 15 after each hour, the service
#                                             backup GUI, and from GFE via the
#                                             'Send Grids to NDFD...' script
#                                     2 = grids are exported only by the
#                                         service backup GUI and from GFE via
#                                         the 'Send Grids to NDFD...' script'
#
# SVCBU_USER            Indicates that the site can configure a special user to
#                       run GFE when in service backup
#                       VALID VALUES: 0 = do not use a designated user to run
#                                         GFE when in service backup
#                                     1 = use a designated user to run GFE
#                                         when in service backup
#
# SVCBU_USER_ID         The user id of the designated user to run GFE when
#                       in service backup
#
# PRIMARY_SITES         (Optional) For dual-domain sites, a comma-separated
#                       list of sites for the export grids cron to run for
#                       instead of the site defined as AW_SITE_IDENTIFIER. If
#                       this setting is empty or not defined, cron will only
#                       export grids for site set as AW_SITE_IDENTIFIER.
##

SVCBU_HOST=ev
MSG_SEND_COMMAND=msg_send
CDSPORT=9581
SVCBU_DB=Official
SVCBU_TRIM_ELEMS=1
SVCBU_GRIDAREA=ISC_Send_Area
SVCBU_ADDRESSEE="ANCF,BNCF"
SVCBU_WMO_HEADER=SVCBKPIFP
SVCBU_USER=0

# Do not use quotes when setting SVCBU_USER_ID
# Example syntax: SVCBU_USER_ID=backuser
SVCBU_USER_ID=

EXPORT_GRID=1
PRIMARY_SITES=
