#!/bin/ksh
# file name: run_IHFS_RAX_Sync_batch
# Created: 05/24/2007
# Edited : 08/03/2007 - Added unix remove command to delete log files
# Edited : 09/06/2007 - Removed delete log file logic
# Edited : 10/24/2007 - Renamed jar from raxdb_sync.jar to rax_apps.jar

# This allows you to run this script from outside of ./bin
RUN_FROM_DIR=`dirname $0`

# set up SOME environment variables for RAX applications
. /rfc_arc/lib/rax.profile

# need to add a path to the jar file for this application
export CLASSPATH=$DB_DRIVER_PATH:$RUN_FROM_DIR/rax_apps.jar

# Java bin directory
JBINDIR=$SYS_JAVA_DIR/bin

# run application using java
$JBINDIR/java ohd.hseb.raxdb_sync.RaxDbSyncBatch $IHFS_JDBCURL $RAX_JDBCURL
