C MEMBER PM0326
C  (from old member FCPM0326)
C
      SUBROUTINE PM0326(WORK,IUSEW,LEFTW,NP03,GETTS,GETCO,NCOVAL,
     .                  LENDSU,JDEST,IERR)
C---------------------------------------------------------------------
C  SUBROUTINE TO READ AND INTERPRET PARAMETER INPUT FOR S/U #3
C    PRESCRIBED ELEVATION
C---------------------------------------------------------------------
C  JTOSTROWSKI - HRL - MARCH 1983
C----------------------------------------------------------------
C
      INCLUDE 'common/comn26'
C
C
      INCLUDE 'common/err26'
C
C
      INCLUDE 'common/fld26'
C
C
      INCLUDE 'common/read26'
C
C
C
      INCLUDE 'common/suky26'
C
C
      INCLUDE 'common/warn26'
C
C
      DIMENSION INPUT(2,2),LINPUT(2),WORK(1),IP(2)
      LOGICAL GETTS,GETCO,ENDFND,HOK,OPTOK,ALLOK
C
C    ================================= RCS keyword statements ==========
      CHARACTER*68     RCSKW1,RCSKW2
      DATA             RCSKW1,RCSKW2 /                                 '
     .$Source: /fs/hseb/ob72/rfc/ofs/src/fcinit_res/RCS/pm0326.f,v $
     . $',                                                             '
     .$Id: pm0326.f,v 1.1 1995/09/17 18:51:56 dws Exp $
     . $' /
C    ===================================================================
C
C
      DATA INPUT/4HHVAL,4HUE  ,4HOPTI,4HON  /
      DATA LINPUT/2,2/
      DATA NINPUT/2/
      DATA NDINPU/2/
C
      DATA TS/4HTS  /
C
C  INITIALIZE LOCAL VARIABLES AND COUNTERS
C
      NP03 = 0
      GETTS = .FALSE.
      GETCO = .FALSE.
      HOK = .FALSE.
      OPTOK = .TRUE.
      ALLOK = .TRUE.
      OPT = 0.01
C
      DO 3 I = 1,2
           IP(I) = 0
    3 CONTINUE
C
      IERR = 0
C
C  PARMS FOUND, LOOKING FOR ENDP
C
      LPOS = LSPEC + NCARD + 1
      LASTCD = LENDSU
      IBLOCK = 1
C
    5 IF (NCARD .LT. LASTCD) GO TO 8
           CALL STRN26(59,1,SUKYWD(1,7),3)
           IERR = 99
           GO TO 9
    8 NUMFLD = 0
      CALL UFLD26(NUMFLD,IERF)
      IF(IERF .GT. 0 ) GO TO 9000
      NUMWD = (LEN -1)/4 + 1
      IDEST = IKEY26(CHAR,NUMWD,SUKYWD,LSUKEY,NSUKEY,NDSUKY)
      IF (IDEST.EQ.0) GO TO 5
C
C  IDEST = 7 IS FOR ENDP
C
      IF (IDEST.EQ.7.OR.IDEST.EQ.8) GO TO 9
          CALL STRN26(59,1,SUKYWD(1,7),3)
          JDEST = IDEST
          IERR = 89
    9 LENDP = NCARD
C
C  ENDP CARD OR TS OR CO FOUND AT LENDP,
C  ALSO ERR RECOVERY IF NEITHER ONE OF THEM FOUND.
C
C
      IBLOCK = 2
      CALL POSN26(MUNI26,LPOS)
      NCARD = LPOS - LSPEC -1
C
   10 CONTINUE
      NUMFLD = 0
      CALL UFLD26(NUMFLD,IERF)
      IF(IERF .GT. 0) GO TO 9000
      NUMWD = (LEN -1)/4 + 1
      IDEST = IKEY26(CHAR,NUMWD,INPUT,LINPUT,NINPUT,NDINPU)
      IF(IDEST .GT. 0) GO TO 50
      IF(NCARD .GE. LENDP) GO TO 300
C
C  NO VALID KEYWORD FOUND
C
      CALL STER26(1,1)
      ALLOK = .FALSE.
      GO TO 10
C
C  NOW SEND CONTROL TO PROPER LOCATION FOR PROCESSING EXPECTED INPUT
C
   50 CONTINUE
      GO TO (100,200) , IDEST
C
C-----------------------------------------------------------------------
C  'HVALUE' REQUIRED. IF NOT FOUND, SIGNAL AN ERROR.
C
  100 CONTINUE
      IP(1) = IP(1) + 1
      IF (IP(1).GT.1) CALL STER26(39,1)
C
C  'HVALUE' FOUND. NEXT FIELD MUST BE EITHER 'TS' OR A REAL VALUE.
C
C
      NUMFLD = -2
      CALL UFLD26(NUMFLD,IERF)
      IF (IERF.GT.0) GO TO 9000
C
C
C  IF NEXT FIELD IS ALL CHARACTERS, IT MUST BE 'TS'
C
      IF (ITYPE.EQ.2) GO TO 160
C
C  SET INDICATOR FOR USER SPECIFIED ELEVATION
C
      WHICH = 0.01
C
C  SEE IF ELEVATION IS WITHIN BOUNDS OF ELEV VS. STORAGE CURVE
C
      HVAL = REAL/CONVL
C
      DO 120 J=2,NSE
      IF (ELSTOR(J-1).LE.HVAL.AND.HVAL.LE.ELSTOR(J)) GO TO 150
  120 CONTINUE
C
      CALL STER26(63,1)
      GO TO 10
C
  150 CONTINUE
      HOK = .TRUE.
      GO TO 10
C
C------------------------------
C  CHARACTER FIELD FOUND AFTER 'HVALUE'. IT MUST BE 'TS'
C
  160 CONTINUE
      IF (IUSAME(CHAR,TS,1).EQ.1) GO TO 170
C
      CALL STER26(1,1)
      GO TO 10
C
  170 CONTINUE
      WHICH = 1.01
      GETTS = .TRUE.
      HOK = .TRUE.
      GO TO 10
C-----------------------------------------------------------------
C  'OPTION' KEYWORD EXPECTED. ONLY ALLOWED IF ELEVATION IS TIME-SERIES
C   SPECIFIED. IF FOUND, GET NEXT FIELD ON CARD.
C   IF NOT FOUND, STORE VALUES IN WORK ARRAY USING DEFAULT
C
  200 CONTINUE
      NCPVAL = 0
C
      IP(2) = IP(2) + 1
      IF (IP(2).GT.1) CALL STER26(39,1)
      IF (GETTS) GO TO 210
           CALL STRN26(60,1,INPUT(1,IDEST),LINPUT(IDEST))
           GO TO 10
C
C  AN INTEGER VALUE ( OR A NULL FIELD) MUST FOLLOW
C
  210 CONTINUE
      OPTOK = .FALSE.
      NUMFLD = -2
      CALL UFLD26(NUMFLD,IERF)
      IF (IERF.GT.1) GO TO 9000
      IF (IERF.EQ.1) GO TO 250
C
      IF (ITYPE.EQ.0) GO TO 220
      CALL STER26(5,1)
      GO TO 10
C
  220 CONTINUE
C
C  OPTION MUST BE .GE. ZERO
C
      IF (INTEGR.GE.0) GO TO 230
C
      CALL STER26(95,1)
      GO TO 10
C
  230 CONTINUE
      OPT = REAL
      NCOVAL = INTEGR
      IF (NCOVAL.GT.0) GETCO = .TRUE.
      GO TO 250
C
C  EVERYTHING IS OK
C
  250 CONTINUE
      OPTOK = .TRUE.
      GO TO 10
C
C--------------------------------------------------------------------
C  END OF INPUT. STORE VALUES IN WORK ARRAY IF EVERYTHING WAS ENTERED
C  WITHOUT ERROR.
C
  300 CONTINUE
C
      IF (IP(1).EQ.0) CALL STRN26(59,1,INPUT(1,1),LINPUT(1))
C
      IF (HOK.AND.OPTOK.AND.ALLOK) GO TO 310
      GO TO 9999
C
C  DIFFERENT VALUES NEED TO BE STORED IF PRESCRIBED H IS USER-DEFINED
C  OR EXPECTED FROM A TIME-SERIES.
C
  310 CONTINUE
      IF (GETTS) GO TO 350
C
C  THIS SECTION IS FOR USER-DEFINED ELEVATION
C
      CALL FLWK26(WORK,IUSEW,LEFTW,WHICH,501)
      CALL FLWK26(WORK,IUSEW,LEFTW,HVAL,501)
      NP03 = 2
      GO TO 9999
C
C  THIS SECTION IS FOR TIME-SERIES SPECIFIED ELEVATION
C
  350 CONTINUE
      CALL FLWK26(WORK,IUSEW,LEFTW,WHICH,501)
      CALL FLWK26(WORK,IUSEW,LEFTW,OPT,501)
      NP03 = 2
      GO TO 9999
C
C--------------------------------------------------------------
C  ERROR IN UFLD26
C
 9000 CONTINUE
      IF (IERF.EQ.1) CALL STER26(19,1)
      IF (IERF.EQ.2) CALL STER26(20,1)
      IF (IERF.EQ.3) CALL STER26(21,1)
      IF (IERF.EQ.4) CALL STER26( 1,1)
C
      IF (NCARD.GE.LASTCD) GO TO 9100
      IF (IBLOCK.EQ.1)  GO TO 5
      IF (IBLOCK.EQ.2)  GO TO 10
C
 9100 USEDUP = .TRUE.
C
 9999 CONTINUE
      RETURN
      END
