C MEMBER TS0826
C  (from old member FCTS0826)
C
      SUBROUTINE TS0826(WORK,IUSEW,LEFTW,NTS08,GETTWO,
     .            LENDSU,JDEST,IERR)
C--------------------------------------------------------------------
C  ROUTINE TO GET AND CHECK TS SPECIFICATIONS FOR S/U #08 -
C   DOWNSTREAM STAGE AND POOL ELEVATION CONTROLLED DISCHARGE.
C---------------------------------------------------------------------
C  JTOSTROWSKI - HRL - DEC 1983
C----------------------------------------------------------------
C
      INCLUDE 'common/comn26'
C
C
      INCLUDE 'common/err26'
C
C
      INCLUDE 'common/fld26'
C
C
      INCLUDE 'common/read26'
C
C
      INCLUDE 'common/suky26'
C
C
      INCLUDE 'common/warn26'
C
C
C
      DIMENSION TSID(2,2),IDT(2),DTYPE(2),IT(2),
     .          INPUT(2,2),LINPUT(2)
      DIMENSION WORK(1)
C
      LOGICAL TS1OK,TS2OK,ALLOK,GETTWO
C
C    ================================= RCS keyword statements ==========
      CHARACTER*68     RCSKW1,RCSKW2
      DATA             RCSKW1,RCSKW2 /                                 '
     .$Source: /fs/hseb/ob72/rfc/ofs/src/fcinit_res/RCS/ts0826.f,v $
     . $',                                                             '
     .$Id: ts0826.f,v 1.1 1995/09/17 18:53:17 dws Exp $
     . $' /
C    ===================================================================
C
C
      DATA INPUT/4HLOCA,4HL1  ,4HLOCA,4HL2  /
      DATA LINPUT/2,2/
      DATA NINPUT/2/
      DATA NDINPU/2/
C
      DATA BLANK/4H    /
C
C  INITIALIZE LOCAL VARIABLES AND COUNTERS
C
      ALLOK = .TRUE.
      TS1OK = .TRUE.
      USEDUP = .FALSE.
      TS2OK = .TRUE.
      NTS08 = 0
C
      DO 3 I = 1,2
           IT(I) = 0
    3 CONTINUE
C
      IERR = 0
C
C  TS FOUND, LOOKING FOR ENDT
C
      LPOS = LSPEC + NCARD + 1
      LASTCD = LENDSU
      IBLOCK = 1
C
    5 IF (NCARD .LT. LASTCD) GO TO 8
           CALL STRN26(59,1,SUKYWD(1,9),3)
           IERR = 99
           GO TO 9
    8 NUMFLD = 0
      CALL UFLD26(NUMFLD,IERF)
      IF(IERF .GT. 0 ) GO TO 9000
      NUMWD = (LEN -1)/4 + 1
      IDEST = IKEY26(CHAR,NUMWD,SUKYWD,LSUKEY,NSUKEY,NDSUKY)
      IF (IDEST.EQ.0) GO TO 5
C
C  IDEST = 9 IS FOR ENDT
C
      IF (IDEST.EQ.9.OR.IDEST.EQ.10) GO TO 9
          CALL STRN26(59,1,SUKYWD(1,9),3)
          JDEST = IDEST
          IERR = 89
    9 LENDT = NCARD
C
C  ENDT CARD OR PARMS OR CO FOUND AT LENDT,
C  ALSO ERR RECOVERY IF NEITHER ONE OF THEM FOUND.
C
C
      IBLOCK = 2
      CALL POSN26(MUNI26,LPOS)
      NCARD = LPOS - LSPEC -1
C
   10 CONTINUE
      NUMFLD = 0
      CALL UFLD26(NUMFLD,IERF)
      IF(IERF .GT. 0) GO TO 9000
      NUMWD = (LEN -1)/4 + 1
      IDEST = IKEY26(CHAR,NUMWD,INPUT,LINPUT,NINPUT,NDINPU)
      IF(IDEST .GT. 0) GO TO 50
      IF(NCARD .GE. LENDT) GO TO 300
C
C  NO VALID KEYWORD FOUND
C
      CALL STER26(1,1)
      ALLOK = .FALSE.
      GO TO 10
C
C  NOW SEND CONTROL TO PROPER LOCATION FOR PROCESSING EXPECTED INPUT
C
   50 CONTINUE
      GO TO (100,200), IDEST
C
C----------------------------------------------------------------------
C  'LOCAL1' FOUND. GET THE TS INFO FROM THE REST OF THE LINE.
C   IF NOT FOUND, TS IS NOT TO BE USED. ONLY BLANKS WILL BE STORED.
C
  100 CONTINUE
      IT(1) = IT(1) + 1
      IF (IT(1).GT.1) CALL STER26(39,1)
C
      TS1OK = .FALSE.
      CALL TSID26(TSID(1,IDEST),DTYPE(IDEST),IDT(IDEST),TS1OK)
      IF (.NOT.TS1OK) GO TO 10
C
C  TIME INTERVAL MUST BE EQUAL TO THE OPERATION TIME INTERVAL.
C
  130 CONTINUE
      IF (IDT(IDEST).EQ.MINODT) GO TO 140
C
      CALL STER26(47,1)
      GO TO 10
C
C  SEE IF TIME SERIES EXISTS
C
  140 CONTINUE
      CALL CHEKTS(TSID(1,IDEST),DTYPE(IDEST),IDT(IDEST),
     .            0,DCODE,0,1,IERCK)
      IF (IERCK.EQ.0) GO TO 145
C
      CALL STER26(45,1)
      GO TO 10
C
C  CHECK UNITS FOR THIS TIME-SERIES
C
  145 CONTINUE
      CALL FDCODE(DTYPE(IDEST),UCODE,X,IX,IX,X,IX,IERD)
      IF (UCODE.EQ.UCMS) GO TO 150
C
      CALL STRN26(93,1,UCODE,1)
      GO TO 10
C
C  CHECK DIMENSIONS AGAINST ALLOWED FOR THIS TIME SERIES.
C
  150 CONTINUE
      IF (DCODE.EQ.DIMLT) GO TO 160
C
      CALL STER26(46,1)
      GO TO 10
C
C  SEE IF THIS TIME SERIES WAS ALREADY DEFINED, AND ADD ID TO LIST
C  OF INPUT TIME-SERIES IF IT'S NEW.
C
  160 CONTINUE
      IO = 0
      CALL MLTS26(TSID(1,IDEST),DTYPE(IDEST),IDT(IDEST),IO,IERM)
      IF (IERM.GT.0) GO TO 10
C
C  INPUT IS OK
C
  190 CONTINUE
      TS1OK = .TRUE.
      GO TO 10
C
C----------------------------------------------------------------------
C  'LOCAL2' FOUND. GET THE TS INFO FROM THE REST OF THE LINE.
C
  200 CONTINUE
      IT(2) = IT(2) + 1
      IF (IT(2).GT.1) CALL STER26(39,1)
C
      TS2OK = .FALSE.
      IF (GETTWO) GO TO 210
C
      CALL STRN26(60,1,INPUT(1,2),LINPUT(2))
      GO TO 10
C
C  GET REST OF TS SPECIFICATION.
C
  210 CONTINUE
      CALL TSID26(TSID(1,IDEST),DTYPE(IDEST),IDT(IDEST),TS2OK)
      IF (.NOT.TS2OK) GO TO 10
C
C  SEE IF TIME INTERVAL IS EQUAL TO OPERATION TIME INTERVAL.
C
  230 CONTINUE
      IF (IDT(IDEST).EQ.MINODT) GO TO 240
C
      CALL STER26(47,1)
      GO TO 10
C
C  SEE IF TIME SERIES EXISTS
C
  240 CONTINUE
      CALL CHEKTS(TSID(1,IDEST),DTYPE(IDEST),IDT(IDEST),
     .            0,DCODE,0,1,IERCK)
      IF (IERCK.EQ.0) GO TO 245
C
      CALL STER26(45,1)
      GO TO 10
C
C  CHECK UNITS FOR THIS TIME-SERIES
C
  245 CONTINUE
      CALL FDCODE(DTYPE(IDEST),UCODE,X,IX,IX,X,IX,IERD)
      IF (UCODE.EQ.UCMS) GO TO 250
C
      CALL STRN26(93,1,UCODE,1)
      GO TO 10
C
C  CHECK DIMENSIONS AGAINST ALLOWED FOR THIS TIME SERIES.
C
  250 CONTINUE
      IF (DCODE.EQ.DIMLT) GO TO 260
C
      CALL STER26(46,1)
      GO TO 10
C
C  SEE IF THIS TIME SERIES WAS ALREADY DEFINED, AND ADD ID TO LIST
C  OF INPUT TIME-SERIES IF IT'S NEW.
C
  260 CONTINUE
      IO = 0
      CALL MLTS26(TSID(1,IDEST),DTYPE(IDEST),IDT(IDEST),IO,IERM)
      IF (IERM.GT.0) GO TO 10
C
C  INPUT IS OK
C
  290 CONTINUE
      TS2OK = .TRUE.
      GO TO 10
C
C------------------------------------------------------------------
C  'ENDT' FOUND. STORE TS INFO IF INPUT WAS ERROR FREE
C
  300 CONTINUE
      IF (ALLOK.AND.TS1OK.AND.TS2OK) GO TO 310
C
C  IF ERRORS OCCURRED, JUST EXIT
C
      GO TO 9999
C
  310 CONTINUE
C
      NEND = 1
      IF (GETTWO) NEND = 2
C
      DO 320 IDEST = 1,NEND
C
C  IF THE TIME-SERIES IS NOT TO BE USED, JUST STORE AN ALL BLANK ID
C  IN 'WORK'.
C
      IF (IT(IDEST).EQ.0) GO TO 315
C
      DT = IDT(IDEST) + 0.01
      CALL FLWK26(WORK,IUSEW,LEFTW,TSID(1,IDEST),501)
      CALL FLWK26(WORK,IUSEW,LEFTW,TSID(2,IDEST),501)
      CALL FLWK26(WORK,IUSEW,LEFTW,DTYPE(IDEST),501)
      CALL FLWK26(WORK,IUSEW,LEFTW,DT,501)
      CALL FLWK26(WORK,IUSEW,LEFTW,0.01,501)
C
      NTS08 = NTS08 + 5
      GO TO 320
C
C  STORE ALL BLANK ID IF TS IS NOT USED.
C
  315 CONTINUE
      CALL FLWK26(WORK,IUSEW,LEFTW,BLANK,501)
      CALL FLWK26(WORK,IUSEW,LEFTW,BLANK,501)
      NTS08 = NTS08 + 2
C
  320 CONTINUE
      GO TO 9999
C
C--------------------------------------------------------------
C  ERROR IN UFLD26
C
 9000 CONTINUE
      IF (IERF.EQ.1) CALL STER26(19,1)
      IF (IERF.EQ.2) CALL STER26(20,1)
      IF (IERF.EQ.3) CALL STER26(21,1)
      IF (IERF.EQ.4) CALL STER26( 1,1)
C
      IF (NCARD.GE.LASTCD) GO TO 9100
      IF (IBLOCK.EQ.1)  GO TO 5
      IF (IBLOCK.EQ.2)  GO TO 10
C
 9100 USEDUP = .TRUE.
C
 9999 CONTINUE
      RETURN
      END
