#!/bin/sh

dir=`dirname $0`

sedCmd=''
if [ -n "$1" ]
then
        sedCmd="s/Change-Id/Amend: $1\n\nChange-Id/"
fi

sedCmd="sed -i '$sedCmd'"

git add -A
export EDITOR=$sedCmd
echo "EDITOR command = $EDITOR"
git commit --amend

# Push
$dir/upush

# Show stats
$dir/ustat
