#!/bin/bash

if [ -z "$1" ] 
then
        echo "Enter a commit message in the form: 'Issue #xxx did something'"
else
        # Add all files to index
        git add -A

        # Commit using first argument as message
        git commit -m "$1"

        git status
fi
