#!/bin/bash

# Get current branch name
branch=`git branch | grep "*"`
branch="${branch:2}"

# Set remote push repo to branch
git config remote.origin.push $branch:refs/for/$branch

git pull --rebase

# Push now
git push

git status
