C MEMBER XEST24
C  (from old member PPXEST24)
C
      SUBROUTINE XEST24(PP24,PT24,MDR6,PPSR,CHAR,OP24,PARM,LWORK,IERR)
C.......................................
C     THIS SUBROUTINE ESTIMATES MISSING 24 HOUR TOTALS FOR
C      STATIONS WITH ONLY DAILY PRECIP REPORTS.  ALSO DISPLAYS
C       OBSERVED AND ESTIMATED VALUES IF REQUESTED.
C.......................................
C     WRITTEN BY--ERIC ANDERSON, HRL--FEBRUARY 1983
C.......................................
      INTEGER*2 PP24(1),PT24(1),MDR6(1),PPSR(1),CHAR(1),OP24(1)
      INTEGER*2 MSNG24,MSNG6,MSGMDR,MSNGSR,VAL,MDR24,MDRSIX(4)
       DIMENSION PARM(1),STA(2)
C
C     COMMON BLOCKS
      COMMON/PUDBUG/IOPDBG,IPTRCE,NDBUG,PDBUG(20),IPALL
      COMMON/XSIZE/NMAP,NDUPL,NSLT24,NSLOT6,LDATA6,LMDR,LPPSR,
     1  MSNG24,MSNG6,MSGMDR,MSNGSR,NRECTP,MXTEMP,SMALL
      COMMON/XDISPL/MDRPRT,MDRCOM,IPRT24,IPLT24,IPRT6,IPRSSR,
     1 IPRSRW,MAPPRT,METRIC,LASTDY,IPRDAY,IPLTMP
      COMMON/IONUM/IN,IPR,IPU
      COMMON/XTIME/KZDA,KDA,KHR,LSTMO,KMO,KID,KYR,KIH,TZCODE,
     1  ISW,IUTMP,NSSR,IDAY
      COMMON/XMDR/MDRSTA,ICTMDR,MDRST6,ICMDR,NCMDR,IRMDR,NRMDR,
     1  NMDR,MDR,MDRNUV
      COMMON/XALPHA/IOP24,NOP24,LOP24,IOPVR,NOPVR,LOPVR
C
C    ================================= RCS keyword statements ==========
      CHARACTER*68     RCSKW1,RCSKW2
      DATA             RCSKW1,RCSKW2 /                                 '
     .$Source: /fs/hseb/ob72/rfc/ofs/src/fcst_map/RCS/xest24.f,v $
     . $',                                                             '
     .$Id: xest24.f,v 1.1 1995/09/17 18:59:33 dws Exp $
     . $' /
C    ===================================================================
C
C
C     DATA STATEMENTS
      DATA PCPN/4HPCPN/
      DATA BLANK/4H    /
      DATA XALL/4HXALL/
C.......................................
C     CHECK TRACE LEVEL
      IF(IPTRCE.GE.1) WRITE(IOPDBG,900)
 900  FORMAT(1H0,17H** XEST24 ENTERED)
C.......................................
C     CHECK IF DEBUG ON.
      IBUG=0
      IF(IPBUG(PCPN).EQ.1) IBUG=1
      JBUG=0
      IF (IPBUG(XALL).EQ.1) JBUG=1
C.......................................
C     SET INITIAL VALUES
      ITITLE=1
      IERR=0
      NPRT=0
      ISAVE=IPRDAY
      NUM=NOP24
      IF (IOP24.EQ.0) NUM=NSLT24
      IF (IPRDAY.EQ.0) GO TO 105
      IPRDAY=IPRT24
  105 IND=24
C.......................................
C.......................................
C     BEGIN LOOP THROUGH ALL 24 HOUR STATIONS.
      IF (NUM.EQ.0) GO TO 99
      DO 100 NN=1,NUM
      IF (IOP24.EQ.0) GO TO 101
      I=OP24(NN)
      N=((I-1)/5)+1
      GO TO 102
  101 I=(NN-1)*5+1
      N=NN
  102 IF(PT24(I).EQ.0) GO TO 100
      J=PT24(I+2)
      IF(J.GT.0) GO TO 100
      IGO=1
      IEST=0
      VAL=PP24(N)
      IF(VAL.EQ.MSNG24) GO TO 140
      IGO=0
      J=PT24(I+3)
      IF (PT24(I+1).GE.10000) GO TO 115
      IF(VAL.GT.0) GO TO 120
      IF(J.GT.-10000) GO TO 110
C
C     DAILY PRECIP. WAS SET TO ZERO IN XPPCHK.
      PT24(I+3)=J+10000
      IF(IPRDAY.LT.2) GO TO 100
      IF (JBUG.EQ.0) GO TO 100
      IEST=-1
      ICF=0
      GO TO 130
  110  IF(PT24(I+4).GE.0) GO TO 120
C
C     DAILY PRECIP. WAS SET TO ZERO BECAUSE MDR WAS ZERO.
      PT24(I+4)=-PT24(I+4)
      IF(IPRDAY.LT.2) GO TO 100
      IF (JBUG.EQ.0) GO TO 100
      IEST=2
      ICF=0
      GO TO 130
C
C     DAILY PRECIP. WAS OBTAINED FROM A COLOCATED GAGE.
 115  PT24(I+1)=PT24(I+1)-10000
      IF(IPRDAY.LT.2) GO TO 100
      IEST=3
      ICF=100
      IF(VAL.GT.0) GO TO 130
      IF(JBUG.EQ.0) GO TO 100
      ICF=0
      GO TO 130
C
C     DAILY PRECIP. WAS OBSERVED
  120 IF ((IPRDAY.EQ.0).AND.(IPLT24.EQ.0)) GO TO 100
      ICF=100
      IF (VAL.GT.0) GO TO 122
      IF (IPRDAY.GT.0) GO TO 130
      GO TO 100
  122 IF(J.LT.0) J=-J
      IW=J/100
      IS=J-IW*100
      IF(IS.EQ.0) GO TO 121
      IF(ISW.EQ.1) GO TO 121
      ICF=IS*5
      GO TO 130
 121  ICF=IW*5
C.......................................
C     READ PCPN PARAMETERS
 130  TYPE=PCPN
      LP=PT24(I)
      LP=IABS(LP)
      STA(1)=BLANK
      STA(2)=BLANK
      LP=-LP
      CALL RPPREC(STA,TYPE,LP,LWORK,PARM(1),NFILL,J,ISTAT)
      IF(ISTAT.EQ.0) GO TO 135
      CALL PSTRDC(ISTAT,TYPE,STA,LP,LWORK,NFILL)
      WRITE(IPR,901)
 901  FORMAT(1H0,40H**FATAL ERROR** THE ABOVE ERROR IS FATAL)
      CALL KILLFN(8HMAP     )
      IERR=1
      GO TO 99
 135  IF(IBUG.EQ.1) CALL PDUMPA(NFILL,PARM(1),TYPE,STA,1)
      IF(IGO.EQ.0) GO TO 137
      IF(IEST.EQ.2) GO TO 165
      GO TO 150
C.......................................
C     PRINT OBSERVED OR ZERO ESTIMATE OR PLOT OBSERVED.
  137 IF (IPRDAY.GT.0) CALL XPRT24(STA,PARM(5),PARM(22),VAL,ITITLE,
     1  NPRT,ICF,IEST,JBUG)
      IF((IPLT24.GT.0).AND.(VAL.GT.0)) CALL XPLT24(VAL,IND,PARM(10),
     1  PARM(11),IEST,ICF,ISW,STA)
      GO TO 100
C.......................................
C     MISSING VALUE--ESTIMATE.
C       CHECK FIRST IF MDR CAN BE USED.
 140  IF((MDR.EQ.0).OR.(MDRSTA.LT.2)) GO TO 130
      MDRBOX=PT24(I+4)
      IF(MDRBOX.EQ.0) GO TO 130
      CALL XPPMDR(MDRBOX,MDR6,KHR,MDR24,MDRSIX,MSNG,ISTAT)
      IF(ISTAT.EQ.1) GO TO 130
      IF (MSNG.EQ.1) GO TO 130
      IF(MDRSTA.GT.2) GO TO 145
      J=MDR24
      IF(J.GT.ICTMDR) GO TO 130
 145  VAL=MDR24
      IEST=2
      GO TO 160
C
C     ESTIMATE USING STATION DATA
 150  NWT=PARM(19)
      INET=PARM(20)
      IF (INET.EQ.0) GO TO 100
      IWGT=PARM(21)
      IF (IWGT.EQ.0) GO TO 100
      LCHAR=PT24(I+1)
      IF(NWT.GT.0) GO TO 155
C
C     USE ONE OVER DISTANCE SQUARED WEIGHTS.
      CALL XESTD2(PP24,PT24,CHAR,PARM(24),PARM(44),PPSR,NSSR,
     1  PARM(12),PARM(13),LCHAR,VAL)
      IEST=1
      GO TO 160
C
C     USE SIGNIFICANT WEIGHTS
 155  CALL XSGFWT(PP24,PT24,CHAR,NWT,PARM(44),PARM(54),LCHAR,VAL)
       IEST=1
C
C     PRINT OR PLOT ESTIMATE IF REQUESTED.
  160 IF ((IPRDAY.LT.2).AND.(IPLT24.LT.2)) GO TO 170
      IF (VAL.GT.0) GO TO 161
      IF ((JBUG.EQ.1).AND.(IPRDAY.EQ.2)) CALL XPRT24(STA,PARM(5),
     1  PARM(22),VAL,ITITLE,NPRT,ICF,IEST,JBUG)
      GO TO 170
  161 IF(IEST.EQ.2) GO TO 130
 165  ICF=0
      IF (IPRDAY.EQ.2) CALL XPRT24(STA,PARM(5),PARM(22),VAL,ITITLE,
     1  NPRT,ICF,IEST,JBUG)
      IF (IPLT24.EQ.2) CALL XPLT24(VAL,IND,PARM(10),PARM(11),IEST,ICF,
     1    ISW,STA)
C
C     STORE ESTIMATE IN PP24 AS A NEGATIVE
C      STORE ESTIMATE ZERO AS -9998
 170  IF(VAL.GT.0) GO TO 175
      PP24(N)=-9998
      GO TO 100
 175  PP24(N)=-VAL
 100  CONTINUE
C.......................................
C.......................................
C     FLUSH PRINT ARRAY IF NOT EMPTY.
      IF(NPRT.EQ.0) GO TO 99
      ITITLE=-1
      CALL XPRT24(STA,PARM(5),PARM(22),VAL,ITITLE,NPRT,ICF,IEST,JBUG)
   99 IPRDAY=ISAVE
      IF(IPTRCE.GE.1) WRITE(IOPDBG,902)
 902  FORMAT(1H0,14H** EXIT XEST24)
      RETURN
      END
