C MODULE XGTSYS
C-----------------------------------------------------------------------
C
      SUBROUTINE XGTSYS
C.......................................
C     THIS SUBROUTINE GETS SYSTEM LEVEL TECHNIQUE VALUES FOR
C         THE MAP FUNCTION
C.......................................
C     WRITTEN BY -- ERIC ANDERSON,HRL -- JULY 1983
C.......................................
      DIMENSION SNAME(2),IARGS(60)
C
C     COMMON BLOCKS
      COMMON/WHERE/IA(2),IND,SUB(2)
      COMMON/IONUM/IN,IPR,IPU
      COMMON/ERRDAT/IOERR,NWARN,NERRS
      COMMON/PUDBUG/IOPDBG,IPTRCE,NDBUG,PDBUG(20),IPALL
      INCLUDE 'common/sysbug'
C
C    ================================= RCS keyword statements ==========
      CHARACTER*68     RCSKW1,RCSKW2
      DATA             RCSKW1,RCSKW2 /                                 '
     .$Source: /fs/hseb/ob72/rfc/ofs/src/fcst_map/RCS/xgtsys.f,v $
     . $',                                                             '
     .$Id: xgtsys.f,v 1.3 2002/02/11 20:44:03 dws Exp $
     . $' /
C    ===================================================================
C
C     DATA STATEMENTS
      DATA SNAME/4HXGTS,4HYS  /
      DATA BLANK,ALL/4H    ,4HALL /
C
C.......................................
C     SET WHERE COMMON BLOCK
      IND=-1
      SUB(1)=SNAME(1)
      SUB(2)=SNAME(2)
C.......................................
C     CALL HCL ROUTINES AND FILL COMMON BLOCKS.
C
      IOUNT=0
      IF (IOUNT.EQ.1) THEN
C
C     COMMON IONUM
C
      CALL HPAST(8HPRINT   ,IPR,ISTAT)
      IF(ISTAT.NE.0)CALL FPHPWN(ISTAT,8HPRINT   )
      IF((IPR.EQ.6).OR.(IPR.EQ.8).OR.(IPR.EQ.9)) GO TO 101
      IPR=6
      WRITE(IPR,900)
 900  FORMAT(1H0,10X,88H**WARNING** THE VALUE FOR TECHNIQUE PRINT MUST B
     1E 6, 8 OR 9--THE PRINT UNIT IS SET TO 6.)
      CALL WARN
  101 CALL HPAST(8HPPPRINT ,IPPPR,ISTAT)
      IF (ISTAT.NE.0) CALL FPHPWN(ISTAT,8HPPPRINT )
      IF ((IPPPR.EQ.6).OR.(IPPPR.EQ.8).OR.(IPPPR.EQ.9)) GO TO 107
      IPPPR=0
      WRITE(IPR,904) IPR
  904 FORMAT(1H0,10X,100H**WARNING** THE VALUE FOR TECHNIQUE PPPRINT MUS
     1T BE 6, 8 OR 9--THE PREPROCESSOR PRINT UNIT IS SET TO,I3)
      CALL WARN
  107 IF (IPPPR.GT.0) IPR=IPPPR
      CALL HPAST(8HPUNCH   ,IPU,ISTAT)
      IF(ISTAT.NE.0) CALL FPHPWN(ISTAT,8HPUNCH   )
      CALL FTEKCK(IPU,8HPUNCH   ,7,IPU,7,7)
C
C     COMMON PUDBUG
C
      CALL HPAST(8HDEBUGPR ,IOPDBG,ISTAT)
      IF(ISTAT.NE.0) CALL FPHPWN(ISTAT,8HDEBUGPR )
      IF((IOPDBG.EQ.6).OR.(IOPDBG.EQ.8).OR.(IOPDBG.EQ.9)) GO TO 102
      IOPDBG=6
      WRITE(IPR,901)
 901  FORMAT(1H0,10X,96H**WARNING** THE VALUE FOR TECHNIQUE DEBUGPR MUST
     1 BE 6, 8 OR 9--THE DEBUG PRINT UNIT IS SET TO 6.)
      CALL WARN
C
C     COMMON ERRDAT
C
 102  CALL HPAST(8HERRORPR ,IOERR,ISTAT)
      IF(ISTAT.NE.0) CALL FPHPWN(ISTAT,8HERRORPR )
      IF((IOERR.EQ.6).OR.(IOERR.EQ.8).OR.(IOERR.EQ.9)) GO TO 109
      IOERR=9
      WRITE(IPR,903)
 903  FORMAT(1H0,10X,96H**WARNING** THE VALUE FOR TECHNIQUE ERRORPR MUST
     1 BE 6, 8 OR 9--THE ERROR PRINT UNIT IS SET TO 9.)
      CALL WARN
C
      ENDIF
C
 109  CALL HPAST(8HPPTRACE ,IPTRCE,ISTAT)
      IF(ISTAT.NE.0) CALL FPHPWN(ISTAT,8HPPTRACE )
      CALL FTEKCK(IPTRCE,8HPPTRACE ,0,IPTRCE,0,5)
C
      NDBUG=0
      IPALL=0
      NDEBGS=0
      IALL=0
      CALL HPASTA(8HPPDEBUG ,60,IVAL,NR,IARGS,ISTAT)
      IF(ISTAT.EQ.0) GO TO 103
      CALL FPHPWN(ISTAT,8HPPDEBUG )
      IF(ISTAT.NE.1) GO TO 109
 103  NR=NR/3
      DO 105 I=1,NR
      CALL HGTSTR(1,IARGS(1+(I-1)*3),CODE,IFL,ISTAT)
      IF(ISTAT.EQ.0) GO TO 104
      WRITE(IPR,902) ISTAT
 902  FORMAT(1H0,10X,81H**ERROR** AN ARGUMENT FOR THE PPDEBUG TECHNIQUE
     1CANNOT BE DECODED--HGTSTR(STATUS=,I2,1H))
      CALL ERROR
      GO TO 105
 104  IF(CODE.EQ.BLANK) GO TO 105
      IF(CODE.NE.ALL) GO TO 106
      IPALL=1
      IALL=1
      GO TO 199
 106  NDBUG=NDBUG+1
      PDBUG(NDBUG)=CODE
      NDEBGS=NDEBGS+1
      IDEBGS(NDEBGS)=CODE
 105  CONTINUE
C.......................................
  199 RETURN
      END
