! Generated by X-Designer


! agcyoffDS

! agcyoffFM

! agcyoffaLbl

! agcyoffaSL

! agcyoffaHSB

! agcyoffaVSB

! agcyoffaL

! agcyoff_addPB

! agcyoff_delPB

! agcyoffsLbl

! agcyoffsSL

! agcyoffsHSB

! agcyoffsVSB

! agcyoffsL

! agcyoff_agencyTxt

! agcyoff_officeTxt

! agcyoffSP

! agcyoff_closePB

! agcyoff_agencyLA

! agcyoff_officeLA

! ao_AvailListLA

! ao_SelectedListLA

