/*
** Generated by X-Designer
*/
/*
**LIBS: -lXm -lXt -lX11
*/

#include <stdlib.h>
#include <X11/Xatom.h>
#include <X11/Intrinsic.h>
#include <X11/Shell.h>

#include <Xm/Xm.h>
#include <Xm/DialogS.h>
#include <Xm/Form.h>
#include <Xm/Frame.h>
#include <Xm/Label.h>
#include <Xm/List.h>
#include <Xm/PushB.h>
#include <Xm/ScrollBar.h>
#include <Xm/Separator.h>
#include <Xm/Text.h>


Widget datumDS = (Widget) NULL;
Widget datumFM = (Widget) NULL;
Widget dtapplyPB = (Widget) NULL;
Widget dtclosePB = (Widget) NULL;
Widget dtdelPB = (Widget) NULL;
Widget dtinfoFrm = (Widget) NULL;
Widget dtinfoFM = (Widget) NULL;
Widget dtdateLbl = (Widget) NULL;
Widget dtdateTxt = (Widget) NULL;
Widget dtelevLbl = (Widget) NULL;
Widget dtelevTxt = (Widget) NULL;
Widget dtinfoLbl = (Widget) NULL;
Widget dt_listLbl = (Widget) NULL;
Widget datumSLB = (Widget) NULL;
Widget dt_horizSB = (Widget) NULL;
Widget dt_vertSB = (Widget) NULL;
Widget datumLB = (Widget) NULL;
Widget datumSP = (Widget) NULL;



void create_datumDS (Widget parent)
{
	Widget children[7];      /* Children to manage */
	Arg al[64];                    /* Arg List */
	register int ac = 0;           /* Arg Count */
	XtPointer tmp_value;             /* ditto */
	XmString xmstrings[16];    /* temporary storage for XmStrings */

	XtSetArg(al[ac], XmNwidth, 485); ac++;
	XtSetArg(al[ac], XmNheight, 385); ac++;
	XtSetArg(al[ac], XmNallowShellResize, TRUE); ac++;
	XtSetArg(al[ac], XmNtitle, "Datum"); ac++;
	XtSetArg(al[ac], XmNminWidth, 485); ac++;
	XtSetArg(al[ac], XmNminHeight, 385); ac++;
	XtSetArg(al[ac], XmNmaxWidth, 485); ac++;
	XtSetArg(al[ac], XmNmaxHeight, 385); ac++;
	datumDS = XmCreateDialogShell ( parent, (char *) "datumDS", al, ac );
	ac = 0;
	XtSetArg(al[ac], XmNwidth, 485); ac++;
	XtSetArg(al[ac], XmNheight, 385); ac++;
	XtSetArg(al[ac], XmNautoUnmanage, FALSE); ac++;
	datumFM = XmCreateForm ( datumDS, (char *) "datumFM", al, ac );
	ac = 0;
	XtSetArg(al[ac], XmNwidth, 85); ac++;
	XtSetArg(al[ac], XmNheight, 35); ac++;
	xmstrings[0] = XmStringGenerate ( (XtPointer) "Save", XmFONTLIST_DEFAULT_TAG, XmCHARSET_TEXT, NULL );
	XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
	dtapplyPB = XmCreatePushButton ( datumFM, (char *) "dtapplyPB", al, ac );
	ac = 0;
	XmStringFree ( xmstrings [ 0 ] );
	XtSetArg(al[ac], XmNwidth, 85); ac++;
	XtSetArg(al[ac], XmNheight, 35); ac++;
	xmstrings[0] = XmStringGenerate ( (XtPointer) "Close", XmFONTLIST_DEFAULT_TAG, XmCHARSET_TEXT, NULL );
	XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
	dtclosePB = XmCreatePushButton ( datumFM, (char *) "dtclosePB", al, ac );
	ac = 0;
	XmStringFree ( xmstrings [ 0 ] );
	XtSetArg(al[ac], XmNwidth, 85); ac++;
	XtSetArg(al[ac], XmNheight, 35); ac++;
	xmstrings[0] = XmStringGenerate ( (XtPointer) "Delete", XmFONTLIST_DEFAULT_TAG, XmCHARSET_TEXT, NULL );
	XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
	dtdelPB = XmCreatePushButton ( datumFM, (char *) "dtdelPB", al, ac );
	ac = 0;
	XmStringFree ( xmstrings [ 0 ] );
	dtinfoFrm = XmCreateFrame ( datumFM, (char *) "dtinfoFrm", al, ac );
	XtSetArg(al[ac], XmNwidth, 461); ac++;
	XtSetArg(al[ac], XmNheight, 83); ac++;
	dtinfoFM = XmCreateForm ( dtinfoFrm, (char *) "dtinfoFM", al, ac );
	ac = 0;
	xmstrings[0] = XmStringGenerate ( (XtPointer) "Date:", XmFONTLIST_DEFAULT_TAG, XmCHARSET_TEXT, NULL );
	XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
	dtdateLbl = XmCreateLabel ( dtinfoFM, (char *) "dtdateLbl", al, ac );
	ac = 0;
	XmStringFree ( xmstrings [ 0 ] );
	XtSetArg(al[ac], XmNmaxLength, 10); ac++;
	XtSetArg(al[ac], XmNcolumns, 10); ac++;
	dtdateTxt = XmCreateText ( dtinfoFM, (char *) "dtdateTxt", al, ac );
	ac = 0;
	xmstrings[0] = XmStringGenerate ( (XtPointer) "Elevation:", XmFONTLIST_DEFAULT_TAG, XmCHARSET_TEXT, NULL );
	XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
	dtelevLbl = XmCreateLabel ( dtinfoFM, (char *) "dtelevLbl", al, ac );
	ac = 0;
	XmStringFree ( xmstrings [ 0 ] );
	XtSetArg(al[ac], XmNmaxLength, 10); ac++;
	XtSetArg(al[ac], XmNcolumns, 10); ac++;
	dtelevTxt = XmCreateText ( dtinfoFM, (char *) "dtelevTxt", al, ac );
	ac = 0;
	XtSetArg(al[ac], XmNframeChildType, XmFRAME_TITLE_CHILD); ac++;
	xmstrings[0] = XmStringGenerate ( (XtPointer) "Information", XmFONTLIST_DEFAULT_TAG, XmCHARSET_TEXT, NULL );
	XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
	dtinfoLbl = XmCreateLabel ( dtinfoFrm, (char *) "dtinfoLbl", al, ac );
	ac = 0;
	XmStringFree ( xmstrings [ 0 ] );
	xmstrings[0] = XmStringGenerate ( (XtPointer) "  Date                                                            Elevation", XmFONTLIST_DEFAULT_TAG, XmCHARSET_TEXT, NULL );
	XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
	dt_listLbl = XmCreateLabel ( datumFM, (char *) "dt_listLbl", al, ac );
	ac = 0;
	XmStringFree ( xmstrings [ 0 ] );
	XtSetArg(al[ac], XmNwidth, 465); ac++;
	XtSetArg(al[ac], XmNvisibleItemCount, 7); ac++;
	XtSetArg(al[ac], XmNlistSizePolicy, XmCONSTANT); ac++;
	datumLB = XmCreateScrolledList ( datumFM, (char *) "datumLB", al, ac );
	ac = 0;
	datumSLB = XtParent ( datumLB );

	XtSetArg(al[ac], XmNhorizontalScrollBar, &dt_horizSB); ac++;
	XtSetArg(al[ac], XmNverticalScrollBar, &dt_vertSB); ac++;
	XtGetValues(datumSLB, al, ac );
	ac = 0;
	datumSP = XmCreateSeparator ( datumFM, (char *) "datumSP", al, ac );


	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNtopOffset, 335); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_OPPOSITE_FORM); ac++;
	XtSetArg(al[ac], XmNbottomOffset, -375); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNleftOffset, 20); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_OPPOSITE_FORM); ac++;
	XtSetArg(al[ac], XmNrightOffset, -135); ac++;
	XtSetValues ( dtapplyPB, al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNtopOffset, 335); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_OPPOSITE_FORM); ac++;
	XtSetArg(al[ac], XmNbottomOffset, -375); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNleftOffset, 350); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_OPPOSITE_FORM); ac++;
	XtSetArg(al[ac], XmNrightOffset, -465); ac++;
	XtSetValues ( dtclosePB, al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNtopOffset, 335); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_OPPOSITE_FORM); ac++;
	XtSetArg(al[ac], XmNbottomOffset, -375); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNleftOffset, 185); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_OPPOSITE_FORM); ac++;
	XtSetArg(al[ac], XmNrightOffset, -300); ac++;
	XtSetValues ( dtdelPB, al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_WIDGET); ac++;
	XtSetArg(al[ac], XmNtopOffset, 10); ac++;
	XtSetArg(al[ac], XmNtopWidget, datumSLB); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_NONE); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNleftOffset, 10); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNrightOffset, 10); ac++;
	XtSetValues ( dtinfoFrm, al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNtopOffset, 10); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_NONE); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNleftOffset, 10); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_NONE); ac++;
	XtSetValues ( dt_listLbl, al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNtopOffset, 35); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_NONE); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNleftOffset, 10); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNrightOffset, 10); ac++;
	XtSetValues ( datumSLB, al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_NONE); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNbottomOffset, 60); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNleftOffset, 0); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNrightOffset, 0); ac++;
	XtSetValues ( datumSP, al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNtopOffset, 10); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_NONE); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNleftOffset, 10); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_NONE); ac++;
	XtSetValues ( dtdateLbl, al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNtopOffset, 36); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNbottomOffset, 10); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNleftOffset, 11); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_NONE); ac++;
	XtSetValues ( dtdateTxt, al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNtopOffset, 10); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_NONE); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_OPPOSITE_WIDGET); ac++;
	XtSetArg(al[ac], XmNleftOffset, 0); ac++;
	XtSetArg(al[ac], XmNleftWidget, dtelevTxt); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_NONE); ac++;
	XtSetValues ( dtelevLbl, al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNtopOffset, 36); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_NONE); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_NONE); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNrightOffset, 10); ac++;
	XtSetValues ( dtelevTxt, al, ac );
	ac = 0;
	if ((children[ac] = dtdateLbl) != (Widget) 0) { ac++; }
	if ((children[ac] = dtdateTxt) != (Widget) 0) { ac++; }
	if ((children[ac] = dtelevLbl) != (Widget) 0) { ac++; }
	if ((children[ac] = dtelevTxt) != (Widget) 0) { ac++; }
	if (ac > 0) { XtManageChildren(children, ac); }
	ac = 0;
	if ((children[ac] = dtinfoFM) != (Widget) 0) { ac++; }
	if ((children[ac] = dtinfoLbl) != (Widget) 0) { ac++; }
	if (ac > 0) { XtManageChildren(children, ac); }
	ac = 0;
	if (datumLB != (Widget) 0) { XtManageChild(datumLB); }
	if ((children[ac] = dtapplyPB) != (Widget) 0) { ac++; }
	if ((children[ac] = dtclosePB) != (Widget) 0) { ac++; }
	if ((children[ac] = dtdelPB) != (Widget) 0) { ac++; }
	if ((children[ac] = dtinfoFrm) != (Widget) 0) { ac++; }
	if ((children[ac] = dt_listLbl) != (Widget) 0) { ac++; }
	if ((children[ac] = datumSP) != (Widget) 0) { ac++; }
	if (ac > 0) { XtManageChildren(children, ac); }
	ac = 0;
}

