/*
** Generated by X-Designer
*/
#ifndef _lwds_h
#define _lwds_h

#define XD_MOTIF



extern Widget lwDS;
extern Widget lwFM;
extern Widget lwstageListLb1;
extern Widget lwstageListLb2;
extern Widget lwstageListLb3;
extern Widget lwSLB;
extern Widget lwhorizSB;
extern Widget lwvertSB;
extern Widget lwLB;
extern Widget lwinfoFrm;
extern Widget lwinfoFM;
extern Widget lwstgTxt;
extern Widget lwdateTxt;
extern Widget lwqTxt;
extern Widget lwnoteLbl;
extern Widget lwnoteTxt;
extern Widget lwstageLbl;
extern Widget lwflowLbl;
extern Widget lwdateLbl;
extern Widget lwinfoLbl;
extern Widget lwSep1;
extern Widget lwokPB;
extern Widget lwapplyPB;
extern Widget lwclosePB;
extern Widget lwnewPB;
extern Widget lwdelPB;

extern void create_lwDS (Widget);


#endif
