/*
** Generated by X-Designer
*/
/*
**LIBS: -lXm -lXt -lX11
*/

#include <stdlib.h>
#include <X11/Xatom.h>
#include <X11/Intrinsic.h>
#include <X11/Shell.h>

#include <Xm/Xm.h>
#include <Xm/DialogS.h>
#include <Xm/Form.h>
#include <Xm/List.h>
#include <Xm/PushB.h>
#include <Xm/RowColumn.h>
#include <Xm/ScrollBar.h>
#include <Xm/Separator.h>
#include <Xm/Text.h>
#include <Xm/CascadeBG.h>
#include <Xm/LabelG.h>


Widget rfieldsDS = (Widget) NULL;
Widget rfieldsFO = (Widget) NULL;
Widget rfieldsSE = (Widget) NULL;
Widget rfields_okPB = (Widget) NULL;
Widget rfieldsOM = (Widget) NULL;
Widget rfieldsLA = (Widget) NULL;
Widget rfieldsCB = (Widget) NULL;
Widget rfieldsPDM = (Widget) NULL;
Widget rownerPB = (Widget) NULL;
Widget rtypePB = (Widget) NULL;
Widget coopCommsPB = (Widget) NULL;
Widget coopRecipPB = (Widget) NULL;
Widget coopSponsPB = (Widget) NULL;
Widget dcpOwnerPB = (Widget) NULL;
Widget gageOwnerPB = (Widget) NULL;
Widget gageMaintPB = (Widget) NULL;
Widget gageTypePB = (Widget) NULL;
Widget hsaPB = (Widget) NULL;
Widget netPB = (Widget) NULL;
Widget rfcPB = (Widget) NULL;
Widget townerPB = (Widget) NULL;
Widget tpayorPB = (Widget) NULL;
Widget ttypePB = (Widget) NULL;
Widget wfoPB = (Widget) NULL;
Widget rfieldswkFO = (Widget) NULL;
Widget rfields_addPB = (Widget) NULL;
Widget rfields_updatePB = (Widget) NULL;
Widget rfields_deletePB = (Widget) NULL;
Widget rfieldsTE = (Widget) NULL;
Widget rfieldsSL = (Widget) NULL;
Widget rfieldsHB = (Widget) NULL;
Widget rfieldsVB = (Widget) NULL;
Widget rfieldsLI = (Widget) NULL;



void create_rfieldsDS (Widget parent)
{
	Widget children[16];      /* Children to manage */
	Arg al[64];                    /* Arg List */
	register int ac = 0;           /* Arg Count */
	XtPointer tmp_value;             /* ditto */
	XmString xmstrings[16];    /* temporary storage for XmStrings */

	XtSetArg(al[ac], XmNallowShellResize, TRUE); ac++;
	rfieldsDS = XmCreateDialogShell ( parent, (char *) "rfieldsDS", al, ac );
	ac = 0;
	XtSetArg(al[ac], XmNautoUnmanage, FALSE); ac++;
	rfieldsFO = XmCreateForm ( rfieldsDS, (char *) "rfieldsFO", al, ac );
	ac = 0;
	rfieldsSE = XmCreateSeparator ( rfieldsFO, (char *) "rfieldsSE", al, ac );
	XtSetArg(al[ac], XmNwidth, 85); ac++;
	XtSetArg(al[ac], XmNheight, 35); ac++;
	rfields_okPB = XmCreatePushButton ( rfieldsFO, (char *) "rfields_okPB", al, ac );
	ac = 0;
#if       ((XmVERSION > 1) && (XmREVISION == 1) && (XmUPDATE_LEVEL < 20))
	xmstrings[0] = XmStringGenerate((XtPointer) "Field:", XmFONTLIST_DEFAULT_TAG, XmCHARSET_TEXT, NULL);
#else  /* ((XmVERSION > 1) && (XmREVISION == 1) && (XmUPDATE_LEVEL < 20)) */
	xmstrings[0] = XmStringCreateLtoR("Field:", (XmStringCharSet) XmFONTLIST_DEFAULT_TAG);
#endif /* ((XmVERSION > 1) && (XmREVISION == 1) && (XmUPDATE_LEVEL < 20)) */
	XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
	rfieldsOM = XmCreateOptionMenu ( rfieldsFO, (char *) "rfieldsOM", al, ac );
	ac = 0;
	XmStringFree ( xmstrings [ 0 ] );
	rfieldsLA = XmOptionLabelGadget ( rfieldsOM );
	rfieldsCB = XmOptionButtonGadget ( rfieldsOM );
	rfieldsPDM = XmCreatePulldownMenu ( rfieldsOM, (char *) "rfieldsPDM", al, ac );
	rownerPB = XmCreatePushButton ( rfieldsPDM, (char *) "rownerPB", al, ac );
	rtypePB = XmCreatePushButton ( rfieldsPDM, (char *) "rtypePB", al, ac );
	coopCommsPB = XmCreatePushButton ( rfieldsPDM, (char *) "coopCommsPB", al, ac );
	coopRecipPB = XmCreatePushButton ( rfieldsPDM, (char *) "coopRecipPB", al, ac );
	coopSponsPB = XmCreatePushButton ( rfieldsPDM, (char *) "coopSponsPB", al, ac );
	dcpOwnerPB = XmCreatePushButton ( rfieldsPDM, (char *) "dcpOwnerPB", al, ac );
	gageOwnerPB = XmCreatePushButton ( rfieldsPDM, (char *) "gageOwnerPB", al, ac );
	gageMaintPB = XmCreatePushButton ( rfieldsPDM, (char *) "gageMaintPB", al, ac );
	gageTypePB = XmCreatePushButton ( rfieldsPDM, (char *) "gageTypePB", al, ac );
	hsaPB = XmCreatePushButton ( rfieldsPDM, (char *) "hsaPB", al, ac );
	netPB = XmCreatePushButton ( rfieldsPDM, (char *) "netPB", al, ac );
	rfcPB = XmCreatePushButton ( rfieldsPDM, (char *) "rfcPB", al, ac );
	townerPB = XmCreatePushButton ( rfieldsPDM, (char *) "townerPB", al, ac );
	tpayorPB = XmCreatePushButton ( rfieldsPDM, (char *) "tpayorPB", al, ac );
	ttypePB = XmCreatePushButton ( rfieldsPDM, (char *) "ttypePB", al, ac );
	wfoPB = XmCreatePushButton ( rfieldsPDM, (char *) "wfoPB", al, ac );
	XtSetArg(al[ac], XmNx, 41); ac++;
	XtSetArg(al[ac], XmNy, 3); ac++;
	XtSetArg(al[ac], XmNwidth, 216); ac++;
	XtSetArg(al[ac], XmNheight, 52); ac++;
	XtSetArg(al[ac], XmNalignment, XmALIGNMENT_BEGINNING); ac++;
	if (rfieldsCB)
		XtSetValues ( rfieldsCB, al, ac );
	ac = 0;
	rfieldswkFO = XmCreateForm ( rfieldsFO, (char *) "rfieldswkFO", al, ac );
	XtSetArg(al[ac], XmNwidth, 85); ac++;
	XtSetArg(al[ac], XmNheight, 35); ac++;
	rfields_addPB = XmCreatePushButton ( rfieldswkFO, (char *) "rfields_addPB", al, ac );
	ac = 0;
	XtSetArg(al[ac], XmNwidth, 85); ac++;
	XtSetArg(al[ac], XmNheight, 35); ac++;
	rfields_updatePB = XmCreatePushButton ( rfieldswkFO, (char *) "rfields_updatePB", al, ac );
	ac = 0;
	XtSetArg(al[ac], XmNwidth, 85); ac++;
	XtSetArg(al[ac], XmNheight, 35); ac++;
	rfields_deletePB = XmCreatePushButton ( rfieldswkFO, (char *) "rfields_deletePB", al, ac );
	ac = 0;
	rfieldsTE = XmCreateText ( rfieldswkFO, (char *) "rfieldsTE", al, ac );
	XtSetArg(al[ac], XmNvisibleItemCount, 11); ac++;
	XtSetArg(al[ac], XmNlistSizePolicy, XmRESIZE_IF_POSSIBLE); ac++;
	rfieldsLI = XmCreateScrolledList ( rfieldswkFO, (char *) "rfieldsLI", al, ac );
	ac = 0;
	rfieldsSL = XtParent ( rfieldsLI );

	XtSetArg(al[ac], XmNhorizontalScrollBar, &rfieldsHB); ac++;
	XtSetArg(al[ac], XmNverticalScrollBar, &rfieldsVB); ac++;
	XtGetValues(rfieldsSL, al, ac );
	ac = 0;
	XtSetArg(al[ac], XmNwidth, 200); ac++;
	if (rfieldsSL)
		XtSetValues ( rfieldsSL, al, ac );
	ac = 0;


	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNtopOffset, 275); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_OPPOSITE_FORM); ac++;
	XtSetArg(al[ac], XmNbottomOffset, -285); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNleftOffset, 0); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_OPPOSITE_FORM); ac++;
	XtSetArg(al[ac], XmNrightOffset, -635); ac++;
	XtSetValues ( rfieldsSE, al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNtopOffset, 290); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_NONE); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNleftOffset, 275); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_NONE); ac++;
	XtSetValues ( rfields_okPB, al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNtopOffset, 17); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_OPPOSITE_FORM); ac++;
	XtSetArg(al[ac], XmNbottomOffset, -151); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNleftOffset, 9); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_OPPOSITE_FORM); ac++;
	XtSetArg(al[ac], XmNrightOffset, -302); ac++;
	XtSetValues ( rfieldsOM, al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNtopOffset, 10); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_OPPOSITE_FORM); ac++;
	XtSetArg(al[ac], XmNbottomOffset, -265); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNleftOffset, 330); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_OPPOSITE_FORM); ac++;
	XtSetArg(al[ac], XmNrightOffset, -630); ac++;
	XtSetValues ( rfieldswkFO, al, ac );
	ac = 0;
	if ((children[ac] = rownerPB) != (Widget) 0) { ac++; }
	if ((children[ac] = rtypePB) != (Widget) 0) { ac++; }
	if ((children[ac] = coopCommsPB) != (Widget) 0) { ac++; }
	if ((children[ac] = coopRecipPB) != (Widget) 0) { ac++; }
	if ((children[ac] = coopSponsPB) != (Widget) 0) { ac++; }
	if ((children[ac] = dcpOwnerPB) != (Widget) 0) { ac++; }
	if ((children[ac] = gageOwnerPB) != (Widget) 0) { ac++; }
	if ((children[ac] = gageMaintPB) != (Widget) 0) { ac++; }
	if ((children[ac] = gageTypePB) != (Widget) 0) { ac++; }
	if ((children[ac] = hsaPB) != (Widget) 0) { ac++; }
	if ((children[ac] = netPB) != (Widget) 0) { ac++; }
	if ((children[ac] = rfcPB) != (Widget) 0) { ac++; }
	if ((children[ac] = townerPB) != (Widget) 0) { ac++; }
	if ((children[ac] = tpayorPB) != (Widget) 0) { ac++; }
	if ((children[ac] = ttypePB) != (Widget) 0) { ac++; }
	if ((children[ac] = wfoPB) != (Widget) 0) { ac++; }
	if (ac > 0) { XtManageChildren(children, ac); }
	ac = 0;
	XtSetArg(al[ac], XmNsubMenuId, rfieldsPDM); ac++;
	XtSetValues(rfieldsCB, al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNtopOffset, 30); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_NONE); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNleftOffset, 5); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_NONE); ac++;
	XtSetValues ( rfields_addPB, al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNtopOffset, 90); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_NONE); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNleftOffset, 5); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_NONE); ac++;
	XtSetValues ( rfields_updatePB, al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNtopOffset, 145); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_NONE); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNleftOffset, 5); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_NONE); ac++;
	XtSetValues ( rfields_deletePB, al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNtopOffset, 205); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_OPPOSITE_FORM); ac++;
	XtSetArg(al[ac], XmNbottomOffset, -245); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNleftOffset, 95); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_OPPOSITE_FORM); ac++;
	XtSetArg(al[ac], XmNrightOffset, -295); ac++;
	XtSetValues ( rfieldsTE, al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNtopOffset, 10); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_OPPOSITE_FORM); ac++;
	XtSetArg(al[ac], XmNbottomOffset, -200); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNleftOffset, 95); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_OPPOSITE_FORM); ac++;
	XtSetArg(al[ac], XmNrightOffset, -295); ac++;
	XtSetValues ( rfieldsSL, al, ac );
	ac = 0;
	if (rfieldsLI != (Widget) 0) { XtManageChild(rfieldsLI); }
	if ((children[ac] = rfields_addPB) != (Widget) 0) { ac++; }
	if ((children[ac] = rfields_updatePB) != (Widget) 0) { ac++; }
	if ((children[ac] = rfields_deletePB) != (Widget) 0) { ac++; }
	if ((children[ac] = rfieldsTE) != (Widget) 0) { ac++; }
	if (ac > 0) { XtManageChildren(children, ac); }
	ac = 0;
	if ((children[ac] = rfieldsSE) != (Widget) 0) { ac++; }
	if ((children[ac] = rfields_okPB) != (Widget) 0) { ac++; }
	if ((children[ac] = rfieldsOM) != (Widget) 0) { ac++; }
	if ((children[ac] = rfieldswkFO) != (Widget) 0) { ac++; }
	if (ac > 0) { XtManageChildren(children, ac); }
	ac = 0;
}

