! Generated by X-Designer


! uhgDS

! uhgFM

! uhgimpPB
*Hb*uhgimpPB.width: 85
*Hb*uhgimpPB.height: 35
*Hb*uhgimpPB.labelString: Import

! uhgaddPB
*Hb*uhgaddPB.width: 85
*Hb*uhgaddPB.height: 35
*Hb*uhgaddPB.labelString: Add

! uhgmodifyPB

! uhgremPB
*Hb*uhgremPB.width: 85
*Hb*uhgremPB.height: 35
*Hb*uhgremPB.labelString: Remove

! uhgstgLbl
*Hb*uhgstgLbl.labelString:     Area ID         Dur       Ord       Discharge

! uhgSLB

! uhg_vSB

! uhg_hSB

! uhgLB
*Hb*uhgLBSW.uhgLB.width: 244
*Hb*uhgLBSW.uhgLB.height: 261

! uhgstgTxt
*Hb*uhgstgTxt.maxLength: 3
*Hb*uhgstgTxt.columns: 3

! uhgdurTxt

! uhgqTxt
*Hb*uhgqTxt.maxLength: 8
*Hb*uhgqTxt.columns: 10

! uhgareaTxt

! uhgfmSP
*Hb*uhgfmSP.width: 966

! uhgokPB
*Hb*uhgokPB.width: 85
*Hb*uhgokPB.height: 35
*Hb*uhgokPB.labelString: Ok

! uhgapplyPB
*Hb*uhgapplyPB.width: 85
*Hb*uhgapplyPB.height: 35
*Hb*uhgapplyPB.labelString: Apply

! uhgclosePB
*Hb*uhgclosePB.width: 85
*Hb*uhgclosePB.height: 35
*Hb*uhgclosePB.labelString: Cancel

! uhgdelPB
*Hb*uhgdelPB.width: 85
*Hb*uhgdelPB.height: 35
*Hb*uhgdelPB.labelString: Delete

