//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.10 at 11:00:08 AM CST 
//


package net.opengis.gml._3;

import javax.xml.bind.JAXBElement;
import javax.xml.namespace.QName;

public class GeodeticDatumSub
    extends JAXBElement<GeodeticDatumType>
{

    protected final static QName NAME = new QName("http://www.opengis.net/gml/3.2", "GeodeticDatum");

    public GeodeticDatumSub(GeodeticDatumType value) {
        super(NAME, ((Class) GeodeticDatumType.class), null, value);
    }

    public GeodeticDatumSub() {
        super(NAME, ((Class) GeodeticDatumType.class), null, null);
    }

}
