#!/bin/ksh

# File name: run_damcrest
# This allows you to run this script from outside of ./bin
RUN_FROM_DIR=`dirname $0`

# set up SOME environment variables for WHFS applications
. $RUN_FROM_DIR/../../set_hydro_env


export CONNECTION_STRING=$DAMCREST_JDBCURL

#get java dir
export SYS_JAVA_DIR=$($GAD_DIR/get_apps_defaults$OS_SUFFIX sys_java_dir)
export SYS_JAVA_BIN_DIR=$SYS_JAVA_DIR/bin

# set java classpath

export CLASSPATH=.:$SYS_JAVA_DIR\
:$SYS_JAVA_BIN_DIR\
:$SYS_JAVA_DIR/JClassDesktopViews/lib/jcchart.jar\
:$DB_DRIVER_PATH\
:$WHFS_BIN_DIR/damcrest.jar\
:$WHFS_BIN_DIR/fldat.jar

export DBDRIVER=org.postgresql.Driver
export DAMCREST_HOME=$WHFS_BIN_DIR

# set up an X Terminal window to write stdout and run the DamCrest 
# application using java
xterm -T "DamCrest standard output window" -iconic \
-e "$SYS_JAVA_BIN_DIR/java -Ddamcrest.home=$DAMCREST_HOME gov.dambreak.menu.Launcher $1" 
