# $Id: Makefile,v 1.4 2003/02/26 23:43:30 steve Exp $
#
#	Makefile for configuration subdirectory (config/)
#
include ../macros.make

HEADERS		= ldmconfig.h
DISTCLEAN_GARBAGE = ldmconfig.h
PACKING_LIST	= Makefile ldmconfig.h.in

all:

include ../rules.make
