# $Id: Makefile,v 1.1.16.1 2006/03/08 16:35:45 steve Exp $
include ../macros.make

TAG_SRCS	= \
	../misc/*.c ../misc/*.h \
	../ulog/*.c ../ulog/*.h \
	../protocol/*.c ../protocol/*.h \
	../pq/*.c ../pq/*.h \
	../gdbm/*.c ../gdbm/*.h

PROGRAM	= pqexpire
include ../simple_program.make
include ../rules.make
include depends
