#!/bin/sh

usage(){
    cat <<EOF
      This script is used to convert legacy miscset.tbl file into an equivalent
      resource attribute files.

      Usage: miscset2new <sourcedf> <target>
      - <sourcedf>: the source file (example:  \$GEMTBL/config/miscset.tbl)
      - <target>: the target directory (example:  . [current working directory])
      The converted attribute files are placed in resource-specific subdirectories
      of the output directory; they all end in ".attr".

EOF
    exit
}

srcpath=$1
tgtpath=$2

if [ $# -lt 2 ];  then
     usage
fi

java -jar %{CONV_INSTALL}%/distMisc/miscsetConverter.jar $srcpath $tgtpath

