#!/bin/sh 

usage(){
    cat <<EOF
      This scripts is used to compare *.xml files with *A.xml files. 
 
      Usage: xmlnxml <sourcedf> <targetdf>
      - <sourcedf>: the source directory or the source file.
      - <targetdf>: the target directory or the target file. Put *A.xml files in <target>
EOF
    exit
}

srcpath=$1
tgtpath=$2

if [ $# -lt 2 ]; then
     usage
fi

if [ -d $srcpath ]; then
    
     for file in ${srcpath}/*.xml ; do
         tem=`echo ${file} | cut -d. -f1`
         java -jar compareXml.jar ${srcpath}/${tem}.xml ${tgtpath}/${tem}.xml        
     done
fi

if [ -f $srcpath ]; then
     java -jar compareXml.jar $srcpath $tgtpath
fi

