//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.29 at 09:28:54 AM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://metar.edex.uf.raytheon.com", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)

package com.raytheon.uf.edex.plugin.obs.ogc.metar.feature;
