/*
** Generated by X-Designer
*/
/*
**LIBS: -lXm -lXt -lX11
*/

#include <stdlib.h>
#include <X11/Xatom.h>
#include <X11/Intrinsic.h>
#include <X11/Shell.h>

#include <Xm/Xm.h>
#include <Xm/DialogS.h>
#include <Xm/Form.h>
#include <Xm/Label.h>
#include <Xm/List.h>
#include <Xm/PushB.h>
#include <Xm/ScrollBar.h>


Widget pc_tableDS = (Widget) NULL;
Widget pc_tableFO = (Widget) NULL;
Widget pc_tablelistLB = (Widget) NULL;
Widget pc_tableSL = (Widget) NULL;
Widget pc_tableHSB = (Widget) NULL;
Widget pc_tableVSB = (Widget) NULL;
Widget pc_tableLS = (Widget) NULL;
Widget pc_table_closePB = (Widget) NULL;
Widget pc_table_printPB = (Widget) NULL;
Widget pc_table_savePB = (Widget) NULL;
Widget pc_table_graphtsPB = (Widget) NULL;
Widget pc_table_tabtsPB = (Widget) NULL;



void create_pc_tableDS (Widget parent)
{
	Widget children[7];      /* Children to manage */
	Arg al[64];                    /* Arg List */
	register int ac = 0;           /* Arg Count */
	XmString xmstrings[16];    /* temporary storage for XmStrings */

	XtSetArg(al[ac], XmNwidth, 750); ac++;
	XtSetArg(al[ac], XmNheight, 600); ac++;
	XtSetArg(al[ac], XmNallowShellResize, TRUE); ac++;
	XtSetArg(al[ac], XmNtitle, "Point Data Tabular Display"); ac++;
	XtSetArg(al[ac], XmNminWidth, 750); ac++;
	XtSetArg(al[ac], XmNminHeight, 600); ac++;
	XtSetArg(al[ac], XmNmaxWidth, 750); ac++;
	XtSetArg(al[ac], XmNmaxHeight, 600); ac++;
	pc_tableDS = XmCreateDialogShell ( parent, "pc_tableDS", al, ac );
	ac = 0;
	XtSetArg(al[ac], XmNwidth, 750); ac++;
	XtSetArg(al[ac], XmNautoUnmanage, FALSE); ac++;
	pc_tableFO = XmCreateForm ( pc_tableDS, "pc_tableFO", al, ac );
	ac = 0;
	xmstrings[0] = XmStringCreateLtoR ( "Station    Name                       Value  [Stg Flow]       Time               PE TS Dur Extr [Fld, Depart]", (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
	XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
	XtSetArg(al[ac], XmNalignment, XmALIGNMENT_BEGINNING); ac++;
	pc_tablelistLB = XmCreateLabel ( pc_tableFO, "pc_tablelistLB", al, ac );
	ac = 0;
	XmStringFree ( xmstrings [ 0 ] );
	XtSetArg(al[ac], XmNlistSizePolicy, XmRESIZE_IF_POSSIBLE); ac++;
	pc_tableLS = XmCreateScrolledList ( pc_tableFO, "pc_tableLS", al, ac );
	ac = 0;
	pc_tableSL = XtParent ( pc_tableLS );

	XtSetArg(al[ac], XmNhorizontalScrollBar, &pc_tableHSB); ac++;
	XtSetArg(al[ac], XmNverticalScrollBar, &pc_tableVSB); ac++;
	XtGetValues(pc_tableSL, al, ac );
	ac = 0;
	XtSetArg(al[ac], XmNlistSizePolicy, XmRESIZE_IF_POSSIBLE); ac++;
	XtSetValues ( pc_tableLS,al, ac );
	ac = 0;
	XtSetArg(al[ac], XmNwidth, 550); ac++;
	XtSetValues ( pc_tableSL,al, ac );
	ac = 0;
	xmstrings[0] = XmStringCreateLtoR ( "Close", (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
	XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
	pc_table_closePB = XmCreatePushButton ( pc_tableFO, "pc_table_closePB", al, ac );
	ac = 0;
	XmStringFree ( xmstrings [ 0 ] );
	xmstrings[0] = XmStringCreateLtoR ( "Print", (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
	XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
	pc_table_printPB = XmCreatePushButton ( pc_tableFO, "pc_table_printPB", al, ac );
	ac = 0;
	XmStringFree ( xmstrings [ 0 ] );
	xmstrings[0] = XmStringCreateLtoR ( "Save", (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
	XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
	pc_table_savePB = XmCreatePushButton ( pc_tableFO, "pc_table_savePB", al, ac );
	ac = 0;
	XmStringFree ( xmstrings [ 0 ] );
	xmstrings[0] = XmStringCreateLtoR ( "Time Series Graph", (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
	XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
	pc_table_graphtsPB = XmCreatePushButton ( pc_tableFO, "pc_table_graphtsPB", al, ac );
	ac = 0;
	XmStringFree ( xmstrings [ 0 ] );
	xmstrings[0] = XmStringCreateLtoR ( "Time Series Table", (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
	XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
	pc_table_tabtsPB = XmCreatePushButton ( pc_tableFO, "pc_table_tabtsPB", al, ac );
	ac = 0;
	XmStringFree ( xmstrings [ 0 ] );


	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNtopOffset, 1); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_OPPOSITE_FORM); ac++;
	XtSetArg(al[ac], XmNbottomOffset, -30); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNleftOffset, 1); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_OPPOSITE_FORM); ac++;
	XtSetArg(al[ac], XmNrightOffset, -711); ac++;
	XtSetValues ( pc_tablelistLB,al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNtopOffset, 31); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_OPPOSITE_FORM); ac++;
	XtSetArg(al[ac], XmNbottomOffset, -521); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNleftOffset, 0); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_OPPOSITE_FORM); ac++;
	XtSetArg(al[ac], XmNrightOffset, -744); ac++;
	XtSetValues ( pc_tableSL,al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNtopOffset, 565); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_OPPOSITE_FORM); ac++;
	XtSetArg(al[ac], XmNbottomOffset, -595); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNleftOffset, 390); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_OPPOSITE_FORM); ac++;
	XtSetArg(al[ac], XmNrightOffset, -495); ac++;
	XtSetValues ( pc_table_closePB,al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNtopOffset, 530); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_OPPOSITE_FORM); ac++;
	XtSetArg(al[ac], XmNbottomOffset, -560); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNleftOffset, 225); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_OPPOSITE_FORM); ac++;
	XtSetArg(al[ac], XmNrightOffset, -315); ac++;
	XtSetValues ( pc_table_printPB,al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNtopOffset, 565); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_OPPOSITE_FORM); ac++;
	XtSetArg(al[ac], XmNbottomOffset, -595); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNleftOffset, 225); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_OPPOSITE_FORM); ac++;
	XtSetArg(al[ac], XmNrightOffset, -315); ac++;
	XtSetValues ( pc_table_savePB,al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNtopOffset, 530); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_OPPOSITE_FORM); ac++;
	XtSetArg(al[ac], XmNbottomOffset, -560); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNleftOffset, 5); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_OPPOSITE_FORM); ac++;
	XtSetArg(al[ac], XmNrightOffset, -175); ac++;
	XtSetValues ( pc_table_graphtsPB,al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNtopOffset, 565); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_OPPOSITE_FORM); ac++;
	XtSetArg(al[ac], XmNbottomOffset, -595); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNleftOffset, 5); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_OPPOSITE_FORM); ac++;
	XtSetArg(al[ac], XmNrightOffset, -175); ac++;
	XtSetValues ( pc_table_tabtsPB,al, ac );
	ac = 0;
	XtManageChild(pc_tableLS);
	children[ac++] = pc_tablelistLB;
	children[ac++] = pc_table_closePB;
	children[ac++] = pc_table_printPB;
	children[ac++] = pc_table_savePB;
	children[ac++] = pc_table_graphtsPB;
	children[ac++] = pc_table_tabtsPB;
	XtManageChildren(children, ac);
	ac = 0;
}

