C MODULE SLCHK
C-----------------------------------------------------------------------
C
C  ROUTINE TO CHECK IF IDENTIFIER USED IN PARAMETER DEFINITIONS.
C
      SUBROUTINE SLCHK (TYPE,CHKID,LARAY1,IARAY1,LARRAY,ARRAY,
     *   LARAY3,ARAY3,IFIRST,IXSORT,NUMID1,NUMID2,NUMID3,NUMERR,ISTAT)
C
      CHARACTER*4 TYPE
      CHARACTER*5 SEASN
      CHARACTER*8 XCHKID
      CHARACTER*8 FMAPID,XTSID,XSEGID,XFGID,XCGID
      CHARACTER*30 STRING
C
      DIMENSION IARAY1(LARAY1),ARRAY(LARRAY),ARAY3(LARAY3)
      DIMENSION CHKID(2)
C
C  ARRAYS USED BY MORE THAN ONE AREA PARAMETER TYPE
      CHARACTER*8 AREAID,BASNID
      DIMENSION DESCRP(5),CENTRD(2)
C
C  STAN PARAMETER ARRAYS
      CHARACTER*8 STAID
      DIMENSION STALOC(2),STACOR(2)
C
      INCLUDE 'scommon/dimpcpn'
C
C  MAP PARAMETERS
      DIMENSION ITECHS(5)
      PARAMETER (MSTWT=100)
      CHARACTER*8 TSTAID(MSTWT)
      DIMENSION TSTAWT(MSTWT),CTSTA(2,MSTWT)
      DIMENSION IPD6(MSTWT)
      PARAMETER (MPCPN=100)
      CHARACTER*8 CSTAID(MPCPN)
      DIMENSION CSTAWT(MPCPN,2),CCSTA(2,MPCPN)
      DIMENSION IPD24(MPCPN)
      PARAMETER (MBOX=100)
      DIMENSION MDRBOX(MBOX),CORMDR(MBOX)
C
C  BASN PARAMETER ARRAYS
      DIMENSION BDESC(5),DMYID(2)
      PARAMETER (MBPTS=3000)
      DIMENSION LAT(MBPTS),LON(MBPTS)
      DIMENSION IY(MBPTS),IXB(MBPTS),IXE(MBPTS)
      DIMENSION X(MBPTS),Y(MBPTS)
      DIMENSION JX(MBPTS),JY(MBPTS),JN(MBPTS)
C
C  MAT PARAMETER ARRAYS
      PARAMETER (MTEMP=100)
      CHARACTER*8 TEMPID(MTEMP)
      DIMENSION IPDMMT(MTEMP),WTMMT(MTEMP)
C
C  MAPE PARAMETER ARRAYS
      DIMENSION PEMEAN(12),PECHNG(12)
      PARAMETER (MPE=5)
      CHARACTER*8 PSTAID(MPE)
      DIMENSION IPDPTR(MPE),STAWT(MPE)
C
      DIMENSION UNUSED(10)
C
      INCLUDE 'uio'
      INCLUDE 'scommon/sudbgx'
C
C    ================================= RCS keyword statements ==========
      CHARACTER*68     RCSKW1,RCSKW2
      DATA             RCSKW1,RCSKW2 /                                 '
     .$Source: /fs/hseb/ob72/rfc/ofs/src/ppinit_delete/RCS/slchk.f,v $
     . $',                                                             '
     .$Id: slchk.f,v 1.8 2002/10/16 20:11:19 dws Exp $
     . $' /
C    ===================================================================
C
C
      IF (ISTRCE.GT.0) THEN
         WRITE (IOSDBG,*) 'ENTER SLCHK'
         CALL SULINE (IOSDBG,1)
         ENDIF
C
C  SET DEBUG LEVEL
      LDEBUG=ISBUG('DELT')
C
      ISTAT=0
C
      ISORT=1
      ISTATE=0
      NWORDS=2
      MAXID=LARAY1/(NWORDS+1)
C
      IPRERR=1
      IPRNT=1
C
      NSPCPN=0
      NMAP=0
      NMAPX=0
      NMAT=0
      NMAPE=0
C
      CALL SUBSTR (CHKID,1,LEN(XCHKID),XCHKID,1)
C
      IF (LDEBUG.GT.0) THEN
         WRITE (IOSDBG,*)
     *      ' NUMID1=',NUMID1,
     *      ' NUMID2=',NUMID2,
     *      ' NUMID3=',NUMID3,
     *      ' TYPE=',TYPE,
     *      ' XCHKID=',XCHKID,
     *      ' IFIRST=',IFIRST,
     *      ' '
         CALL SULINE (IOSDBG,1)
         ENDIF
C
      IF (LDEBUG.GT.0) THEN
         WRITE (IOSDBG,*) 'IN SLCHK - MBPTS=',MBPTS
         CALL SULINE (IOSDBG,1)
         ENDIF
C
C- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
C
      IF (TYPE.EQ.'PCPN') THEN
C
C  CHECK IF PCPN STATION USED AS SIGNIFICANCE STATION IN PCPN STATION
C  DEFINITIONS
C
      IF (IFIRST.EQ.1) THEN
C     GET SORTED LIST OF IDENTIFIERS
         IXSORT=ISORT
         IARAY1(MAXID*NWORDS+1)=1
         IPRMSG=0
         CALL SURIDS ('PCPN',IXSORT,MAXID,ISTATE,NWORDS,
     *      IARAY1,IARAY1(MAXID*NWORDS+1),
     *      NUMID1,LARRAY,ARRAY,IPRMSG,IPRERR,IERR)
         IF (IERR.GT.0) IXSORT=0
         ENDIF
C
      IF (NUMID1.EQ.0) GO TO 300
C
      IPTRNX=0
C
10    STAID=' '
      IF (IXSORT.EQ.0) THEN
         IPTR=IPTRNX
         ELSE
            IPTR=IARAY1(MAXID*NWORDS+NSPCPN+1)
         ENDIF
      IREAD=1
      INCLUDE 'scommon/callsrpcpn'
      NSPCPN=NSPCPN+1
      IF (IERR.GT.0) THEN
         WRITE (LP,340) 'PCPN','STATION',STAID
         CALL SUERRS (LP,2,NUMERR)
         GO TO 40
         ENDIF
C
C  PRINT PARAMETERS
      LEVEL=1
      IPREST=0
      IF (LDEBUG.GT.0) THEN
         INCLUDE 'scommon/callsppcpn'
         ENDIF
C
C  CHECK IF SIGNIFICANCE WEIGHTS USED
      IF (IPTWGT.GT.0) GO TO 20
         IF (LDEBUG.GT.0) THEN
            WRITE (IOSDBG,320) STAID
            CALL SULINE (IOSDBG,1)
            ENDIF
         GO TO 40
C
C  CHECK IF STATION IDENTIFIER USED
20    DO 30 I=1,IPTWGT
         IF (STASID(I).EQ.XCHKID) THEN
            WRITE (LP,330) XCHKID,TYPE,'PCPN',STAID(1:LENSTR(STAID))
            CALL SUERRS (LP,2,NUMERR)
            ISTAT=2
            ENDIF
30       CONTINUE
C
40    IF (IXSORT.EQ.0) THEN
         IF (IPTRNX.GT.0) GO TO 10
         ELSE
            IF (NSPCPN.LT.NUMID1) GO TO 10
         ENDIF
C
C      -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -
C
C  CHECK IF STATION USED AS PREDETERMINED STATION IN MAP AREA
C
      IF (IFIRST.EQ.1) THEN
C     GET SORTED LIST OF IDENTIFIERS
         IXSORT=ISORT
         IARAY1(MAXID*NWORDS+1)=1
         IPRMSG=0
         CALL SURIDS ('MAP ',IXSORT,MAXID,ISTATE,NWORDS,
     *      IARAY1,IARAY1(MAXID*NWORDS+1),
     *      NUMID1,LARRAY,ARRAY,IPRMSG,IPRERR,IERR)
         IF (IERR.GT.0) IXSORT=0
         ENDIF
C
      IF (NUMID1.EQ.0) GO TO 300
C
      IPTRNX=0
C
50    AREAID=' '
      IF (IXSORT.EQ.0) THEN
         IPTR=IPTRNX
         ELSE
            IPTR=IARAY1(MAXID*NWORDS+NMAP+1)
         ENDIF
      IPTR2=0
      CALL SRMAP (IVMAP,AREAID,ITIME,ITMWT,POWER,MSTWT,NSTWT,
     *   ISTWT,MPCPN,NPCPN,NSETS,DESCRP,BASNID,FMAPID,CENTRD,
     *   TSTAID,TSTAWT,CTSTA,CSTAID,CSTAWT,CCSTA,
     *   UNUSED,LARRAY,ARRAY,IPTR,IPRERR,IPTRNX,IERR)
      CALL SRMAPS (IVMAPS,AREAID,CENTRD,RADINF,IPMAP,NTECH,
     *   IBASN,MSTWT,NSTWT,MPCPN,NPCPN,MBOX,NBOX,ITECHS,IPD6,IPD24,
     *   MDRBOX,CORMDR,UNUSED,LARRAY,ARRAY,IPTR2,IPRERR,IPTRN2,IERR2)
      IF (IERR.NE.0.OR.IERR2.NE.0) THEN
         IF (IERR.NE.2.OR.IERR2.NE.2) THEN
            WRITE (LP,340) 'MAP','AREA',AREAID
            CALL SUERRS (LP,2,NUMERR)
            ENDIF
         IF (IERR.EQ.2.AND.LDEBUG.GT.0) THEN
            WRITE (IOSDBG,350) 'MAP'
            CALL SULINE (IOSDBG,1)
            ENDIF
         GO TO 100
         ENDIF
C
      IF (LDEBUG.GT.0) THEN
         IF (BASNID.NE.' ') THEN
         IPTR3=0
         CALL SRBASN (ARRAY,LARRAY,IJ,BASNID,BDESC,LAT,LON,
     *      MBPTS,NBPTS,AREA,CAREA,ELEV,CENTRD(1),CENTRD(2),
     *      MAPFLG,MATFLG,DMYID,DMYID,DMYID,
     *      MBPTS,NSEGS,IY,IXB,IXE,LFACTR,IPTR3,IPTRN3,IPRERR,IERR)
         IF (IERR.EQ.0) THEN
         CALL SPMAP (IPRNT,IVMAP,IVMAPS,AREAID,ITIME,ITMWT,POWER,NSTWT,
     *      ISTWT,NPCPN,NSETS,DESCRP,BASNID,FMAPID,CENTRD,TSTAID,
     *      TSTAWT,CTSTA,CSTAID,CSTAWT,CCSTA,
     *      RADINF,IPMAP,NTECH,IBASN,NBOX,ITECHS,IPD6,IPD24,MDRBOX,
     *      CORMDR,UNUSED,IY,IXB,IXE,NSEGS,X,Y,JX,JY,NBPTS,
     *      LFACTR,PLOT,LARRAY,ARRAY,UNITS,AREA,CAREA,JN,IERR)
            ENDIF
         ENDIF
         ENDIF
C
      NMAP=NMAP+1
C
C  CHECK IF PREDETERMINED WEIGHTS USED FOR TIMING WEIGHTS
      IF (ITMWT.NE.1) THEN
         IF (LDEBUG.GT.0) THEN
             IF (ITMWT.EQ.2) THEN
                WRITE (IOSDBG,360) AREAID,'1/D**2 TIMING'
                CALL SULINE (IOSDBG,1)
                ENDIF
             IF (ITMWT.EQ.3) THEN
                WRITE (IOSDBG,360) AREAID,'1/D**POWER TIMING'
                CALL SULINE (IOSDBG,1)
                ENDIF
             ENDIF
          GO TO 70
          ENDIF
C
C  CHECK IF STATION IDENTIFIER USED
      DO 60 I=1,NSTWT
         IF (TSTAID(I).EQ.XCHKID) THEN
            WRITE (LP,370) XCHKID,TYPE,
     *         'PREDETERMINED TIMING',
     *         'MAP',AREAID(1:LENSTR(AREAID))
            CALL SUERRS (LP,2,NUMERR)
            ISTAT=2
            ENDIF
60       CONTINUE
C
C  CHECK IF PREDETERMINED WEIGHTS USED FOR STATION WEIGHTS
70    IF (ISTWT.NE.1) THEN
         IF (LDEBUG.GT.0) THEN
             IF (ISTWT.EQ.2) THEN
                WRITE (IOSDBG,360) AREAID,'GRID POINT STATION'
                CALL SULINE (IOSDBG,1)
                ENDIF
             IF (ISTWT.EQ.3) THEN
                WRITE (IOSDBG,360) AREAID,'THIESSEN STATION'
                CALL SULINE (IOSDBG,1)
                ENDIF
             IF (ISTWT.EQ.4) THEN
                WRITE (IOSDBG,360) AREAID,'1/D**POWER TIMING'
                CALL SULINE (IOSDBG,1)
                ENDIF
             ENDIF
          GO TO 100
          ENDIF
C
C  CHECK IF STATION IDENTIFIER USED
      DO 90 J=1,NSETS
         SEASN=' '
         LSEASN=1
         IF (NSETS.EQ.2) THEN
            IF (J.EQ.1) SEASN=' WNTR'
            IF (J.EQ.2) SEASN=' SUMR'
            LSEASN=LENSTR(SEASN)
            ENDIF
         DO 80 I=1,NPCPN
            IF (CSTAID(I).EQ.XCHKID.AND.CSTAWT(I,J).GT.0.0) THEN
               WRITE (LP,380) XCHKID,TYPE,
     *            'PREDETERMINED',SEASN(1:LENSTR(SEASN)),' WEIGHTING',
     *            'MAP',AREAID(1:LENSTR(AREAID))
               CALL SUERRS (LP,2,NUMERR)
               ISTAT=2
               ENDIF
80          CONTINUE
90       CONTINUE
C
100   IF (IXSORT.EQ.0) THEN
         IF (IPTRNX.GT.0) GO TO 50
         ELSE
            IF (NMAP.LT.NUMID1) GO TO 50
         ENDIF
C
      GO TO 300
C
      ENDIF
C
C- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
C
      IF (TYPE.EQ.'TEMP') THEN
C
C  CHECK IF USED AS PREDETERMINED STATION IN MAT AREA
C
      IF (IFIRST.EQ.1) THEN
C     GET SORTED LIST OF IDENTIFIERS
         IXSORT=ISORT
         IARAY1(MAXID*NWORDS+1)=1
         IPRMSG=0
         CALL SURIDS ('MAT ',IXSORT,MAXID,ISTATE,NWORDS,
     *      IARAY1,IARAY1(MAXID*NWORDS+1),
     *      NUMID1,LARRAY,ARRAY,IPRMSG,IPRERR,IERR)
         IF (IERR.GT.0) IXSORT=0
         ENDIF
C
      IF (NUMID1.EQ.0) GO TO 300
C
      IPTRNX=0
C
110   AREAID=' '
      IF (IXSORT.EQ.0) THEN
         IPTR=IPTRNX
         ELSE
            IPTR=IARAY1(MAXID*NWORDS+NMAT+1)
         ENDIF
      CALL SRMAT (IVMAT,AREAID,DESCRP,CENTRD,BASNID,ISTWT,POWER,
     *   MTEMP,NTEMP,TEMPID,IPDMMT,WTMMT,UNUSED,LARRAY,ARRAY,
     *   IPTR,IPRERR,IPTRNX,IERR)
      IF (IERR.NE.0) THEN
         IF (IERR.NE.2) THEN
            WRITE (LP,340) 'MAT','AREA',AREAID
            CALL SUERRS (LP,2,NUMERR)
            ENDIF
         IF (IERR.EQ.2.AND.LDEBUG.GT.0) THEN
            WRITE (IOSDBG,350) 'MAT'
            CALL SULINE (IOSDBG,1)
            ENDIF
         GO TO 140
         ENDIF
C
      IF (LDEBUG.GT.0) THEN
         CALL SPMAT (IPRNT,UNITS,IVMAT,AREAID,DESCRP,CENTRD,BASNID,
     *      ISTWT,POWER,NTEMP,TEMPID,IPDMMT,WTMMT,UNUSED,LARRAY,ARRAY,
     *      IERR)
         ENDIF
C
      NMAT=NMAT+1
C
C  CHECK IF PREDETERMINED WEIGHTS USED FOR STATION WEIGHTS
      IF (ISTWT.EQ.1) GO TO 120
         IF (LDEBUG.GT.0) THEN
             IF (ISTWT.EQ.2) THEN
                WRITE (IOSDBG,360) AREAID,'GRID POINT STATION'
                CALL SULINE (IOSDBG,1)
                ENDIF
             IF (ISTWT.EQ.3) THEN
                WRITE (IOSDBG,360) AREAID,'1/D**POWER TIMING'
                CALL SULINE (IOSDBG,1)
                ENDIF
             ENDIF
          GO TO 140
C
C  CHECK IF STATION IDENTIFIER USED
120   DO 130 I=1,NTEMP
         IF (TEMPID(I).EQ.XCHKID) THEN
            WRITE (LP,370) XCHKID,TYPE,
     *         'PREDETERMINED',
     *         'MAT',AREAID(1:LENSTR(AREAID))
            CALL SUERRS (LP,2,NUMERR)
            ISTAT=2
            ENDIF
130      CONTINUE
C
140   IF (IXSORT.EQ.0) THEN
         IF (IPTRNX.GT.0) GO TO 110
         ELSE
            IF (NMAT.LT.NUMID1) GO TO 110
         ENDIF
C
      GO TO 300
C
      ENDIF
C
C- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
C
      IF (TYPE.EQ.'PE') THEN
C
C  CHECK IF USED AS PREDETERMINED STATION IN MAPE AREA
C
      IF (IFIRST.EQ.1) THEN
C     GET SORTED LIST OF IDENTIFIERS
         IXSORT=ISORT
         IARAY1(MAXID*NWORDS+1)=1
         IPRMSG=0
         CALL SURIDS ('MAPE',IXSORT,MAXID,ISTATE,NWORDS,
     *      IARAY1,IARAY1(MAXID*NWORDS+1),
     *      NUMID1,LARRAY,ARRAY,IPRMSG,IPRERR,IERR)
         IF (IERR.GT.0) IXSORT=0
         ENDIF
C
      IF (NUMID1.EQ.0) GO TO 300
C
      IPTRNX=0
C
150   AREAID=' '
      IF (IXSORT.EQ.0) THEN
         IPTR=IPTRNX
         ELSE
            IPTR=IARAY1(MAXID*NWORDS+NMAPE+1)
         ENDIF
      CALL SRMAPE (IVMAPE,AREAID,DESCRP,CENTRD,ISTWT,POWER,
     *   PEMEAN,PECHNG,MPE,NPE,PSTAID,IPDPTR,STAWT,
     *   UNUSED,LARRAY,ARRAY,IPTR,IPRERR,IPTRNX,IERR)
      IF (IERR.NE.0) THEN
         IF (IERR.NE.2) THEN
            WRITE (LP,340) 'MAPE','AREA',AREAID
            CALL SUERRS (LP,2,NUMERR)
            ENDIF
         IF (IERR.EQ.2.AND.LDEBUG.GT.0) THEN
            WRITE (IOSDBG,350) 'MAPE'
            CALL SULINE (IOSDBG,1)
            ENDIF
         GO TO 180
         ENDIF
C
      IF (LDEBUG.GT.0) THEN
         CALL SPMAPE (UNITS,IVMAPE,AREAID,DESCRP,CENTRD,ISTWT,
     *      POWER,PEMEAN,PECHNG,NPE,PSTAID,IPDPTR,STAWT,
     *      UNUSED,IERR)
         ENDIF
C
      NMAPE=NMAPE+1
C
C  CHECK IF PREDETERMINED WEIGHTS USED FOR STATION WEIGHTS
      IF (ISTWT.EQ.1) GO TO 160
         IF (LDEBUG.GT.0) THEN
             IF (ISTWT.EQ.2) THEN
                WRITE (IOSDBG,360) AREAID,'1/D**POWER TIMING'
                CALL SULINE (IOSDBG,1)
                ENDIF
             ENDIF
          GO TO 180
C
C  CHECK IF STATION IDENTIFIER USED
160   DO 170 I=1,NPE
         IF (PSTAID(I).EQ.XCHKID) THEN
            WRITE (LP,370) XCHKID,TYPE,
     *          'PREDETERMINED',
     *          'MAPE',AREAID(1:LENSTR(AREAID))
            CALL SUERRS (LP,2,NUMERR)
            ISTAT=2
            ENDIF
170      CONTINUE
C
180   IF (IXSORT.EQ.0) THEN
         IF (IPTRNX.GT.0) GO TO 150
         ELSE
            IF (NMAPE.LT.NUMID1) GO TO 150
         ENDIF
C
      GO TO 300
C
      ENDIF
C
C- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
C
      IF (TYPE.EQ.'BASN') THEN
C
      NTYPE=3
      MAXID=LARAY1/((NWORDS+1)*NTYPE)
      IARYP2=0
C
C  CHECK IF BASIN IS USED IN MAP AREA
C
      IARYP1=IARYP2+1
      IARYP2=IARYP1+MAXID*NWORDS
C
      IF (IFIRST.EQ.1) THEN
C     GET SORTED LIST OF IDENTIFIERS
         IXSORT=ISORT
         IARAY1(IARYP2)=1
         IPRMSG=0
         CALL SURIDS ('MAP ',IXSORT,MAXID,ISTATE,NWORDS,
     *      IARAY1(IARYP1),IARAY1(IARYP2),
     *      NUMID1,LARRAY,ARRAY,IPRMSG,IPRERR,IERR)
         IF (IERR.GT.0) IXSORT=0
         ENDIF
C
      IF (NUMID1.EQ.0) GO TO 210
C
      IPTRNX=0
C
190   AREAID=' '
      IF (IXSORT.EQ.0) THEN
         IPTR=IPTRNX
         ELSE
            IPTR=IARAY1(IARYP2+NMAP)
         ENDIF
      IPTR2=0
      CALL SRMAP (IVMAP,AREAID,ITIME,ITMWT,POWER,MSTWT,NSTWT,
     *   ISTWT,MPCPN,NPCPN,NSETS,DESCRP,BASNID,FMAPID,CENTRD,
     *   TSTAID,TSTAWT,CTSTA,CSTAID,CSTAWT,CCSTA,
     *   UNUSED,LARRAY,ARRAY,IPTR,IPRERR,IPTRNX,IERR)
      CALL SRMAPS (IVMAPS,AREAID,CENTRD,RADINF,IPMAP,NTECH,
     *   IBASN,MSTWT,NSTWT,MPCPN,NPCPN,MBOX,NBOX,ITECHS,IPD6,IPD24,
     *   MDRBOX,CORMDR,UNUSED,LARRAY,ARRAY,IPTR2,IPRERR,IPTRN2,IERR2)
      IF (IERR.NE.0.OR.IERR2.NE.0) THEN
         IF (IERR.NE.2.AND.IERR2.NE.2) THEN
            WRITE (LP,340) 'MAP','AREA',AREAID
            CALL SUERRS (LP,2,NUMERR)
            ISTAT=1
            ENDIF
         IF (IERR.EQ.2.AND.LDEBUG.GT.0) THEN
            WRITE (IOSDBG,350) 'MAP'
            CALL SULINE (IOSDBG,1)
            ENDIF
         GO TO 200
         ENDIF
C
      IF (LDEBUG.GT.0) THEN
         IF (LDEBUG.EQ.1) THEN
            WRITE (IOSDBG,390) AREAID,BASNID,XCHKID
            CALL SULINE (IOSDBG,1)
            ENDIF
         IF (LDEBUG.GT.1) THEN
            IPTR3=0
            CALL SRBASN (ARRAY,LARRAY,IJ,BASNID,BDESC,LAT,LON,
     *         MBPTS,NBPTS,AREA,CAREA,ELEV,CENTRD(1),CENTRD(2),
     *         MAPFLG,MATFLG,DMYID,DMYID,DMYID,
     *         MBPTS,NSEGS,IY,IXB,IXE,LFACTR,IPTR3,IPTRN3,IPRERR,IERR)
            IF (IERR.EQ.0) THEN
      CALL SPMAP (IPRNT,IVMAP,IVMAPS,AREAID,ITIME,ITMWT,POWER,NSTWT,
     *   ISTWT,NPCPN,NSETS,DESCRP,BASNID,FMAPID,CENTRD,TSTAID,
     *   TSTAWT,CTSTA,CSTAID,CSTAWT,CCSTA,
     *   RADINF,IPMAP,NTECH,IBASN,NBOX,ITECHS,IPD6,IPD24,MDRBOX,
     *   CORMDR,UNUSED,IY,IXB,IXE,NSEGS,X,Y,JX,JY,NBPTS,
     *   LFACTR,PLOT,LARRAY,ARRAY,UNITS,AREA,CAREA,JN,IERR)
               ENDIF
            ENDIF
         ENDIF
C
      NMAP=NMAP+1
C
C  CHECK IF BASIN ID USED
      IF (BASNID.EQ.XCHKID) THEN
         WRITE (LP,400) 'BASIN',BASNID,
     *      'MAP ',AREAID(1:LENSTR(AREAID))
         CALL SUERRS (LP,2,NUMERR)
         ISTAT=2
         ENDIF
C
200   IF (IXSORT.EQ.0) THEN
         IF (IPTRNX.GT.0) GO TO 190
         ELSE
            IF (NMAP.LT.NUMID1) GO TO 190
         ENDIF
C
C      -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -
C
C  CHECK IF BASIN IS USED IN MAT AREA
C
210   IARYP1=IARYP2+MAXID+1
      IARYP2=IARYP1+MAXID*NWORDS
C
      IF (IFIRST.EQ.1) THEN
C     GET SORTED LIST OF IDENTIFIERS
         IXSORT=ISORT
         IARAY1(IARYP2)=1
         IPRMSG=0
         CALL SURIDS ('MAT ',IXSORT,MAXID,ISTATE,NWORDS,
     *      IARAY1(IARYP1),IARAY1(IARYP2),
     *      NUMID2,LARRAY,ARRAY,IPRMSG,IPRERR,IERR)
         IF (IERR.GT.0) IXSORT=0
         ENDIF
C
      IF (NUMID2.EQ.0) GO TO 240
C
      IPTRNX=0
C
220   AREAID=' '
      IF (IXSORT.EQ.0) THEN
         IPTR=IPTRNX
         ELSE
            IPTR=IARAY1(IARYP2+NMAT)
         ENDIF
      CALL SRMAT (IVMAT,AREAID,DESCRP,CENTRD,BASNID,ISTWT,POWER,
     *   MTEMP,NTEMP,TEMPID,IPDMMT,WTMMT,UNUSED,LARRAY,ARRAY,
     *   IPTR,IPRERR,IPTRNX,IERR)
      IF (IERR.NE.0) THEN
         IF (IERR.NE.2) THEN
            WRITE (LP,340) 'MAT','AREA',AREAID
            CALL SUERRS (LP,2,NUMERR)
            ISTAT=1
            ENDIF
         IF (IERR.EQ.2.AND.LDEBUG.GT.0) THEN
            WRITE (IOSDBG,350) 'MAT'
            CALL SULINE (IOSDBG,1)
            ENDIF
         GO TO 230
         ENDIF
C
      IF (LDEBUG.GT.0) THEN
         IF (LDEBUG.EQ.1) THEN
            WRITE (IOSDBG,390) AREAID,BASNID,XCHKID
            CALL SULINE (IOSDBG,1)
            ENDIF
         IF (LDEBUG.GT.1) THEN
            CALL SPMAT (IPRNT,UNITS,IVMAT,AREAID,DESCRP,CENTRD,BASNID,
     *         ISTWT,POWER,NTEMP,TEMPID,IPDMMT,WTMMT,
     *         UNUSED,LARRAY,ARRAY,IERR)
            ENDIF
         ENDIF
C
      NMAT=NMAT+1
C
C  CHECK IF BASIN ID USED
      IF (BASNID.EQ.XCHKID) THEN
         WRITE (LP,400) 'BASIN',BASNID,
     *      'MAT ',AREAID(1:LENSTR(AREAID))
         CALL SUERRS (LP,2,NUMERR)
         ISTAT=2
         ENDIF
C
230   IF (IXSORT.EQ.0) THEN
         IF (IPTRNX.GT.0) GO TO 220
         ELSE
            IF (NMAT.LT.NUMID2) GO TO 220
         ENDIF
C
C      -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -
C
C  CHECK IF BASIN IS USED IN MAPX AREA
C
240   IARYP1=IARYP2+MAXID+1
      IARYP2=IARYP1+MAXID*NWORDS
C
      IF (IFIRST.EQ.1) THEN
C     GET SORTED LIST OF IDENTIFIERS
         IXSORT=ISORT
         IARAY1(IARYP2)=1
         IPRMSG=0
         CALL SURIDS ('MAPX',IXSORT,MAXID,ISTATE,NWORDS,
     *      IARAY1(IARYP1),IARAY1(IARYP2),
     *      NUMID3,LARRAY,ARRAY,IPRMSG,IPRERR,IERR)
         IF (IERR.GT.0) IXSORT=0
         ENDIF
C
      IF (NUMID3.EQ.0) GO TO 300
C
      IPTRNX=0
C
250   AREAID=' '
      IF (IXSORT.EQ.0) THEN
         IPTR=IPTRNX
         ELSE
            IPTR=IARAY1(IARYP2+NMAPX)
         ENDIF
      CALL SRMAPX (IVMAPX,AREAID,ITIME,DESCRP,BASNID,FMAPID,
     *   UNUSED,LARRAY,ARRAY,IPTR,IPRERR,IPTRNX,IERR,NUMB)  !cfan 08/23
      IF (IERR.NE.0) THEN
         IF (IERR.NE.2) THEN
            WRITE (LP,340) 'MAPX','AREA',AREAID
            CALL SUERRS (LP,2,NUMERR)
            ISTAT=1
            ENDIF
         IF (IERR.EQ.2.AND.LDEBUG.GT.0) THEN
            WRITE (IOSDBG,350) 'MAPX'
            CALL SULINE (IOSDBG,1)
            ENDIF
         GO TO 260
         ENDIF
C
      IF (LDEBUG.GT.0) THEN
         IF (LDEBUG.EQ.1) THEN
            WRITE (IOSDBG,390) AREAID,BASNID,XCHKID
            CALL SULINE (IOSDBG,1)
            ENDIF
         IF (LDEBUG.GT.1) THEN
            CALL SPMAPX (IPRNT,IVMAPX,AREAID,DESCRP,ITIME,
     *         BASNID,FMAPID,UNUSED,IERR,NUMB)     !cfan 08/23
            ENDIF
        ENDIF
C
      NMAPX=NMAPX+1
C
C  CHECK IF BASIN ID USED
      IF (BASNID.EQ.XCHKID) THEN
         WRITE (LP,400) 'BASIN',BASNID,
     *      'MAPX',AREAID(1:LENSTR(AREAID))
         CALL SUERRS (LP,2,NUMERR)
         ISTAT=2
         ENDIF
C
260   IF (IXSORT.EQ.0) THEN
         IF (IPTRNX.GT.0) GO TO 250
         ELSE
            IF (NMAPX.LT.NUMID3) GO TO 250
         ENDIF
C
      GO TO 300
C
      ENDIF
C
C- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
C
      IF (TYPE.EQ.'FMAP') THEN
C
      MAXID=LARAY1/(NWORDS+1)/2
C
C  CHECK IF FMAP AREA IS USED IN ANY MAP AREAS
C
      IF (IFIRST.EQ.1) THEN
C     GET SORTED LIST OF IDENTIFIERS
         IXSORT=ISORT
         IARAY1(MAXID*NWORDS+1)=1
         IPRMSG=0
         CALL SURIDS ('MAP ',IXSORT,MAXID,ISTATE,NWORDS,
     *      IARAY1,IARAY1(MAXID*NWORDS+1),
     *      NUMID1,LARRAY,ARRAY,IPRMSG,IPRERR,IERR)
         IF (IERR.GT.0) IXSORT=0
         ENDIF
C
      IF (NUMID1.EQ.0) GO TO 300
C
      IPTRNX=0
      NAREA=0
C
270   AREAID=' '
      IF (IXSORT.EQ.0) THEN
         IPTR=IPTRNX
         ELSE
            IPTR=IARAY1(MAXID*NWORDS+NAREA+1)
         ENDIF
      CALL SRMAP (IVMAP,AREAID,ITIME,ITMWT,POWER,MSTWT,NSTWT,
     *   ISTWT,MPCPN,NPCPN,NSETS,DESCRP,BASNID,FMAPID,CENTRD,
     *   TSTAID,TSTAWT,CTSTA,CSTAID,CSTAWT,CCSTA,
     *   UNUSED,LARRAY,ARRAY,IPTR,IPRERR,IPTRNX,IERR)
      IF (IERR.NE.0) THEN
         IF (IERR.NE.2) THEN
            WRITE (LP,340) 'MAP','AREA',AREAID
            CALL SUERRS (LP,2,NUMERR)
            ENDIF
         IF (IERR.EQ.2.AND.LDEBUG.GT.0) THEN
            WRITE (IOSDBG,350) 'MAP'
            CALL SULINE (IOSDBG,1)
            ENDIF
         GO TO 280
         ENDIF
C
      IF (LDEBUG.GT.0) THEN
         IF (LDEBUG.EQ.1) THEN
            WRITE (IOSDBG,395) AREAID,FMAPID,XCHKID
            CALL SULINE (IOSDBG,1)
            ENDIF
         IF (LDEBUG.GT.1) THEN
            IPTR2=0
      CALL SRMAPS (IVMAPS,AREAID,CENTRD,RADINF,IPMAP,NTECH,
     *   IBASN,MSTWT,NSTWT,MPCPN,NPCPN,MBOX,NBOX,ITECHS,IPD6,IPD24,
     *   MDRBOX,CORMDR,UNUSED,LARRAY,ARRAY,IPTR2,IPRERR,IPTRN2,IERR2)
            IF (BASNID.NE.' ') THEN
            IPTR3=0
            CALL SRBASN (ARRAY,LARRAY,IJ,BASNID,BDESC,LAT,LON,
     *         MBPTS,NBPTS,AREA,CAREA,ELEV,CENTRD(1),CENTRD(2),
     *         MAPFLG,MATFLG,DMYID,DMYID,DMYID,
     *         MBPTS,NSEGS,IY,IXB,IXE,LFACTR,IPTR3,IPTRN3,IPRERR,IERR)
            IF (IERR.EQ.0) THEN
         CALL SPMAP (IPRNT,IVMAP,IVMAPS,AREAID,ITIME,ITMWT,POWER,NSTWT,
     *      ISTWT,NPCPN,NSETS,DESCRP,BASNID,FMAPID,CENTRD,TSTAID,
     *      TSTAWT,CTSTA,CSTAID,CSTAWT,CCSTA,
     *      RADINF,IPMAP,NTECH,IBASN,NBOX,ITECHS,IPD6,IPD24,MDRBOX,
     *      CORMDR,UNUSED,IY,IXB,IXE,NSEGS,X,Y,JX,JY,NBPTS,
     *      LFACTR,PLOT,LARRAY,ARRAY,UNITS,AREA,CAREA,JN,IERR)
               ENDIF
            ENDIF
            ENDIF
         ENDIF
C
      NAREA=NAREA+1
C
C  CHECK IF FMAP AREA USED
      IF (FMAPID.EQ.XCHKID) THEN
         WRITE (LP,400) 'FMAP',XCHKID,'MAP ',AREAID(1:LENSTR(AREAID))
         CALL SUERRS (LP,2,NUMERR)
         ISTAT=2
         ENDIF
C
280   IF (IXSORT.EQ.0) THEN
         IF (IPTRNX.GT.0) GO TO 270
         ELSE
            IF (NAREA.LT.NUMID1) GO TO 270
         ENDIF
C
C      -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -
C
C  CHECK IF FMAP AREA IS USED IN ANY MAPX AREAS
C
      IF (IFIRST.EQ.1) THEN
C     GET SORTED LIST OF IDENTIFIERS
         IXSORT=ISORT
         IARAY1(2*MAXID*NWORDS+1)=1
         IPRMSG=0
         CALL SURIDS ('MAPX',IXSORT,MAXID,ISTATE,NWORDS,
     *      IARAY1,IARAY1(2*MAXID*NWORDS+1),
     *      NUMID1,LARRAY,ARRAY,IPRMSG,IPRERR,IERR)
         IF (IERR.GT.0) IXSORT=0
         ENDIF
C
      IF (NUMID1.EQ.0) GO TO 300
C
      IPTRNX=0
      NAREA=0
C
283   AREAID=' '
      IF (IXSORT.EQ.0) THEN
         IPTR=IPTRNX
         ELSE
            IPTR=IARAY1(2*MAXID*NWORDS+NAREA+1)
         ENDIF
      CALL SRMAPX (IVMAPX,AREAID,ITIME,DESCRP,BASNID,FMAPID,
     *   UNUSED,LARRAY,ARRAY,IPTR,IPRERR,IPTRNX,IERR,NUMB)
      IF (IERR.NE.0) THEN
         IF (IERR.NE.2) THEN
            WRITE (LP,340) 'MAPX','AREA',AREAID
            CALL SUERRS (LP,2,NUMERR)
            ISTAT=1
            ENDIF
         IF (IERR.EQ.2.AND.LDEBUG.GT.0) THEN
            WRITE (IOSDBG,350) 'MAPX'
            CALL SULINE (IOSDBG,1)
            ENDIF
         GO TO 285
         ENDIF
C
      IF (LDEBUG.GT.0) THEN
         IF (LDEBUG.EQ.1) THEN
            WRITE (IOSDBG,395) AREAID,FMAPID,XCHKID
            CALL SULINE (IOSDBG,1)
            ENDIF
         IF (LDEBUG.GT.1) THEN
            CALL SPMAPX (IPRNT,IVMAPX,AREAID,DESCRP,ITIME,
     *         BASNID,FMAPID,UNUSED,IERR,NUMB)    !cfan 08/23
            ENDIF
        ENDIF
C
      NAREA=NAREA+1
C
C  CHECK IF FMAP ID USED
      IF (FMAPID.EQ.XCHKID) THEN
         WRITE (LP,400) 'FMAP',XCHKID,'MAPX',AREAID(1:LENSTR(AREAID))
         CALL SUERRS (LP,2,NUMERR)
         ISTAT=2
         ENDIF
C
285   IF (IXSORT.EQ.0) THEN
         IF (IPTRNX.GT.0) GO TO 283
         ELSE
            IF (NAREA.LT.NUMID1) GO TO 283
         ENDIF
C
      GO TO 300
C
      ENDIF
C
C- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
C
C  DIVIDE WORK SPACE
      MAXID=LARAY3/8
C  TIME SERIES IDS
      ID1=1
C  CARRYOVER GROUP IDS
      ID2=MAXID*NWORDS+1
C  FORECAST GROUP IDS
      ID3=MAXID*3+1
C  SEGMENT IDS
      ID4=MAXID*4+1
C
C  GET IDENTIFIERS USED IN ALL CARRYOVER GROUPS
      IF (IFIRST.EQ.1) THEN
         IFILFC=1
         IPRMSG=0
         CALL SUGTFC (TYPE,MAXID,ARAY3(ID1),NUMID1,IFILFC,
     *      ARAY3(ID2),ARAY3(ID3),ARAY3(ID4),IPRMSG,IERR)
         IF (IERR.NE.0) THEN
            IF (IERR.NE.1) THEN
               WRITE (LP,430) TYPE
               CALL SUERRS (LP,2,NUMERR)
               ISTAT=2
               ENDIF
            GO TO 300
            ENDIF
         ENDIF
C
      IF (NUMID1.EQ.0) GO TO 300
C
C  CHECK IF IDENTIFIER USED IN A SEGMENT
      NUM=NUMID1*2
      IFOUND=0
      DO 290 I=1,NUM,2
         J=ID1+I-1
         CALL SUBSTR (ARAY3(J),1,LEN(XTSID),XTSID,1)
         IF (XCHKID.EQ.XTSID) THEN
            IF (IFOUND.EQ.0) THEN
               IF (TYPE.EQ.'MAP'.OR.
     *             TYPE.EQ.'MAPX'.OR.
     *             TYPE.EQ.'MAT'.OR.
     *             TYPE.EQ.'MAPE'.OR.
     *             TYPE.EQ.'FMAP') THEN
                  STRING='AREA'
                  ELSE
                     STRING='TIME SERIES FOR STATION'
                  ENDIF
               WRITE (LP,440) TYPE,STRING(1:LENSTR(STRING)),XCHKID
               CALL SUERRS (LP,2,NUMERR)
               IFOUND=1
               ENDIF
            CALL SUBSTR (ARAY3(ID4+I-1),1,LEN(XTSID),XSEGID,1)
            CALL SUBSTR (ARAY3(ID3+I-1),1,LEN(XTSID),XFGID,1)
            CALL SUBSTR (ARAY3(ID2+I-1),1,LEN(XTSID),XCGID,1)
            WRITE (LP,450) XSEGID,XFGID,XCGID
            CALL SULINE (LP,1)
            ISTAT=2
            ENDIF
290      CONTINUE
C
      GO TO 300
C
C- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
C
300   IF (LDEBUG.GT.0) THEN
         WRITE (IOSDBG,420) NSPCPN,'PCPN'
         CALL SULINE (IOSDBG,1)
         WRITE (IOSDBG,420) NMAP,'MAP'
         CALL SULINE (IOSDBG,1)
         WRITE (IOSDBG,420) NMAT,'MAT'
         CALL SULINE (IOSDBG,1)
         WRITE (IOSDBG,420) NMAPX,'MAPX'
         CALL SULINE (IOSDBG,1)
         WRITE (IOSDBG,420) NMAPE,'MAPE'
         CALL SULINE (IOSDBG,1)
         ENDIF
C
      IF (ISTRCE.GT.0) THEN
         WRITE (IOSDBG,*) 'EXIT SLCHK'
         CALL SULINE (IOSDBG,1)
         ENDIF
C
      RETURN
C
C- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
C
320   FORMAT (' STATION ',A,' HAS 1/D**2 WEIGHTS')
330   FORMAT ('0*** ERROR - STATION ',A,' IS USED AS A ',A,' ',
     *   'SIGNIFICANCE STATION BY ',A,' STATION ',A,'.')
340   FORMAT ('0*** ERROR - IN SLCHK - READING ',A,' ',
     *   'PARAMETERS FOR ',A,' ',A,'.')
350   FORMAT (' NO ',A,' AREAS DEFINED')
360   FORMAT (' AREA ',A,' HAS ',A,' WEIGHTS')
370   FORMAT ('0*** ERROR - STATION ',A,' IS USED AS A ',A,' ',
     *   A,' STATION BY ',A,' AREA ',A,'.')
380   FORMAT ('0*** ERROR - STATION ',A,' IS USED AS A ',A,' ',
     *   A,A,A,' STATION BY ',A,' AREA ',A,'.')
390   FORMAT (' AREAID=',A,3X,'BASNID=',A,3X,'XCHKID=',A)
395   FORMAT (' AREAID=',A,3X,'FMAPID=',A,3X,'XCHKID=',A)
400   FORMAT ('0*** ERROR - ',A,' ',A,' IS USED BY ',A,' AREA ',A,'.')
420   FORMAT (' ' ,I4,1X,A,' AREAS CHECKED')
430   FORMAT ('0*** ERROR - TIME SERIES IDENTIFIERS FOR ',A,' ',
     *   'AREAS NOT SUCCESSFULLY BE READ. REQUIRED CHECKS CANNOT BE ',
     *   'MADE.')
440   FORMAT ('0*** ERROR - ',A,' ',A,' ',A,'IS USED BY:')
450   FORMAT (T14,
     *   'SEGMENT: ',A : 5X,
     *   'FORECAST GROUP: ',A : 5X,
     *   'CARRYOVER GROUP: ',A : 5X
     *    )
C
      END
