." $Id: ldmd.1,v 1.7.20.3.2.8 2009/07/23 21:08:57 steve Exp $
.TH LDMD 1 "$Date: 2009/07/23 21:08:57 $"
.SH NAME
rpc.ldmd \- Unidata LDM Server (version 6)
.SH SYNOPSIS
.HP
.ft B
rpc.ldmd
.nh
\fP[\fB-I\ \fIIP_addr\fR]
\fP[\fB-l\ \fIlogpath\fR]
\fP[\fB-M\ \fImax_clients\fR]
\fP[\fB-m\ \fImax_latency\fR]
\fP[\fB-o\ \fItoffset\fR]
\fP[\fB-P\ \fIport\fR]
\fP[\fB-q\ \fIpqfname\fR]
\fP[\fB-t\ \fIrpctimeo\fR]
\fP[\fB\-vx\fP]
\fP[\fIconf_filename\fR]
.hy
.ft
.SH DESCRIPTION
.PP
This program is the LDM server. 
.PP
The LDM server performs several functions:
.sp
.RS 4
.TP 3
1)
It starts up the programs which
access a local product queue (see \fBpq(3)\fP). These are specified
by the "exec" entries in the configuration file. It serves as the
process group leader for these programs and specialized copies of
itself.
.TP
2)
It forks processes which request and then receive data from
other LDM servers. The data received is placed in the product
queue and the local programs are notified. This function is
controlled by the "request" entries in the configuration file.
.TP
3)
It compiles access control information from the configuration file.
These are the "accept" (input) and "allow" (output) entries.
They are used to determine which hosts can request what services
from this server.
.TP
4)
It registers a TCP RPC service for version 5 and version 6 of the
protocol. It listens for connections, performs access control
similar to \fBtcpd\fP and forks to service requests on that connection.
.PP
.RE
.TP
\fIconf_filename\fP is the pathname of the configuration file.
.SH OPTIONS
.TP
.BI "-I " IP_addr
IP address of network interface to use.  The default is to use all
available network interfaces.
.TP
.BI "-l " logpath
Log file pathname.
The program uses Unidata's ulog(3) package to write error and diagnostic
messages.
The default is to write to the \fBsyslogd\fP(8) daemon.  If this option is
specified, however, then messages will be written to the file
\fIlogpath\fP unless that pathname is "\fB-\fP", in which case all 
messages will be written to standard error.
.TP
.BI "-M " max_clients
The maximum number of clients allowed to connect to the LDM server before
additional connections are rejected.  Default is 256.
.TP
.BI "-m " max_latency
\fBFor connections using LDM 5 protocols only.\fP
Receipt of a product older than \fImax_latency\fP (plus \fIrpctimeo\fP)
seconds triggers a RECLASS response, which generally causes the
sender to skip ahead in it's queue. If \fItoffset\fP was specified, then
the "from" time of the RECLASS response is \fItoffset\fP seconds before now,
otherwise, \fImax_latency\fP is used.
.TP
.BI "-o " toffset
No products older than \fItoffset\fP seconds are requested.
Defaults to the value of \fImax_latency\fP.
If this parameter is not specified, and
your queue is not empty, then your initial requests will be for the most
recent data in the queue which is younger than \fImax_latency\fP.
The value of \fItoffset\fP should be strickly less than \fImax_latency\fP.
.TP
.BI "-P " port
Port on the remote host on which to connect.  The default is set when the
LDM package is compiled.  The well-known LDM port is 388.
.TP
.BI "-q " pqfname
Set the pathname of the data product queue to \fIpqfname\fP.
The default is \fBdata/ldm.pq\fP relative to the installation point,
which is typically \fB/usr/local/ldm\fP.
As a convenience, the process group leader sets the environment
variable \fBLDMPQFNAME\fP to this value, overriding the default in
in cooperative children.
.TP
.BI "-t " rpctimeo
Sets the timeout for LDM 5 remote procedure calls to \fIrpctimeo\fP seconds.
.TP
.B -v
Verbose logging.
Informative messages (level \fBLOG_INFO\fP) are logged.
By default, only messages of severity \fBLOG_NOTICE\fP and greater are
logged. Incoming products are logged as they are received.
.TP
.B -x
Debug logging.
Debugging messages (level \fBLOG_DEBUG\fP) are logged.
At least three times the output of verbose logging. A message
is printed for each RPC transaction (except NULLPROC). In
particular, the progress of incoming products is may be monitored.
The MD5 checksum of each product is printed.
.SH SIGNALS
.TP
.BR SIGTERM
Normal termination. If sent to the process group leader,
it forwards the signal to the process group
and waits termination of all the children.
.BR SIGINT
Slightly expedited termination. If sent to the process group leader,
it still sends SIGTERM to the process group and waits. Caution: killing
receivers with SIGINT or SIGKILL (-9) can result in queue corruption.
.TP
.B SIGUSR2
Cyclically increment the verbosity of the program. Assumming the program was
started without the \fB-v\fP or \fB-x\fP switches, the first \fBSIGUSR2\fP will
make it verbose and \fBLOG_INFO\fP priority messages will appear.
The second will turn on the \fBLOG_DEBUG\fP priority messages as well.
A third will take it back to the normal state.
.SH "SEE ALSO"
.LP
.BR ulog (3),
.BR syslogd (8),
.BR portmap (8),
\fBhttp://www.unidata.ucar.edu/software/ldm/\fP.
.SH SUPPORT
.LP
If you have problems with this program, then you should first examine the 
LDM email archive for similar problems and how they were solved.
The email archive is available via the following URL:
.sp
.RS
\fBhttp://www.unidata.ucar.edu/software/ldm/\fP
.RE
.sp
If this does not suffice, then send an inquiry via email -- together will 
all relevant information -- to
.sp
.RS
\fBsupport-ldm@unidata.ucar.edu\fP
.RE
