#!/bin/sh

#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
# 
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

#
# Library names (without path or .so) and CppUnit test paths can be
# specified on the command line or in env var UNIT_TESTS. For example:
#
# Selected test classes:
# ./run-unit-tests ValueTest ClientChannelTest
# 
# Individual test method
# ./run-unit-tests ValueTest :ValueTest::testStringValueEquals
# 
# Build and run selected tests:
# make check TESTS=run-unit-tests UNIT_TESTS=ClientChannelTest
#

for u in $* $UNIT_TESTS ; do
    case $u in
	:*) TEST_ARGS="$TEST_ARGS $u" ;; # A test path.
	*) TEST_ARGS="$TEST_ARGS .libs/$u.so" ;; # A test library.
    esac
done
test -z "$TEST_ARGS" && TEST_ARGS=".libs/*Test.so"

test -z "$srcdir" && srcdir=.

# libdlclose_noop prevents unloading symbols needed for valgrind output.
export LD_PRELOAD=.libs/libdlclose_noop.so
source $srcdir/run_test DllPlugInTester -c -b $TEST_ARGS
