#!/bin/bash

#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
#script to run a sequence of ring queue tests via make

#setup path to find qpid-config and sender/receiver test progs
source ./test_env.sh

export PATH=$PWD:$srcdir:$PYTHON_COMMANDS:$PATH

#set port to connect to via env var
test -s qpidd.port && QPID_PORT=`cat qpidd.port`
export QPID_PORT

ring_queue_test -c -s 4 -r 4
ring_queue_test -s 4 -r 0
ring_queue_test -s 1 -r 1


