#!/bin/sh

#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
# 
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

# Start a cluster of brokers on local host, put the list of ports for cluster members in cluster.ports
#

# Execute command with the ais group set.
source ./test_env.sh
. `dirname $0`/ais_check

rm -f cluster*.log cluster.ports qpidd.port

SIZE=${1:-3}; shift
CLUSTER=$HOSTNAME.$$
OPTS="-d --no-module-dir --load-module $CLUSTER_LIB  --cluster-name=$CLUSTER --auth=no --log-enable notice+ --log-enable debug+:cluster $@"

for (( i=0; i<SIZE; ++i )); do
    DDIR=`mktemp -d /tmp/start_cluster.XXXXXXXXXX`
    PORT=`with_ais_group ../qpidd  -p0 --log-to-file=cluster$i.log $OPTS --data-dir=$DDIR`  || exit 1
    echo $PORT >> cluster.ports
done

head -n 1 cluster.ports > qpidd.port	# First member's port for tests.

