#!/bin/sh

#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
# 
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

# Read the started broker port, set appropriate env vars
# then run the program under test

QPID_PORT=`cat qpidd.port`
export QPID_PORT

program=$1
shift

QPID_LOG_TO_FILE=`basename $program`.log
export QPID_LOG_TO_FILE

ERROR=0
$program $* || ERROR=1

# Check qpidd.log.
egrep 'warning\|error\|critical' $QPID_LOG_TO_FILE && {
    echo "WARNING: Suspicious broker log entries in $QPID_LOG_TO_FILE, above."
}

# Check valgrind log.
#if test -n "$VALGRIND"; then
#    . `dirname $0`/vg_check $VG_LOG*
#   vg_check qpidd.vglog* || ERROR=1
#fi

exit $ERROR
