# Frequency for running Registry Status check
registry.healthCheck.cron=0 * * ? * *
# Time interval in minutes to send AlertViz notification message
alertVizNotificationInterval=30
# Enable registry health check
registry.healthCheck.enabled=true