#!/bin/bash
_USER=`whoami`
if [ ${_USER} != 'root' ]
then
  echo WARNING: this script requires root access to run,
  echo          please su to root and run again.
  exit 1 
fi
echo running as ${_USER}
echo mapping int1 log directory as /logs/int1
mount awips-int1:/awips/edex/logs /logs/int1
echo mapping int2 log directory to /logs/int2
mount awips-int2:/awips/edex/logs /logs/int2
echo mapping dev1 log directory to /logs/dev1
mount awips-dev1:/awips/edex/logs /logs/dev1
echo mapping dev2 log directory to /logs/dev2
mount awips-dev2:/awips/edex/logs /logs/dev2

