#!/bin/bash
_USER=`whoami`
if [ ${_USER} != 'root' ]
then 
  echo WARNING: this script requires root access to run,
  echo          please su to root and run again.
  exit 1
fi
echo running as ${_USER}
echo unmapping log directory on INT1
umount -l /logs/int1
echo unmapping log directory on INT2
umount -l /logs/int2
echo unmapping log directory on DEV1
umount -l /logs/dev1
echo unmapping log directory on DEV2
umount -l /logs/dev2
