C MEMBER SPMAT
C-----------------------------------------------------------------------
C
C                             LAST UPDATE: 09/21/94.12:58:49 BY $WC20SV
C
C @PROCESS LVL(77)
C
C  ROUTINE TO PRINT AREA MAT PARAMETER RECORD
C
      SUBROUTINE SPMAT (IPRNT,UNITS,IVMAT,XMATID,DESCRP,CENTRD,BASNID,
     *   ISTWT,POWER,NTEMP,TEMPID,IPDMMT,WTMMT,UNUSED,LARRAY,ARRAY,
     *   ISTAT)
C
      CHARACTER*8 TYPMSG
      REAL ENGL/4HENGL/
      REAL FEET/4HFT  /
      REAL METERS/4HM   /
      REAL*8 BSNID
C
      DIMENSION ARRAY(LARRAY)
      DIMENSION XMATID(2),DESCRP(5),CENTRD(2)
      DIMENSION BASNID(2),TEMPID(2,1),IPDMMT(1),WTMMT(1)
      DIMENSION STAID(2),DESC(5),STACOR(2)
      DIMENSION UNUSED(1)
C
      INCLUDE 'uio'
      INCLUDE 'scommon/sudbgx'
C
C    ================================= RCS keyword statements ==========
      CHARACTER*68     RCSKW1,RCSKW2
      DATA             RCSKW1,RCSKW2 /                                 '
     .$Source: /fs/hseb/ob72/rfc/ofs/src/ppinit_print/RCS/spmat.f,v $
     . $',                                                             '
     .$Id: spmat.f,v 1.1 1995/09/17 19:14:14 dws Exp $
     . $' /
C    ===================================================================
C
C
C
      IF (ISTRCE.GT.0) THEN
         WRITE (IOSDBG,130)
         CALL SULINE (IOSDBG,1)
         ENDIF
C
C  SET DEBUG LEVEL
      LDEBUG=ISBUG('MAT ')
C
      ISTAT=0
      NUMERR=0
C
C  CHECK NUMBER OF LINES LEFT ON PAGE
      IF (ISLEFT(5).GT.0) CALL SUPAGE
C
C  PRINT HEADING
      IF (IPRNT.NE.2) WRITE (LP,140) XMATID
      IF (IPRNT.EQ.2) WRITE (LP,150) XMATID
      CALL SULINE (LP,2)
      WRITE (LP,160) XMATID
      CALL SULINE (LP,2)
      WRITE (LP,170)
      CALL SULINE (LP,1)
C
C  PRINT PARAMETER ARRAY VERSION NUMBER
      IF (LDEBUG.EQ.0) GO TO 10
         WRITE (LP,180) IVMAT
         CALL SULINE (LP,2)
C
C  PRINT MAT AREA IDENTIFIER, DESCRIPTIVE INFORMATION, CENTROID
C  COORDINATES AND BASIN BOUNDARY IDENTIFIER
10    CALL SUBSTR (BASNID,1,8,BSNID,1)
      CALL SUBLID (BSNID,IERR)
      WRITE (LP,190) DESCRP,CENTRD,BSNID
      CALL SULINE (LP,2)
C
C  PRINT TYPE OF STATION WEIGHTS AND EXPONENT IN 1/D**POWER
      GO TO (20,30,40),ISTWT
         WRITE (LP,200) ISTWT
         CALL SUERRS (LP,2,NUMERR)
         GO TO 55
20       WRITE (LP,210)
         GO TO 50
30       WRITE (LP,220)
         GO TO 50
40       WRITE (LP,230) POWER
50       CALL SULINE (LP,2)
C
C  PRINT IDENTIFIER AND WEIGHT FOR MAT COMPUTATION STATIONS
55    IF (NTEMP.GT.0) GO TO 60
         WRITE (LP,240)
         CALL SULINE (LP,2)
         GO TO 100
60    IF (ISLEFT(5).GT.0) CALL SUPAGE
      WRITE (LP,250)
      CALL SULINE (LP,2)
      XUNITS=METERS
      IF (UNITS.EQ.ENGL) XUNITS=FEET
      WRITE (LP,260) XUNITS
      CALL SULINE (LP,3)
      DO 70 I=1,NTEMP
         CALL SUBSTR (TEMPID(1,I),1,8,STAID,1)
         TYPMSG='ERROR'
         CALL SUGTDS (STAID,DESC,STATE,STACOR,STAELV,LARRAY,ARRAY,
     *      TYPMSG,IERR)
         IF (IERR.NE.0) GO TO 70
         CALL SBLLGD (XLON,XLAT,1,STACOR(1),STACOR(2),0,IERR)
         IF (UNITS.EQ.ENGL)
     *      CALL UDUCNV (METERS,FEET,1,1,STAELV,STAELV,IERR)
         IF (ISNWPG(LP).EQ.1) WRITE (LP,260) XUNITS
         IF (ISNWPG(LP).EQ.1) CALL SULINE (LP,3)
         WRITE (LP,270) I,DESC,STAID,WTMMT(I),XLAT,XLON,STAELV
         CALL SULINE (LP,1)
70       CONTINUE
C
C  PRINT ARRAY LOCATIONS OF POINTERS FOR MAX/MIN TEMP DATA FOR STATION
      IF (LDEBUG.EQ.0) GO TO 100
         IF (ISLEFT(5).GT.0) CALL SUPAGE
         WRITE (LP,290)
         CALL SULINE (LP,3)
         DO 90 I=1,NTEMP
            IF (ISNWPG(LP).EQ.1) WRITE (LP,290)
            IF (ISNWPG(LP).EQ.1) CALL SULINE (LP,3)
            WRITE (LP,300) I,TEMPID(1,I),TEMPID(2,I),IPDMMT(I)
            CALL SULINE (LP,1)
90          CONTINUE
C
C  PRINT NUMBER OF UNUSED POSITIONS
100   NUNUSD=2
      IF (LDEBUG.GT.0) WRITE (LP,280) NUNUSD
      IF (LDEBUG.GT.0) CALL SULINE (LP,2)
C
      WRITE (LP,310)
      CALL SULINE (LP,2)
C
      IF (LDEBUG.GT.0.AND.ISTAT.EQ.0) WRITE (IOSDBG,320)
      IF (LDEBUG.GT.0.AND.ISTAT.EQ.0) CALL SULINE (IOSDBG,1)
C
      IF (ISTRCE.GT.0) THEN
         WRITE (IOSDBG,330)
         CALL SULINE (IOSDBG,1)
         ENDIF
C
      RETURN
C
C- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
C
130   FORMAT (' *** ENTER SPMAT')
140   FORMAT ('0',33('-'),' ID=',2A4,2X,85('-'))
150   FORMAT ('0',26('-'),' DESC=',5A4,2X,78('-'))
160   FORMAT ('0*--> MAT PARAMETERS : IDENTIFIER = ',2A4)
170   FORMAT (' ')
180   FORMAT ('0PARAMETER ARRAY VERSION NUMBER = ',I2)
190   FORMAT ('0DESCRIPTION = ',5A4,5X,
     *   'CENTROID: LATITUDE = ',F7.2,2X,'LONGITUDE = ',F7.2,5X,
     *   'BASIN IDENTIFIER = ',A8)
200   FORMAT ('0*** ERROR - IN SPMAT - INDICATOR FOR TYPE OF STATION ',
     *    'WEIGHTS NOT RECOGNIZED: ',I3,'.')
210   FORMAT ('0TYPE OF STATION WEIGHTS = PREDETERMINED')
220   FORMAT ('0TYPE OF STATION WEIGHTS = GRID POINT')
230   FORMAT ('0TYPE OF STATION WEIGHTS = 1/D**POWER      EXPONENT ',
     *   'IN 1/D**POWER = ',F6.1)
240   FORMAT ('0STATIONS USED FOR COMPUTING MAT:  ** NONE DEFINED **')
250   FORMAT ('0',5X,'STATIONS USED FOR COMPUTING MAT')
260   FORMAT ('0',T10,'DESCRIPTION',12X,'IDENTIFIER',3X,
     *   'WEIGHT',3X,'LAT',5X,'LONG',5X,'ELEV(',A2,')' /
     *   T10,20('-'),3X,10('-'),3X,6('-'),3X,5('-'),3X,6('-'),3X,8('-'))
270   FORMAT (5X,I2,2X,5A4,3X,2A4,5X,F6.2,3X,F5.2,3X,F6.2,3X,F8.1)
280   FORMAT ('0NUMBER OF UNUSED POSITIONS = ',I2)
290   FORMAT ('0PPDB ARRAY LOCATION POINTERS:',
     *   5X,'IDENTIFIER',8X,'POINTER',/,35X,
     *   10('-'),8X,7('-'))
300   FORMAT (30X,I2,4X,2A4,10X,I5)
310   FORMAT ('0',132('-'))
320   FORMAT  (' *** NOTE - MAT PARAMETERS SUCCESSFULLY ',
     *   'PRINTED.')
330   FORMAT(' *** EXIT SPMAT')
C
      END
