#!/bin/ksh

export JAVA_BIN_DIR=/usr/local/java//bin

export DRIVERPATH=/usr/lib/postgresql-8.2-506.jdbc3.jar
export RUN_FROM_DIR=`dirname $0`
export PROJECTS_DIR=$RUN_FROM_DIR/../..
export DAMCRESTDB_DIR=$PROJECTS_DIR/damcrestdb
export DB_DIR=$PROJECTS_DIR/db


#export JAVA_VM_DIR=/fs/hseb/${DS_BUILD}/ohd/java/ohd-common/projects
#export DAMCRESTDB_DIR=$JAVA_VM_DIR/damcrestdb
#export DB_DIR=$JAVA_VM_DIR/db

export BASEPATH=$DB_DIR/classes

export CLASSPATH=./:$BASEPATH/:$DRIVERPATH
echo "CLASSPATH =" $CLASSPATH

#The connection string
connecturl="jdbc:postgresql://genessee:5432/dc_ob7empty?user=pguser"


#The location of the PreferredTableNames.txt file.
namingfile=$DAMCRESTDB_DIR/scripts/PreferredTableNames.txt

#The destination of the generated source files 
targetdir=/fs/hseb/${DS_BUILD}/ohd/whfs_lib/src/DamCrestDBGenerated/TEXT

#db name
dbname=dc_ob7empty

#package name -- NONE means no packaging
# Note: this does NOT affect directly in which the generated class is placed
package=ohd.hseb.ihfsdb.generated

db_driver_class_name=org.postgresql.Driver

rm -f /fs/hseb/${DS_BUILD}/ohd/whfs_lib/src/DamCrestDBGenerated/TEXT/*.pgc
rm -f /fs/hseb/${DS_BUILD}/ohd/whfs_lib/src/DamCrestDBGenerated/TEXT/*.h
$JAVA_BIN_DIR/java ohd.hseb.dbgen.CDbGen $connecturl $namingfile $dbname $targetdir $db_driver_class_name

mv $targetdir/*.h /fs/hseb/${DS_BUILD}/ohd/whfs_lib/inc/dbms/
#cd -
return $?
