C MODULE MAESCC
C-----------------------------------------------------------------------
C
C     DESC - PERFORMS THE AESCCHNG MOD
C
      SUBROUTINE MAESCC(NCARDS,MODCRD,IDATE,IHZERO)
C
      LOGICAL FIRST
C
      CHARACTER*8 OPNAME,IFIELD,BLANK8,SLASH,MODNAM
C
      INCLUDE 'common/fmodft'
      COMMON/FRARSW/NRARSW,RARESW(6,10)
      INCLUDE 'common/ionum'
      INCLUDE 'common/fpwarn'
      INCLUDE 'common/fdbug'
      INCLUDE 'common/fctime'
      INCLUDE 'common/fctim2'
      INCLUDE 'ufreex'
C
      DIMENSION OLDOPN(2),MODCRD(20,NCARDS)
C
C    ================================= RCS keyword statements ==========
      CHARACTER*68     RCSKW1,RCSKW2
      DATA             RCSKW1,RCSKW2 /                                 '
     .$Source: /fs/hseb/ob72/rfc/ofs/src/fcst_mods/RCS/maescc.f,v $
     . $',                                                             '
     .$Id: maescc.f,v 1.3 1998/07/02 20:35:10 page Exp $
     . $' /
C    ===================================================================
C
C
      DATA BLANK8/'        '/,SLASH/'/       '/
      DATA MODNAM/'AESCCHNG'/
C
      CALL FSTWHR(8HMAESCC  ,0,OLDOPN,IOLDOP)
C
C     SET DEBUG SWITCH
C
      IBUG=IFBUG(4HMODS)+IFBUG(4HAESC)
C
      IF(IBUG.GT.0)WRITE(IPR,10)IDATE
10    FORMAT(1H0,10X,'** IN SUBROUTINE MAESCC - IDATE = ',I11)
C
      ICOMP=((LDACPD-1)*24)+LHRCPD
      IF (IDATE.LE.ICOMP) GOTO 20
         IF (MODWRN.EQ.0) GOTO 320
         ITYPE=2
         CALL MODS1(NCARDS,ICMND,MODNAM,MODCRD,ITYPE)
         GOTO 320
C
C     SEE IF DATE IS WITHIN - OR + 12 HOURS OF START OR END OF RUN
C
20    ISTHR=(IDA-1)*24+IHZERO
      IENHR=(LDA-1)*24+LHR
C
      IF(ISTHR-12.LE.IDATE.AND.IENHR+12.GE.IDATE)GO TO 40
C
C     DATE NOT WITHIN ALLOWABLE WINDOW
C
      CALL MDYH2(IDA,IHZERO,IM1,ID1,IY1,IH1,DUM1,DUM2,MODTZC)
      CALL MDYH2(LDA,LHR,IM2,ID2,IY2,IH2,DUM1,DUM2,MODTZC)
      IXDA=IDATE/24+1
      IXHR=IDATE-(IXDA-1)*24
      IF(IXHR.EQ.0)IXDA=IXDA-1
      IF(IXHR.EQ.0)IXHR=24
      CALL MDYH2(IXDA,IXHR,IM3,ID3,IY3,IH3,DUM1,DUM2,MODTZC)
C
      IF(MODWRN.EQ.1)
     .WRITE(IPR,30)IM3,ID3,IY3,IH3,MODTZC,IM1,ID1,IY1,IH1,MODTZC,
     1IM2,ID2,IY2,IH2,MODTZC
30    FORMAT(1H0,10X,'**WARNING** THE DATE FOR CHANGES ENTERED IN THE ',
     1 'AESCCHNG MOD (',I2,1H/,I2,1H/,I4,1H-,I2,1X,A4,1H)/11X,
     2 'IS NOT WITHIN 12 HOURS OF THE CURRENT RUN PERIOD (',I2,1H/,I2,
     3 1H/,I4,1H-,I2,1X,A4,4H TO ,I2,1H/,I2,1H/,I4,1H-,I2,1X,A4,1H)/
     4 11X,'THESE CHANGES WILL BE IGNORED.')
      IF(MODWRN.EQ.1)CALL WARN
      GO TO 320
C
C     READ MOD CARDS FOR THIS SEGMENT - STORE VALUES IN ARRAYS() -
C      WILL TRANSFER TO CB /FRARSW/ AFTER ALL INFO IS READ
C
C     READ CARD - IF COMMAND, LEAVE - IF COMMAND AND 1ST CARD, ERROR
C
40    FIRST=.TRUE.
C
      IF(NRDCRD.EQ.NCARDS)GO TO 60
C
50    IF(NRDCRD.EQ.NCARDS)GO TO 320
C
      OPNAME=BLANK8
C
      IF(MISCMD(NCARDS,MODCRD).EQ.0)GO TO 80
C
      IF(.NOT.FIRST)GO TO 320
C
C     HAVE FOUND COMMAND AS FIRST SUBSEQUENT CARD - ERROR
C
60    IF(MODWRN.EQ.1)WRITE(IPR,70)
70    FORMAT(1H0,10X,'**WARNING** NO SUBSEQUENT CARDS FOUND FOR THE ',
     1  'SACCO MOD.  PROCESSING CONTINUES')
      IF(MODWRN.EQ.1)CALL WARN
      GO TO 320
C
80    FIRST=.FALSE.
      NRDCRD=NRDCRD+1
C
C     NOW READ THE 2ND FIELD - MUST BE AN INTEGER OR REAL NUMBER
C
      NFLD=1
      ISTRT=-3
      NCHAR=2
      ICKDAT=0
C
      CALL UFIEL2(NCARDS,MODCRD,NFLD,ISTRT,LEN,ITYPE,NREP,INTGER,VALUE,
     1  NCHAR,IFIELD,LLPAR,LRPAR,LASK,LATSGN,LAMPS,LEQUAL,ISTAT)
C
      IF(ITYPE.NE.-1)GO TO 100
C
      IF(MODWRN.EQ.1)WRITE(IPR,90)(MODCRD(I,NRDCRD),I=1,20)
90    FORMAT(1H0,10X,'**WARNING** IN THE AESCCHNG MOD - NOT ENOUGH ',
     1  'FIELDS ON SUBSEQUENT CARD.  THE CARD BEING PROCESSED IS:'/
     2  11X,20A4)
      GO TO 310
C
100   IF(ITYPE.LT.2.AND.NREP.EQ.-1)GO TO 120
C
C     VALUE IS NOT AN INTEGER NOR A REAL NUMBER
C
      IF(MODWRN.EQ.1)WRITE(IPR,110)(MODCRD(I,NRDCRD),I=1,20)
110   FORMAT(1H0,10X,'**WARNING** A NONNUMERIC VALUE WAS DECODED ',
     1  'WHERE ONE WAS EXPECTED'/11X,'THE CURRENT MOD CARD IS'/11X,20A4)
      GO TO 310
C
C     SEE IF THERE IS ANOTHER FIELD - IF NOT PROCESS THE INFO
C     IN ARRAYS() - IF SO IT MUST BE A KEYWORD OR A SLASH (/)
C
120   ISTRT=-3
C
      CALL UFIEL2(NCARDS,MODCRD,NFLD,ISTRT,LEN,ITYPE,NREP,INTGER,REAL,
     1  NCHAR,IFIELD,LLPAR,LRPAR,LASK,LATSGN,LAMPS,LEQUAL,ISTAT)
C
      IF(ISTRT.EQ.-2)GO TO 170
C
C     ANOTHER FIELD - IS IT A SLASH ? - IS NOT SEE IF A KEYWORD
C
      IF(IFIELD.EQ.SLASH)GO TO 140
C
      IF(MODWRN.EQ.1)WRITE(IPR,130)(MODCRD(I,NRDCRD),I=1,20)
130   FORMAT(1H0,10X,'**WARNING** IN THE AESCCHNG MOD - AN INVALID ',
     1  'FIELD WAS FOUND ON THE FOLLOWING MOD CARD'/11X,20A4)
      GO TO 310
C
C     GET HERE IF FIELD IS A SLASH
C     NOW READ NEXT FIELD - OPERATION NAME
C
140   ISTRT=-3
C
      CALL UFIEL2(NCARDS,MODCRD,NFLD,ISTRT,LEN,ITYPE,NREP,INTGER,REAL,
     1  NCHAR,OPNAME,LLPAR,LRPAR,LASK,LATSGN,LAMPS,LEQUAL,ISTAT)
C
      IF(ISTRT.NE.-2)GO TO 160
      IF(MODWRN.EQ.0)GO TO 50
      WRITE(IODBUG,150)(MODCRD(I,NRDCRD),I=1,20)
150   FORMAT(11X,'** WARNING ** NO OPERATION NAME ENTERED ',
     1 'AFTER A SLASH ON THE FOLLOWING MOD CARD'/11X,20A4/
     2 11X,'THIS CARD IS IGNORED.')
      GO TO 310
160   CONTINUE
C
C     SEE IF ANY SETS OF CARRYOVER IN CB /FRARSW/
C
170   IF(NRARSW.GT.0)GO TO 220
C
C     NONE IN CB - JUST ADD THIS AREAL EXTENT OF SNOW COVER TO CB
C
      NRARSW=1
      CALL UMEMOV(OPNAME,RARESW(1,1),2)
      RARESW(3,1)=IDATE+0.01
      DO 180 I=4,6
180   RARESW(I,1)=-99.
      IF(VALUE.GE.0.0.AND.VALUE.LE.1.0)GO TO 200
C
C     BAD AREAL EXTENT OF SNOW COVER ENTERED
C
      IF(MODWRN.EQ.1)WRITE(IPR,190)VALUE
190   FORMAT(1H0,10X,'**WARNING** IN AESCCHNG MOD - VALUE IS OUT OF ',
     1 'VALID RANGE '/11X,'VALUE = ',G10.4)
      GO TO 310
C
200   RARESW(5,1)=VALUE
      IF(IBUG.GT.0)WRITE(IODBUG,210)VALUE
210   FORMAT(11X,'AREAL EXTENT OF SNOW COVER VALUE OF ',G10.2,' ',
     1 'STORED IN THE 1ST ROW OF ARRAY RARESW.')
      GO TO 50
C
C     CHECK IF NAME MATCHES ANY NAME IN CB OR IS BLANK -
C       AND IF DATE MATCHES ANY DATE IN CB
C
220   DO 250 I=1,NRARSW
      IF(IUSAME(OPNAME,RARESW(1,I),2).EQ.0)GO TO 250
C
C     NAME IN CB MATCHES NAME TO BE STORED
C     NOW SEE IF DATES MATCH
C
      IDTCHK=RARESW(3,I)
      IF(IDTCHK.NE.IDATE)GO TO 250
C
C     DATES MATCH TOO - ADD INFO TO THIS SPOT IN CB
C
      IF(VALUE.GE.0.0.AND.VALUE.LE.1.0)GO TO 230
C
C     BAD AREAL EXTENT OF SNOW COVER INPUT
C
      IF(MODWRN.EQ.1)WRITE(IPR,190)VALUE
      GO TO 310
C
230   RARESW(5,I)=VALUE
      IF(IBUG.GT.0)WRITE(IODBUG,240)VALUE,I
240   FORMAT(11X,'AREAL EXTENT OF SNOW COVER VALUE OF ',G10.2,' ',
     1 'REPLACED IN THE ROW ',I2,' OF ARRAY RARESW.')
      GO TO 50
C
250   CONTINUE
C
C     HAVE NOT FOUND MATCH FOR NAME AND DATE -
C     ADD NEW ENTRY TO CB
C
      IF(NRARSW.LT.10)GO TO 270
C
C     NOT ENOUGH ROOM IN CB
C
      IF(MODWRN.EQ.1)WRITE(IPR,260)(MODCRD(I,NRDCRD),I=1,20)
260   FORMAT(1H0,10X,'**WARNING** NOT ENOUGH ROOM IN COMMON BLOCK ',
     1 '/FRARSW/'/11X,'TO HOLD A NEW AREAL EXTENT OF SNOW COVER.',
     2 '  THE CURRENT MOD CARD IMAGE IS'/11X,20A4)
      GO TO 310
C
C     ENOUGH ROOM - ADD NEW ENTRY TO CB
C
270   NRARSW=NRARSW+1
      I=NRARSW
      CALL UMEMOV(OPNAME,RARESW(1,I),2)
      RARESW(3,I)=IDATE+0.01
      DO 280 J=4,6
280   RARESW(J,I)=-99.
      IF(VALUE.GE.0.0.AND.VALUE.LE.1.0)GO TO 290
C
C     BAD AREAL EXTENT OF SNOW COVER ENTERED
C
      IF(MODWRN.EQ.1)WRITE(IPR,190)VALUE
      GO TO 310
C
290   RARESW(5,I)=VALUE
      IF(IBUG.GT.0)WRITE(IODBUG,300)VALUE,I
300   FORMAT(11X,'AREAL EXTENT OF SNOW COVER VALUE OF ',G10.2,' ',
     1 'ADDED IN THE ROW ',I2,' OF ARRAY RARESW.')
      GO TO 50
C
310   IF(MODWRN.EQ.1)CALL WARN
      GO TO 50
C
320   IF(IBUG.EQ.0)GO TO 350
C
      WRITE(IODBUG,330)NRARSW
330   FORMAT(11X,'***LEAVING SUBROUTINE MAESCC*** NRARSW=',I3)
      IF(NRARSW.GT.0)WRITE(IODBUG,340)((RARESW(I,J),I=1,6),J=1,NRARSW)
340   FORMAT(11X,'ARRAY RARESW ='/(11X,2A4,1X,F11.0,3F9.2))
C
350   CALL FSTWHR(OLDOPN,IOLDOP,OLDOPN,IOLDOP)
C
      RETURN
      END
