C     MODULE MRDA2
C
C     THIS SUBROUTINE READS ONE MOD CARD IMAGE IN A2 FORMAT
C
C
      SUBROUTINE MRDA2(NCARDS,MODCRD,TSID,DTYPE,IDT,
     1  MXVALS,NVALS,VALUES,KEY,OPTYPE,OPNAME,ISTAT)
C
      LOGICAL*1 PRTNAM(8)
      CHARACTER*8   TSID,OPTYPE,OPNAME,BLANK8
C
      EQUIVALENCE (PRTNAM(1),OLDOPN(1))
C
      COMMON/IONUM/IN,IPR,IPU
      INCLUDE 'common/fpwarn'
      COMMON/FDBUG/IODBUG,ITRACE,IDBALL,NDEBUG,IDEBUG(20)
      INCLUDE 'ufreex'
      INCLUDE 'common/modctl'
C
      DIMENSION MODCRD(20,NCARDS),VALUES(MXVALS),OLDOPN(2)
C
C    ================================= RCS keyword statements ==========
      CHARACTER*68     RCSKW1,RCSKW2
      DATA             RCSKW1,RCSKW2 /                                 '
     .$Source: /fs/hseb/ob72/rfc/ofs/src/fcst_mods/RCS/mrda2.f,v $
     . $',                                                             '
     .$Id: mrda2.f,v 1.2 1998/07/02 20:46:23 page Exp $
     . $' /
C    ===================================================================
C
C
      DATA BLANK8/8H        /
C
      CALL FSTWHR(8HMRDA2   ,0,OLDOPN,IOLDOP)
C
      KEY=0
      OPTYPE=BLANK8
      OPNAME=BLANK8
C
C     READ CARD - IF COMMAND, LEAVE - IF COMMAND AND 1ST CARD, ERROR
C
      IF(NRDCRD.EQ.NCARDS)GO TO 998
C
      IF(MISCMD(NCARDS,MODCRD).NE.0)GO TO 998
      NRDCRD=NRDCRD+1
C
C     READ TSID,DTYPE,IDT
C
      CALL MRDTSH(NCARDS,MODCRD,NFLD,TSID,DTYPE,IDT,ISTAT)
C
      IF(ISTAT.EQ.0)GO TO 10
C
      IF(IWHERE.GT.1.OR.MODWRN.EQ.0)GO TO 999
      WRITE(IPR,900)(MODCRD(I,NRDCRD),I=1,20)
  900 FORMAT(1H0,10X,'**WARNING** INVALID TIME SERIES ID, ',
     1  'DATA TYPE, OR TIME INTERVAL FOUND ON THE FOLLOWING ',
     2  'MOD CARD'/11X,20A4)
      CALL WARN
      GO TO 999
C
C     READ VALUES UNTIL END OF CARD IMAGE OR NON-NUMERIC VALUE FOUND
C
   10 CALL MRDVAL(NCARDS,MODCRD,NFLD,MXVALS,NVALS,VALUES,ISTAT)
C
      IF(ISTAT.EQ.0)GO TO 999
      IF(ISTAT.EQ.2)GO TO 20
      IF(ISTAT.EQ.-1)GO TO 15
C
C     TOO MANY VALUES FOUND - DO NOT PROCESS THIS CARD
C
      IF(IWHERE.GT.1.OR.MODWRN.EQ.0)GO TO 999
      WRITE(IPR,901)
     1 (PRTNAM(I),I=2,6),MXVALS,TSID,DTYPE,IDT,(MODCRD(I,NRDCRD),I=1,20)
  901 FORMAT(1H0,10X,'**WARNING** IN ',5A1,' MOD - MORE THAN ',I3,
     1 ' VALUES ENTERED FOR TIME SERIES'/11X,A8,1X,A4,1X,I2/
     2  11X,'THE LAST CARD IMAGE READ IS'/11X,20A4)
      CALL WARN
      GO TO 999
C
C     NO VALUES FOUND
C
   15 ISTAT=1
      IF(IWHERE.GT.1.OR.MODWRN.EQ.0)GO TO 999
      WRITE(IPR,902)
     1 (PRTNAM(I),I=2,6),TSID,DTYPE,IDT,(MODCRD(I,NRDCRD),I=1,20)
  902 FORMAT(1H0,10X,'**WARNING** IN ',5A1,' MOD - NO VALUES ENTERED ',
     1  'FOR TIME SERIES'/11X,A8,1X,A4,1X,I2/
     2  11X,'THE CURRENT CARD IMAGE IS'/11X,20A4)
      CALL WARN
      GO TO 999
C
C     MORE FIELDS TO BE PROCESSED - MUST BE KEYWORD OR OPERATION TYPE
C
   20 CALL MRDA2K(NCARDS,MODCRD,NFLD,KEY,OPTYPE,OPNAME,ISTAT)
C
      GO TO 999
C
C     GET HERE IF AT END OF CARD IMAGE
C
  998 ISTAT=-1
C
  999 CALL FSTWHR(OLDOPN,IOLDOP,OLDOPN,IOLDOP)
      RETURN
      END
