C     MODULE MRDA2K
C
C     THIS SUBROUTINE READ THE OPTIONAL FIELDS ON AN A2 FORMAT
C
C     MOD CARD - THESE ARE A KEYWORD, OPER. TYPE, AND OPER. NAME
C
      SUBROUTINE MRDA2K(NCARDS,MODCRD,NFLD,KEY,OPTYPE,OPNAME,ISTAT)
C
      CHARACTER*8   OPTYPE,OPNAME,FIRST,BLANK,LAST
C
      INCLUDE 'common/ionum'
      INCLUDE 'common/fpwarn'
      INCLUDE 'common/modctl'
      INCLUDE 'ufreex'
C
      DIMENSION MODCRD(20,NCARDS),OLDOPN(2)
C
C    ================================= RCS keyword statements ==========
      CHARACTER*68     RCSKW1,RCSKW2
      DATA             RCSKW1,RCSKW2 /                                 '
     .$Source: /fs/hseb/ob72/rfc/ofs/src/fcst_mods/RCS/mrda2k.f,v $
     . $',                                                             '
     .$Id: mrda2k.f,v 1.2 1998/07/02 20:46:35 page Exp $
     . $' /
C    ===================================================================
C
C
      DATA FIRST/8HFIRST   /,LAST/8HLAST    /,BLANK/8H        /
C
      CALL FSTWHR(8HMRDA2K  ,0,OLDOPN,IOLDOP)
C
      OPTYPE=BLANK
      OPNAME=BLANK
C
C     REPROCESS CURRENT FIELD
C
      ISTRT=-1
      NCHAR=2
      ICKDAT=0
C
      CALL UFIEL2(NCARDS,MODCRD,NFLD,ISTRT,LEN,ITYPE,NREP,INTGER,REAL,
     1  NCHAR,OPTYPE,LLPAR,LRPAR,LASK,LATSGN,LAMPS,LEQUAL,ISTAT)
C
      IF(ITYPE.GT.-1)GO TO 10
C
C     END OF FILE
C
      IF(IWHERE.GT.1.OR.MODWRN.EQ.0)GO TO 55
      WRITE(IPR,913)(MODCRD(I,NRDCRD),I=1,20)
  913 FORMAT(1H0,10X,'**WARNING** IN A TIME SERIES MOD - ADDITIONAL ',
     1  'FIELD(S) EXPECTED ON THE FOLLOWING MOD CARD'/
     2  11X,20A4)
      GO TO 50
C
C     SEE IF FIELD IS 'FIRST' OR 'LAST', IF NOT MUST BE OPER. TYPE
C
   10 KEY=0
      IF(OPTYPE.EQ.FIRST)KEY=-1
      IF(OPTYPE.EQ.LAST) KEY=-2
      IF(KEY.NE.0)GO TO 15
C
C     WAS NOT KEYWORD 'FIRST' OR 'LAST' - SEE IF OPER. TYPE
C
      CALL FOPCDE(OPTYPE,NUMOP)
C
      IF(NUMOP.GT.0)KEY=NUMOP
C
C     IF KEY EQ 0 FIELD WAS NOT OPER. TYPE, NOR 'FIRST' NOR 'LAST'
C     THIS IS INVALID - WRITE MESSAGE AND LEAVE
C
   15 IF(KEY.NE.0)GO TO 20
C
      OPTYPE=BLANK
      IF(IWHERE.GT.1.OR.MODWRN.EQ.0)GO TO 55
      WRITE(IPR,912)NFLD,(MODCRD(I,NRDCRD),I=1,20)
  912 FORMAT(1H0,10X,'**WARNING** IN A TIME SERIES MOD - ',
     1  'FIELD NUMBER ',I2,' ON THE ',
     2  'FOLLOWING MOD CARD IS INVALID'/
     3  11X,'IT MUST BE ''FIRST'', ''LAST'', OR AN OPERATION TYPE'/
     4  11X,'THIS MOD CARD WILL BE IGNORED.'//
     5  11X,20A4)
      GO TO 50
C
C     IF KEYWORD WAS 'FIRST' OR 'LAST' NO MORE FIELDS ON CARD
C     IF KEYWORD WAS OPER. THERE MAY BE ANOTHER FIELD WITH OPER. NAME
C
   20 IF(KEY.GT.0)GO TO 30
      OPTYPE=BLANK
      GO TO 40
C
   30 ISTRT=-3
      NCHAR=2
      ICKDAT=0
C
      CALL UFIEL2(NCARDS,MODCRD,NFLD,ISTRT,LEN,ITYPE,NREP,IDT,REAL,
     1  NCHAR,OPNAME,LLPAR,LRPAR,LASK,LATSGN,LAMPS,LEQUAL,ISTAT)
C
   40 ISTAT=0
      GO TO 999
C
 50   CALL WARN
 55   ISTAT=1
C
  999 CALL FSTWHR(OLDOPN,IOLDOP,OLDOPN,IOLDOP)
C
      RETURN
      END
