C  MODULE MSSARR
C--------------------------------------------------------------------
C
C  ROUTINE TO PERFORM THE SSARREG MOD
C
      SUBROUTINE MSSARR(MP,P,NCARDS,MODCRD,IIDATE,NXTOPN,NXTNAM,IHZERO)
C
      LOGICAL FIRST
      CHARACTER*8 IFIELD,JFIELD,SLASH,BLANK8,MODNAM
C
C
      INCLUDE 'common/fprog'
      INCLUDE 'common/fmodft'
      INCLUDE 'common/ionum'
      INCLUDE 'common/fpwarn'
      INCLUDE 'common/fdbug'
      INCLUDE 'common/fctime'
      INCLUDE 'common/fctim2'
      INCLUDE 'ufreex'

      PARAMETER (MAXPTS=300,NROWS=907)
      COMMON/MOD151/RRC(NROWS,2)
C
      DIMENSION OLDOPN(2),MODCRD(20,NCARDS),P(MP)
      INTEGER JTEMP(MAXPTS),STEMP(NROWS)
      REAL TEMP(NROWS),TEMP1(MAXPTS,2),STORE(NROWS,2),FINAL(NROWS,2)
      CHARACTER*8 KWRDS(7),KEYWRD,OPNAME,PTLAND,NXTNAM,ONAME
      CHARACTER*4 UNIT1(7),UNIT2(7),ENGUN
      CHARACTER*20 WORD
      CHARACTER*2 UPSTRM,DOSTRM,US,DS
C
C    ================================= RCS keyword statements ==========
      CHARACTER*68     RCSKW1,RCSKW2
      DATA             RCSKW1,RCSKW2 /                                 '
     .$Source: /fs/hseb/ob72/rfc/ofs/src/fcst_mods/RCS/mssarr.f,v $
     . $',                                                             '
     .$Id: mssarr.f,v 1.7 2002/05/15 18:57:45 dws Exp $
     . $' /
C    ===================================================================
C
C
      DATA KWRDS /'FREEFLOW','SETQ    ','SETH    ','SETS    ',
     1            'SETDQ   ','SETDH   ','SETDS   '/,US/'US'/,DS/'DS'/
      DATA UNIT1 /'NONE','CMS ','M   ','CMSD','CMS ','M   ','CMSD'/
      DATA UNIT2 /'NONE','V   ','L   ','V   ','V   ','L   ','V   '/
      DATA MODNAM/'SSARREG '/,NUMKEY/7/,LWORD/20/,MXTEMP/MAXPTS/
      DATA SLASH/'/       '/,BLANK8/'        '/

C
      CALL FSTWHR(8HMSSARR  ,0,OLDOPN,IOLDOP)
C
C     SET DEBUG SWITCH
C
      IBUG=IFBUG(4HMODS)+IFBUG(4HSSAR)
c
      iold=ickdat
C
      IF (IBUG.GT.0) WRITE(IODBUG,10) IABS(IIDATE),NXTOPN,NXTNAM
10    FORMAT(1H0,10X,'*** SUBROUTINE MSSARR ENTERED ***  IIDATE,',
     1  'NXTOPN,NXTNAM = ',I11,2X,I2,2X,A8)
C
C  CHECK IF NEXT OPERATION IS A SSARRESV OPERATION
C
      IF (NXTOPN.NE.51) GOTO 5000
C
      FIRST=.TRUE.
      IDATE=IABS(IIDATE)
C
C     NOW SEE IF EFFECTIVE DATE LESS THAN <= LSTCMPDY VALUE
C
      ICOMP=((LDACPD-1)*24)+LHRCPD
C
      IF (IDATE.LE.ICOMP) GOTO 20
C
      IF (MODWRN.EQ.1) THEN
         WRITE(IPR,15) (MODCRD(I,NRDCRD),I=1,20)
         GOTO 5000
         ENDIF
15    FORMAT(1H0,10X,'**WARNING** THE EFFECTIVE DATE IS GREATER ',
     1 'THAN THE DATE AND HOUR OF OBSERVED DATA.  THESE CHANGES WILL ',
     2 'BE IGNORED.',/,11X,'THE CURRENT CARD IMAGE IS : ',20A4)
C
C     SEE IF DATE IS WITHIN RUN PERIOD
C
20    ISTHR=(IDA-1)*24+IHZERO
      IENHR=(LDA-1)*24+LHR
C
cew skip this check in ESP
      if(mainum.ne.2)then
         IF(IDATE.LT.ISTHR.OR.IDATE.GT.IENHR) GOTO 30
      endif

      GOTO 40
C
C     PERIOD FOR CHANGES NOT WITHIN RUN PERIOD
C
30    IF(MODWRN.EQ.0) GOTO 5000
      CALL MDYH2(IDA,IHZERO,IM1,ID1,IY1,IH1,DUM1,DUM2,MODTZC)
      CALL MDYH2(LDA,LHR,IM2,ID2,IY2,IH2,DUM1,DUM2,MODTZC)
      IXDA=IDATE/24+1
      IXHR=IDATE-(IXDA-1)*24
      IF(IXHR.EQ.0)IXDA=IXDA-1
      IF(IXHR.EQ.0)IXHR=24
      CALL MDYH2(IXDA,IXHR,IM3,ID3,IY3,IH3,DUM1,DUM2,MODTZC)
C
      WRITE(IPR,85)IM3,ID3,IY3,IH3,MODTZC,
     1IM1,ID1,IY1,IH1,MODTZC,IM2,ID2,IY2,IH2,MODTZC
85    FORMAT(1H0,10X,'**WARNING** THE DATES FOR CHANGES IN THE ',
     1 'SSARREG MOD (',I2,1H/,I2,1H/,I4,1H-,I2,1X,A4,/,11X,
     2 'ARE NOT WITHIN THE CURRENT RUN PERIOD (',I2,1H/,I2,
     3 1H/,I4,1H-,I2,1X,A4,4H TO ,I2,1H/,I2,1H/,I4,1H-,I2,1X,A4,1H)/
     4 11X,'THESE CHANGES WILL BE IGNORED.')
      CALL WARN
      GOTO 5000
C
40    CONTINUE
C
C     READ MOD CARDS FOR THIS SEGMENT - STORE VALUES IN ARRAYS() -
C     WILL TRANSFER TO CB /MOD151/ AFTER ALL INFO IS READ AND CHECK
C     FOR ERRORS
C
C     READ CARD - IF COMMAND, LEAVE - IF COMMAND AND 1ST CARD, ERROR
C
      FIRST=.TRUE.
C
      IF (NRDCRD.EQ.NCARDS) GOTO 80
C
70    IF (NRDCRD.EQ.NCARDS) GOTO 5000
C
      IF (MISCMD(NCARDS,MODCRD).EQ.0) GOTO 100
C
      IF (.NOT.FIRST) GOTO 5000
C
C     HAVE FOUND COMMAND AS FIRST SUBSEQUENT CARD - ERROR
C
80    IF (MODWRN.EQ.1) THEN
         WRITE (IPR,90)
         CALL WARN
         GOTO 5000
         ENDIF
90    FORMAT(1H0,10X,'**WARNING** NO SUBSEQUENT CARDS FOUND FOR THE ',
     1  'SSARREG MOD.  PROCESSING CONTINUES')
C
100   FIRST=.FALSE.
C
      NRDCRD=NRDCRD+1
C
C  RE(SET) VARIABLE LTEMP TO 7 AND ZEROING OUT ARRAY STORE
C
      CALL UMEMOV(0,JTEMP(1),MAXPTS)
      CALL UMEMOV(0.0,TEMP(1),NROWS)
      CALL UMEMOV(0,STEMP(1),NROWS)
      CALL UMEMOV(0.0,STORE(1,1),2*NROWS)
      LTEMP=7
C
C     NOW READ 2ND FIELD - CHECKING FOR AN OPTIONAL 'US' ENTRY
C
      NFLD=1
      ISTRT=-3
      NCHAR=2
      KEYWRD=' '
      JDATE=0
      ickdat=0
C
      CALL UFIEL2(NCARDS,MODCRD,NFLD,ISTRT,LEN,ITYPE,NREP,IVALUE,VALUE,
     1  NCHAR,KEYWRD,LLPAR,LRPAR,LASK,LATSGN,LAMPS,LEQUAL,ISTAT)
C
      IF (ISTRT.NE.-2) GOTO 140
C
C     ERROR - DATA EXPECTED - PROCESS NEXT CARD
C
      IF (MODWRN.EQ.1) THEN
         WRITE (IPR,130) (MODCRD(I,NRDCRD),I=1,20)
         CALL WARN
         GOTO 70
         ENDIF
130   FORMAT(1H0,10X,'**WARNING** IN THE SSARREG MOD - NOT ENOUGH ',
     1  'FIELDS ON SUBSEQUENT CARD.  THE CARD BEING PROCESSED IS:'/
     2  11X,20A4)
C
135   FORMAT(1H0,10X,A,' **WARNING** IN THE SSARREG MOD - INVALID ',
     1  'FIELD ENTERED.  THE CARD BEING PROCESSED IS:'/11X,20A4)
C
C     OPTIONAL 'US' ENTRY FOUND
C
140   IUS=0
      IDS=0
      UPSTRM=KEYWRD
      IF (UPSTRM.EQ.US) IUS=1
      GOTO 143
C
C  ----------------------------------------
C  THIS SECTION IS REQUIRED ONLY FOR SEGMENT THAT HAS AN UPSTREAM
C  RESERVOIR.  THEREFORE, A DOWNSTREAM IS REQUIRED.
C
141   CONTINUE
      IUS=0
      ISTRT=-1
      JDATE=0
      KEYWRD=' '
      ickdat=0
C
      CALL UFIEL2(NCARDS,MODCRD,NFLD,ISTRT,LEN,ITYPE,NREP,IVALUE,VALUE,
     1  NCHAR,KEYWRD,LLPAR,LRPAR,LASK,LATSGN,LAMPS,LEQUAL,ISTAT)
C
      IF (ISTAT.NE.0) GOTO 144

      IF (KEYWRD.EQ.'DS') THEN
         IDS=1
         LTEMP=7
         GOTO 143
         ENDIF

144   IF(MODWRN.EQ.1) THEN
        WRITE(IPR,142) (MODCRD(I,NRDCRD),I=1,20)
        CALL WARN
        GOTO 70
        ENDIF
142   FORMAT(1H0,10X,'**WARNING** IN THE SSARREG MOD - A KEYWORD DS ',
     1  'IS REQUIRED FOR A DOWNSTREAM RESERVOIR.  THE CARD IMAGE IS: ',
     2  /,20A4)
C
143   ISTRT=-3
      IF (IDS.EQ.1) GOTO 145
      IF (KEYWRD.NE.US.AND.KEYWRD.NE.DS) ISTRT=-1
C
C  BEGIN DECODING KEYWORD, DELTA-T (IF ANY), DATE AND DATA VALUES
C
C  DECODE KEYWORD
C
145   IKEYWD=0
      IDELTA=0
      ITIME=0
      IDATA=0
      KEYWRD=' '
      ickdat=0
C
      CALL UFIEL2(NCARDS,MODCRD,NFLD,ISTRT,LEN,ITYPE,NREP,IVALUE,VALUE,
     1  NCHAR,KEYWRD,LLPAR,LRPAR,LASK,LATSGN,LAMPS,LEQUAL,ISTAT)
C
      IF (ISTAT.NE.0) GOTO 155
C
      IKEY=-1
      DO 150 I=1,NUMKEY
         IF (KEYWRD.EQ.KWRDS(I)) THEN
            IKEYWD=1
            IKEY=I-1
            GOTO 170
            ENDIF
150   CONTINUE
C
155   IF(MODWRN.EQ.1) THEN
         WRITE(IPR,160) (MODCRD(I,NRDCRD),I=1,20)
         CALL WARN
         GOTO 70
         ENDIF
C
160   FORMAT(1H0,10X,'**WARNING** IN THE SSARREG MOD - AN INVALID ',
     1  'KEYWORD FOUND ON THE FOLLOWING MOD CARD:'/11X,20A4)
C
170   CONTINUE
C
C  DECODE DELTA-T (IF EXISTS)
C
      ISTRT=-3
      WORD=' '
      ickdat=0
C
      CALL UFIEL2(NCARDS,MODCRD,NFLD,ISTRT,LEN,ITYPE,NREP,INTGER,REAL,
     1  LWORD,WORD,LLPAR,LRPAR,LASK,LATSGN,LAMPS,LEQUAL,ISTAT)
C
      IF (ISTRT.NE.-2) GOTO 180
C
      IF (MODWRN.EQ.1) THEN
         WRITE (IPR,130) (MODCRD(I,NRDCRD),I=1,20)
         CALL WARN
         GOTO 70
         ENDIF
C
C  CHECK IF STRING IS INTEGER
180   IF (ITYPE.NE.0) GO TO 185
C
      IF (INTGER.GT.24) GO TO 185
C
      IF (INTGER.GT.0.AND.INTGER.LE.24) THEN
         IF (MOD(IDELTA,24).EQ.0.OR.INTGER.EQ.1.OR.INTGER.EQ.3) THEN
            IDELTA=INTGER
            GOTO 185
            ENDIF
         ENDIF
C
      IF (MODWRN.EQ.1) THEN
         WRITE (IPR,184) (MODCRD(I,NRDCRD),I=1,20)
         CALL WARN
         GOTO 70
         ENDIF
C
184   FORMAT(1H0,10X,A,' **WARNING** IN THE SSARREG MOD - INVALID ',
     1  'TIME STEP ENTERED.  THE CARD BEING PROCESSED IS:'/11X,20A4)
C
185   ISTRT=-3
C
      IF (ITYPE.NE.0.OR.INTGER.GT.24) ISTRT=-1
C
190   CONTINUE
C
C  DECODE ASSOCIATED DATE(S)
C
      WORD=' '
      ickdat=0
      CALL UFIEL2(NCARDS,MODCRD,NFLD,ISTRT,LEN,ITYPE,NREP,INTGER,REAL,
     1  LWORD,WORD,LLPAR,LRPAR,LASK,LATSGN,LAMPS,LEQUAL,ISTAT)
C
      IF (ISTRT.NE.-2) GOTO 200
C
      IF (MODWRN.EQ.1) THEN
         WRITE (IPR,130) (MODCRD(I,NRDCRD),I=1,20)
         CALL WARN
         GOTO 70
         ENDIF
C
200   CONTINUE
C
      IF (ITYPE.EQ.0.OR.ITYPE.EQ.2) GOTO 210
C
      IF (MODWRN.EQ.1) THEN
         WRITE (IPR,135) '1',(MODCRD(I,NRDCRD),I=1,20)
         CALL WARN
         GOTO 70
         ENDIF
C
210   CALL UDATEA (LWORD,WORD,1,0,1,0,JDA,IHR,ITIME,ISTAT)
      IF (ISTAT.EQ.0) THEN
         ITIME=IABS(ITIME)
         GOTO 220
         ENDIF
C
      IF (MODWRN.EQ.1) THEN
         WRITE (IPR,135) '2',(MODCRD(I,NRDCRD),I=1,20)
         CALL WARN
         GOTO 70
         ENDIF
C
C  BEGIN TO DECODE VALUE(S) ASSOCIATE WITH DATES
C
220   CONTINUE
C
      DO 222 L=1,MAXPTS
         TEMP1(L,1)=0.
         TEMP1(L,2)=0.
222   CONTINUE
C
      NTEMP1=0
      IPASS=0
C
225   CONTINUE
C
      ISTRT=-3
      WORD=' '
      INEW=0
      ISTART=0
      IALERT=0
      IOVER=0
      ickdat=0
C
      CALL UFIEL2(NCARDS,MODCRD,NFLD,ISTRT,LEN,ITYPE,NREP,INTGER,REAL,
     1  LWORD,WORD,LLPAR,LRPAR,LASK,LATSGN,LAMPS,LEQUAL,ISTAT)
C
      IF (ISTRT.EQ.-2.AND.IKEY.EQ.0) GOTO 240
C
      IF (ISTRT.EQ.-2.AND.IPASS.EQ.0) GOTO 227
C
      IF (ITYPE.EQ.1.AND.IKEY.EQ.0) GOTO 225
C
      IF (ITYPE.EQ.1) GOTO 230
C
      IF (ITYPE.EQ.2.AND.WORD.EQ.'DS') GOTO 240
C
      IF (ITYPE.EQ.2) THEN
         DO 223 L=1,LWORD
            IF (WORD(L:L).EQ.'Z') THEN
               ISTRT=-1
               INEW=1
               GOTO 240
               ENDIF
223      CONTINUE
         ENDIF
C
      IF (ITYPE.EQ.2) THEN
         IF (WORD.EQ.'/') IALERT=1
         ISTRT=-1
         ISTART=0
         DO 226 J=1,NUMKEY
            IF (WORD.EQ.KWRDS(J)) THEN
               ISTART=1
               ENDIF
226      CONTINUE
         GOTO 230
         ENDIF
C
      IF (ITYPE.EQ.0.AND.INTGER.GT.24) THEN
         ISTRT=-1
         INEW=1
         GOTO 240
         ENDIF
C
      IF (IPASS.EQ.1.AND.ISTRT.EQ.-2) GOTO 240
C
227   IF (MODWRN.EQ.1) THEN
         WRITE (IPR,135) '3',(MODCRD(I,NRDCRD),I=1,20)
         CALL WARN
         GOTO 70
         ENDIF
C
230   CONTINUE
C
      IF (ITYPE.EQ.2) GOTO 240
C
      IPASS=1
      IDATA=1
      TEMP1(NTEMP1+1,1)=NREP
      AM2IN=1.0
      IF (IUMGEN.EQ.0.OR.IKEY.EQ.0) GOTO 235
      CALL FCONVT(UNIT1(IKEY+1),UNIT2(IKEY+1),ENGUN,AM2IN,BM2IN,IER)
235   TEMP1(NTEMP1+1,2)=REAL*AM2IN
C     JTEMP(NTEMP1+1)=NREP
      STEMP(NTEMP1+1)=NREP
      NTEMP1=NTEMP1+1
C
      GOTO 225
C
240   CONTINUE
C
      IF (IKEY.EQ.0) THEN
         NTEMP1=1
C        JTEMP(NTEMP1)=1
         STEMP(NTEMP1)=1
         TEMP1(NTEMP1,1)=0.
         TEMP1(NTEMP1,2)=0.
         ENDIF
C
      NEW=0
      DO 245 I=1,NTEMP1
C        IF (JTEMP(I).LE.1) NEW=NEW+1
         IF (STEMP(I).LE.1) NEW=NEW+1
C        IF (JTEMP(I).GE.2) NEW=NEW+2
         IF (STEMP(I).GE.2) NEW=NEW+2
245   CONTINUE
C
      IF ((LTEMP/3)+NEW.LE.MXTEMP+2) GOTO 270
C
      IF (MODWRN.EQ.1) THEN
         WRITE (IPR,260) (MODCRD(I,NRDCRD),I=1,20)
         CALL WARN
         GOTO 5000
         ENDIF
C
260   FORMAT(1H0,10X,'**WARNING** IN THE SSARREG MOD - NOT ENOUGH ',
     1  'SPACE IN COMMON BLOCK /MOD151/.  THE CURRENT CARD IMAGE IS: ',
     2  /,11X,20A4)
C
270   CONTINUE
C
      IF (ITIME.LT.IDATE.AND.ITIME.GE.JDATE) THEN
         IF (JDATE.NE.0) IOVER=1
         JDATE=ITIME
         TEMP1(1,1)=1.0
         TEMP1(1,2)=TEMP1(NTEMP1,2)
C        JTEMP(1)=1
         STEMP(1)=1
         NTEMP1=1
         ENDIF
C
      IF (IOVER.EQ.1) LTEMP=LTEMP-3
C
      NWTIME=0
      DO 280 I=1,NTEMP1
         IPOS=0
C        IF (JTEMP(I).LT.2.OR.IDELTA.LE.0) GOTO 285
         IF (STEMP(I).LT.2.OR.IDELTA.LE.0) GOTO 285
            LTEMP=LTEMP+3
            TEMP(LTEMP-2)=ITIME+.01
            IF (NWTIME.GT.0) TEMP(LTEMP-2)=NWTIME+IDELTA
            TEMP(LTEMP-1)=TEMP1(I,2)
            TEMP(LTEMP-0)=IKEY
C
            IPOS=I
C           NWTIME=ITIME+((JTEMP(1)-1)*IDELTA)
            NWTIME=ITIME+((STEMP(1)-1)*IDELTA)
            IF (NTEMP1.LE.1) GOTO 282
C
            DO 281 INC=2,I
C              NWTIME=NWTIME+(JTEMP(INC)*IDELTA)
               NWTIME=NWTIME+(STEMP(INC)*IDELTA)
281         CONTINUE
C
282         LTEMP=LTEMP+3
            TEMP(LTEMP-2)=NWTIME+.01
            TEMP(LTEMP-1)=TEMP1(I,2)
            TEMP(LTEMP-0)=IKEY
            GOTO 280
C
285      LTEMP=LTEMP+3
         TEMP(LTEMP-2)=ITIME+.01
         TEMP(LTEMP-1)=TEMP1(I,2)
         TEMP(LTEMP-0)=IKEY+.01
         TEMP(1)=LTEMP+.01
280   CONTINUE
C
      IF (WORD.EQ.'DS'.AND.IUS.EQ.1) THEN
         CALL UMEMOV(TEMP,STORE(1,1),NROWS)
         GOTO 141
         ENDIF
C
      IF (ITYPE.EQ.2.AND.ISTART.EQ.1) GOTO 145
C
      IF (IALERT.EQ.1) GOTO 500
C
      IF (ISTRT.EQ.-2) GOTO 500
C
      IF (INEW.EQ.1) GOTO 190
C
      GOTO 210
C
C  LOOKING FOR A SLASH AND OPERATION NAME
C
500   CONTINUE
C
      IF (IDS.EQ.0) CALL UMEMOV(TEMP,STORE(1,1),NROWS)
      IF (IDS.EQ.1) CALL UMEMOV(TEMP,STORE(1,2),NROWS)
C
      ISTRT=-3
      WORD=' '
      IF (IALERT.EQ.1) ISTRT=-1
      ickdat=0
C
      CALL UFIEL2(NCARDS,MODCRD,NFLD,ISTRT,LEN,ITYPE,NREP,INTGER,REAL,
     1  LWORD,WORD,LLPAR,LRPAR,LASK,LATSGN,LAMPS,LEQUAL,ISTAT)
C
      IF (ISTRT.EQ.-2) GOTO 320
C
      IF (WORD.EQ.'/') GOTO 300
C
      IF (MODWRN.EQ.1) THEN
         WRITE (IPR,290) (MODCRD(I,NRDCRD),I=1,20)
         CALL WARN
         GOTO 5000
         ENDIF
290   FORMAT(1H0,10X,'**WARNING** IN THE SSARREG MOD - A SLASH ',
     1  'IS REQUIRED BEFORE AN OPERATION NAME IS ALLOWED. THE CARD ',
     2  'IMAGE IS: ',/,11X,20A4)
C
300   CONTINUE
C
      ISTRT=-3
      WORD=' '
      ickdat=0
C
      CALL UFIEL2(NCARDS,MODCRD,NFLD,ISTRT,LEN,ITYPE,NREP,INTGER,REAL,
     1  LWORD,WORD,LLPAR,LRPAR,LASK,LATSGN,LAMPS,LEQUAL,ISTAT)
C
      IF (ISTRT.NE.-2) GOTO 320
C
      IF (MODWRN.EQ.1) THEN
         WRITE (IPR,310) (MODCRD(I,NRDCRD),I=1,20)
         CALL WARN
         GOTO 5000
         ENDIF
310   FORMAT(1H0,10X,'**WARNING** IN THE SSARREG MOD - A OPERATION ',
     1  'NAME IS REQUIRED. THESE CHANGES WILL BE IGNORED.  THE CARD ',
     2  'IMAGE IS: ',/,11X,20A4)
C
320   CONTINUE
C
      OPNAME=WORD
      IF (IDS.EQ.0) THEN
         STORE(3,1)=IDATE+.01
         CALL UMEMOV(WORD,STORE(4,1),2)
         ENDIF
C
      IF (IDS.EQ.1) THEN
         STORE(3,1)=IDATE+.01
         STORE(4,1)=IDATE+.01
         STORE(3,2)=IDATE+.01
         STORE(4,2)=IDATE+.01
         CALL UMEMOV(WORD,STORE(4,1),2)
         CALL UMEMOV(WORD,STORE(4,2),2)
         ENDIF
C
      IY=RRC(3,1)
      IREP=0
      IF (OPNAME.EQ.' ') GOTO 325
      IF (NXTNAM.NE.OPNAME) GO TO 5000
 325  IF (IY.LE.0) GOTO 400
C
      IF (IDATE.GT.IY.AND.IDATE.LE.ICOMP) THEN
         IREP=1
         GOTO 400
         ENDIF
C
      IF (IDATE.EQ.IY.AND.IDATE.LE.ICOMP) GOTO 340
C
      IF (MODWRN.EQ.1) THEN
         WRITE (IPR,330) (MODCRD(I,NRDCRD),I=1,20)
         CALL WARN
         GOTO 5000
         ENDIF
330   FORMAT(1H0,10X,'**WARNING** IN THE SSARREG MOD - THE EFFECTIVE ',
     1  'DATE IN PROCESS IS BEFORE THE ONE STORE IN MOD151.',
     2  ' THESE CHANGES WILL BE IGNORED.',/,11X,'THE CARD IMAGE IS: ',
     3  11X,20A4)
C
340   CONTINUE
C
cc      CALL UMEMOV(BLANK8,OPNAME,2)
cc      CALL UMEMOV(RRC(4,1),OPNAME,2)
C
cc      IF (OPNAME.EQ.' '.AND.WORD.NE.' ') THEN
      IF (OPNAME.EQ.' ') THEN
         IF (RRC(1,1).GT.1.0) IREP=1
         GOTO 400
         ENDIF
C
      IF (NXTNAM.EQ.OPNAME) THEN
         IREP=1
         GOTO 400
         ENDIF
C
cc      IF (WORD.EQ.OPNAME) THEN
cc         IREP=1
cc         GOTO 400
cc         ENDIF
C
      IF (MODWRN.EQ.1) THEN
         WRITE (IPR,350) (MODCRD(I,NRDCRD),I=1,20)
         CALL WARN
         GOTO 5000
         ENDIF
350   FORMAT(1H0,10X,'**WARNING** IN THE SSARREG MOD - OPERATION ',
     1  'NAME DOES NOT MATCH THE ONE STORE IN COMMON BLOCK 151. THESE',
     2  ' CHANGES WILL BE IGNORED.',/,11X,'THE CARD IMAGE IS: ',
     3  11X,20A4)
C
400   CONTINUE
C
      IF (IDS.EQ.0) GOTO 430
C
      LOCP=1
      PTLAND=WORD
      CALL FSERCH(51,PTLAND,LOCP,P,MP)
      IF (LOCP.GT.0) GOTO 420
C
      IF (MODWRN.EQ.1) THEN
         WRITE (IPR,415) (MODCRD(I,NRDCRD),I=1,20)
         CALL WARN
         GOTO 5000
         ENDIF
415   FORMAT(1H0,10X,'**WARNING** IN THE SSARREG MOD - NO SSARRESV ',
     1  'OPERATIONS FOUND.  THIS CHANGE WILL BE IGNORED.',/,11X,'THE ',
     2  'CARD IMAGE IS : ',20A4)
C
420   CONTINUE
C
      IPO=P(LOCP+12)
      IF (IPO.GT.0) GOTO 430
C
      IF (MODWRN.EQ.1) THEN
         WRITE (IPR,425) (MODCRD(I,NRDCRD),I=1,20)
         CALL WARN
         GOTO 5000
         ENDIF
425   FORMAT(1H0,10X,'**WARNING** IN THE SSARREG MOD - POSITION ',
     1  'PO(13) IS NOT GREATER THAN ZERO.  THIS CHANGE WILL BE ',
     2  'IGNORED.',/,11X,'THE CURRENT CARD IMAGE IS : ',20A4)
C
430   IMOVE=1
      IF (IDS.EQ.1) IMOVE=2
      DO 440 N=1,IMOVE
         CALL UMEMOV(STORE(1,N),RRC(1,N),1)
         CALL UMEMOV(STORE(3,N),RRC(3,N),3)
         CALL UMEMOV(STORE(8,N),RRC(8,N),NROWS-7)
440   CONTINUE

C
      CALL UMEMOV(0.0,FINAL(1,1),2*NROWS)
C
      DO 445 L=1,IMOVE
      LDATE1=RRC(8,L)
      LDATE2=RRC(11,L)
      IF (LDATE1.LE.IDATE.AND.LDATE2.LT.1) THEN
         RRC(1,L)=7.01
         CALL UMEMOV(RRC(1,L),FINAL(1,L),7)
         CALL UMEMOV(FINAL(1,L),RRC(1,L),NROWS)
         ENDIF
445   CONTINUE
C
      IF (IBUG.EQ.0) GOTO 70
C
      IF (IREP.EQ.0) WRITE(IODBUG,450) IDATE,WORD,'ADDED TO'
      IF (IREP.EQ.1) WRITE(IODBUG,450) IDATE,WORD,'REPLACED IN'
450   FORMAT('***** NOTE : A SSARREG MOD WITH EFFECTIVE DATE ',
     1  I9,' AND OPNAME ',A8,' IS ',A,' COMMON BLOCK MOD151.')
C

      GOTO 70
C
5000  IF(IBUG.EQ.0) GOTO 5040
C
      DO 5005 I=1,IMOVE
         IZ=RRC(1,I)
         ONAME=' '
         CALL UMEMOV(RRC(4,I),ONAME,2)
         WRITE(IODBUG,5010) (RRC(J,I),J=1,3),
     &   ONAME(1:4),ONAME(5:8),(RRC(K,I),K=6,7)
         IF (IZ.LE.7) GOTO 5005
         WRITE(IODBUG,5015) (RRC(M,I),M=8,IZ)
5010     FORMAT(' RRC = ',F5.1,1X,F5.1,1X,F10.1,1X,A4,1X,A4,1X,F10.1,1X,
     *                    F10.1)
5015     FORMAT('       ',10(F10.1,1X))
5005  CONTINUE
C
      WRITE(IODBUG,5030)
5030  FORMAT(11X,'- LEAVING SUBROUTINE MSSARR -')
C
5040  CALL FSTWHR(OLDOPN,IOLDOP,OLDOPN,IOLDOP)
C
      ickdat=iold

      RETURN
      END
