C MEMBER AREAD
C-----------------------------------------------------------------------
C
C                             LAST UPDATE: 12/01/93.09:30:15 BY $WC20SV
C
C @PROCESS LVL(77)
C***********************************************************************
C
      SUBROUTINE AREAD (FNAME,DUNITS,FUNITS,BMO,BYR,EMO,EYR,IPUNCH,
     *   DLIST,ISTRT,NFLD,ISTAT,IERR,LDEBUG)
      INTEGER BMO,BYR,EMO,EYR
      REAL LABEL,INCHES
      DIMENSION FNAME(3)
C
C    ================================= RCS keyword statements ==========
      CHARACTER*68     RCSKW1,RCSKW2
      DATA             RCSKW1,RCSKW2 /                                 '
     .$Source: /fs/hseb/ob72/rfc/calb/src/pproc_shared/RCS/aread.f,v $
     . $',                                                             '
     .$Id: aread.f,v 1.1 1997/01/23 15:27:15 dws Exp $
     . $' /
C    ===================================================================
C
      DATA CPUNCH/4HPNCH/
      DATA ALABEL/4H@A  /,BLABEL/4H@B  /,BLNK/4H    /
      DATA INCHES/4HIN  /
      NCHAR=1
      LABEL=ALABEL
10    CALL UFIELD(NFLD,ISTRT,LENGTH,ITYPEU,NREP,INTEGR,UREAL,
     * NCHAR,UCHAR,LLPAR,LRPAR,LASK,LATSGN,LAMPS,LEQUAL,ISTAT)
      CALL AFTERU(LATSGN,ITYPEU,UCHAR,LABEL,3,ISTAT,LENGTH,IERR)
      IF (ISTAT.EQ.7) GO TO 10
      CALL UFIELD(NFLD,ISTRT,LENGTH,ITYPEU,NREP,BMO   ,UREAL,
     * NCHAR,UCHAR,LLPAR,LRPAR,LASK,LATSGN,LAMPS,LEQUAL,ISTAT)
      CALL AFTERU(LATSGN,ITYPEU,UCHAR,LABEL,0,ISTAT,LENGTH,IERR)
      IF (ISTAT.EQ.6) ISTRT=-1
      IF (ISTAT.EQ.6) GO TO 20
      CALL UFIELD(NFLD,ISTRT,LENGTH,ITYPEU,NREP,BYR   ,UREAL,
     * NCHAR,UCHAR,LLPAR,LRPAR,LASK,LATSGN,LAMPS,LEQUAL,ISTAT)
      CALL AFTERU(LATSGN,ITYPEU,UCHAR,LABEL,0,ISTAT,LENGTH,IERR)
      IF (ISTAT.EQ.6) ISTRT=-1
      IF (ISTAT.EQ.6) GO TO 20
      CALL UFIELD(NFLD,ISTRT,LENGTH,ITYPEU,NREP,EMO   ,UREAL,
     * NCHAR,UCHAR,LLPAR,LRPAR,LASK,LATSGN,LAMPS,LEQUAL,ISTAT)
      CALL AFTERU(LATSGN,ITYPEU,UCHAR,LABEL,0,ISTAT,LENGTH,IERR)
      IF (ISTAT.EQ.6) ISTRT=-1
      IF (ISTAT.EQ.6) GO TO 20
      CALL UFIELD(NFLD,ISTRT,LENGTH,ITYPEU,NREP,EYR   ,UREAL,
     * NCHAR,UCHAR,LLPAR,LRPAR,LASK,LATSGN,LAMPS,LEQUAL,ISTAT)
      CALL AFTERU(LATSGN,ITYPEU,UCHAR,LABEL,0,ISTAT,LENGTH,IERR)
      IF (ISTAT.EQ.6) ISTRT=-1
      IF (ISTAT.EQ.6) GO TO 20
      NCHAR=1
      CALL UFIELD(NFLD,ISTRT,LENGTH,ITYPEU,NREP,INTEGR,UREAL,
     * NCHAR,DUNITS,LLPAR,LRPAR,LASK,LATSGN,LAMPS,LEQUAL,ISTAT)
      CALL AFTERU(LATSGN,ITYPEU,DUNITS,LABEL,2,ISTAT,LENGTH,IERR)
      IF (ISTAT.EQ.6) ISTRT=-1
      IF (ISTAT.EQ.6) GO TO 20
      CALL UFIELD(NFLD,ISTRT,LENGTH,ITYPEU,NREP,INTEGR,UREAL,
     * NCHAR,FUNITS,LLPAR,LRPAR,LASK,LATSGN,LAMPS,LEQUAL,ISTAT)
      CALL AFTERU(LATSGN,ITYPEU,FUNITS,LABEL,2,ISTAT,LENGTH,IERR)
      IF (ISTAT.EQ.6) ISTRT=-1
      IF (ISTAT.EQ.6) GO TO 20
      CALL UFIELD(NFLD,ISTRT,LENGTH,ITYPEU,NREP,INTEGR,UREAL,
     * NCHAR,UCHAR,LLPAR,LRPAR,LASK,LATSGN,LAMPS,LEQUAL,ISTAT)
      CALL AFTERU(LATSGN,ITYPEU,UCHAR,LABEL,2,ISTAT,LENGTH,IERR)
      IF (UCHAR.EQ.CPUNCH)IPUNCH=1
      IF (ISTAT.EQ.6) ISTRT=-1
      IF (ISTAT.EQ.6) GO TO 20
      CALL UFIELD(NFLD,ISTRT,LENGTH,ITYPEU,NREP,INTEGR,UREAL,
     * NCHAR,DLIST,LLPAR,LRPAR,LASK,LATSGN,LAMPS,LEQUAL,ISTAT)
      CALL AFTERU(LATSGN,ITYPEU,DLIST,LABEL,2,ISTAT,LENGTH,IERR)
      IF (ISTAT.EQ.6) ISTRT=-1
      IF (ISTAT.EQ.6) GO TO 20
      NCHAR=3
      CALL UFIELD(NFLD,ISTRT,LENGTH,ITYPEU,NREP,INTEGR,UREAL,
     * NCHAR,FNAME,LLPAR,LRPAR,LASK,LATSGN,LAMPS,LEQUAL,ISTAT)
      UCHAR=FNAME(1)
      CALL AFTERU(LATSGN,ITYPEU,UCHAR,LABEL,2,ISTAT,LENGTH,IERR)
      IF (ISTAT.EQ.6) ISTRT=-1
20    CONTINUE
C
      IF (DUNITS.EQ.BLABEL)   DUNITS=INCHES
      IF (FUNITS.EQ.BLABEL)   FUNITS=INCHES
      IF (DLIST.EQ.BLABEL)    FNAME(1)=BLNK
      IF (FNAME(1).EQ.BLABEL) FNAME(1)=BLNK
      RETURN
      END
