C MODULE FILSGO
C-----------------------------------------------------------------------
C
      SUBROUTINE FILSGO
C
C  THIS ROUTINE FILLS THE VARIABLES IN FORECAST COMPONENT COMMON
C  BLOCKS WHICH CAN CHANGE SEGMENT BY SEGMENT. THE VALUES ARE SPECIFIED
C  BY THE NONUNIVERSAL TECHNIQUES.
C
      CHARACTER*8 RTNNAM,OLDOPN,TECHNAME,OPRNAM,STRNG
C
      PARAMETER (LIARGS=84)
      DIMENSION IARGS(LIARGS)
C
      INCLUDE 'common/ionum'
      INCLUDE 'common/fdbug'
      INCLUDE 'common/sysbug'
      INCLUDE 'common/fnopr'
      INCLUDE 'common/fpltab'
      INCLUDE 'common/fsnw'
      INCLUDE 'common/fpwarn'
      INCLUDE 'common/fdisps'
      INCLUDE 'common/fcary'
      INCLUDE 'common/fcassm'
      COMMON /FSNWUP/ IUPWE,IUPSC
      COMMON /FSACPR/ IPRSAC,NOFRZE
      COMMON/OUTCTL/IOUTYP
C
C    ================================= RCS keyword statements ==========
      CHARACTER*68     RCSKW1,RCSKW2
      DATA             RCSKW1,RCSKW2 /                                 '
     .$Source: /fs/hseb/ob72/rfc/ofs/src/shared_esp/RCS/filsgo.f,v $
     . $',                                                             '
     .$Id: filsgo.f,v 1.3 2004/06/21 14:09:26 hsu Exp $
     . $' /
C    ===================================================================
C
      DATA IBLNK/4h    /
C
C
      RTNNAM='FILSGO'
C
      IF (ITRACE.GT.0) WRITE (IODBUG,*) 'ENTER ',RTNNAM
C
      IOPNUM=0
      CALL FSTWHR (RTNNAM,IOPNUM,OLDOPN,IOLDOP)
C
C  SET TRACE LEVEL FROM ARGUMENT OF TECH FCDEBUG
      TECHNAME='FCDEBUG'
      CALL HPASTA (TECHNAME,LIARGS,IFCDBG,NWORDS,IARGS,ISTAT)
      IF (ISTAT.GT.0) CALL FPHPWN (ISTAT,TECHNAME)
      ITRACE=IARGS(84)
C
      IDBALL=0
      NDEBUG=0
C
C  CHECK IF TECHNIQUE IS ON
      IF (IFCDBG.EQ.0) GO TO 120
C
C  GET VALUE OF IDBALL (DEBUG PRINTOUT FOR ALL OPERATIONS)
      NSTRNG=LEN(STRNG)/4
      CALL HGTSTR (NSTRNG,IARGS(81),STRNG,LSTRNG,ISTAT)
      IF (ISTAT.NE.0) THEN
         WRITE (IPR,80) ISTAT,TECHNAME
80    FORMAT ('0**ERROR** STATUS CODE ',I3,' RETURNED FROM ROUTINE ',
     *   'HGTSTR WHILE GETTING VALUES FOR TECHNIQUE ',A,'.')
         CALL ERROR
      ENDIF
C
      IF (STRNG.EQ.'YES') IDBALL=1
C
      IF (IDBALL.EQ.1) GO TO 120
C
C  GET DEBUG CODES
      DO 110 I=1,NWORDS/4
         NOPRNAM=LEN(OPRNAM)/4
         IPOS=1+(I-1)*3
         CALL HGTSTR (NOPRNAM,IARGS(IPOS),OPRNAM,LOPRNAM,ISTAT)
         IF (ISTAT.NE.0) THEN
            WRITE (IPR,81) ISTAT,TECHNAME
81    FORMAT ('0**WARNING** STATUS CODE ',I3,' RETURNED FROM ROUTINE ',
     *   'HGTSTR WHILE GETTING VALUES FOR TECHNIQUE ',A,'.')
            CALL WARN
            GO TO 110
            ENDIF
         IF (OPRNAM.EQ.' ') GO TO 120
C     GET OPERATION NUMBER
         CALL FOPCDE (OPRNAM,NUMOP)
         IF (NUMOP.EQ.0) THEN
            WRITE (IPR,105) OPRNAM(1:LOPRNAM)
105   FORMAT ('0**WARNING** THE OPERATION NUMBER RETURNED FROM ',
     *   'ROUTINE FOPCDE FOR OPERATION NAME ',A,' IS ZERO.')
         CALL WARN
            GO TO 110
            ENDIF
         NDEBUG=NDEBUG+1
         IDEBUG(NDEBUG)=NUMOP
110      CONTINUE
C
120   IALL=0
      NDEBGS=0
C
C  GET TECH VALUE AND ARGUMENTS FOR TECH SYSDEBUG
      TECHNAME='SYSDEBUG'
      CALL HPASTA (TECHNAME,LIARGS,ISYDBG,NWORDS,IARGS,ISTAT)
      IF (ISTAT.GT.0) CALL FPHPWN (ISTAT,TECHNAME)
C
C  CHECK IF TECHNIQUE IS ON
      IF (ISYDBG.EQ.0) GO TO 210
C
C  GET VALUE OF IALL (DEBUG PRINTOUT FOR ALL DEBUG CODES)
      NSTRNG=LEN(STRNG)/4
      CALL HGTSTR (NSTRNG,IARGS(61),STRNG,LSTRNG,ISTAT)
      IF (ISTAT.NE.0) THEN
         WRITE (IPR,80) ISTAT,TECHNAME
         CALL ERROR
         ENDIF
C
      IF (STRNG.EQ.'YES') IALL=1
C
      IF (IALL.EQ.1) GO TO 210
C
C  GET DEBUG CODES
      DO 200 I=1,NWORDS/4
         NICDS=1
         IPOS=1+(I-1)*3
         CALL HGTSTR (NICDS,IARGS(IPOS),ICDS,LICDS,ISTAT)
         IF (ISTAT.NE.0) THEN
            WRITE (IPR,80) ISTAT,TECHNAME
            CALL ERROR
            GO TO 200
            ENDIF
         IF (ICDS.EQ.IBLNK) GO TO 210
            NDEBGS=NDEBGS+1
            IDEBGS(NDEBGS)=ICDS
200      CONTINUE
C
210   IBUG=IFBUG('FILS')
C
      IF (IBUG.GT.0) THEN
         WRITE (IODBUG,*) 'IALL=',IALL,' NDEBGS=',NDEBGS
         IF (NDEBGS.GT.0) WRITE (IODBUG,250) (IDEBGS(I),I=1,NDEBGS)
250   FORMAT (' IDEBGS=',20(A4,1X))
            WRITE (IODBUG,*) 'IDBALL=',IDBALL,' NDEBUG=',NDEBUG
        IF (NDEBGS.GT.0) WRITE (IODBUG,270) (IDEBUG(I),I=1,NDEBUG)
270   FORMAT (' IDEBUG=',20(I4,1X))
         ENDIF
C
      NOPROT=0
C
      INASSIM=0
C
      ICKASSIM=0
      IF (ICKASSIM.EQ.1) THEN
C     TECHINQUE ASSMRUN - NO ARGUMENTS
         TECHNAME='ASSMRUN'
         CALL HPAST (TECHNAME,ASSMRUN,ISTAT)
         IF (ISTAT.GT.0) CALL FPHPWN (ISTAT,TECHNAME)
         CALL FTEKCK (ASSMRUN,TECHNAME,0,ASSMRUN,0,2)
         IF (ASSMRUN.EQ.1.AND.NCSTOR.NE.0) THEN
            WRITE (IPR,701)
  701 FORMAT ('0**WARNING** CARRYOVER IS NOT ALLOWED TO BE SAVED ',
     * 'WHILE ASSIMILATOR OPTION IS SET TO OPTIMIZE. ',
     * 'ASSIMILATOR TURNED OFF.' )
            ASSMRUN=0
            ENDIF
         IF (ASSMRUN.EQ.2.AND.NCSTOR.EQ.0) THEN
            WRITE (IPR,702)
  702 FORMAT ('0**WARNING** THE INCORPORATE OPTION OF THE ',
     * 'ASSIMILATOR IS NOT ALLOWED TO BE RUN WHILE CARRYOVER ',
     * 'IS NOT BEING SAVED. ASSIMILATOR TURNED OFF' )
            ASSMRUN=0
            ENDIF
C     TECHINQUE ASSMPAR - NO ARGUMENTS
         TECHNAME='ASSMPAR'
         CALL HPAST (TECHNAME,ASSMPAR,ISTAT)
         IF (ISTAT.GT.0) CALL FPHPWN (ISTAT,TECHNAME)
         CALL FTEKCK (ASSMPAR,TECHNAME,3,ASSMPAR,1,3)
C     TECHINQUE PRECSEN - NO ARGUMENTS
         TECHNAME='PRECSEN'
         CALL HPAST (TECHNAME,PRSEN,ISTAT)
         IF (ISTAT.GT.0) CALL FPHPWN (ISTAT,TECHNAME)
         CALL FTEKCK (PRSEN,TECHNAME,1,PRSEN,0,1)
C     TECHINQUE KPTIME - NO ARGUMENTS
         TECHNAME='KPTIME'
         CALL HPAST (TECHNAME,KPTIME,ISTAT)
         IF (ISTAT.GT.0) CALL FPHPWN (ISTAT,TECHNAME)
         CALL FTEKCK (KPTIME,TECHNAME,0,KPTIME,0,1)
         ENDIF
C
C  TECHNIQUE PRINTOUT - NO ARGUMENTS
      TECHNAME='PRINTOUT'
      CALL HPAST (TECHNAME,IPROUT,ISTAT)
      IF (ISTAT.GT.0) CALL FPHPWN (ISTAT,TECHNAME)
      CALL FTEKCK (IPROUT,TECHNAME,1,IPROUT,0,1)
C
      IF (IPROUT.EQ.0) NOPROT=1
C
C  SET VALUES IN /FPLTAB/
C  VALUE OF 0 FOR TECHNIQUE GIVES VALUE OF -1 IN /FPLTAB/
C  VALUE OF 1 FOR TECHNIQUE GIVES VALUE OF  1 IN /FPLTAB/
C  VALUE OF 2 FOR TECHNIQUE GIVES VALUE OF  0 IN /FPLTAB/
C
C  TECHNIQUE TABLES - NO ARGUMENTS
      TECHNAME='TABLES'
      CALL HPAST (TECHNAME,ITABLE,ISTAT)
      IF (ISTAT.GT.0) CALL FPHPWN (ISTAT,TECHNAME)
      CALL FTEKCK (ITABLE,TECHNAME,2,ITABLE,0,2)
      IPRHY=0
      IF (ITABLE.EQ.0) IPRHY=-1
      IF (ITABLE.EQ.1) IPRHY=1
C
C  TECHNIQUE PLOTHYD - NO ARGUMENTS
      CALL HPAST (8HPLOTHYD ,IPLOTH,ISTAT)
      IF (ISTAT.GT.0) CALL FPHPWN (ISTAT,8HPLOTHYD )
      CALL FTEKCK (IPLOTH,8HPLOTHYD ,2,IPLOTH,0,2)
      IPLHY=0
      IF (IPLOTH.EQ.0) IPLHY=-1
      IF (IPLOTH.EQ.1) IPLHY=1
C
C  TECHNIQUE SNOW - NO ARGUMENTS
      CALL HPAST (8HSNOW    ,ISNOW,ISTAT)
      IF (ISTAT.GT.0) CALL FPHPWN (ISTAT,8HSNOW    )
      CALL FTEKCK (ISNOW,8HSNOW    ,1,ISNOW,0,1)
      NOSNOW=0
      IF (ISNOW.EQ.0) NOSNOW=1
C
C  TECHNIQUE UPWE - NO ARGUMENTS
      CALL HPAST (8HUPWE    ,IUPWE,ISTAT)
      IF (ISTAT.GT.0) CALL FPHPWN (ISTAT,8HUPWE    )
      CALL FTEKCK (IUPWE,8HUPWE    ,1,IUPWE,0,1)
C
C  TECHNIQUE UPSC - NO ARGUMENTS
      CALL HPAST (8HUPSC    ,IUPSC,ISTAT)
      IF (ISTAT.GT.0) CALL FPHPWN (ISTAT,8HUPSC    )
      CALL FTEKCK (IUPSC,8HUPSC    ,1,IUPSC,0,1)
C
C  SET VALUE IN /FSNW/
C  VALUE OF 0 FOR TECHNIQUE GIVES VALUE OF -1 IN /FSNW/
C  VALUE OF 1 FOR TECHNIQUE GIVES VALUE OF  1 IN /FSNW/
C  VALUE OF 2 FOR TECHNIQUE GIVES VALUE OF  0 IN /FSNW/
C
C  TECHNIQUE PRINTSNW - NO ARGUMENTS
      CALL HPAST (8HPRINTSNW,IPRTSN,ISTAT)
      IF (ISTAT.GT.0) CALL FPHPWN (ISTAT,8HPRINTSNW)
      CALL FTEKCK (IPRTSN,8HPRINTSNW,2,IPRTSN,0,2)
      IPRSNW=0
      IF (IPRTSN.EQ.0) IPRSNW=-1
      IF (IPRTSN.EQ.1) IPRSNW=1
C
C  SET VALUE IN /FSACPR/
C  VALUE OF 0 FOR TECHNIQUE GIVES VALUE OF -1 IN /FSACPR/
C  VALUE OF 1 FOR TECHNIQUE GIVES VALUE OF  1 IN /FSACPR/
C  VALUE OF 2 FOR TECHNIQUE GIVES VALUE OF  0 IN /FSACPR/
C
C  TECHNIQUE PRINTSMA - NO ARGUMENTS
      CALL HPAST (8HPRINTSMA,IPRTSM,ISTAT)
      IF (ISTAT.GT.0) CALL FPHPWN (ISTAT,8HPRINTSMA)
      CALL FTEKCK (IPRTSM,8HPRINTSMA,0,IPRTSM,0,2)
      IPRSAC=0
      IF (IPRTSM.EQ.0) IPRSAC=-1
      IF (IPRTSM.EQ.1) IPRSAC=1
C
C  TECHNIQUE FROST - NO ARGUMENTS
C  VALUE OF 0 FOR TECHNIQUE GIVES VALUE OF  1 IN /FSACPR/
C  VALUE OF 1 FOR TECHNIQUE GIVES VALUE OF  0 IN /FSACPR/
      CALL HPAST (8HFROST   ,IFROST,ISTAT)
      IF (ISTAT.GT.0) CALL FPHPWN (ISTAT,8HFROST   )
      CALL FTEKCK (IFROST,8HFROST   ,0,IFROST,0,1)
      NOFRZE=0
      IF (IFROST.EQ.0) NOFRZE=1
C
C  TECHNIQUE MODWARN - NO ARGUMENTS
      CALL HPAST (8HMODWARN ,MODWRN,ISTAT)
      IF (ISTAT.GT.0) CALL FPHPWN (ISTAT,8HMODWARN )
      CALL FTEKCK (MODWRN,8HMODWARN ,1,MODWRN,0,1)
C
C  TECHNIQUE PRTRO - NO ARGUMENTS
      CALL HPAST (8HPRTRO   ,ICRTRO,ISTAT)
      IF (ISTAT.GT.0) CALL FPHPWN (ISTAT,8HPRTRO   )
      CALL FTEKCK (ICRTRO,8HPRTRO   ,0,ICRTRO,0,3)

C
C  TECHNIQUE SACSNOW  - NO ARGUMENTS
C
      CALL HPAST (8HSACSNOW ,IOUTYP,ISTAT)
      IF (ISTAT.GT.0) CALL FPHPWN (ISTAT,8HSACSNOW )
      CALL FTEKCK (IOUTYP, 8HSACSNOW ,0,IOUTYP,0,1)
c
c
C
      IF (IBUG.EQ.1) WRITE (IODBUG,290) NOPROT,IPLHY,IPRHY,NOSNOW,IUPWE,
     *  IUPSC,IPRSNW,IPRSAC,NOFRZE,MODWRN,ICRTRO, IOUTYP
290   FORMAT ('0** IN FILSGO - NOPROT,IPLHY,IPRHY,NOSNOW,IUPWE,',
     *  'IUPSC,IPRSNW,IPRSAC,NOFRZE,MODWRN,ICRTRO, IOUTYP='/11X,12I8)
C
      IF (IBUG.EQ.1) WRITE (IODBUG,300) ICRTRO
300   FORMAT ('0** IN FILSGO - ICRTRO='/11X,1I11)
C
      CALL FSTWHR (OLDOPN,IOLDOP,OLDOPN,IOLDOP)
C
      IF (ITRACE.GT.0) WRITE (IODBUG,*) 'EXIT ',RTNNAM
C
      RETURN
C
      END
