C MODULE MAPMN
C-----------------------------------------------------------------------
C
      SUBROUTINE MAPMN (STAID,ANAME,AREAID,
     *   IGS,BASE,PX,
     *   PXSUM,
     *   X,Y,
     *   SW,SWX,
     *   OBTMO,OBTMOX,IND,NORMAL,
     *   SUN,
     *    MOCHK,NSTH,NSTAH,NSTD,NSTAD,
     *   TIMEOB,PCORR,IMCOR,IOBCGE,SCORF,A,
     *   C1,
     *   NSEQ,NEXTRD,FILES,XDATA,
     *   ICK,MC)
C
      CHARACTER*8 TYPERR
      INTEGER OBTMO(M1),OBTMOX(M1)
      REAL NORMAL,INCHES,MMETER,LIST,LABEL,NORM
C
C
      DIMENSION A(80,80),FNAME(3)
      DIMENSION NORMAL(M1,12),C1(M1,817)
      DIMENSION TIMEOB(M1,MC),PCORR(M1,MC),IMCOR(M1,MC)
      DIMENSION IOBCGE(M1,MC),SCORF(M1,MC)
      DIMENSION ANAME(5,M2),AREAID(3,M2),STAID(7,M1)
      DIMENSION NSTH(M1),NSTAH(M1),NSTD(M1),NSTAD(M1)
      DIMENSION X(M1),Y(M1),IND(M1)
      DIMENSION IGS(3,M1),BASE(3,M3),PX(M1,M3)
      DIMENSION NSEQ(M2),NEXTRD(M2),FILES(3,M2),XDATA(744,M2)
      DIMENSION SW(M1),SWX(M2,M1,2)
      DIMENSION SUN(2,M3)
      DIMENSION MOCHK(M3)
      DIMENSION PXSUM(M2,M6,12)
      DIMENSION SLAT(3000),SLON(3000),FLAT(3000),FLON(3000),IPT(3000)
      DIMENSION NDUMST(200),OBT(200)
      DIMENSION WORD1(3),WORD2(3),WORD3(3),WORD4(3),WORD5(3)
      DIMENSION WORD6(3),WORD7(3),WORD8(3),WORD9(3)
      DIMENSION GRD(3),THI(3),PRED(3),SEA(3),POW(3),STP(3)
      DIMENSION CON(3),HOUR1(3),HOUR3(3),HOUR6(3)
      DIMENSION ADJ1(3),ADJ2(3),NO(3),YES(3)
      DIMENSION PLOT1(3),PLOT2(3),PLOT3(3)
      DIMENSION CHAR1(3),CHAR2(3)
      DIMENSION PRINT1(3),PRINT2(3),PRINT3(3)
      DIMENSION COMPR1(3),COMPR2(3)

      REAL        TREAL
      CHARACTER*4 TCHAR
      EQUIVALENCE (TREAL,TCHAR)
C
      INCLUDE 'uiox'
      INCLUDE 'upvrsx'
      INCLUDE 'common/ionum'
      INCLUDE 'scommon/sntwkx'
      INCLUDE 'scommon/sudbgx'
      INCLUDE 'clbcommon/crwctl'
      COMMON /CARRAY/ C(200,817)
      COMMON /DIM/ M1,M2,M3,M4,M5,M6
      COMMON /MAP/ IDBUG,IDBUGA
      COMMON /LSDTA/ IDEC,IBMO,IBYR,IEMO,IEYR,UNITW,FILE(3),TYPE,IT,
     *   TSTAID(3),DESCRP(5),DESCR(5),JMO,JYR,TDATA(744)
      COMMON /MNC1/ AREA,DUNITS,FLAT,FLON,FNAME,FUNITS,ILIST,NDUMST
      COMMON /MNC2/ IMOS,IMOW,IPT,IPUNCH,ISTAT,ISTRT,JB,NBASIN,NFLD
      COMMON /MNC3/ NDLSTA,NUM,NUMM5,NUMM6,OBNEW,IOPT1,IOPT2,IOPT3,IOPT4
      COMMON /MNC4/ IOPT5,IOPT6,IOPT8,IOPT9,IOPT10,NHLSTA,IERR,STMNWT
C
C    ================================= RCS keyword statements ==========
      CHARACTER*68     RCSKW1,RCSKW2
      DATA             RCSKW1,RCSKW2 /                                 '
     .$Source: /fs/hseb/ob72/rfc/calb/src/map/RCS/mapmn.f,v $
     . $',                                                             '
     .$Id: mapmn.f,v 1.6 2001/06/12 15:29:08 aivo Exp $
     . $' /
C    ===================================================================
C
C
C
      DATA IP/1/
      DATA INCHES/4HIN  /,MMETER/4HMM  /,LIST/4HLIST/
      DATA DTYPE/4HMAP /, DIMF/4HL   /
      DATA THIE/4HTHIE/,GRID/4HGRID/,DP/4HDP  /,PRE/4HPRE /
      DATA SEAS/4HSEAS/,BLNK/4H    /
      DATA STOP/4HSTOP/
      DATA CONT/4HCONT/
      DATA ADJ/4HADJ /
      DATA PLOT/4HPLOT/,SESN/4HSESN/,CHAR/4HCHAR/,NORM/4HNORM/
      DATA COMP/4HCOMP/,DIST/4HDIST/,SMRY/4HSMRY/,CMPR/4HCMPR/
      DATA GRD/4HGRID,4H POI,4HNT  /
      DATA THI/4H  TH,4HIESS,4HEN  /
      DATA PRED/4HPRED,4HETER,4HMINE/
      DATA SEA/4H  SE,4HASON,4HAL  /
      DATA POW/4HNO  ,4H YES,4H    /
      DATA CON/4H  CO,4HNTIN,4HUE  /
      DATA STP/4H    ,4HSTOP,4H    /
      DATA HOUR1/4H   1,4H HOU,4HR   /
      DATA HOUR3/4H   3,4H HOU,4HR   /
      DATA HOUR6/4H   6,4H HOU,4HR   /
      DATA ADJ1/4H    ,4HNONE,4H    /
      DATA ADJ2/4H   A,4HDJUS,4HT   /
      DATA NO/4H    ,4H NO ,4H    /
      DATA YES/4H    ,4HYES ,4H    /
      DATA PLOT1/4H    ,4HNONE,4H    /
      DATA PLOT2/4H   A,4HNNUA,4HL   /
      DATA PLOT3/4H  SE,4HASON,4HAL  /
      DATA CHAR1/4H  NO,4HT US,4HED  /
      DATA CHAR2/4H    ,4HUSED,4H    /
      DATA PRINT1/4HDEBU,4HG OU,4HTPUT/
      DATA PRINT2/4H  DE,4HFAUL,4HT   /
      DATA PRINT3/4H  CO,4HMPLE,4HTE  /
      DATA COMPR1/4H    ,4HNONE,4H    /
      DATA COMPR2/4H  CO,4HMPAR,4HE   /
      DATA DLABEL/4H@D  /
      DATA GLABEL/4H@G  /
      DATA HLABEL/4H@H  /
      DATA VCTIM/4HCTIM/
C
C
      IUSTOP=0
C
      DO 10 I=1,M1
         DO 10 J=1,817
           C(I,J)=C1(I,J)
10       CONTINUE
C
      IDEC=2
C
C   SET DEFAULTS FOR INPUT DATA
      RKEY1=THIE
      RKEY2=CONT
      RKEY4=BLNK
      RKEY6=BLNK
      RKEY10=BLNK
      RKEY7=BLNK
      RKEY8=SMRY
      RKEY9=BLNK
      STMNWT=0.01
      IT=6
      NUMM5=0
      NUMM6=0
C
      IPRERR=-1
      IPUNIT=IPR
      TYPERR='ERROR'
      LDEBUG=0
      INCLUDE 'clugtres'
      IF (IERR.NE.0) CALL USTOP (IPR,IUSTOP)
C
C  SET VALUES FOR MAXIMUM NUMBER OF PRECIPITATION STATIONS, MAP SUB
C  AREAS, NEEDED SCRATCH FILE RECORDS, AND MONTHS
      MAXSTA=M1
      MAXMAP=M2
      MAXMO=M3
      IOPT5=1
C
C  SET DEFALUTS FOR CARD A INPUT
      DUNITS=INCHES
      FUNITS=INCHES
      IPUNCH=0
      DLIST=BLNK
      FNAME(1)=BLNK
      FNAME(2)=BLNK
      FNAME(3)=BLNK
      IERR=0
      NFLD=0
      ISTRT=0
      CALL AREAD (FNAME,DUNITS,FUNITS,IBMO,IBYR,IEMO,IEYR,IPUNCH,DLIST,
     *   ISTRT,NFLD,ISTAT,IERR,LIDBUG)
C
      IDBUG=0
      IDBUGA=0
      INDERR=0
      IBASEY=1900
C
C  CHECK BEGINNING AND ENDING YEAR
      IF (IBYR.LT.IBASEY) THEN
         CALL UEROR (LP,0,-1)
         WRITE (IPR,400) 'BEGINNING YEAR',IBYR,IBASEY
         INDERR=1
         ENDIF
      IF (IEYR.LT.IBASEY) THEN
         CALL UEROR (LP,0,-1)
         WRITE (IPR,400) 'ENDING YEAR',IEYR,IBASEY
         INDERR=1
         ENDIF
C
C  CHECK FOR MAXIMUM NUMBER OF MONTHS
      NMO=(IEMO+IEYR*12)-(IBMO+IBYR*12)+1
      IF (NMO.GT.0.AND.NMO.LE.MAXMO) GO TO 70
         CALL UEROR (LP,0,-1)
         WRITE (IPR,610) NMO,MAXMO,IBMO,IBYR,IEMO,IEYR
         INDERR=1
C
C  CHECK FOR VALID DATA UNITS
70    IF (FUNITS.EQ.BLNK) FUNITS=INCHES
      IF (DUNITS.EQ.BLNK) DUNITS=INCHES
      IF (FUNITS.EQ.INCHES.OR.FUNITS.EQ.MMETER) GO TO 80
         CALL UEROR (LP,0,-1)
         WRITE (IPR,590) FUNITS
         INDERR=1
80    IF (DUNITS.EQ.INCHES.OR.DUNITS.EQ.MMETER) GO TO 90
         CALL UEROR (LP,0,-1)
         WRITE (IPR,580) DUNITS
         INDERR=1
C
90    IF (INDERR.EQ.1) CALL USTOP (IPR,IUSTOP)
C
C  SET DEFAULTS FOR OPTIONS
      IOPT1=9
      IOPT2=9
      IOPT4=9
      IOPT6=9
      IOPT7=9
      IOPT8=9
      IOPT9=9
      IOPT10=9
C
      CALL BCREAD (NBASIN,RKEY1,MULT,RKEY2,IT,RKEY4,RKEY6,
     *   IMOW,IMOS,RKEY7,RKEY8,RKEY9,STMNWT,RKEY10,
     *   ISTRT,NFLD,ISTAT,IERR )
C
C  CHECK IOPT1
      IF (RKEY1.EQ.THIE) IOPT1=1
      IF (RKEY1.EQ.GRID) IOPT1=0
      IF (RKEY1.EQ.DP) IOPT1=4
      IF (RKEY1.EQ.PRE) IOPT1=2
      IF (RKEY1.EQ.SEAS) IOPT1=3
      IF (IOPT1.EQ.9) THEN
         CALL UWARN (LP,0,-1)
         WRITE (IPR,320)
         IOPT1=1
         ENDIF
C
C  CHECK IOPT2
      IF (RKEY2.EQ.STOP) IOPT2=0
      IF (RKEY2.EQ.CONT) IOPT2=1
      IF (IOPT2.EQ.9) THEN
         CALL UWARN (LP,0,-1)
         WRITE (IPR,330)
         IOPT2=1
         ENDIF
C
C  CHECK TIME INTERVAL
      IF (IT.EQ.0) IT=6
      IF (IT.EQ.1.OR.IT.EQ.3.OR.IT.EQ.6) GO TO 100
         CALL UWARN (LP,0,-1)
         WRITE (IPR,340)
         IT=6
C
100   IF (IT.EQ.1) IOPT3=1
      IF (IT.EQ.3) IOPT3=2
      IF (IT.EQ.6) IOPT3=3
C
C  CHECK IOPT4
      IF (RKEY4.EQ.BLNK) IOPT4=1
      IF (RKEY4.EQ.ADJ) IOPT4=2
      IF (IOPT4.EQ.9) THEN
         CALL UWARN (LP,0,-1)
         WRITE (IPR,350)
         IOPT4=1
         ENDIF
C
C  CHECK IOPT6
      IF (RKEY6.EQ.BLNK) IOPT6=0
      IF (RKEY6.EQ.PLOT) IOPT6=1
      IF (RKEY6.EQ.SESN) IOPT6=2
      IF (IOPT6.EQ.9) THEN
         CALL UWARN (LP,0,-1)
         WRITE (IPR,360)
         IOPT6=0
         ENDIF
C
C  CHECK IOPT7
      IF (RKEY7.EQ.BLNK) IOPT7=1
      IF (RKEY7.EQ.NORM.OR.RKEY7.EQ.CHAR) IOPT7=2
      IF (IOPT7.EQ.9) THEN
         CALL UWARN (LP,0,-1)
         WRITE (IPR,370)
         IOPT7=1
         ENDIF
C
C  CHECK IOPT8
      IF (RKEY8.EQ.COMP) IOPT8=0
      IF (RKEY8.NE.COMP) IOPT8=1
      IF (IOPT8.EQ.9) THEN
         CALL UWARN (LP,0,-1)
         WRITE (IPR,380)
         IOPT8=1
         ENDIF
C
C  CHECK IOPT9
      IF (RKEY9.EQ.BLNK) IOPT9=1
      IF (RKEY9.EQ.CMPR) IOPT9=2
      IF (IOPT9.EQ.9) THEN
         CALL UWARN (LP,0,-1)
         WRITE (IPR,390)
         IOPT9=1
         ENDIF
C
C  CHECK IOPT10
      IF (RKEY10.EQ.BLNK) IOPT10=1
      IF (RKEY10.EQ.VCTIM) IOPT10=2
      IF (IOPT10.EQ.9) THEN
         CALL UWARN (LP,0,-1)
         WRITE (IPR,410)
         IOPT10=1
         ENDIF
C
C  CHECK MINIMUM STATION WEIGHT
      IF (STMNWT.LT.0.001)  STMNWT=0.01
      IF (IMOW.EQ.0) IMOW=10
      IF (IMOS.EQ.0) IMOS=5
C
C  DO NOT CALL HEADER IF THE NUMBER OF AREAS IS ZERO
      IF (NBASIN.EQ.0) IOPT5=0
C
C  ASSIGN CHARACTER WORDS TO OPTIONS FOR WRITING TO TABLE
      DO 110 I=1,3
         IF (IOPT1.EQ.0) WORD1(I)=GRD(I)
         IF (IOPT1.EQ.1) WORD1(I)=THI(I)
         IF (IOPT1.EQ.2) WORD1(I)=PRED(I)
         IF (IOPT1.EQ.3) WORD1(I)=SEA(I)
         IF (IOPT1.EQ.4) WORD1(I)=POW(I)
         IF (IOPT2.EQ.0) WORD2(I)=STP(I)
         IF (IOPT2.EQ.1) WORD2(I)=CON(I)
         IF (IT.EQ.1) WORD3(I)=HOUR1(I)
         IF (IT.EQ.3) WORD3(I)=HOUR3(I)
         IF (IT.EQ.6) WORD3(I)=HOUR6(I)
         IF (IOPT4.EQ.1) WORD4(I)=ADJ1(I)
         IF (IOPT4.EQ.2) WORD4(I)=ADJ2(I)
         IF (IOPT5.EQ.0) WORD5(I)=NO(I)
         IF (IOPT5.EQ.1) WORD5(I)=YES(I)
         IF (IOPT6.EQ.0) WORD6(I)=PLOT1(I)
         IF (IOPT6.EQ.1) WORD6(I)=PLOT2(I)
         IF (IOPT6.EQ.2) WORD6(I)=PLOT3(I)
         IF (IOPT7.EQ.1) WORD7(I)=CHAR1(I)
         IF (IOPT7.EQ.2) WORD7(I)=CHAR2(I)
         IF (IOPT8.EQ.0) WORD8(I)=PRINT1(I)
         IF (IOPT8.EQ.1) WORD8(I)=PRINT2(I)
         IF (IOPT9.EQ.1) WORD9(I)=COMPR1(I)
         IF (IOPT9.EQ.2) WORD9(I)=COMPR2(I)
110      CONTINUE
C
C  PRINT OPTIONS TABLE
      WRITE (IPR,430)
      WRITE (IPR,440)
      WRITE (IPR,450)
      WRITE (IPR,460)
      WRITE (IPR,430)
      WRITE (IPR,500) NBASIN,(WORD1(I),I=1,3),(WORD2(I),I=1,3),
     *   (WORD3(I),I=1,3),(WORD4(I),I=1,3)
      WRITE (IPR,420)
      WRITE (IPR,470)
      WRITE (IPR,480)
      WRITE (IPR,490)
      WRITE (IPR,430)
      WRITE (IPR,510) (WORD6(I),I=1,3),(WORD7(I),I=1,3),
     *   (WORD8(I),I=1,3),(WORD9(I),I=1,3),STMNWT,
     *   IMOW,IMOS
      IF (NBASIN.EQ.0.AND.IOPT6.GT.0) IOPT2=1
C
C  CHECK FOR DATA LISTING OPTION
      ILIST=0
      IF (DLIST.NE.LIST) GO TO 120
      ILIST=1
      WRITE (IPR,520)
C
C  CHECK FOR MAXIMUM NUMBER OF MAP SUBAREAS
120   IF (NBASIN.GE.0.AND.NBASIN.LE.MAXMAP) GO TO 130
         CALL UEROR (LP,0,-1)
         WRITE (IPR,620) NBASIN,MAXMAP
         CALL USTOP (IPR,IUSTOP)
C
130   IBYR=IBYR-IBASEY
      IEYR=IEYR-IBASEY
C
C  INITIALIZE ARRAYS
      DO 140 I=1,MAXMO
         SUN(1,I)=0.
         SUN(2,I)=0.
140      CONTINUE
      DO 150 I=1,M2
      DO 150 J=1,M6
      DO 150 K=1,12
         PXSUM(I,J,K)=-999.
150      CONTINUE
C
C  READ NUMBER OF HOURLY RECORDING STATIONS AND NUMBER OF DAILY STATIONS
      LABEL=DLABEL
      NCHAR=1
      CALL UFIELD (NFLD,ISTRT,LENGTH,ITYPEU,NREP,INTEGR,UREAL,
     *   NCHAR,UCHAR,LLPAR,LRPAR,LASK,LATSGN,LAMPS,LEQUAL,ISTAT)
      CALL AFTERU (LATSGN,ITYPEU,UCHAR,LABEL,3,ISTAT,LENGTH,IERR)
      IF (ISTAT.EQ.7) GO TO 160
      CALL UFIELD (NFLD,ISTRT,LENGTH,ITYPEU,NREP,NHLSTA,UREAL,
     *   NCHAR,UCHAR,LLPAR,LRPAR,LASK,LATSGN,LAMPS,LEQUAL,ISTAT)
      CALL AFTERU (LATSGN,ITYPEU,UCHAR,LABEL,0,ISTAT,LENGTH,IERR)
      IF (ISTAT.EQ.6) ISTRT=-1
      IF (ISTAT.EQ.6) GO TO 160
      CALL UFIELD (NFLD,ISTRT,LENGTH,ITYPEU,NREP,NDLSTA,UREAL,
     *   NCHAR,UCHAR,LLPAR,LRPAR,LASK,LATSGN,LAMPS,LEQUAL,ISTAT)
      CALL AFTERU (LATSGN,ITYPEU,UCHAR,LABEL,0,ISTAT,LENGTH,IERR)
      IF (ISTAT.EQ.6) ISTRT=-1
C
160   NUM=NDLSTA+NHLSTA
C
C  CHECK FOR MAXIMUM NUMBER OF PRECIP STATIONS
      IF (NUM.LE.MAXSTA.AND.NUM.GT.0) GO TO 180
         CALL UEROR (LP,0,-1)
         WRITE (IPR,600) NUM,MAXSTA
         CALL USTOP (IPR,IUSTOP)
C
180   DO 230 J=1,NUM
         JJ2=J-NHLSTA
C        READ STATION IDENTIFICATION AND LAT AND LON COORDINATES
         CALL LREAD (STAID,TIMEOB,SLAT,SLON,NDUMST,JJ2,J,M1,OBT,
     *      ISTRT,NFLD,ISTAT,IERR)
         IF (IOPT7.NE.2) GO TO 210
         LABEL=GLABEL
         NCHAR=1
190      CALL UFIELD (NFLD,ISTRT,LENGTH,ITYPEU,NREP,INTEGR,UREAL,
     *      NCHAR,UCHAR,LLPAR,LRPAR,LASK,LATSGN,LAMPS,LEQUAL,ISTAT)
         CALL AFTERU (LATSGN,ITYPEU,UCHAR,LABEL,3,ISTAT,LENGTH,IERR)
         IF (ISTAT.EQ.7) GO TO 190
         DO 200 I=1,12
            CALL UFIELD (NFLD,ISTRT,LENGTH,ITYPEU,NREP,INTEGR,
     *         NORMAL(J,I),
     *         NCHAR,UCHAR,LLPAR,LRPAR,LASK,LATSGN,LAMPS,LEQUAL,ISTAT)
            CALL AFTERU (LATSGN,ITYPEU,UCHAR,LABEL,1,ISTAT,LENGTH,IERR)
            IF (ISTAT.EQ.6) ISTRT=-1
            IF (ISTAT.EQ.6) GO TO 230
            IF (NORMAL(J,I).LT.0.001) NORMAL(J,I)=0.01
200         CONTINUE
         GO TO 230
210      DO 220 I=1,12
            NORMAL(J,I)=1.0
220         CONTINUE
230      CONTINUE
C
C  CONVERT FROM LAT/LON TO GRID COORDINATES
      ILLGD=1
      CALL SBLLGD (SLON,SLAT,NUM,X,Y,ILLGD,ISTAT)
C
C  LOAD SNTWKX COMMON BLOCK
      INWTYP=2
      INWFIL=NUM
      DO 240 I=1,NUM
         SFLGNW(I)=20
         CORDNW(1,I)=X(I)*10
         CORDNW(2,I)=Y(I)*10
         PP24NW(I)=I
240      CONTINUE
      DO 250 I=1,NUM
         WORKNW(I)=0.0
250      CONTINUE
C
C  READ NUMBER OF STATION TO BE REPLACED BY DUMMY STATION AND NUMBER OF
C  THE DUMMY STATION
      IF (IOPT9.EQ.1) GO TO 270
         LABEL=HLABEL
         NCHAR=1
260      CALL UFIELD (NFLD,ISTRT,LENGTH,ITYPEU,NREP,INTEGR,UREAL,
     *      NCHAR,UCHAR,LLPAR,LRPAR,LASK,LATSGN,LAMPS,LEQUAL,ISTAT)
         CALL AFTERU (LATSGN,ITYPEU,UCHAR,LABEL,3,ISTAT,LENGTH,IERR)
         IF (ISTAT.EQ.7) GO TO 260
         CALL UFIELD (NFLD,ISTRT,LENGTH,ITYPEU,NREP,NUMM5,UREAL,
     *      NCHAR,UCHAR,LLPAR,LRPAR,LASK,LATSGN,LAMPS,LEQUAL,ISTAT)
         CALL AFTERU (LATSGN,ITYPEU,UCHAR,LABEL,0,ISTAT,LENGTH,IERR)
         IF (ISTAT.EQ.6) ISTRT=-1
         IF (ISTAT.EQ.6) GO TO 270
         CALL UFIELD (NFLD,ISTRT,LENGTH,ITYPEU,NREP,NUMM6,UREAL,
     *      NCHAR,UCHAR,LLPAR,LRPAR,LASK,LATSGN,LAMPS,LEQUAL,ISTAT)
         CALL AFTERU (LATSGN,ITYPEU,UCHAR,LABEL,0,ISTAT,LENGTH,IERR)
         IF (ISTAT.EQ.6) ISTRT=-1
C
C  PRINT SUMMARY
270   WRITE (IPR,310) IBMO,IBYR+IBASEY,IEMO,IEYR+IBASEY
      CALL UPAGE (IPR)
      WRITE (IPR,420)
      WRITE (IPR,530)
      DO 280 IRG=1,NUM
         WRITE (IPR,540) IRG,(STAID(I,IRG),I=1,6),SLAT(IRG),SLON(IRG),
     *      OBT(IRG)
280      CONTINUE
      IF (IOPT7.EQ.1) GO TO 300
         CALL UPAGE (IPR)
         WRITE (IPR,550)
         WRITE (IPR,420)
         WRITE (IPR,570)
         DO 290 J=1,NUM
            WRITE (IPR,560) J,(STAID(I,J),I=1,7),(NORMAL(J,I),I=1,12)
290         CONTINUE
C
300   CALL MAPMN2 (MC,IP,DIMF,DTYPE,IGS,
     *   ANAME,AREAID,BASE,FILES,IMCOR,IND,IOBCGE,MOCHK,NEXTRD,NORMAL,
     *   NSEQ,OBTMO,OBTMOX,PCORR,PX,PXSUM,SCORF,STAID,SUN,SW,SWX,
     *   TIMEOB,X,XDATA,Y)
C
      RETURN
C
C- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
C
310   FORMAT ('0PERIOD OF RECORD: ',I2.2,'/',I4,
     *   ' THROUGH ',I2.2,'/',I4)
320   FORMAT ('0*** WARNING - INCORRECT WEIGHTING KEYWORD SPECIFIED. ',
     *   'THIESSEN WEIGHTS WILL BE USED.')
330   FORMAT ('0*** WARNING - INCORRECT TERMINATION KEYWORD SPECIFIED.')
340   FORMAT ('0*** WARNING - INCORRECT INCREMENT HOUR SPECIFIED. ',
     *   '6-HOUR INCREMENTS WILL BE USED.')
350   FORMAT ('0*** WARNING - INCORRECT KEYWORD FOR PRECIP ADJUSTMENT ',
     *   'OPTION. NO PRECIPITATION ADJUSTMENT WILL BE COMPUTED.')
360   FORMAT ('0*** WARNING - INCORRECT KEYWORD SPECIFIED FOR ',
     *   'CONSISTENCY PLOT OPTION. NO CONSISTENCY PLOTS WILL BE DONE.')
370   FORMAT ('0*** WARNING - INCORRECT STATION CHARACTERISTIC ',
     *   'OPTION SPECIFIED. STATION CHARACTERISTICS WILL NOT BE USED.')
380   FORMAT ('0*** WARNING - INCORRECT OUTPUT KEYWORD SPECIFIED. ',
     *   'MAP SUMARY WILL BE PRINTED ONLY.')
390   FORMAT ('0*** WARNING - INCORRECT KEYWORD FOR PRECIPITATION ',
     *   'COMPARISON. NO COMPARISON WILL BE PERFORMED.')
400   FORMAT ('0*** ERROR - ',A,' (',I4,') IS LESS THAN ',I4,'.')
410   FORMAT ('0*** WARNING - INCORRECT KEYWORD FOR OBSERVATION TIME ',
     *   'CHANGE. NO TIME CHANGE WILL BE PERFORMED.')
420   FORMAT (///)
430   FORMAT (/)
440   FORMAT(63H   NUMBER       TYPE      PROGRAM       MAP        PRECI
     *P      )
450   FORMAT(63H     OF          OF      TERMINATE     OUTPUT      ADJUS
     *T-     )
460   FORMAT(56H   AREAS       WEIGHT      OPTION    INCREMENTS     MENT
     *)
470   FORMAT(79H    TYPE        MEAN       PRINT       PRECIP     MINIMU
     *M      FIRST      FIRST)
480   FORMAT(79H     OF        MONTHLY     OPTION    COMPARISON   STATIO
     *N     WINTER     SUMMER)
490   FORMAT(79H    PLOT       PRECIP                  OPTION      WEIGH
     *T      MONTH      MONTH)
500   FORMAT (5X,I2,5X,4(3A4))
510   FORMAT (4(3A4),4X,F4.2,8X,I2,9X,I2)
520   FORMAT (34H0 *** MAP DATA LISTING REQUESTED.    / )
530   FORMAT ( T5,7HSTATION,T26,7HSTATION,T47,8HLATITUDE,T62,
     *         9HLONGITUDE,T75,11HOBSERVATION     /
     *         T5,6HNUMBER,T27,4HNAME,T47,10HCOORDINATE,T62,
     *         10HCOORDINATE,T78,4HTIME   /
     *         T5,7H-------,T17,25H-------------------------,T47,
     *         10H----------,T62,10H----------,T75,
     *         11H-----------  )
540   FORMAT ('0',T6,I3,T17,6A4,T47,F8.4,T63,F8.4,T78,F5.2)
550   FORMAT ('0',' MEAN MONTHLY PRECIPITATION')
560   FORMAT ('0',T5,I3,T15,6A4,A1,T45,12F5.2 )
570   FORMAT (T3,7HSTATION,T24,7HSTATION  /  T3,6HNUMBER,T25,4HNAME,
     *        T45,5H JAN ,5H FEB ,5H MAR ,5H APR ,5H MAY ,5H JUN ,
     *            5H JUL ,5H AUG ,5H SEP ,5H OCT ,5H NOV ,5H DEC  /
     *        T3,7H-------,T15,25H-------------------------,T45,
     *        60('-'))
580   FORMAT ('0*** ERROR - MAP CAN BE COMPUTED AND PRINTED IN ',
     *   'INCHES (IN) OR MILLIMETERS (MM). ',A4,' WAS SPECIFIED.')
590   FORMAT ('0*** ERROR - MAP RESULTS CAN BE WRITTEN TO FILE IN ',
     *   'INCHES (IN) OR MILLIMETERS (MM). ',A4,' WAS SPECIFIED.')
600   FORMAT ('0*** ERROR - THE NUMBER OF STATIONS ',
     *   '(',I5,') EXCEEDS THE MAXIMUM ALLOWABLE VALUE (',I5,').')
610   FORMAT ('0*** ERROR - THE NUMBER OF MONTHS TO BE PROCESSED ',
     *   '(',I4,') EXCEEDS THE MAXIMUM ALLOWABLE VALUE (',I4,').' /
     *   T14,'BEGINNING MONTH AND YEAR = ',I2.2,'/',I4 /
     *   T14,'ENDING MONTH AND YEAR    = ',I2.2,'/',I4)
620   FORMAT ('0*** ERROR - THE NUMBER OF MAP AREAS ',
     *   '(',I5,') EXCEEDS THE MAXIMUM ALLOWABLE VALUE (',I5,').')
C
      END
