C MODULE TILUVO
C-----------------------------------------------------------------------
C
      SUBROUTINE TILUVO
C
      INTEGER PDBUG
C
      DIMENSION SBNAME(2),OLDOPN(2),BLANK(2),IARGS(60)
C
      INCLUDE 'common/ionum'
      INCLUDE 'common/pudbug'
      INCLUDE 'common/where'
      INCLUDE 'common/errdat'
      INCLUDE 'common/tary'
      INCLUDE 'common/tuser'
      INCLUDE 'common/fctime'
      INCLUDE 'common/fctim2'
      INCLUDE 'common/tout'
      INCLUDE 'common/fdbug'
      INCLUDE 'common/sysbug'
C
      COMMON/HDFLTS/XHCL(2),LINPTZ,YHCL(18),LCLHCL,LTZHCL,NPDHCL,NCAHCL
CFAN
C      INTEGER DIURNAL
C      REAL K1,K2,K3,K4,K5,K6,K7,K8,K9,K0(9,4)

C jgg-replaced the above line for DR 18651,allows 3 more sites-May,2007
C     note this change was also made in fun008.f, tmeanm.f, temp.f
      INTEGER DIURNAL
      REAL K1,K2,K3,K4,K5,K6,K7,K8,K9,K0(9,16)
C jgg

      COMMON/DIURNAL0/DIURNAL,K1,K2,K3,K4,K5,K6,K7,K8,K9,K0
CFAN
C
C    ================================= RCS keyword statements ==========
      CHARACTER*68     RCSKW1,RCSKW2
      DATA             RCSKW1,RCSKW2 /                                 '
     .$Source: /fs/hseb/ob82/ohd/ofs/src/fcst_mat/RCS/tiluvo.f,v $
     . $',                                                             '
     .$Id: tiluvo.f,v 1.4 2005/03/01 19:25:33 dsa Exp jgofus $
     . $' /
C    ===================================================================
C
      DATA SBNAME/4HTILU,4HVO  /,USER/4HUSER/,BLANK/4H    ,4H    /
      DATA IBLANK/4H    /,IBALL/4HALL /
C
C
      IF (IPTRCE.GT.0) WRITE (IOPDBG,*) 'ENTER TILUVO'
C
      DO 10 I=1,2
      OLDOPN(I)=OPNAME(I)
10    OPNAME(I)=SBNAME(I)
      IOLDOP=IOPNUM
      IOPNUM=-1
C
C   COMMON PUDBUG
C
      CALL HPASTA (8HPPDEBUG ,60,IPDBG,NWORDS,IARGS,ISTAT)
      IF (ISTAT.NE.0) CALL FPHPWN (ISTAT,8HPPDEBUG )
      NDBUG=0
      IPALL=0
      DO 50 I=1,20
         CALL HGTSTR (1,IARGS(1+(I-1)*3),ICDS,IFL,ISTAT)
         IF (ISTAT.EQ.0) GO TO 30
         WRITE (IPR,20) ISTAT
20    FORMAT('0**ERROR** STATUS OF ',I3,' RETURNED FROM ',
     1 'HGTSTR.')
         CALL ERROR
30       IF (ICDS.EQ.IBLANK) GO TO 50
            IF (ICDS.NE.IBALL) GO TO 40
            IPALL=1
            GO TO 60
40       NDBUG=NDBUG+1
         PDBUG(NDBUG)=ICDS
C     COMMON SYSBUG
         IDEBGS(NDBUG)=ICDS
50       CONTINUE
      NDEBGS=NDBUG
60    IALL=IPALL
C
C   COMMON FDBUG
C
      IODBUG=IOPDBG
      ITRACE=IPTRCE
      IDBALL=0
      NDEBUG=0
C
      IPTR=0
      CALL RPPREC (BLANK,USER,IPTR,MARY,ARY,NFILL,IPTRN,IER)
      IF (IER.EQ.0) GO TO 80
      WRITE (IPR,70) USER,IER
70    FORMAT(1H0,10X,29H**ERROR** IN RPPREC FOR TYPE ,A4,8HISTAT = ,I5)
       GO TO 140
C
80    IBLEND=ARY(16)
      BLEND=1./IBLEND
      ISTMAT=ARY(19)
C
C   COMMON FCTIME
C
      CALL HPASTA (8HSTARTRUN,60,ISTRUN,NWORDS,IARGS,ISTAT)
      IF (ISTAT.NE.0) CALL FPHPWN (ISTAT,8HSTARTRUN)
      IDARUN=IARGS(1)/24+1
      IHRRUN=24
C
      CALL HPASTA (8HENDRUN  ,60,IENRUN,NWORDS,IARGS,ISTAT)
      IF (ISTAT.NE.0) CALL FPHPWN (ISTAT,8HENDRUN  )
      LDARUN=IARGS(1)/24+1
      LHRRUN=IARGS(1)-LDARUN*24+24
      IF (LHRRUN.EQ.0) GO TO 90
      LHRRUN=24
      GO TO 100
90    LDARUN=LDARUN-1
      LHRRUN=24
C
100   CALL HPASTA (8HLSTCMPDY,60,ILSTOB,NWORDS,IARGS,ISTAT)
      IF (ISTAT.NE.0) CALL FPHPWN (ISTAT,8HLSTCMPDY)
      LDACPD=IARGS(1)/24+1
      LHRCPD=IARGS(1)-LDACPD*24+24
      IF (LHRCPD.NE.0) GO TO 110
      LDACPD=LDACPD-1
      LHRCPD=24
C
110   CALL HPAST (8HNOUTZ   ,NOUTZ,ISTAT)
      IF (ISTAT.NE.0) CALL FPHPWN (ISTAT,8HNOUTZ   )
      CALL FTEKCK (NOUTZ,8HNOUTZ   ,-5,NOUTZ,-12,12)
C
      CALL HPAST (8HNOUTDS  ,NOUTDS,ISTAT)
      IF (ISTAT.NE.0) CALL FPHPWN (ISTAT,8HNOUTDS  )
      CALL FTEKCK (NOUTDS,8HNOUTDS  ,0,NOUTDS,0,1)
C
      LOCAL=LCLHCL
      NLSTZ=LTZHCL
C
C   COMMON FCTIM2
C
      INPTZC=LINPTZ
      NHOPDB=NPDHCL
      NHOCAL=NCAHCL
C
CFAN
C
C   COMMON DIURNAL
C
      CALL HPAST (8HDIURNAL ,DIURNAL,ISTAT)
      IF (ISTAT.NE.0) CALL FPHPWN (ISTAT,8HDIURNAL )
C jgg - DR 18651 
C      CALL FTEKCK (DIURNAL,8HDIURNAL ,0,DIURNAL,0,4)
      CALL FTEKCK (DIURNAL,8HDIURNAL ,0,DIURNAL,0,16)
C jgg
      IF (DIURNAL.NE.0) THEN
        K1=K0(1,DIURNAL)
        K2=K0(2,DIURNAL)
        K3=K0(3,DIURNAL)
        K4=K0(4,DIURNAL)
        K5=K0(5,DIURNAL)
        K6=K0(6,DIURNAL)
        K7=K0(7,DIURNAL)
        K8=K0(8,DIURNAL)
        K9=K0(9,DIURNAL)
       ENDIF
CFAN
C
C   COMMON TOUT
C
      CALL HPAST (8HPRTTINST,IPRIO,ISTAT)
      IF (ISTAT.NE.0) CALL FPHPWN (ISTAT,8HPRTTINST)
      CALL FTEKCK (IPRIO,8HPRTTINST,0,IPRIO,0,1)
C
      CALL HPAST (8HPRTT24  ,IPRMO,ISTAT)
      IF (ISTAT.NE.0) CALL FPHPWN (ISTAT,8HPRTT24  )
      CALL FTEKCK (IPRMO,8HPRTT24  ,0,IPRMO,0,1)
C
      CALL HPAST (8HPRTTFUT ,IPRMF,ISTAT)
      IF (ISTAT.NE.0) CALL FPHPWN (ISTAT,8HPRTTFUT )
      CALL FTEKCK (IPRMF,8HPRTTFUT ,0,IPRMF,0,1)
C
      CALL HPAST (8HPRTMAT  ,IPRMAT,ISTAT)
      IF (ISTAT.NE.0) CALL FPHPWN (ISTAT,8HPRTMAT  )
      CALL FTEKCK (IPRMAT,8HPRTMAT  ,0,IPRMAT,0,1)
C
      CALL HPAST (8HPRLASTDY,IPRLST,ISTAT)
      IF (ISTAT.NE.0) CALL FPHPWN (ISTAT,8HPRLASTDY)
      CALL FTEKCK (IPRLST,8HPRLASTDY,0,IPRLST,0,1)
C
      CALL HPAST (8HMETRIC  ,METRIC,ISTAT)
      IF (ISTAT.NE.0) CALL FPHPWN (ISTAT,8HMETRIC  )
      CALL FTEKCK (METRIC,8HMETRIC  ,0,METRIC,0,1)
C
CCC      IHR=IHRRUN
      IHR=0
      CALL MDYH2 (IDARUN,IHR,IM,ID,IY,IH,ITZ,IDSAV,INPTZC)
      LHR=LHRRUN
      CALL MDYH2 (LDARUN,LHR,LM,LD,LY,LH,ITZ,IDSAV,INPTZC)
      CALL MDYH2 (LDACPD,LHRCPD,JM,JD,JY,JH,ITZ,IDSAV,INPTZC)
      WRITE (IPR,120) IM,ID,IY,IH,INPTZC,LM,LD,LY,LH,INPTZC
120   FORMAT('0',30X,'RUN PERIOD',2X,
     1 I2.2,'/',I2.2,'/',I4,'-',I2.2,A4,' THRU ',
     2 I2.2,'/',I2.2,'/',I4,'-',I2.2,A4)
      WRITE (IPR,130) JM,JD,JY,JH,INPTZC
130   FORMAT('0',30X,'OBSERVED DATA ENDS',2X,
     1 I2.2,'/',I2.2,'/',I4,'-',I2.2,A4)
C
140   IOPNUM=IOLDOP
      OPNAME(1)=OLDOPN(1)
      OPNAME(2)=OLDOPN(2)
C
      RETURN
C
      END
