#!/bin/bash
if [ ${#AWIPS_HOME} = 0 ]
then
        path_to_script=`readlink -f $0`
		export AWIPS_HOME=$(dirname $(dirname $(dirname $(dirname  $path_to_script))))
fi

# $1=failed site
SITE_CAPS=`echo ${1}|tr [a-z] [A-Z]`

. ${AWIPS_HOME}/GFESuite/ServiceBackup/configuration/svcbu.env

# Create the log file
logdir=${IFPS_LOG}/`date +%Y%m%d`
logfil=svcbu_createGFEStartScript`date +%H%M`
logfile=${logdir}/${logfil}

[ ! -d ${logdir} ] && (umask 000;mkdir ${logdir})
touch ${logdir}/${logfil}
exec 1>${logdir}/${logfil} 2>&1


LAUNCH_SCRIPT=${AWIPS_HOME}/GFESuite/ServiceBackup/.launch_cave.sh

log_msg "Creating GFE launch script for ${SITE_CAPS} at ${LAUNCH_SCRIPT}"
log_msg "CAVE location: ${CAVE_LAUNCH_SCRIPT}"

if [ $SVCBU_USER -eq 1 ] && [ "$SVCBU_USER_ID" = "" ]; then
  log_msg "You do not have a user id configured for ServiceBackup"
  log_msg "GFE will start with your regular user id"
fi

echo "#!/bin/bash">${LAUNCH_SCRIPT}
if [ $SVCBU_USER -eq 1 ] && [ "$SVCBU_USER_ID" != "" ]; then
  echo "${CAVE_LAUNCH_SCRIPT} -site ${SITE_CAPS} -u $SVCBU_USER_ID -perspective GFE -server ec:9581/services" >> ${LAUNCH_SCRIPT}
else
  echo "${CAVE_LAUNCH_SCRIPT} -site ${SITE_CAPS} -perspective GFE -server ec:9581/services" >> ${LAUNCH_SCRIPT}
fi

chmod +x ${LAUNCH_SCRIPT}

SITE_LOWER=`echo ${AW_SITE_IDENTIFIER}|tr [a-z] [A-Z]`
echo  $SITE_LOWER > $SCRIPTS_DIR/siteID.txt

log_msg "GFE launch script created for ${SITE_CAPS}"
