#!/bin/bash
if [ ${#AWIPS_HOME} = 0 ]
then
        path_to_script=`readlink -f $0`
		export AWIPS_HOME=$(dirname $(dirname $(dirname $(dirname  $path_to_script))))
fi

LOCK_DIR=/awips2/GFESuite/ServiceBackup/locks
cd $LOCK_DIR
for fileName in `ls`
do
	if [[ $fileName != *svcbuMode ]]
	then
	  	rm -f $fileName		
	fi
done

