#!/bin/bash
if [ ${#AWIPS_HOME} = 0 ]
then
        path_to_script=`readlink -f $0`
		export AWIPS_HOME=$(dirname $(dirname $(dirname $(dirname  $path_to_script))))
fi

. ${AWIPS_HOME}/GFESuite/ServiceBackup/configuration/svcbu.env

# Create the log file
configureLogging "ndfd_mhs" ${AW_SITE_IDENTIFIER}

# Retrieve the name of the site from the tar file.
ndfd_msg=${1}
if [ -a ${ndfd_msg} ]
then
    echo "Received NDFD banner message"
    mv ${ndfd_msg} ${GFESUITE_HOME}/ndfdMsg
    msg=`cat ${GFESUITE_HOME}/ndfdMsg`

    # Generate a GFE message saying an alert was received from NDFD.
    ${GFESUITE_BIN}/sendGfeMessage -h ${SVCBU_HOST} -p ${CDSPORT} -c NDFD -m "$msg" -s
else
    echo "Unable to locate the NDFD banner message"
    exit 1
fi

#clean-up.
rm -f ${GFESUITE_HOME}/ndfdMsg

#ALL well, send a msg and get out of here
echo "$msg successfully sent to GFE."
exit 0
