#!/bin/bash
if [ ${#AWIPS_HOME} = 0 ]
then
        path_to_script=`readlink -f $0`
		export AWIPS_HOME=$(dirname $(dirname $(dirname $(dirname  $path_to_script))))
fi

. ${AWIPS_HOME}/GFESuite/ServiceBackup/configuration/svcbu.env

# Create the log file
logdir=${IFPS_LOG}/`date +%Y%m%d`
logfil=ndfd_mhs`date +%H%M`
logfile=${logdir}/${logfil}

[ ! -d ${logdir} ] && (umask 000;mkdir ${logdir})
touch ${logdir}/${logfil}
exec 1>${logdir}/${logfil} 2>&1

log_msg 0

# Retrieve the name of the site from the tar file.
ndfd_msg=${1}
if [ -a ${ndfd_msg} ]
then
    log_msg "Received NDFD banner message"
    mv ${ndfd_msg} ${GFESUITE_HOME}/ndfdMsg
    msg=`cat ${GFESUITE_HOME}/ndfdMsg`

    # Generate a GFE message saying an alert was received from NDFD.
    ${GFESUITE_BIN}/sendGfeMessage -h ${SVCBU_HOST} -p ${CDSPORT} -c NDFD -m "$msg" -s
else
    log_msg "Unable to locate the NDFD banner message"
    log_msg 100
    exit 1
fi

log_msg 50

#clean-up.
rm -f ${GFESUITE_HOME}/ndfdMsg
log_msg 100
#ALL well, send a msg and get out of here
log_msg "$msg successfully sent to GFE."
exit 0

