#!/bin/bash
if [ ${#AWIPS_HOME} = 0 ]
then
        path_to_script=`readlink -f $0`
		export AWIPS_HOME=$(dirname $(dirname $(dirname $(dirname  $path_to_script))))
fi

. ${AWIPS_HOME}/GFESuite/ServiceBackup/configuration/svcbu.env

# Create the log file
logdir=${IFPS_LOG}/`date +%Y%m%d`
logfil=svcbu_receive_configuration_`date +%H%M`
logfile=${logdir}/${logfil}
[ ! -d ${logdir} ] && (umask 000;mkdir ${logdir})
touch ${logdir}/${logfil}
exec 1>${logdir}/${logfil} 2>&1

# Check the status of the lock file to see if we are OK to proceed
if [ ! -f ${LOCK_DIR}/importConfiguration ];
then
	log_msg Lock file not present for importing configuration!  Cannot continue!
	touch ${LOCK_DIR}/svcbuerr
    rm -f ${LOCK_DIR}/importConfiguration
    rm -f ${LOCK_DIR}/trMode
    log_msg 100
	exit 1
fi

USER=$(whoami)
if [ $USER = "root" ]
then 
	log_msg "Running script as root"
elif [ $USER = "awips" ]
then
	log_msg "Running script as user awips"
else
	log_msg "Script must be run as user root or awips"
	touch ${LOCK_DIR}/svcbuerr
    rm -f ${LOCK_DIR}/importConfiguration
    rm -f ${LOCK_DIR}/trMode
    log_msg 100
	exit 1
fi

. $SCRIPTS_DIR/proc_receive_config ${1}
exitValue=($?)
if [ $exitValue -ne 0 ]; then
    log_msg "Receive configuration returned with errors..."
    touch ${LOCK_DIR}/svcbuerr
    rm -f ${LOCK_DIR}/importConfiguration
    rm -f ${LOCK_DIR}/trMode
    log_msg 100
    exit 1
fi
exit 0

