#!/bin/bash

##
# This software was developed and / or modified by Raytheon Company,
# pursuant to Contract DG133W-05-CQ-1067 with the US Government.
# 
# U.S. EXPORT CONTROLLED TECHNICAL DATA
# This software product contains export-restricted data whose
# export/transfer/disclosure is restricted by U.S. law. Dissemination
# to non-U.S. persons whether in the United States or abroad requires
# an export license or other authorization.
# 
# Contractor Name:        Raytheon Company
# Contractor Address:     6825 Pine Street, Suite 340
#                         Mail Stop B8
#                         Omaha, NE 68106
#                         402.291.0100
# 
# See the AWIPS II Master Rights File ("Master Rights File.pdf") for
# further licensing information.
#
##

##
#
# SOFTWARE HISTORY
# Date         Ticket#    Engineer    Description
# ------------ ---------- ----------- --------------------------
# Feb 09, 2015  #4103     dgilling    Refactored to support multiple svcbu 
#                                     sites.
#
##


if [ ${#AWIPS_HOME} = 0 ]
then
        path_to_script=`readlink -f $0`
		export AWIPS_HOME=$(dirname $(dirname $(dirname $(dirname  $path_to_script))))
fi

# $1 = Failed site
# $2 = enable/disable troubleshooting mode

if [ $# -ne 2 ]
then
   echo "Incorrect number of arguments\nCorrect usage: request_configuration failed_site trMode"
   exit 1
fi

. ${AWIPS_HOME}/GFESuite/ServiceBackup/configuration/svcbu.env
source ${AWIPS_HOME}/GFESuite/ServiceBackup/scripts/serviceBackupUtil.sh

FAILED_SITE="${1}"

# Create the log file
configureLogging "svcbu_request_configuration" ${FAILED_SITE}

# Check the status of the lock file to see if we are OK to proceed
import_lock_file=$(getLockFile "importConfiguration" ${FAILED_SITE})
import_lock_status=$(isOperationInProgress "importConfiguration" ${FAILED_SITE})
trmode_lock_file=$(getLockFile "trMode" ${FAILED_SITE})
if [[ "${import_lock_status}" = "true" ]]
then
	echo "Cannot import configuration for ${FAILED_SITE}.  Import configuration process already in progress!"
	exit 1
fi

echo "IN_PROGRESS" > ${import_lock_file}
if [ $2 -eq 1 ]; then
	echo "IN_PROGRESS" > ${trmode_lock_file}
	echo "You are in troubleshooting mode - no ISC/VTEC will be available"
fi

echo "Contacting central server to get configuration for ${FAILED_SITE}"

if [ -n "${SVCBU_WMO_HEADER}" ]; then
    msgSendOutput=$($MSG_SEND_COMMAND -a "DEFAULTNCF" -i ${SVCBU_WMO_HEADER} -s ${FAILED_SITE}2 -c 21 -p 1)
    exitValue=$?
    if [ $exitValue -ne 0 ]; then
		echo "msg_send failed while requesting configuration for ${FAILED_SITE}`date`"
		echo "FAILED" > ${import_lock_file}
		echo "FAILED" > ${trmode_lock_file}
		echo "msg_send FAILED with exit value $exitValue and the following error: $msgSendOutput"
		exit 1
    fi
else
    msgSendOutput=$($MSG_SEND_COMMAND -a "DEFAULTNCF" -s ${FAILED_SITE}2 -c 21 -p 1)
    exitValue=$?
    if [ $exitValue -ne 0 ]; then
		echo "msg_send failed while requesting configuration for ${FAILED_SITE}`date`"
		echo "FAILED" > ${import_lock_file}
		echo "FAILED" > ${trmode_lock_file}
		echo "msg_send FAILED with exit value $exitValue and the following error: $msgSendOutput"
		exit 1
    fi
fi

echo "Successfully sent message. MESSAGE ID: $msgSendOutput"
echo "Waiting to receive configuration..."
exit 0
