<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<project default="create_run_jar" name="Create Runnable Jar for Project awips.dependency.evaluator with Jar-in-Jar Loader">
	<property name="dest.dir" value="/tmp" />
	<property name="eclipse.dir" value="/opt/eclipse" />
	<property name="baseline.dir" value="/common/bkowal/git/Baseline-4759/AWIPS2_baseline/javaUtilities" />
	
	<path id="ECLIPSE.classpath">
		<pathelement path="${eclipse.dir}/plugins/org.eclipse.osgi_3.19.0.v20240213-1246.jar" />
		<pathelement path="${eclipse.dir}/plugins/org.eclipse.pde.core_3.18.0.v20240215-1456.jar" />
		<pathelement path="${eclipse.dir}/plugins/org.eclipse.core.resources_3.20.100.v20240209-1706.jar" />
		<pathelement path="${eclipse.dir}/plugins/org.eclipse.debug.core_3.21.300.v20240109-1022.jar" />
		<pathelement path="${eclipse.dir}/plugins/org.eclipse.equinox.common_3.19.0.v20240214-0846.jar" />
		<pathelement path="${eclipse.dir}/plugins/org.eclipse.core.runtime_3.31.0.v20240215-1631.jar" />
		<pathelement path="${eclipse.dir}/plugins/org.eclipse.core.jobs_3.15.200.v20231214-1526.jar" />
		<pathelement path="${eclipse.dir}/plugins/org.eclipse.equinox.registry_3.12.0.v20240213-1057.jar" />
		<pathelement path="${eclipse.dir}/plugins/org.eclipse.equinox.preferences_3.11.0.v20240210-0844.jar" />
		<pathelement path="${eclipse.dir}/plugins/org.eclipse.core.contenttype_3.9.300.v20231218-0909.jar" />
		<pathelement path="${eclipse.dir}/plugins/org.eclipse.equinox.app_1.7.0.v20240213-1427.jar" />
		<pathelement path="${eclipse.dir}/plugins/org.eclipse.jdt.launching_3.21.100.v20240214-1729.jar" />
		<pathelement path="${eclipse.dir}/plugins/org.eclipse.jdt.core_3.37.0.v20240215-1452.jar" />
	</path>
	
	<target name="compile">
		<javac destdir="${baseline.dir}/awips.dependency.evaluator/bin" 
			srcdir="${baseline.dir}/awips.dependency.evaluator/src" 
			executable="/awips2/java/bin/javac" fork="true"
			classpathref="ECLIPSE.classpath">
			
			<include name="**/*.java" />
			
		</javac>
	</target>
	
	<target name="retrieve-jar-zip">
		<mkdir dir="${baseline.dir}/awips.dependency.evaluator/lib" />
		<unzip src="${eclipse.dir}/plugins/org.eclipse.jdt.ui_3.32.0.v20240215-0312.jar"
			dest="${baseline.dir}/awips.dependency.evaluator/lib" 
			overwrite="true">
			
        	<patternset>
        		<include name="jar-in-jar-loader.zip" />
        	</patternset>			
			
		</unzip>
	</target>
	
    <!--this file was created by Eclipse Runnable JAR Export Wizard-->
    <!--ANT 1.7 is required                                        -->
    <target name="create_run_jar" depends="compile, retrieve-jar-zip">
        <jar destfile="${dest.dir}/AwipsDependencyEvaluator.jar">
            <manifest>
                <attribute name="Main-Class" value="org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader"/>
                <attribute name="Rsrc-Main-Class" value="awips.dependency.evaluator.Main"/>
                <attribute name="Class-Path" value="."/>
                <attribute name="Rsrc-Class-Path" value="./ org.eclipse.osgi_3.19.0.v20240213-1246.jar org.eclipse.pde.core_3.18.0.v20240215-1456.jar org.eclipse.core.resources_3.20.100.v20240209-1706.jar org.eclipse.debug.core_3.21.300.v20240109-1022.jar org.eclipse.equinox.common_3.19.0.v20240214-0846.jar org.eclipse.core.runtime_3.31.0.v20240215-1631.jar org.eclipse.core.jobs_3.15.200.v20231214-1526.jar org.eclipse.equinox.registry_3.12.0.v20240213-1057.jar org.eclipse.equinox.preferences_3.11.0.v20240210-0844.jar org.eclipse.core.contenttype_3.9.300.v20231218-0909.jar org.eclipse.equinox.app_1.7.0.v20240213-1427.jar org.eclipse.jdt.launching_3.21.100.v20240214-1729.jar org.eclipse.jdt.core_3.37.0.v20240215-1452.jar"/>
            </manifest>
            <zipfileset src="${baseline.dir}/awips.dependency.evaluator/lib/jar-in-jar-loader.zip"/>
            <zipfileset dir="${eclipse.dir}/plugins" includes="org.eclipse.osgi_3.19.0.v20240213-1246.jar"/>
            <zipfileset dir="${eclipse.dir}/plugins" includes="org.eclipse.pde.core_3.18.0.v20240215-1456.jar"/>
            <zipfileset dir="${eclipse.dir}/plugins" includes="org.eclipse.core.resources_3.20.100.v20240209-1706.jar"/>
            <zipfileset dir="${eclipse.dir}/plugins" includes="org.eclipse.debug.core_3.21.300.v20240109-1022.jar"/>
            <zipfileset dir="${eclipse.dir}/plugins" includes="org.eclipse.equinox.common_3.19.0.v20240214-0846.jar"/>
            <zipfileset dir="${eclipse.dir}/plugins" includes="org.eclipse.core.runtime_3.31.0.v20240215-1631.jar"/>
            <zipfileset dir="${eclipse.dir}/plugins" includes="org.eclipse.core.jobs_3.15.200.v20231214-1526.jar"/>
            <zipfileset dir="${eclipse.dir}/plugins" includes="org.eclipse.equinox.registry_3.12.0.v20240213-1057.jar"/>
            <zipfileset dir="${eclipse.dir}/plugins" includes="org.eclipse.equinox.preferences_3.11.0.v20240210-0844.jar"/>
            <zipfileset dir="${eclipse.dir}/plugins" includes="org.eclipse.core.contenttype_3.9.300.v20231218-0909.jar"/>
            <zipfileset dir="${eclipse.dir}/plugins" includes="org.eclipse.equinox.app_1.7.0.v20240213-1427.jar"/>
            <zipfileset dir="${eclipse.dir}/plugins" includes="org.eclipse.jdt.launching_3.21.100.v20240214-1729.jar"/>
            <zipfileset dir="${eclipse.dir}/plugins" includes="org.eclipse.jdt.core_3.37.0.v20240215-1452.jar"/>
            <fileset dir="${baseline.dir}/awips.dependency.evaluator/bin"/>
        </jar>
    </target>
</project>
