# If "true", text products will be disseminated using the Java version
# of handleOUP, which is called OUPDisseminator, and is newer.
#
# If "false" or any other value, text products will be disseminated by
# calling the old handleOUP.py script.
#
# If this property is not present, the default is "true".
handleoup.java.enable=true
