//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.25 at 04:38:22 PM EDT 
//


package gov.noaa.nws.ncep.viz.ui.locator.resource;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}LocatorName"/>
 *         &lt;element ref="{}ShapefileName" minOccurs="0"/>
 *         &lt;element ref="{}ShapefilePath" minOccurs="0"/>
 *         &lt;element ref="{}AttributeName" minOccurs="0"/>
 *         &lt;element ref="{}AttributeID" minOccurs="0"/>
 *         &lt;element ref="{}UsedInSeek" minOccurs="0"/>
 *         &lt;element ref="{}StateID" minOccurs="0"/>
 *         &lt;element ref="{}DisplayOptions" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "locatorName",
    "shapefileName",
    "shapefilePath",
    "attributeName",
    "attributeID",
    "usedInSeek",
    "stateID",
    "displayOptions"
})
@XmlRootElement(name = "Locator")
public class Locator {

    @XmlElement(name = "LocatorName", required = true)
    protected String locatorName;
    @XmlElement(name = "ShapefileName")
    protected String shapefileName;
    @XmlElement(name = "ShapefilePath")
    protected String shapefilePath;
    @XmlElement(name = "AttributeName")
    protected String attributeName;
    @XmlElement(name = "AttributeID")
    protected String attributeID;
    @XmlElement(name = "UsedInSeek")
    protected Boolean usedInSeek;
    @XmlElement(name = "StateID")
    protected String stateID;
    @XmlElement(name = "DisplayOptions")
    protected DisplayOptions displayOptions;

    /**
     * Gets the value of the locatorName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocatorName() {
        return locatorName;
    }

    /**
     * Sets the value of the locatorName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocatorName(String value) {
        this.locatorName = value;
    }

    /**
     * Gets the value of the shapefileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShapefileName() {
        return shapefileName;
    }

    /**
     * Sets the value of the shapefileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShapefileName(String value) {
        this.shapefileName = value;
    }

    /**
     * Gets the value of the shapefilePath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShapefilePath() {
        return shapefilePath;
    }

    /**
     * Sets the value of the shapefilePath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShapefilePath(String value) {
        this.shapefilePath = value;
    }

    /**
     * Gets the value of the attributeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttributeName() {
        return attributeName;
    }

    /**
     * Sets the value of the attributeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttributeName(String value) {
        this.attributeName = value;
    }

    /**
     * Gets the value of the attributeID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttributeID() {
        return attributeID;
    }

    /**
     * Sets the value of the attributeID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttributeID(String value) {
        this.attributeID = value;
    }

    /**
     * Gets the value of the usedInSeek property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUsedInSeek() {
        return usedInSeek;
    }

    /**
     * Sets the value of the usedInSeek property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUsedInSeek(Boolean value) {
        this.usedInSeek = value;
    }

    /**
     * Gets the value of the stateID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStateID() {
        return stateID;
    }

    /**
     * Sets the value of the stateID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStateID(String value) {
        this.stateID = value;
    }
    
    /**
     * Gets the value of the displayOptions property.
     * 
     * @return
     *     possible object is
     *     {@link DisplayOptions }
     *     
     */
    public DisplayOptions getDisplayOptions() {
        return displayOptions;
    }

    /**
     * Sets the value of the displayOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link DisplayOptions }
     *     
     */
    public void setDisplayOptions(DisplayOptions value) {
        this.displayOptions = value;
    }

    public Locator copy() {
    	Locator loc = new Locator();
    	
    	loc.setDisplayOptions(displayOptions.copy());
    	loc.setAttributeID(attributeID);
    	loc.setUsedInSeek(usedInSeek);
    	loc.setAttributeName(attributeName);
    	loc.setLocatorName(locatorName);
    	loc.setShapefileName(shapefileName);
    	loc.setShapefilePath(shapefilePath);
    	
    	return loc;
    	
    }
}
