#!/bin/bash
#-----------------------------------------------------------------------#
# Options                                                               #
#                                                                       #
# edex [status]                                                         #
#       'edex' defaults to 'edex status', notifying the user whether    #
#       edex services are on, and which ones.                           #
#                                                                       #
# edex start/stop                                                       #
#       Controls stopping / starting all edex standalone services:      #
#               edex_postgres                                           #
#               edex_camel                                              #
#               httpd-pypies                                            #
#               qpidd                                                   #
#               edex_ldm                                                #
#                                                                       #
# edex log [ingest|request|grib|text|satellite|radar|ldm]               #
#       Monitors the current day's requested log. Defaults to ingest.   #
#                                                                       #
# edex setup                                                            #
#   Adds server IP and hostname to EDEX config files if they don't      #
#   contain the correct setting already (requires user prompt)          #
#                                                                       #
#-----------------------------------------------------------------------#
# ChangeLog                                                             #
# 07/2011 M.James/Unidata	Created					#
# 10/2015 M.James/Unidata	Log files fixed; purge check added	#
# 11/2015 M.James/Unidata	Added CAVE user count as "edex users"	#
# 10/2016 M.James/Unidata	No longer need to edit ldmd.conf	#
# 06/2017 M.James/Unidata       Restart					#
# 09/2017 M.James/Unidata       Rudimentary remote db password control, #
#                               remove pg_hba.conf edits                #
# 01/2018 M.James/Unidata       Added qpid-stat wrapper as edex qpid    #
#-----------------------------------------------------------------------#
. /etc/profile.d/awips2.sh
# directories definitions
EDEX_PATH=/awips2/edex
DATA_PATH=/awips2/data
LOG_PATH=${EDEX_PATH}/logs
EDEX_ENV_FILE=${EDEX_PATH}/bin/setup.env

# valid options
options=( 'status' 'start' 'stop' 'log' 'setup' 'purge' 'password' 'users' 'qpid' 'restart')
nopts=${options[@]}

# find interface for routeable IPs
usedev=`netstat -rn | egrep "^0.0.0.0" | awk '{print $8}'| head -1`
IP=`/sbin/ifconfig $usedev | grep -v "inet6" | grep "inet" | awk '{ print $2 }' | cut -d: -f2`

# truncate
IP_CIDR="${IP%.*}"
editFiles=($EDEX_ENV_FILE)
boolFiles=(true)
editFuncs=(edit_setup)

YMD=`date '+%Y%m%d'`

args=("$@")

# functions
edex_status() { # report back edex server on/off status
   echo ''
   echo '[edex status]'

   if [ -d "/awips2/data" ]; then
      # CHECK POSTGRES
      postgres_prc=`ps aux | grep postgresql | grep -v grep | grep -v java |awk '{ print $11 }'`
      if [ -z $postgres_prc ]; then
         echo ' postgres    :: not running'
      else
         postgresPid=`ps aux | grep postgresql\/bin\/postmaster | grep -v grep | awk '{ print $2 }'`
         echo ' postgres    :: running :: pid '$postgresPid''
      fi
   fi

   if [ -d "/awips2/httpd_pypies" ]; then
       # CHECK PYPIES
       pypies_prc=`ps aux | grep httpd_pypies | grep -v grep | head -1 | awk '{ print $11 }'`
       if [ -z $pypies_prc ]; then
          echo ' pypies      :: not running'
       else
          pypiesPid=`ps aux | grep awips2\/httpd_pypies\/usr\/sbin\/httpd | grep -v grep | head -1 | awk '{ print $2 }'`
          echo ' pypies      :: running :: pid '$pypiesPid''
       fi
   fi

   # CHECK QPID
   qpid_prc=`ps aux | grep qpid- | grep -v grep | head -1 | awk '{ print $11 }'`
   if [ -z $qpid_prc ]; then
      echo ' qpid        :: not running'
   else
      qpidPid=`ps aux | grep qpid- | grep -v grep | head -1 | awk '{ print $2 }'`
      echo ' qpid        :: running :: pid '$qpidPid''
   fi

   # CHECK EDEX
   edex_ingest_ps=`ps aux | grep edex.run.mode=ingest | grep -v edex.run.mode=ingestGrib | awk '{ print $15 }'`
   if [ -z $edex_ingest_ps ]; then
      echo ' EDEXingest  :: not running'
   else
      edex_ingest_pid=`ps aux | grep edex.run.mode=ingest | grep -v edex.run.mode=ingestGrib | awk '{ print $2 }'`
      echo ' EDEXingest  :: running :: pid '$edex_ingest_pid''
   fi
   edex_ingestGrib_ps=`ps aux | grep edex.run.mode=ingestGrib | awk '{ print $15 }'`
   if [ -z $edex_ingestGrib_ps ]; then
      echo ' EDEXgrib    :: not running'
   else
      edex_ingestGrib_pid=`ps aux | grep edex.run.mode=ingestGrib | awk '{ print $2 }'`
      echo ' EDEXgrib    :: running :: pid '$edex_ingestGrib_pid''
   fi
   edex_request_ps=`ps aux | grep edex.run.mode=request | awk '{ print $15 }'`
   if [ -z $edex_request_ps ]; then
      echo ' EDEXrequest :: not running'   
   else
      edex_request_pid=`ps aux | grep edex.run.mode=request | awk '{ print $2 }'`
      echo ' EDEXrequest :: running :: pid '$edex_request_pid''
   fi

   if [ -d "/awips2/ldm" ]; then
      ldmd_ps=`ps aux | grep ldmd | grep -v "grep ldmd" | head -1 | awk '{ print $2 }'`
      if [ -z $ldmd_ps ]; then
          echo ' ldmadmin    :: not running'
      else
          ldmd_pid=`ps aux | grep ldmd | grep -v "grep ldmd" | head -1 | awk '{ print $2 }'`
          echo ' ldmadmin    :: running :: pid '$ldmd_pid''
      fi
   fi

   echo ''
}

tail_log() {
   if [ -e $LOG_FILE ]; then
      echo ' :: Viewing '${LOG_FILE}'. Press CTRL+C to exit'
      echo ''
      tail --follow=name ${LOG_FILE}
   else 
      echo ' :: '$LOG_FILE' not found'
      echo ' :: Check '$LOG_PATH
      echo ''
   fi
}

edex_log() { # display todays log, default to ingest
   echo '[edex] EDEX Log Viewer'
   echo ''
   # LDM log
   if [ "${args[1]}" == 'ldm' ]; then
      LOG_FILE=/awips2/ldm/logs/ldmd.log
      tail_log
      exit;
   fi
   # EDEX ingestGrib log
   if [ "${args[1]}" == 'grib' ]; then
                LOG_FILE=${LOG_PATH}/edex-ingestGrib-${YMD}.log
      tail_log
      exit;
   fi
   # EDEX request log
   if [ "${args[1]}" == 'request' ]; then   
      LOG_FILE=${LOG_PATH}/edex-request-${YMD}.log
      tail_log
      exit;
   fi
   # Radar
   if [ "${args[1]}" == 'radar' ]; then
      YMD=`date -u '+%Y%m%d'`
      LOG_FILE=${LOG_PATH}/edex-ingest-radar-${YMD}.log
      tail_log
      exit;
   fi
   # Satellite
   if [ "${args[1]}" == 'satellite' ]; then
      YMD=`date -u '+%Y%m%d'`
      LOG_FILE=${LOG_PATH}/edex-ingest-satellite-${YMD}.log
      tail_log
      exit;
   fi
   # Text
   if [ "${args[1]}" == 'text' ]; then
      YMD=`date -u '+%Y%m%d'`
      LOG_FILE=${LOG_PATH}/edex-ingest-text-${YMD}.log
      tail_log
      exit;
   fi
   # OHD
   if [ "${args[1]}" == 'ohd' ]; then
      YMD=`date -u '+%Y%m%d'`
      LOG_FILE=${LOG_PATH}/edex-ingest-ohd-${YMD}.log
      tail_log
      exit;
   fi
   # EDEX ingest log (default)
   LOG_FILE=${LOG_PATH}/edex-ingest-${YMD}.log
   if [ "${args[1]}" == 'ingest' ]; then
      tail_log
      exit;
   fi   
   if [ -z ${args[1]} ]; then
      echo ' :: No log specified - Defaulting to ingest log'
      tail_log
      exit;
   else
      echo 'Unknown argument' ${args[1]}' -  Viewing ingest log'
      tail_log
      exit;
   fi
}

# See /awips2/edex/bin/setup.env
edit_setup() {
   sed -i.setup_$YMD 's/external/'$HOSTNAME'/g' $EDEX_ENV_FILE
   echo '[edit] '$HOSTNAME' added to '$EDEX_ENV_FILE
   echo '       File backed up to '$EDEX_ENV_FILE'.setup_'$YMD
}

edex_edits() {
   for index in ${!editFiles[*]}; do
      if ${boolFiles[$index]}; then
         ${editFuncs[$index]}
      fi
   done
   echo '[done]'
   exit;
}

edex_ipexit() { # abandon ip editing, post msg to guide manual edits
   for index in ${!editFiles[*]}; do
                if ${boolFiles[$index]}; then
                        editCom+='\t'${editFiles[$index]}'\n'
                fi
        done
   echo -e '[edex] Exiting EDEX IP Setup'
   echo -e ''
   echo -e ' You may need to MANUALLY EDIT the following files'
   echo -e '\n'$editCom
   echo -e ' for EDEX to work properly. \n'
}

edex_setup() { # setup IP subnet and domains for EDEX, prompt user for confirm
   echo ''
   # run services on system startup
   if [ -f "/etc/init.d/edex_postgres" ]; then
      chkconfig edex_postgres --add
      chkconfig edex_postgres on --level 35
   fi
   
   if [ -f "/etc/init.d/httpd-pypies" ]; then
      chkconfig httpd-pypies --add
      chkconfig httpd-pypies on --level 35
   fi

   chkconfig qpidd --add
   chkconfig qpidd on --level 35

   chkconfig edex_camel --add
   chkconfig edex_camel on --level 35

   echo '[edex] EDEX IP and Hostname Setup'
   # check files exist
   continue=true
   for index in ${!editFiles[*]}; do
      if [[ ! -f ${editFiles[$index]} ]]; then
         echo '[Error] ** '${editFiles[$index]}' not found.'
         continue=false
      fi
   done
   if ! $continue; then
      echo 'Exiting'
      exit;
   fi
   continue=false

   # ldm regutil
   if [ -d "/awips2/ldm" ]; then
      #echo '[edit] ldm regutil...'
      su - awips -c 'regutil -s '$HOSTNAME' /hostname'
   fi
   echo ''
   edex_edits
   if [ $continue=true ]; then
      echo ' EDEX correctly configured'
   fi
   echo ''
}

edex_start() { # start all edex services
   edex_cleanup
   if [ ! -d /awips2/tmp ]; then
      mkdir -p /awips2/tmp
   fi
   chown -R awips:fxalpha /awips2/data_store /awips2/tmp

   if [ -f "/etc/init.d/edex_postgres" ]; then
      su -c "service edex_postgres start"
   fi
   if [ -f "/etc/init.d/httpd-pypies" ]; then
      su -c "service httpd-pypies start"
   fi
   su -c "service qpidd start"
   edex_purge_reset
   if [ "${args[1]}" == 'base' ]; then
      printf "#!/bin/bash\nexport SERVICES=( 'request' 'ingest' 'ingestGrib' )\n" > /etc/init.d/edexServiceList
      su -c "service edex_camel start"
   elif [ "${args[1]}" == 'ingest' ]; then
      printf "#!/bin/bash\nexport SERVICES=( 'ingest' 'ingestGrib' )\n" > /etc/init.d/edexServiceList
      su -c "service edex_camel start"
      su -c "service edex_ldm start"
   elif [ "${args[1]}" == 'database' ]; then
      printf "#!/bin/bash\nexport SERVICES=( 'request' )\n" > /etc/init.d/edexServiceList
      su -c "service edex_camel start"
   elif [ "${args[1]}" != 'dev' ]; then
      printf "#!/bin/bash\nexport SERVICES=( 'request' 'ingest' 'ingestGrib' )\n" > /etc/init.d/edexServiceList
      su -c "service edex_camel start"
      su -c "service edex_ldm start"
   fi
}

edex_stop() { # stop all edex services
   if [ "${args[1]}" != 'dev' ]; then
      su -c "service edex_camel stop"
      su -c "service edex_ldm stop"
   fi
   su -c "service qpidd stop"
   if [ -f "/etc/init.d/httpd-pypies" ]; then
     su -c "service httpd-pypies stop"
   fi
   if [ -f "/etc/init.d/edex_postgres" ]; then
      su -c "service edex_postgres stop"
   fi
   edex_status;
}

edex_restart() {
   su -c "service edex_camel restart"
   edex_status;
}

edex_password() {
   if [ ! -z "${args[1]}" ]; then
      sed -i 's/<property name="connection.password">awips<\/property>/<property name="connection.password">'${args[1]}'<\/property>/' /awips2/edex/conf/db/hibernateConfig/*.hibernate.cfg.xml
   else
      echo "no password given - usage: edex password <newpassword>"
      exit;
   fi
}

edex_purge() {
   if [ "${args[1]}" == 'reset' ]; then
      edex_purge_reset
      echo ' EDEX purge has been reset'
      exit;
   else
      purgeCheck=`su - awips -c 'psql metadata -c "select plugin from purgejobs where failedcount = 3;"'`
      if [[ ${#purgeCheck} > 26 ]]; then
          su - awips -c 'psql metadata -c "select plugin from purgejobs where failedcount = 3;"'
      fi
      exit;
   fi
}
edex_purge_reset() {
        su - awips -c 'psql metadata -c "update purgejobs set failedcount = 0;"' >& /dev/null
}
edex_qpid() {
   su - awips -c "qpid-stat -q -S msgIn"
}
edex_cleanup() {
   rm -rf /awips2/qpid/edexMessageStore/edex/
}
edex_users(){
        if [ "${args[1]}" != '' ]; then
                YMD=${args[1]}
        fi
        userList=$(cat ${LOG_PATH}/edex-request-thriftSrv-${YMD}.log |grep ":CAVE:"|cut -d "[" -f 3| cut -d ":" -f 1|grep -v pluginName|sort | uniq)
        echo ""
        echo " -- EDEX Users ${YMD} --"
        echo "$userList"
        echo ""
}

edex_options() { # print out options for this programs
   echo ''
   echo '     edex (status|start|stop|setup|log|purge|qpid|users)'
   echo ''
}

edex_invalid() {
   echo ''
   echo "     Invalid option: '"${args[0]}"' not understood"
   edex_options
}

check_input() { # check input against accepted options
   found=false
   for i in "${options[@]}"
   do
      if [[ "${args[0]}" == $i ]]; then
         edexcmd='edex_'${args[0]}
         found=true
      fi
   done
   if [[ "$found" == 'false' ]]; then
      if [[ -z ${args[0]} ]]; then
         # if no input specified, default to status
         edex_status
         edex_options
      else
         # if bad command
         edex_invalid
      fi
   else
      $edexcmd
   fi
}

# check input - first/only program run
#
check_input

exit;



