# $Id: Makefile,v 1.1.18.1 2005/06/22 22:52:30 steve Exp $

include ../macros.make

TAG_SRCS	= *.c *.h \
	../misc/*.c ../misc/*.h \
	../ulog/*.c ../ulog/*.h \
	../protocol/*.c ../protocol/*.h \
	../server/*.c ../server/*.h \
	../pq/*.c ../pq/*.h
PROGRAM	= notifyme
include ../simple_program.make
include ../rules.make
include depends
