##
# This software was developed and / or modified by Raytheon Company,
# pursuant to Contract DG133W-05-CQ-1067 with the US Government.
# 
# U.S. EXPORT CONTROLLED TECHNICAL DATA
# This software product contains export-restricted data whose
# export/transfer/disclosure is restricted by U.S. law. Dissemination
# to non-U.S. persons whether in the United States or abroad requires
# an export license or other authorization.
# 
# Contractor Name:        Raytheon Company
# Contractor Address:     6825 Pine Street, Suite 340
#                         Mail Stop B8
#                         Omaha, NE 68106
#                         402.291.0100
# 
# See the AWIPS II Master Rights File ("Master Rights File.pdf") for
# further licensing information.
##
periodVer1= """Definition["Period_1_version"] = 1"""
periodVer2= """TextProduct.Definition["Period_1_version"] = 2"""


scripts = [
   {
     'commentary':'"""\nPrecip:LE\nSky:LE1\nNonPrecip:LE2\nPoP:LE\nConsolidation:noLE\n\n0-6 : Sky : 50 : [\'AboveElev\']\n0-6 : Sky : 87 : [\'BelowElev\']\n6-12 : Sky : 50 : [\'AboveElev\']\n6-12 : Sky : 50 : [\'BelowElev\']\n0-6 : PoP : 40 : [\'AboveElev\']\n0-6 : PoP : 80 : [\'BelowElev\']\n6-12 : PoP : 40 : [\'AboveElev\']\n6-12 : PoP : 80 : [\'BelowElev\']\n0-6 : Wx : NoWx : \'all\'\n0-6 : Wx : SChc:SW:-:<NoVis>:^Patchy:F:<NoInten>:<NoVis>:^Lkly:RW:-:<NoVis>:^Chc:RW:-:<NoVis>: : [\'AboveElev\']\n0-6 : Wx : SChc:SW:-:<NoVis>:^Patchy:F:<NoInten>:<NoVis>: : [\'BelowElev\']\n6-12 : Wx : NoWx : \'all\'\n6-12 : Wx : Patchy:F:<NoInten>:<NoVis>: : [\'AboveElev\']\n6-12 : Wx : Areas:F:<NoInten>:<NoVis>:^Lkly:RW:-:<NoVis>:^Chc:RW:-:<NoVis>: : [\'BelowElev\']\n"""',
     'createGrids':[
       ('Fcst', 'Sky', 'SCALAR', 0, 6, 50, ['AboveElev']),
       ('Fcst', 'Sky', 'SCALAR', 0, 6, 87, ['BelowElev']),
       ('Fcst', 'Sky', 'SCALAR', 6, 12, 50, ['AboveElev']),
       ('Fcst', 'Sky', 'SCALAR', 6, 12, 50, ['BelowElev']),
       ('Fcst', 'PoP', 'SCALAR', 0, 6, 40, ['AboveElev']),
       ('Fcst', 'PoP', 'SCALAR', 0, 6, 80, ['BelowElev']),
       ('Fcst', 'PoP', 'SCALAR', 6, 12, 40, ['AboveElev']),
       ('Fcst', 'PoP', 'SCALAR', 6, 12, 80, ['BelowElev']),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'NoWx', 'all'),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'SChc:SW:-:<NoVis>:^Patchy:F:<NoInten>:<NoVis>:^Lkly:RW:-:<NoVis>:^Chc:RW:-:<NoVis>:', ['AboveElev']),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'SChc:SW:-:<NoVis>:^Patchy:F:<NoInten>:<NoVis>:', ['BelowElev']),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'NoWx', 'all'),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'Patchy:F:<NoInten>:<NoVis>:', ['AboveElev']),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'Areas:F:<NoInten>:<NoVis>:^Lkly:RW:-:<NoVis>:^Chc:RW:-:<NoVis>:', ['BelowElev']),
     ],
     'name':'SPW_1_1756',
     'checkStrings':[
           "WINDWARD...MOSTLY SUNNY...SHOWERS LIKELY AND SLIGHT CHANCE OF SNOW SHOWERS IN THE MORNING...PATCHY FOG THROUGH THE DAY...CHANCE OF PRECIPITATION 40 PERCENT.",
           "LEEWARD...MOSTLY CLOUDY WITH SLIGHT CHANCE OF SNOW SHOWERS IN THE MORNING...THEN SHOWERS LIKELY IN THE AFTERNOON...PATCHY FOG IN THE MORNING...THEN AREAS OF FOG IN THE AFTERNOON...CHANCE OF PRECIPITATION 70 PERCENT.", 
     ],
   },
   {
     'commentary':'"""\nPrecip:noLE\nSky:LE1\nNonPrecip:null\nPoP:LE1\nConsolidation:noLE\n\n0-6 : Sky : 50 : [\'AboveElev\']\n0-6 : Sky : 87 : [\'BelowElev\']\n6-12 : Sky : 50 : [\'AboveElev\']\n6-12 : Sky : 50 : [\'BelowElev\']\n0-6 : PoP : 40 : [\'AboveElev\']\n0-6 : PoP : 80 : [\'BelowElev\']\n6-12 : PoP : 40 : [\'AboveElev\']\n6-12 : PoP : 40 : [\'BelowElev\']\n0-6 : Wx : NoWx : \'all\'\n0-6 : Wx : SChc:SW:-:<NoVis>:^Chc:RW:-:<NoVis>: : [\'AboveElev\']\n0-6 : Wx : SChc:SW:-:<NoVis>:^Chc:RW:-:<NoVis>: : [\'BelowElev\']\n6-12 : Wx : NoWx : \'all\'\n6-12 : Wx : Chc:RW:-:<NoVis>: : [\'AboveElev\']\n6-12 : Wx : Chc:RW:-:<NoVis>: : [\'BelowElev\']\n"""',
     'createGrids':[
       ('Fcst', 'Sky', 'SCALAR', 0, 6, 50, ['AboveElev']),
       ('Fcst', 'Sky', 'SCALAR', 0, 6, 87, ['BelowElev']),
       ('Fcst', 'Sky', 'SCALAR', 6, 12, 50, ['AboveElev']),
       ('Fcst', 'Sky', 'SCALAR', 6, 12, 50, ['BelowElev']),
       ('Fcst', 'PoP', 'SCALAR', 0, 6, 40, ['AboveElev']),
       ('Fcst', 'PoP', 'SCALAR', 0, 6, 80, ['BelowElev']),
       ('Fcst', 'PoP', 'SCALAR', 6, 12, 40, ['AboveElev']),
       ('Fcst', 'PoP', 'SCALAR', 6, 12, 40, ['BelowElev']),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'NoWx', 'all'),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'SChc:SW:-:<NoVis>:^Chc:RW:-:<NoVis>:', ['AboveElev']),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'SChc:SW:-:<NoVis>:^Chc:RW:-:<NoVis>:', ['BelowElev']),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'NoWx', 'all'),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'Chc:RW:-:<NoVis>:', ['AboveElev']),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'Chc:RW:-:<NoVis>:', ['BelowElev']),
     ],
     'name':'SPW_1_166',
     'checkStrings':[
          "WINDWARD...MOSTLY SUNNY...CHANCE OF SHOWERS AND SLIGHT CHANCE OF SNOW SHOWERS IN THE MORNING...THEN CHANCE OF SHOWERS IN THE AFTERNOON.",
          "LEEWARD...MOSTLY CLOUDY WITH CHANCE OF SHOWERS AND SLIGHT CHANCE OF SNOW SHOWERS IN THE MORNING...THEN MOSTLY SUNNY WITH CHANCE OF SHOWERS IN THE AFTERNOON.",
          "CHANCE OF PRECIPITATION 40 PERCENT.",
     ],
   },
   {
     'commentary':'"""\nPrecip:noLE\nSky:LE1\nNonPrecip:null\nPoP:LE2\nConsolidation:LE\n\n0-6 : Sky : 50 : [\'AboveElev\']\n0-6 : Sky : 87 : [\'BelowElev\']\n6-12 : Sky : 50 : [\'AboveElev\']\n6-12 : Sky : 50 : [\'BelowElev\']\n0-6 : PoP : 40 : [\'AboveElev\']\n0-6 : PoP : 40 : [\'BelowElev\']\n6-12 : PoP : 40 : [\'AboveElev\']\n6-12 : PoP : 80 : [\'BelowElev\']\n0-6 : Wx : NoWx : \'all\'\n0-6 : Wx : SChc:SW:-:<NoVis>:^Chc:RW:-:<NoVis>: : [\'AboveElev\']\n0-6 : Wx : Lkly:SW:-:<NoVis>:^Chc:RW:-:<NoVis>: : [\'BelowElev\']\n6-12 : Wx : NoWx : \'all\'\n6-12 : Wx : Chc:RW:-:<NoVis>: : [\'AboveElev\']\n6-12 : Wx : Chc:RW:-:<NoVis>: : [\'BelowElev\']\n"""',
     'createGrids':[
       ('Fcst', 'Sky', 'SCALAR', 0, 6, 50, ['AboveElev']),
       ('Fcst', 'Sky', 'SCALAR', 0, 6, 87, ['BelowElev']),
       ('Fcst', 'Sky', 'SCALAR', 6, 12, 50, ['AboveElev']),
       ('Fcst', 'Sky', 'SCALAR', 6, 12, 50, ['BelowElev']),
       ('Fcst', 'PoP', 'SCALAR', 0, 6, 40, ['AboveElev']),
       ('Fcst', 'PoP', 'SCALAR', 0, 6, 40, ['BelowElev']),
       ('Fcst', 'PoP', 'SCALAR', 6, 12, 40, ['AboveElev']),
       ('Fcst', 'PoP', 'SCALAR', 6, 12, 80, ['BelowElev']),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'NoWx', 'all'),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'SChc:SW:-:<NoVis>:^Chc:RW:-:<NoVis>:', ['AboveElev']),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'Lkly:SW:-:<NoVis>:^Chc:RW:-:<NoVis>:', ['BelowElev']),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'NoWx', 'all'),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'Chc:RW:-:<NoVis>:', ['AboveElev']),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'Chc:RW:-:<NoVis>:', ['BelowElev']),
     ],
     'name':'SPW_1_175',
     'checkStrings':[
            "WINDWARD...MOSTLY SUNNY...CHANCE OF SHOWERS AND SLIGHT CHANCE OF SNOW SHOWERS IN THE MORNING...THEN CHANCE OF SHOWERS IN THE AFTERNOON.",
            "LEEWARD...MOSTLY CLOUDY WITH SNOW SHOWERS LIKELY AND CHANCE OF SHOWERS IN THE MORNING...THEN MOSTLY SUNNY WITH CHANCE OF SHOWERS IN THE AFTERNOON.",
            "CHANCE OF PRECIPITATION 70 PERCENT.",
            ],
   },
   {
     'commentary':'"""\nPrecip:noLE\nSky:LE1\nNonPrecip:LE\nPoP:LE2\nConsolidation:LE2\n\n0-6 : Sky : 50 : [\'AboveElev\']\n0-6 : Sky : 87 : [\'BelowElev\']\n6-12 : Sky : 50 : [\'AboveElev\']\n6-12 : Sky : 50 : [\'BelowElev\']\n0-6 : PoP : 40 : [\'AboveElev\']\n0-6 : PoP : 40 : [\'BelowElev\']\n6-12 : PoP : 40 : [\'AboveElev\']\n6-12 : PoP : 80 : [\'BelowElev\']\n0-6 : Wx : NoWx : \'all\'\n0-6 : Wx : Patchy:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>: : [\'AboveElev\']\n0-6 : Wx : Areas:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>: : [\'BelowElev\']\n6-12 : Wx : NoWx : \'all\'\n6-12 : Wx : SChc:SW:-:<NoVis>:^Patchy:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>: : [\'AboveElev\']\n6-12 : Wx : Lkly:SW:-:<NoVis>:^Areas:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>: : [\'BelowElev\']\n"""',
     'createGrids':[
       ('Fcst', 'Sky', 'SCALAR', 0, 6, 50, ['AboveElev']),
       ('Fcst', 'Sky', 'SCALAR', 0, 6, 87, ['BelowElev']),
       ('Fcst', 'Sky', 'SCALAR', 6, 12, 50, ['AboveElev']),
       ('Fcst', 'Sky', 'SCALAR', 6, 12, 50, ['BelowElev']),
       ('Fcst', 'PoP', 'SCALAR', 0, 6, 40, ['AboveElev']),
       ('Fcst', 'PoP', 'SCALAR', 0, 6, 40, ['BelowElev']),
       ('Fcst', 'PoP', 'SCALAR', 6, 12, 40, ['AboveElev']),
       ('Fcst', 'PoP', 'SCALAR', 6, 12, 80, ['BelowElev']),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'NoWx', 'all'),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'Patchy:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>:', ['AboveElev']),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'Areas:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>:', ['BelowElev']),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'NoWx', 'all'),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'SChc:SW:-:<NoVis>:^Patchy:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>:', ['AboveElev']),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'Lkly:SW:-:<NoVis>:^Areas:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>:', ['BelowElev']),
     ],
     'name':'SPW_1_193',
     'checkStrings':[
         "WINDWARD...MOSTLY SUNNY...CHANCE OF SHOWERS IN THE MORNING...THEN CHANCE OF SHOWERS AND SLIGHT CHANCE OF SNOW SHOWERS IN THE AFTERNOON...PATCHY FOG THROUGH THE DAY.",
         "LEEWARD...MOSTLY CLOUDY WITH CHANCE OF SHOWERS IN THE MORNING...THEN MOSTLY SUNNY WITH SNOW SHOWERS LIKELY AND CHANCE OF SHOWERS IN THE AFTERNOON...AREAS OF FOG THROUGH THE DAY.", 
         "CHANCE OF PRECIPITATION 70 PERCENT.",
     ],
   },
   {
     'commentary':'"""\nPrecip:noLE\nSky:LE1\nNonPrecip:LE\nPoP:LE\nConsolidation:noLE\n\n0-6 : Sky : 50 : [\'AboveElev\']\n0-6 : Sky : 87 : [\'BelowElev\']\n6-12 : Sky : 50 : [\'AboveElev\']\n6-12 : Sky : 50 : [\'BelowElev\']\n0-6 : PoP : 40 : [\'AboveElev\']\n0-6 : PoP : 80 : [\'BelowElev\']\n6-12 : PoP : 40 : [\'AboveElev\']\n6-12 : PoP : 80 : [\'BelowElev\']\n0-6 : Wx : NoWx : \'all\'\n0-6 : Wx : SChc:SW:-:<NoVis>:^Patchy:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>: : [\'AboveElev\']\n0-6 : Wx : SChc:SW:-:<NoVis>:^Areas:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>: : [\'BelowElev\']\n6-12 : Wx : NoWx : \'all\'\n6-12 : Wx : Patchy:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>: : [\'AboveElev\']\n6-12 : Wx : Areas:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>: : [\'BelowElev\']\n"""',
     'createGrids':[
       ('Fcst', 'Sky', 'SCALAR', 0, 6, 50, ['AboveElev']),
       ('Fcst', 'Sky', 'SCALAR', 0, 6, 87, ['BelowElev']),
       ('Fcst', 'Sky', 'SCALAR', 6, 12, 50, ['AboveElev']),
       ('Fcst', 'Sky', 'SCALAR', 6, 12, 50, ['BelowElev']),
       ('Fcst', 'PoP', 'SCALAR', 0, 6, 40, ['AboveElev']),
       ('Fcst', 'PoP', 'SCALAR', 0, 6, 80, ['BelowElev']),
       ('Fcst', 'PoP', 'SCALAR', 6, 12, 40, ['AboveElev']),
       ('Fcst', 'PoP', 'SCALAR', 6, 12, 80, ['BelowElev']),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'NoWx', 'all'),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'SChc:SW:-:<NoVis>:^Patchy:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>:', ['AboveElev']),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'SChc:SW:-:<NoVis>:^Areas:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>:', ['BelowElev']),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'NoWx', 'all'),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'Patchy:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>:', ['AboveElev']),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'Areas:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>:', ['BelowElev']),
     ],
     'name':'SPW_1_196',
     'checkStrings':[
          "WINDWARD...MOSTLY SUNNY...CHANCE OF SHOWERS AND SLIGHT CHANCE OF SNOW SHOWERS IN THE MORNING...THEN CHANCE OF SHOWERS IN THE AFTERNOON...PATCHY FOG THROUGH THE DAY...CHANCE OF PRECIPITATION 40 PERCENT.",
          "LEEWARD...MOSTLY CLOUDY WITH CHANCE OF SHOWERS AND SLIGHT CHANCE OF SNOW SHOWERS IN THE MORNING...THEN MOSTLY SUNNY WITH CHANCE OF SHOWERS IN THE AFTERNOON...AREAS OF FOG THROUGH THE DAY...CHANCE OF PRECIPITATION 50 PERCENT.",
     ],
   },
   {
     'commentary':'"""\nPrecip:noLE\nSky:LE2\nNonPrecip:null\nPoP:LE1\nConsolidation:null\n\n0-6 : Sky : 50 : [\'AboveElev\']\n0-6 : Sky : 50 : [\'BelowElev\']\n6-12 : Sky : 50 : [\'AboveElev\']\n6-12 : Sky : 87 : [\'BelowElev\']\n0-6 : PoP : 40 : [\'AboveElev\']\n0-6 : PoP : 80 : [\'BelowElev\']\n6-12 : PoP : 40 : [\'AboveElev\']\n6-12 : PoP : 40 : [\'BelowElev\']\n0-6 : Wx : NoWx : \'all\'\n0-6 : Wx : Chc:RW:-:<NoVis>: : [\'AboveElev\']\n0-6 : Wx : Chc:RW:-:<NoVis>: : [\'BelowElev\']\n6-12 : Wx : NoWx : \'all\'\n6-12 : Wx : Chc:RW:-:<NoVis>: : [\'AboveElev\']\n6-12 : Wx : Chc:RW:-:<NoVis>: : [\'BelowElev\']\n"""',
     'createGrids':[
       ('Fcst', 'Sky', 'SCALAR', 0, 6, 50, ['AboveElev']),
       ('Fcst', 'Sky', 'SCALAR', 0, 6, 50, ['BelowElev']),
       ('Fcst', 'Sky', 'SCALAR', 6, 12, 50, ['AboveElev']),
       ('Fcst', 'Sky', 'SCALAR', 6, 12, 87, ['BelowElev']),
       ('Fcst', 'PoP', 'SCALAR', 0, 6, 40, ['AboveElev']),
       ('Fcst', 'PoP', 'SCALAR', 0, 6, 80, ['BelowElev']),
       ('Fcst', 'PoP', 'SCALAR', 6, 12, 40, ['AboveElev']),
       ('Fcst', 'PoP', 'SCALAR', 6, 12, 40, ['BelowElev']),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'NoWx', 'all'),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'Chc:RW:-:<NoVis>:', ['AboveElev']),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'Chc:RW:-:<NoVis>:', ['BelowElev']),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'NoWx', 'all'),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'Chc:RW:-:<NoVis>:', ['AboveElev']),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'Chc:RW:-:<NoVis>:', ['BelowElev']),
     ],
     'name':'SPW_1_269',
     'checkStrings':[
          "LEEWARD...MOSTLY SUNNY IN THE MORNING THEN BECOMING MOSTLY CLOUDY...A 40 PERCENT CHANCE OF SHOWERS.",
          "WINDWARD...MOSTLY SUNNY WITH A 40 PERCENT CHANCE OF SHOWERS.",
     ],
   },
   {
     'commentary':'"""\nPrecip:noLE\nSky:LE2\nNonPrecip:null\nPoP:LE2\nConsolidation:LE1\n\n0-6 : Sky : 50 : [\'AboveElev\']\n0-6 : Sky : 50 : [\'BelowElev\']\n6-12 : Sky : 50 : [\'AboveElev\']\n6-12 : Sky : 87 : [\'BelowElev\']\n0-6 : PoP : 40 : [\'AboveElev\']\n0-6 : PoP : 40 : [\'BelowElev\']\n6-12 : PoP : 40 : [\'AboveElev\']\n6-12 : PoP : 80 : [\'BelowElev\']\n0-6 : Wx : NoWx : \'all\'\n0-6 : Wx : SChc:SW:-:<NoVis>:^Chc:RW:-:<NoVis>: : [\'AboveElev\']\n0-6 : Wx : Lkly:SW:-:<NoVis>:^Chc:RW:-:<NoVis>: : [\'BelowElev\']\n6-12 : Wx : NoWx : \'all\'\n6-12 : Wx : Chc:RW:-:<NoVis>: : [\'AboveElev\']\n6-12 : Wx : Chc:RW:-:<NoVis>: : [\'BelowElev\']\n"""',
     'createGrids':[
       ('Fcst', 'Sky', 'SCALAR', 0, 6, 50, ['AboveElev']),
       ('Fcst', 'Sky', 'SCALAR', 0, 6, 50, ['BelowElev']),
       ('Fcst', 'Sky', 'SCALAR', 6, 12, 50, ['AboveElev']),
       ('Fcst', 'Sky', 'SCALAR', 6, 12, 87, ['BelowElev']),
       ('Fcst', 'PoP', 'SCALAR', 0, 6, 40, ['AboveElev']),
       ('Fcst', 'PoP', 'SCALAR', 0, 6, 40, ['BelowElev']),
       ('Fcst', 'PoP', 'SCALAR', 6, 12, 40, ['AboveElev']),
       ('Fcst', 'PoP', 'SCALAR', 6, 12, 80, ['BelowElev']),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'NoWx', 'all'),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'SChc:SW:-:<NoVis>:^Chc:RW:-:<NoVis>:', ['AboveElev']),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'Lkly:SW:-:<NoVis>:^Chc:RW:-:<NoVis>:', ['BelowElev']),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'NoWx', 'all'),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'Chc:RW:-:<NoVis>:', ['AboveElev']),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'Chc:RW:-:<NoVis>:', ['BelowElev']),
     ],
     'name':'SPW_1_272',
     'checkStrings':[
          "WINDWARD...MOSTLY SUNNY...CHANCE OF SHOWERS AND SLIGHT CHANCE OF SNOW SHOWERS IN THE MORNING...THEN CHANCE OF SHOWERS IN THE AFTERNOON.",
          "LEEWARD...MOSTLY SUNNY WITH SNOW SHOWERS LIKELY AND CHANCE OF SHOWERS IN THE MORNING...THEN MOSTLY CLOUDY WITH CHANCE OF SHOWERS IN THE AFTERNOON.",
          "CHANCE OF PRECIPITATION 70 PERCENT.",
     ],
   },
   {
     'commentary':'"""\nPrecip:noLE\nSky:LE2\nNonPrecip:LE\nPoP:LE2\nConsolidation:LE2\n\n0-6 : Sky : 50 : [\'AboveElev\']\n0-6 : Sky : 50 : [\'BelowElev\']\n6-12 : Sky : 50 : [\'AboveElev\']\n6-12 : Sky : 87 : [\'BelowElev\']\n0-6 : PoP : 40 : [\'AboveElev\']\n0-6 : PoP : 40 : [\'BelowElev\']\n6-12 : PoP : 40 : [\'AboveElev\']\n6-12 : PoP : 80 : [\'BelowElev\']\n0-6 : Wx : NoWx : \'all\'\n0-6 : Wx : Patchy:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>: : [\'AboveElev\']\n0-6 : Wx : Areas:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>: : [\'BelowElev\']\n6-12 : Wx : NoWx : \'all\'\n6-12 : Wx : SChc:SW:-:<NoVis>:^Patchy:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>: : [\'AboveElev\']\n6-12 : Wx : Lkly:SW:-:<NoVis>:^Areas:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>: : [\'BelowElev\']\n"""',
     'createGrids':[
       ('Fcst', 'Sky', 'SCALAR', 0, 6, 50, ['AboveElev']),
       ('Fcst', 'Sky', 'SCALAR', 0, 6, 50, ['BelowElev']),
       ('Fcst', 'Sky', 'SCALAR', 6, 12, 50, ['AboveElev']),
       ('Fcst', 'Sky', 'SCALAR', 6, 12, 87, ['BelowElev']),
       ('Fcst', 'PoP', 'SCALAR', 0, 6, 40, ['AboveElev']),
       ('Fcst', 'PoP', 'SCALAR', 0, 6, 40, ['BelowElev']),
       ('Fcst', 'PoP', 'SCALAR', 6, 12, 40, ['AboveElev']),
       ('Fcst', 'PoP', 'SCALAR', 6, 12, 80, ['BelowElev']),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'NoWx', 'all'),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'Patchy:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>:', ['AboveElev']),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'Areas:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>:', ['BelowElev']),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'NoWx', 'all'),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'SChc:SW:-:<NoVis>:^Patchy:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>:', ['AboveElev']),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'Lkly:SW:-:<NoVis>:^Areas:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>:', ['BelowElev']),
     ],
     'name':'SPW_1_293',
     'checkStrings':[
          "WINDWARD...MOSTLY SUNNY...CHANCE OF SHOWERS IN THE MORNING...THEN CHANCE OF SHOWERS AND SLIGHT CHANCE OF SNOW SHOWERS IN THE AFTERNOON...PATCHY FOG THROUGH THE DAY.", 
          "LEEWARD...MOSTLY SUNNY WITH CHANCE OF SHOWERS IN THE MORNING...THEN MOSTLY CLOUDY WITH SNOW SHOWERS LIKELY AND CHANCE OF SHOWERS IN THE AFTERNOON...AREAS OF FOG THROUGH THE DAY.",
          "CHANCE OF PRECIPITATION 70 PERCENT.",
     ],
   },
   {
     'commentary':'"""\nPrecip:noLE\nSky:LE\nNonPrecip:null\nPoP:LE1\nConsolidation:LE\n\n0-6 : Sky : 50 : [\'AboveElev\']\n0-6 : Sky : 87 : [\'BelowElev\']\n6-12 : Sky : 50 : [\'AboveElev\']\n6-12 : Sky : 87 : [\'BelowElev\']\n0-6 : PoP : 40 : [\'AboveElev\']\n0-6 : PoP : 80 : [\'BelowElev\']\n6-12 : PoP : 40 : [\'AboveElev\']\n6-12 : PoP : 40 : [\'BelowElev\']\n0-6 : Wx : NoWx : \'all\'\n0-6 : Wx : SChc:SW:-:<NoVis>:^Chc:RW:-:<NoVis>: : [\'AboveElev\']\n0-6 : Wx : Lkly:SW:-:<NoVis>:^Chc:RW:-:<NoVis>: : [\'BelowElev\']\n6-12 : Wx : NoWx : \'all\'\n6-12 : Wx : Chc:RW:-:<NoVis>: : [\'AboveElev\']\n6-12 : Wx : Chc:RW:-:<NoVis>: : [\'BelowElev\']\n"""',
     'createGrids':[
       ('Fcst', 'Sky', 'SCALAR', 0, 6, 50, ['AboveElev']),
       ('Fcst', 'Sky', 'SCALAR', 0, 6, 87, ['BelowElev']),
       ('Fcst', 'Sky', 'SCALAR', 6, 12, 50, ['AboveElev']),
       ('Fcst', 'Sky', 'SCALAR', 6, 12, 87, ['BelowElev']),
       ('Fcst', 'PoP', 'SCALAR', 0, 6, 40, ['AboveElev']),
       ('Fcst', 'PoP', 'SCALAR', 0, 6, 80, ['BelowElev']),
       ('Fcst', 'PoP', 'SCALAR', 6, 12, 40, ['AboveElev']),
       ('Fcst', 'PoP', 'SCALAR', 6, 12, 40, ['BelowElev']),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'NoWx', 'all'),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'SChc:SW:-:<NoVis>:^Chc:RW:-:<NoVis>:', ['AboveElev']),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'Lkly:SW:-:<NoVis>:^Chc:RW:-:<NoVis>:', ['BelowElev']),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'NoWx', 'all'),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'Chc:RW:-:<NoVis>:', ['AboveElev']),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'Chc:RW:-:<NoVis>:', ['BelowElev']),
     ],
     'name':'SPW_1_370',
     'checkStrings':[
         "WINDWARD...MOSTLY SUNNY...CHANCE OF SHOWERS AND SLIGHT CHANCE OF SNOW SHOWERS IN THE MORNING.",
         "LEEWARD...MOSTLY CLOUDY...SNOW SHOWERS LIKELY AND CHANCE OF SHOWERS IN THE MORNING.",
         "CHANCE OF SHOWERS IN THE AFTERNOON.",
         "CHANCE OF PRECIPITATION 70 PERCENT.",
     ],
   },
   {
     'commentary':'"""\nPrecip:LE1\nSky:noLE\nNonPrecip:noLE\nPoP:noLE\nConsolidation:null\n\n0-6 : Sky : 50 : [\'AboveElev\']\n0-6 : Sky : 50 : [\'BelowElev\']\n6-12 : Sky : 50 : [\'AboveElev\']\n6-12 : Sky : 50 : [\'BelowElev\']\n0-6 : PoP : 40 : [\'AboveElev\']\n0-6 : PoP : 40 : [\'BelowElev\']\n6-12 : PoP : 40 : [\'AboveElev\']\n6-12 : PoP : 40 : [\'BelowElev\']\n0-6 : Wx : NoWx : \'all\'\n0-6 : Wx : Patchy:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>: : [\'AboveElev\']\n0-6 : Wx : Patchy:F:<NoInten>:<NoVis>:^Lkly:RW:-:<NoVis>: : [\'BelowElev\']\n6-12 : Wx : NoWx : \'all\'\n6-12 : Wx : Patchy:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>: : [\'AboveElev\']\n6-12 : Wx : Patchy:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>: : [\'BelowElev\']\nNOTE:  The Pop is missing for Leeward because the data is set up so there\nis a local effect for SPW but not for PoP.  This should not be the case\nin practice."""',
     'createGrids':[
       ('Fcst', 'Sky', 'SCALAR', 0, 6, 50, ['AboveElev']),
       ('Fcst', 'Sky', 'SCALAR', 0, 6, 50, ['BelowElev']),
       ('Fcst', 'Sky', 'SCALAR', 6, 12, 50, ['AboveElev']),
       ('Fcst', 'Sky', 'SCALAR', 6, 12, 50, ['BelowElev']),
       ('Fcst', 'PoP', 'SCALAR', 0, 6, 40, ['AboveElev']),
       ('Fcst', 'PoP', 'SCALAR', 0, 6, 40, ['BelowElev']),
       ('Fcst', 'PoP', 'SCALAR', 6, 12, 40, ['AboveElev']),
       ('Fcst', 'PoP', 'SCALAR', 6, 12, 40, ['BelowElev']),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'NoWx', 'all'),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'Patchy:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>:', ['AboveElev']),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'Patchy:F:<NoInten>:<NoVis>:^Lkly:RW:-:<NoVis>:', ['BelowElev']),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'NoWx', 'all'),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'Patchy:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>:', ['AboveElev']),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'Patchy:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>:', ['BelowElev']),
     ],
     'name':'SPW_1_404',
     'checkStrings':[
         "MOSTLY SUNNY.",
         "WINDWARD...A 40 PERCENT CHANCE OF SHOWERS.",
         "LEEWARD...SHOWERS LIKELY IN THE MORNING...THEN CHANCE OF SHOWERS IN THE AFTERNOON.",
         "PATCHY FOG THROUGH THE DAY.",
         ],
   },
   {
     'commentary':'"""\nPrecip:LE1\nSky:noLE\nNonPrecip:LE\nPoP:LE1\nConsolidation:LE2\n\n0-6 : Sky : 50 : [\'AboveElev\']\n0-6 : Sky : 50 : [\'BelowElev\']\n6-12 : Sky : 50 : [\'AboveElev\']\n6-12 : Sky : 50 : [\'BelowElev\']\n0-6 : PoP : 40 : [\'AboveElev\']\n0-6 : PoP : 80 : [\'BelowElev\']\n6-12 : PoP : 40 : [\'AboveElev\']\n6-12 : PoP : 40 : [\'BelowElev\']\n0-6 : Wx : NoWx : \'all\'\n0-6 : Wx : Patchy:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>: : [\'AboveElev\']\n0-6 : Wx : Areas:F:<NoInten>:<NoVis>:^Lkly:RW:-:<NoVis>: : [\'BelowElev\']\n6-12 : Wx : NoWx : \'all\'\n6-12 : Wx : SChc:SW:-:<NoVis>:^Patchy:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>: : [\'AboveElev\']\n6-12 : Wx : Lkly:SW:-:<NoVis>:^Areas:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>: : [\'BelowElev\']\n"""',
     'createGrids':[
       ('Fcst', 'Sky', 'SCALAR', 0, 6, 50, ['AboveElev']),
       ('Fcst', 'Sky', 'SCALAR', 0, 6, 50, ['BelowElev']),
       ('Fcst', 'Sky', 'SCALAR', 6, 12, 50, ['AboveElev']),
       ('Fcst', 'Sky', 'SCALAR', 6, 12, 50, ['BelowElev']),
       ('Fcst', 'PoP', 'SCALAR', 0, 6, 40, ['AboveElev']),
       ('Fcst', 'PoP', 'SCALAR', 0, 6, 80, ['BelowElev']),
       ('Fcst', 'PoP', 'SCALAR', 6, 12, 40, ['AboveElev']),
       ('Fcst', 'PoP', 'SCALAR', 6, 12, 40, ['BelowElev']),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'NoWx', 'all'),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'Patchy:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>:', ['AboveElev']),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'Areas:F:<NoInten>:<NoVis>:^Lkly:RW:-:<NoVis>:', ['BelowElev']),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'NoWx', 'all'),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'SChc:SW:-:<NoVis>:^Patchy:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>:', ['AboveElev']),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'Lkly:SW:-:<NoVis>:^Areas:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>:', ['BelowElev']),
     ],
     'name':'SPW_1_488',
     'checkStrings':[
          "WINDWARD...CHANCE OF SHOWERS IN THE MORNING...THEN CHANCE OF SHOWERS AND SLIGHT CHANCE OF SNOW SHOWERS IN THE AFTERNOON...PATCHY FOG THROUGH THE DAY.",
          "LEEWARD...SHOWERS LIKELY IN THE MORNING...THEN SNOW SHOWERS LIKELY AND CHANCE OF SHOWERS IN THE AFTERNOON...AREAS OF FOG THROUGH THE DAY.",
          "CHANCE OF PRECIPITATION 70 PERCENT.",
          ],
   },
   {
     'commentary':'"""\nPrecip:LE1\nSky:LE1\nNonPrecip:LE1\nPoP:noLE\nConsolidation:LE1\n\n0-6 : Sky : 50 : [\'AboveElev\']\n0-6 : Sky : 87 : [\'BelowElev\']\n6-12 : Sky : 50 : [\'AboveElev\']\n6-12 : Sky : 50 : [\'BelowElev\']\n0-6 : PoP : 40 : [\'AboveElev\']\n0-6 : PoP : 40 : [\'BelowElev\']\n6-12 : PoP : 40 : [\'AboveElev\']\n6-12 : PoP : 40 : [\'BelowElev\']\n0-6 : Wx : NoWx : \'all\'\n0-6 : Wx : SChc:SW:-:<NoVis>:^Patchy:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>: : [\'AboveElev\']\n0-6 : Wx : Lkly:SW:-:<NoVis>:^Areas:F:<NoInten>:<NoVis>:^Lkly:RW:-:<NoVis>: : [\'BelowElev\']\n6-12 : Wx : NoWx : \'all\'\n6-12 : Wx : Patchy:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>: : [\'AboveElev\']\n6-12 : Wx : Patchy:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>: : [\'BelowElev\']\n"""',
     'createGrids':[
       ('Fcst', 'Sky', 'SCALAR', 0, 6, 50, ['AboveElev']),
       ('Fcst', 'Sky', 'SCALAR', 0, 6, 87, ['BelowElev']),
       ('Fcst', 'Sky', 'SCALAR', 6, 12, 50, ['AboveElev']),
       ('Fcst', 'Sky', 'SCALAR', 6, 12, 50, ['BelowElev']),
       ('Fcst', 'PoP', 'SCALAR', 0, 6, 40, ['AboveElev']),
       ('Fcst', 'PoP', 'SCALAR', 0, 6, 40, ['BelowElev']),
       ('Fcst', 'PoP', 'SCALAR', 6, 12, 40, ['AboveElev']),
       ('Fcst', 'PoP', 'SCALAR', 6, 12, 40, ['BelowElev']),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'NoWx', 'all'),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'SChc:SW:-:<NoVis>:^Patchy:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>:', ['AboveElev']),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'Lkly:SW:-:<NoVis>:^Areas:F:<NoInten>:<NoVis>:^Lkly:RW:-:<NoVis>:', ['BelowElev']),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'NoWx', 'all'),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'Patchy:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>:', ['AboveElev']),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'Patchy:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>:', ['BelowElev']),
     ],
     'name':'SPW_1_522',
     'checkStrings':[
         "WINDWARD...MOSTLY SUNNY...CHANCE OF SHOWERS AND SLIGHT CHANCE OF SNOW SHOWERS IN THE MORNING...THEN CHANCE OF SHOWERS IN THE AFTERNOON...PATCHY FOG THROUGH THE DAY.", 
         "LEEWARD...MOSTLY CLOUDY WITH SHOWERS AND SNOW SHOWERS LIKELY IN THE MORNING...THEN MOSTLY SUNNY WITH CHANCE OF SHOWERS IN THE AFTERNOON...AREAS OF FOG IN THE MORNING...THEN PATCHY FOG IN THE AFTERNOON.",
         "CHANCE OF PRECIPITATION 40 PERCENT.",
     ],
   },
   {
     'commentary':'"""\nPrecip:LE1\nSky:LE1\nNonPrecip:LE1\nPoP:LE2\nConsolidation:LE1\n\n0-6 : Sky : 50 : [\'AboveElev\']\n0-6 : Sky : 87 : [\'BelowElev\']\n6-12 : Sky : 50 : [\'AboveElev\']\n6-12 : Sky : 50 : [\'BelowElev\']\n0-6 : PoP : 40 : [\'AboveElev\']\n0-6 : PoP : 40 : [\'BelowElev\']\n6-12 : PoP : 40 : [\'AboveElev\']\n6-12 : PoP : 80 : [\'BelowElev\']\n0-6 : Wx : NoWx : \'all\'\n0-6 : Wx : SChc:SW:-:<NoVis>:^Patchy:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>: : [\'AboveElev\']\n0-6 : Wx : Lkly:SW:-:<NoVis>:^Areas:F:<NoInten>:<NoVis>:^Lkly:RW:-:<NoVis>: : [\'BelowElev\']\n6-12 : Wx : NoWx : \'all\'\n6-12 : Wx : Patchy:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>: : [\'AboveElev\']\n6-12 : Wx : Patchy:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>: : [\'BelowElev\']\n"""',
     'createGrids':[
       ('Fcst', 'Sky', 'SCALAR', 0, 6, 50, ['AboveElev']),
       ('Fcst', 'Sky', 'SCALAR', 0, 6, 87, ['BelowElev']),
       ('Fcst', 'Sky', 'SCALAR', 6, 12, 50, ['AboveElev']),
       ('Fcst', 'Sky', 'SCALAR', 6, 12, 50, ['BelowElev']),
       ('Fcst', 'PoP', 'SCALAR', 0, 6, 40, ['AboveElev']),
       ('Fcst', 'PoP', 'SCALAR', 0, 6, 40, ['BelowElev']),
       ('Fcst', 'PoP', 'SCALAR', 6, 12, 40, ['AboveElev']),
       ('Fcst', 'PoP', 'SCALAR', 6, 12, 80, ['BelowElev']),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'NoWx', 'all'),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'SChc:SW:-:<NoVis>:^Patchy:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>:', ['AboveElev']),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'Lkly:SW:-:<NoVis>:^Areas:F:<NoInten>:<NoVis>:^Lkly:RW:-:<NoVis>:', ['BelowElev']),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'NoWx', 'all'),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'Patchy:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>:', ['AboveElev']),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'Patchy:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>:', ['BelowElev']),
     ],
     'name':'SPW_1_532',
     'checkStrings':[
         "WINDWARD...MOSTLY SUNNY...CHANCE OF SHOWERS AND SLIGHT CHANCE OF SNOW SHOWERS IN THE MORNING...THEN CHANCE OF SHOWERS IN THE AFTERNOON...PATCHY FOG THROUGH THE DAY.", 
         "LEEWARD...MOSTLY CLOUDY WITH SHOWERS AND SNOW SHOWERS LIKELY IN THE MORNING...THEN MOSTLY SUNNY WITH CHANCE OF SHOWERS IN THE AFTERNOON...AREAS OF FOG IN THE MORNING...THEN PATCHY FOG IN THE AFTERNOON.",
         "CHANCE OF PRECIPITATION 70 PERCENT.",
     ],
   },
   {
     'commentary':'"""\nPrecip:LE1\nSky:LE1\nNonPrecip:LE2\nPoP:noLE\nConsolidation:null\n\n0-6 : Sky : 50 : [\'AboveElev\']\n0-6 : Sky : 87 : [\'BelowElev\']\n6-12 : Sky : 50 : [\'AboveElev\']\n6-12 : Sky : 50 : [\'BelowElev\']\n0-6 : PoP : 40 : [\'AboveElev\']\n0-6 : PoP : 40 : [\'BelowElev\']\n6-12 : PoP : 40 : [\'AboveElev\']\n6-12 : PoP : 40 : [\'BelowElev\']\n0-6 : Wx : NoWx : \'all\'\n0-6 : Wx : Patchy:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>: : [\'AboveElev\']\n0-6 : Wx : Patchy:F:<NoInten>:<NoVis>:^Lkly:RW:-:<NoVis>: : [\'BelowElev\']\n6-12 : Wx : NoWx : \'all\'\n6-12 : Wx : Patchy:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>: : [\'AboveElev\']\n6-12 : Wx : Areas:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>: : [\'BelowElev\']\nNOTE:  The Pop is missing for Leeward because the data is set up so there\nis a local effect for SPW but not for PoP.  This should not be the case\nin practice."""',
     'createGrids':[
       ('Fcst', 'Sky', 'SCALAR', 0, 6, 50, ['AboveElev']),
       ('Fcst', 'Sky', 'SCALAR', 0, 6, 87, ['BelowElev']),
       ('Fcst', 'Sky', 'SCALAR', 6, 12, 50, ['AboveElev']),
       ('Fcst', 'Sky', 'SCALAR', 6, 12, 50, ['BelowElev']),
       ('Fcst', 'PoP', 'SCALAR', 0, 6, 40, ['AboveElev']),
       ('Fcst', 'PoP', 'SCALAR', 0, 6, 40, ['BelowElev']),
       ('Fcst', 'PoP', 'SCALAR', 6, 12, 40, ['AboveElev']),
       ('Fcst', 'PoP', 'SCALAR', 6, 12, 40, ['BelowElev']),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'NoWx', 'all'),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'Patchy:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>:', ['AboveElev']),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'Patchy:F:<NoInten>:<NoVis>:^Lkly:RW:-:<NoVis>:', ['BelowElev']),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'NoWx', 'all'),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'Patchy:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>:', ['AboveElev']),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'Areas:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>:', ['BelowElev']),
     ],
     'name':'SPW_1_544',
     'checkStrings':[
         "WINDWARD...MOSTLY SUNNY WITH A 40 PERCENT CHANCE OF SHOWERS...PATCHY FOG.",
         "LEEWARD...MOSTLY CLOUDY WITH SHOWERS LIKELY IN THE MORNING...THEN MOSTLY SUNNY WITH CHANCE OF SHOWERS IN THE AFTERNOON...PATCHY FOG IN THE MORNING...THEN AREAS OF FOG IN THE AFTERNOON.",
         ],
   },
   {
     'commentary':'"""\nPrecip:LE1\nSky:LE2\nNonPrecip:LE1\nPoP:LE2\nConsolidation:LE2\n\n0-6 : Sky : 50 : [\'AboveElev\']\n0-6 : Sky : 50 : [\'BelowElev\']\n6-12 : Sky : 50 : [\'AboveElev\']\n6-12 : Sky : 87 : [\'BelowElev\']\n0-6 : PoP : 40 : [\'AboveElev\']\n0-6 : PoP : 40 : [\'BelowElev\']\n6-12 : PoP : 40 : [\'AboveElev\']\n6-12 : PoP : 80 : [\'BelowElev\']\n0-6 : Wx : NoWx : \'all\'\n0-6 : Wx : Patchy:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>: : [\'AboveElev\']\n0-6 : Wx : Areas:F:<NoInten>:<NoVis>:^Lkly:RW:-:<NoVis>: : [\'BelowElev\']\n6-12 : Wx : NoWx : \'all\'\n6-12 : Wx : SChc:SW:-:<NoVis>:^Patchy:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>: : [\'AboveElev\']\n6-12 : Wx : Lkly:SW:-:<NoVis>:^Patchy:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>: : [\'BelowElev\']\n"""',
     'createGrids':[
       ('Fcst', 'Sky', 'SCALAR', 0, 6, 50, ['AboveElev']),
       ('Fcst', 'Sky', 'SCALAR', 0, 6, 50, ['BelowElev']),
       ('Fcst', 'Sky', 'SCALAR', 6, 12, 50, ['AboveElev']),
       ('Fcst', 'Sky', 'SCALAR', 6, 12, 87, ['BelowElev']),
       ('Fcst', 'PoP', 'SCALAR', 0, 6, 40, ['AboveElev']),
       ('Fcst', 'PoP', 'SCALAR', 0, 6, 40, ['BelowElev']),
       ('Fcst', 'PoP', 'SCALAR', 6, 12, 40, ['AboveElev']),
       ('Fcst', 'PoP', 'SCALAR', 6, 12, 80, ['BelowElev']),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'NoWx', 'all'),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'Patchy:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>:', ['AboveElev']),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'Areas:F:<NoInten>:<NoVis>:^Lkly:RW:-:<NoVis>:', ['BelowElev']),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'NoWx', 'all'),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'SChc:SW:-:<NoVis>:^Patchy:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>:', ['AboveElev']),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'Lkly:SW:-:<NoVis>:^Patchy:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>:', ['BelowElev']),
     ],
     'name':'SPW_1_633',
     'checkStrings':[
           "WINDWARD...MOSTLY SUNNY...CHANCE OF SHOWERS IN THE MORNING...THEN CHANCE OF SHOWERS AND SLIGHT CHANCE OF SNOW SHOWERS IN THE AFTERNOON...PATCHY FOG THROUGH THE DAY.", 
           "LEEWARD...MOSTLY SUNNY WITH SHOWERS LIKELY IN THE MORNING...THEN MOSTLY CLOUDY WITH SNOW SHOWERS LIKELY AND CHANCE OF SHOWERS IN THE AFTERNOON...AREAS OF FOG IN THE MORNING...THEN PATCHY FOG IN THE AFTERNOON.",
           "CHANCE OF PRECIPITATION 70 PERCENT.",
     ],
   },
   {
     'commentary':'"""\nPrecip:LE2\nSky:noLE\nNonPrecip:LE1\nPoP:LE2\nConsolidation:LE2\n\n0-6 : Sky : 50 : [\'AboveElev\']\n0-6 : Sky : 50 : [\'BelowElev\']\n6-12 : Sky : 50 : [\'AboveElev\']\n6-12 : Sky : 50 : [\'BelowElev\']\n0-6 : PoP : 40 : [\'AboveElev\']\n0-6 : PoP : 40 : [\'BelowElev\']\n6-12 : PoP : 40 : [\'AboveElev\']\n6-12 : PoP : 80 : [\'BelowElev\']\n0-6 : Wx : NoWx : \'all\'\n0-6 : Wx : Patchy:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>: : [\'AboveElev\']\n0-6 : Wx : Areas:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>: : [\'BelowElev\']\n6-12 : Wx : NoWx : \'all\'\n6-12 : Wx : SChc:SW:-:<NoVis>:^Patchy:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>: : [\'AboveElev\']\n6-12 : Wx : Lkly:SW:-:<NoVis>:^Patchy:F:<NoInten>:<NoVis>:^Lkly:RW:-:<NoVis>: : [\'BelowElev\']\n"""',
     'createGrids':[
       ('Fcst', 'Sky', 'SCALAR', 0, 6, 50, ['AboveElev']),
       ('Fcst', 'Sky', 'SCALAR', 0, 6, 50, ['BelowElev']),
       ('Fcst', 'Sky', 'SCALAR', 6, 12, 50, ['AboveElev']),
       ('Fcst', 'Sky', 'SCALAR', 6, 12, 50, ['BelowElev']),
       ('Fcst', 'PoP', 'SCALAR', 0, 6, 40, ['AboveElev']),
       ('Fcst', 'PoP', 'SCALAR', 0, 6, 40, ['BelowElev']),
       ('Fcst', 'PoP', 'SCALAR', 6, 12, 40, ['AboveElev']),
       ('Fcst', 'PoP', 'SCALAR', 6, 12, 80, ['BelowElev']),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'NoWx', 'all'),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'Patchy:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>:', ['AboveElev']),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'Areas:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>:', ['BelowElev']),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'NoWx', 'all'),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'SChc:SW:-:<NoVis>:^Patchy:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>:', ['AboveElev']),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'Lkly:SW:-:<NoVis>:^Patchy:F:<NoInten>:<NoVis>:^Lkly:RW:-:<NoVis>:', ['BelowElev']),
     ],
     'name':'SPW_1_833',
     'checkStrings':[
         "CHANCE OF SHOWERS IN THE MORNING.",
         "WINDWARD...PATCHY FOG THROUGH THE DAY...CHANCE OF SHOWERS AND SLIGHT CHANCE OF SNOW SHOWERS IN THE AFTERNOON.",
         "LEEWARD...AREAS OF FOG IN THE MORNING...THEN PATCHY FOG IN THE AFTERNOON...SHOWERS AND SNOW SHOWERS LIKELY IN THE AFTERNOON.",
         "CHANCE OF PRECIPITATION 70 PERCENT",
     ],
   },
   {
     'commentary':'"""\nPrecip:LE2\nSky:noLE\nNonPrecip:null\nPoP:LE\nConsolidation:LE1\n\n0-6 : Sky : 50 : [\'AboveElev\']\n0-6 : Sky : 50 : [\'BelowElev\']\n6-12 : Sky : 50 : [\'AboveElev\']\n6-12 : Sky : 50 : [\'BelowElev\']\n0-6 : PoP : 40 : [\'AboveElev\']\n0-6 : PoP : 80 : [\'BelowElev\']\n6-12 : PoP : 40 : [\'AboveElev\']\n6-12 : PoP : 80 : [\'BelowElev\']\n0-6 : Wx : NoWx : \'all\'\n0-6 : Wx : SChc:SW:-:<NoVis>:^Chc:RW:-:<NoVis>: : [\'AboveElev\']\n0-6 : Wx : Lkly:SW:-:<NoVis>:^Chc:RW:-:<NoVis>: : [\'BelowElev\']\n6-12 : Wx : NoWx : \'all\'\n6-12 : Wx : Chc:RW:-:<NoVis>: : [\'AboveElev\']\n6-12 : Wx : Lkly:RW:-:<NoVis>: : [\'BelowElev\']\n"""',
     'createGrids':[
       ('Fcst', 'Sky', 'SCALAR', 0, 6, 50, ['AboveElev']),
       ('Fcst', 'Sky', 'SCALAR', 0, 6, 50, ['BelowElev']),
       ('Fcst', 'Sky', 'SCALAR', 6, 12, 50, ['AboveElev']),
       ('Fcst', 'Sky', 'SCALAR', 6, 12, 50, ['BelowElev']),
       ('Fcst', 'PoP', 'SCALAR', 0, 6, 40, ['AboveElev']),
       ('Fcst', 'PoP', 'SCALAR', 0, 6, 80, ['BelowElev']),
       ('Fcst', 'PoP', 'SCALAR', 6, 12, 40, ['AboveElev']),
       ('Fcst', 'PoP', 'SCALAR', 6, 12, 80, ['BelowElev']),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'NoWx', 'all'),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'SChc:SW:-:<NoVis>:^Chc:RW:-:<NoVis>:', ['AboveElev']),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'Lkly:SW:-:<NoVis>:^Chc:RW:-:<NoVis>:', ['BelowElev']),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'NoWx', 'all'),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'Chc:RW:-:<NoVis>:', ['AboveElev']),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'Lkly:RW:-:<NoVis>:', ['BelowElev']),
     ],
     'name':'SPW_1_877',
     'checkStrings':[
          "WINDWARD...CHANCE OF SHOWERS AND SLIGHT CHANCE OF SNOW SHOWERS IN THE MORNING...THEN CHANCE OF SHOWERS IN THE AFTERNOON...CHANCE OF PRECIPITATION 40 PERCENT.", 
          "LEEWARD...SNOW SHOWERS LIKELY AND CHANCE OF SHOWERS IN THE MORNING...THEN SHOWERS LIKELY IN THE AFTERNOON...CHANCE OF PRECIPITATION 70 PERCENT.",
          ],
   },
   {
     'commentary':'"""\nPrecip:LE2\nSky:noLE\nNonPrecip:LE\nPoP:noLE\nConsolidation:LE\n\n0-6 : Sky : 50 : [\'AboveElev\']\n0-6 : Sky : 50 : [\'BelowElev\']\n6-12 : Sky : 50 : [\'AboveElev\']\n6-12 : Sky : 50 : [\'BelowElev\']\n0-6 : PoP : 40 : [\'AboveElev\']\n0-6 : PoP : 40 : [\'BelowElev\']\n6-12 : PoP : 40 : [\'AboveElev\']\n6-12 : PoP : 40 : [\'BelowElev\']\n0-6 : Wx : NoWx : \'all\'\n0-6 : Wx : SChc:SW:-:<NoVis>:^Patchy:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>: : [\'AboveElev\']\n0-6 : Wx : Lkly:SW:-:<NoVis>:^Areas:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>: : [\'BelowElev\']\n6-12 : Wx : NoWx : \'all\'\n6-12 : Wx : Patchy:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>: : [\'AboveElev\']\n6-12 : Wx : Areas:F:<NoInten>:<NoVis>:^Lkly:RW:-:<NoVis>: : [\'BelowElev\']\n"""',
     'createGrids':[
       ('Fcst', 'Sky', 'SCALAR', 0, 6, 50, ['AboveElev']),
       ('Fcst', 'Sky', 'SCALAR', 0, 6, 50, ['BelowElev']),
       ('Fcst', 'Sky', 'SCALAR', 6, 12, 50, ['AboveElev']),
       ('Fcst', 'Sky', 'SCALAR', 6, 12, 50, ['BelowElev']),
       ('Fcst', 'PoP', 'SCALAR', 0, 6, 40, ['AboveElev']),
       ('Fcst', 'PoP', 'SCALAR', 0, 6, 40, ['BelowElev']),
       ('Fcst', 'PoP', 'SCALAR', 6, 12, 40, ['AboveElev']),
       ('Fcst', 'PoP', 'SCALAR', 6, 12, 40, ['BelowElev']),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'NoWx', 'all'),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'SChc:SW:-:<NoVis>:^Patchy:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>:', ['AboveElev']),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'Lkly:SW:-:<NoVis>:^Areas:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>:', ['BelowElev']),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'NoWx', 'all'),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'Patchy:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>:', ['AboveElev']),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'Areas:F:<NoInten>:<NoVis>:^Lkly:RW:-:<NoVis>:', ['BelowElev']),
     ],
     'name':'SPW_1_885',
     'checkStrings':[
          "MOSTLY SUNNY. WINDWARD...CHANCE OF SHOWERS AND SLIGHT CHANCE OF SNOW SHOWERS IN THE MORNING...THEN CHANCE OF SHOWERS IN THE AFTERNOON...PATCHY FOG THROUGH THE DAY.", 
          "LEEWARD...SNOW SHOWERS LIKELY AND CHANCE OF SHOWERS IN THE MORNING...THEN SHOWERS LIKELY IN THE AFTERNOON...AREAS OF FOG THROUGH THE DAY.",
          "CHANCE OF PRECIPITATION 40 PERCENT.",
     ],
   },
   {
     'commentary':'"""\nPrecip:LE2\nSky:LE2\nNonPrecip:noLE\nPoP:LE2\nConsolidation:LE1\n\n0-6 : Sky : 50 : [\'AboveElev\']\n0-6 : Sky : 50 : [\'BelowElev\']\n6-12 : Sky : 50 : [\'AboveElev\']\n6-12 : Sky : 87 : [\'BelowElev\']\n0-6 : PoP : 40 : [\'AboveElev\']\n0-6 : PoP : 40 : [\'BelowElev\']\n6-12 : PoP : 40 : [\'AboveElev\']\n6-12 : PoP : 80 : [\'BelowElev\']\n0-6 : Wx : NoWx : \'all\'\n0-6 : Wx : SChc:SW:-:<NoVis>:^Patchy:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>: : [\'AboveElev\']\n0-6 : Wx : Lkly:SW:-:<NoVis>:^Patchy:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>: : [\'BelowElev\']\n6-12 : Wx : NoWx : \'all\'\n6-12 : Wx : Patchy:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>: : [\'AboveElev\']\n6-12 : Wx : Patchy:F:<NoInten>:<NoVis>:^Lkly:RW:-:<NoVis>: : [\'BelowElev\']\n"""',
     'createGrids':[
       ('Fcst', 'Sky', 'SCALAR', 0, 6, 50, ['AboveElev']),
       ('Fcst', 'Sky', 'SCALAR', 0, 6, 50, ['BelowElev']),
       ('Fcst', 'Sky', 'SCALAR', 6, 12, 50, ['AboveElev']),
       ('Fcst', 'Sky', 'SCALAR', 6, 12, 87, ['BelowElev']),
       ('Fcst', 'PoP', 'SCALAR', 0, 6, 40, ['AboveElev']),
       ('Fcst', 'PoP', 'SCALAR', 0, 6, 40, ['BelowElev']),
       ('Fcst', 'PoP', 'SCALAR', 6, 12, 40, ['AboveElev']),
       ('Fcst', 'PoP', 'SCALAR', 6, 12, 80, ['BelowElev']),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'NoWx', 'all'),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'SChc:SW:-:<NoVis>:^Patchy:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>:', ['AboveElev']),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'Lkly:SW:-:<NoVis>:^Patchy:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>:', ['BelowElev']),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'NoWx', 'all'),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'Patchy:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>:', ['AboveElev']),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'Patchy:F:<NoInten>:<NoVis>:^Lkly:RW:-:<NoVis>:', ['BelowElev']),
     ],
     'name':'SPW_1_1012',
     'checkStrings':[
          "WINDWARD...MOSTLY SUNNY...CHANCE OF SHOWERS AND SLIGHT CHANCE OF SNOW SHOWERS IN THE MORNING...THEN CHANCE OF SHOWERS IN THE AFTERNOON.",
          "LEEWARD...MOSTLY SUNNY WITH SNOW SHOWERS LIKELY AND CHANCE OF SHOWERS IN THE MORNING...THEN MOSTLY CLOUDY WITH SHOWERS LIKELY IN THE AFTERNOON.",
          "PATCHY FOG.",
          "CHANCE OF PRECIPITATION 70 PERCENT.",
     ],
   },
   {
     'commentary':'"""\nPrecip:LE2\nSky:LE2\nNonPrecip:LE1\nPoP:LE1\nConsolidation:noLE\n\n0-6 : Sky : 50 : [\'AboveElev\']\n0-6 : Sky : 50 : [\'BelowElev\']\n6-12 : Sky : 50 : [\'AboveElev\']\n6-12 : Sky : 87 : [\'BelowElev\']\n0-6 : PoP : 40 : [\'AboveElev\']\n0-6 : PoP : 80 : [\'BelowElev\']\n6-12 : PoP : 40 : [\'AboveElev\']\n6-12 : PoP : 40 : [\'BelowElev\']\n0-6 : Wx : NoWx : \'all\'\n0-6 : Wx : SChc:SW:-:<NoVis>:^Patchy:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>: : [\'AboveElev\']\n0-6 : Wx : SChc:SW:-:<NoVis>:^Areas:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>: : [\'BelowElev\']\n6-12 : Wx : NoWx : \'all\'\n6-12 : Wx : Patchy:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>: : [\'AboveElev\']\n6-12 : Wx : Patchy:F:<NoInten>:<NoVis>:^Lkly:RW:-:<NoVis>: : [\'BelowElev\']\n"""',
     'createGrids':[
       ('Fcst', 'Sky', 'SCALAR', 0, 6, 50, ['AboveElev']),
       ('Fcst', 'Sky', 'SCALAR', 0, 6, 50, ['BelowElev']),
       ('Fcst', 'Sky', 'SCALAR', 6, 12, 50, ['AboveElev']),
       ('Fcst', 'Sky', 'SCALAR', 6, 12, 87, ['BelowElev']),
       ('Fcst', 'PoP', 'SCALAR', 0, 6, 40, ['AboveElev']),
       ('Fcst', 'PoP', 'SCALAR', 0, 6, 80, ['BelowElev']),
       ('Fcst', 'PoP', 'SCALAR', 6, 12, 40, ['AboveElev']),
       ('Fcst', 'PoP', 'SCALAR', 6, 12, 40, ['BelowElev']),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'NoWx', 'all'),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'SChc:SW:-:<NoVis>:^Patchy:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>:', ['AboveElev']),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'SChc:SW:-:<NoVis>:^Areas:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>:', ['BelowElev']),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'NoWx', 'all'),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'Patchy:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>:', ['AboveElev']),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'Patchy:F:<NoInten>:<NoVis>:^Lkly:RW:-:<NoVis>:', ['BelowElev']),
     ],
     'name':'SPW_1_1026',
     'checkStrings':[
         "WINDWARD...MOSTLY SUNNY...CHANCE OF SHOWERS AND SLIGHT CHANCE OF SNOW SHOWERS IN THE MORNING...THEN CHANCE OF SHOWERS IN THE AFTERNOON...PATCHY FOG THROUGH THE DAY.",
         "LEEWARD...MOSTLY SUNNY WITH CHANCE OF SHOWERS AND SLIGHT CHANCE OF SNOW SHOWERS IN THE MORNING...THEN MOSTLY CLOUDY WITH SHOWERS LIKELY IN THE AFTERNOON...AREAS OF FOG IN THE MORNING...THEN PATCHY FOG IN THE AFTERNOON.", 
         "CHANCE OF PRECIPITATION 70 PERCENT.",
     ],
   },
   {
     'commentary':'"""\nPrecip:LE2\nSky:LE\nNonPrecip:LE2\nPoP:LE2\nConsolidation:LE2\n\n0-6 : Sky : 50 : [\'AboveElev\']\n0-6 : Sky : 87 : [\'BelowElev\']\n6-12 : Sky : 50 : [\'AboveElev\']\n6-12 : Sky : 87 : [\'BelowElev\']\n0-6 : PoP : 40 : [\'AboveElev\']\n0-6 : PoP : 40 : [\'BelowElev\']\n6-12 : PoP : 40 : [\'AboveElev\']\n6-12 : PoP : 80 : [\'BelowElev\']\n0-6 : Wx : NoWx : \'all\'\n0-6 : Wx : Patchy:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>: : [\'AboveElev\']\n0-6 : Wx : Patchy:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>: : [\'BelowElev\']\n6-12 : Wx : NoWx : \'all\'\n6-12 : Wx : SChc:SW:-:<NoVis>:^Patchy:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>: : [\'AboveElev\']\n6-12 : Wx : Lkly:SW:-:<NoVis>:^Areas:F:<NoInten>:<NoVis>:^Lkly:RW:-:<NoVis>: : [\'BelowElev\']\nNOTE:  The morning weather for Area 1 appears out of order. This is because\nthere is a local effect for the sky phrase (Windward) which appears before weather phrases\nso orderLocalEffectPhrases groups all the windward phrases first."""',
     'createGrids':[
       ('Fcst', 'Sky', 'SCALAR', 0, 6, 50, ['AboveElev']),
       ('Fcst', 'Sky', 'SCALAR', 0, 6, 87, ['BelowElev']),
       ('Fcst', 'Sky', 'SCALAR', 6, 12, 50, ['AboveElev']),
       ('Fcst', 'Sky', 'SCALAR', 6, 12, 87, ['BelowElev']),
       ('Fcst', 'PoP', 'SCALAR', 0, 6, 40, ['AboveElev']),
       ('Fcst', 'PoP', 'SCALAR', 0, 6, 40, ['BelowElev']),
       ('Fcst', 'PoP', 'SCALAR', 6, 12, 40, ['AboveElev']),
       ('Fcst', 'PoP', 'SCALAR', 6, 12, 80, ['BelowElev']),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'NoWx', 'all'),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'Patchy:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>:', ['AboveElev']),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'Patchy:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>:', ['BelowElev']),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'NoWx', 'all'),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'SChc:SW:-:<NoVis>:^Patchy:F:<NoInten>:<NoVis>:^Chc:RW:-:<NoVis>:', ['AboveElev']),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'Lkly:SW:-:<NoVis>:^Areas:F:<NoInten>:<NoVis>:^Lkly:RW:-:<NoVis>:', ['BelowElev']),
     ],
     'name':'SPW_1_1153',
     'checkStrings':[
          "WINDWARD...MOSTLY SUNNY...PATCHY FOG THROUGH THE DAY...CHANCE OF SHOWERS AND SLIGHT CHANCE OF SNOW SHOWERS IN THE AFTERNOON.",
          "CHANCE OF SHOWERS IN THE MORNING.",
          "LEEWARD...MOSTLY CLOUDY...PATCHY FOG IN THE MORNING...THEN AREAS OF FOG IN THE AFTERNOON...SHOWERS AND SNOW SHOWERS LIKELY IN THE AFTERNOON.",
          "CHANCE OF PRECIPITATION 70 PERCENT.",
          ],
   },
   {
     'commentary':'"""\nPrecip:null\nSky:LE1\nNonPrecip:null\nPoP:LE\nConsolidation:LE1\n\n0-6 : Sky : 50 : [\'AboveElev\']\n0-6 : Sky : 87 : [\'BelowElev\']\n6-12 : Sky : 50 : [\'AboveElev\']\n6-12 : Sky : 50 : [\'BelowElev\']\n0-6 : PoP : 40 : [\'AboveElev\']\n0-6 : PoP : 80 : [\'BelowElev\']\n6-12 : PoP : 40 : [\'AboveElev\']\n6-12 : PoP : 80 : [\'BelowElev\']\n0-6 : Wx : NoWx : \'all\'\n0-6 : Wx : SChc:SW:-:<NoVis>: : [\'AboveElev\']\n0-6 : Wx : Lkly:SW:-:<NoVis>: : [\'BelowElev\']\n"""',
     'createGrids':[
       ('Fcst', 'Sky', 'SCALAR', 0, 6, 50, ['AboveElev']),
       ('Fcst', 'Sky', 'SCALAR', 0, 6, 87, ['BelowElev']),
       ('Fcst', 'Sky', 'SCALAR', 6, 12, 50, ['AboveElev']),
       ('Fcst', 'Sky', 'SCALAR', 6, 12, 50, ['BelowElev']),
       ('Fcst', 'PoP', 'SCALAR', 0, 6, 40, ['AboveElev']),
       ('Fcst', 'PoP', 'SCALAR', 0, 6, 80, ['BelowElev']),
       ('Fcst', 'PoP', 'SCALAR', 6, 12, 40, ['AboveElev']),
       ('Fcst', 'PoP', 'SCALAR', 6, 12, 80, ['BelowElev']),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'NoWx', 'all'),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'SChc:SW:-:<NoVis>:', ['AboveElev']),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'Lkly:SW:-:<NoVis>:', ['BelowElev']),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'NoWx', 'all'),
     ],
     'name':'SPW_1_1377',
     'checkStrings':[
         "WINDWARD...MOSTLY SUNNY...A 20 PERCENT CHANCE OF SNOW SHOWERS IN THE MORNING.",
         "LEEWARD...SNOW SHOWERS LIKELY IN THE MORNING...THEN MOSTLY SUNNY IN THE AFTERNOON...CHANCE OF SNOW 70 PERCENT.", 
     ],
   },
   {
     'commentary':'"""\nPrecip:null\nSky:LE1\nNonPrecip:LE\nPoP:LE\nConsolidation:null\n\n0-6 : Sky : 50 : [\'AboveElev\']\n0-6 : Sky : 87 : [\'BelowElev\']\n6-12 : Sky : 50 : [\'AboveElev\']\n6-12 : Sky : 50 : [\'BelowElev\']\n0-6 : PoP : 40 : [\'AboveElev\']\n0-6 : PoP : 80 : [\'BelowElev\']\n6-12 : PoP : 40 : [\'AboveElev\']\n6-12 : PoP : 80 : [\'BelowElev\']\n0-6 : Wx : NoWx : \'all\'\n0-6 : Wx : Patchy:F:<NoInten>:<NoVis>: : [\'AboveElev\']\n0-6 : Wx : Areas:F:<NoInten>:<NoVis>: : [\'BelowElev\']\n6-12 : Wx : NoWx : \'all\'\n6-12 : Wx : Patchy:F:<NoInten>:<NoVis>: : [\'AboveElev\']\n6-12 : Wx : Areas:F:<NoInten>:<NoVis>: : [\'BelowElev\']\n"""',
     'createGrids':[
       ('Fcst', 'Sky', 'SCALAR', 0, 6, 50, ['AboveElev']),
       ('Fcst', 'Sky', 'SCALAR', 0, 6, 87, ['BelowElev']),
       ('Fcst', 'Sky', 'SCALAR', 6, 12, 50, ['AboveElev']),
       ('Fcst', 'Sky', 'SCALAR', 6, 12, 50, ['BelowElev']),
       ('Fcst', 'PoP', 'SCALAR', 0, 6, 40, ['AboveElev']),
       ('Fcst', 'PoP', 'SCALAR', 0, 6, 80, ['BelowElev']),
       ('Fcst', 'PoP', 'SCALAR', 6, 12, 40, ['AboveElev']),
       ('Fcst', 'PoP', 'SCALAR', 6, 12, 80, ['BelowElev']),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'NoWx', 'all'),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'Patchy:F:<NoInten>:<NoVis>:', ['AboveElev']),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'Areas:F:<NoInten>:<NoVis>:', ['BelowElev']),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'NoWx', 'all'),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'Patchy:F:<NoInten>:<NoVis>:', ['AboveElev']),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'Areas:F:<NoInten>:<NoVis>:', ['BelowElev']),
     ],
     'name':'SPW_1_1399',
     'checkStrings':[
          "WINDWARD...MOSTLY SUNNY...PATCHY FOG.",
          "LEEWARD...MOSTLY CLOUDY IN THE MORNING THEN BECOMING MOSTLY SUNNY...AREAS OF FOG.",
          ],
   },
   {
     'commentary':'"""\nPrecip:LE\nSky:noLE\nNonPrecip:null\nPoP:LE1\nConsolidation:LE2\n\n0-6 : Sky : 50 : [\'AboveElev\']\n0-6 : Sky : 50 : [\'BelowElev\']\n6-12 : Sky : 50 : [\'AboveElev\']\n6-12 : Sky : 50 : [\'BelowElev\']\n0-6 : PoP : 40 : [\'AboveElev\']\n0-6 : PoP : 80 : [\'BelowElev\']\n6-12 : PoP : 40 : [\'AboveElev\']\n6-12 : PoP : 40 : [\'BelowElev\']\n0-6 : Wx : NoWx : \'all\'\n0-6 : Wx : Lkly:RW:-:<NoVis>:^Chc:RW:-:<NoVis>: : [\'AboveElev\']\n6-12 : Wx : NoWx : \'all\'\n6-12 : Wx : SChc:SW:-:<NoVis>: : [\'AboveElev\']\n6-12 : Wx : Lkly:SW:-:<NoVis>:^Lkly:RW:-:<NoVis>:^Chc:RW:-:<NoVis>: : [\'BelowElev\']\n"""',
     'createGrids':[
       ('Fcst', 'Sky', 'SCALAR', 0, 6, 50, ['AboveElev']),
       ('Fcst', 'Sky', 'SCALAR', 0, 6, 50, ['BelowElev']),
       ('Fcst', 'Sky', 'SCALAR', 6, 12, 50, ['AboveElev']),
       ('Fcst', 'Sky', 'SCALAR', 6, 12, 50, ['BelowElev']),
       ('Fcst', 'PoP', 'SCALAR', 0, 6, 40, ['AboveElev']),
       ('Fcst', 'PoP', 'SCALAR', 0, 6, 80, ['BelowElev']),
       ('Fcst', 'PoP', 'SCALAR', 6, 12, 40, ['AboveElev']),
       ('Fcst', 'PoP', 'SCALAR', 6, 12, 40, ['BelowElev']),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'NoWx', 'all'),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'Lkly:RW:-:<NoVis>:^Chc:RW:-:<NoVis>:', ['AboveElev']),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'NoWx', 'all'),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'SChc:SW:-:<NoVis>:', ['AboveElev']),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'Lkly:SW:-:<NoVis>:^Lkly:RW:-:<NoVis>:^Chc:RW:-:<NoVis>:', ['BelowElev']),
     ],
     'name':'SPW_1_1668',
     'checkStrings':[
         "WINDWARD...SHOWERS LIKELY IN THE MORNING...THEN SLIGHT CHANCE OF SNOW SHOWERS IN THE AFTERNOON.",
         "LEEWARD...SHOWERS AND SNOW SHOWERS LIKELY IN THE AFTERNOON.",
         "CHANCE OF PRECIPITATION 70 PERCENT.",
     ],
   },
   {
     'commentary':'"""\nPrecip:LE\nSky:LE1\nNonPrecip:LE1\nPoP:LE2\nConsolidation:LE\n\n0-6 : Sky : 50 : [\'AboveElev\']\n0-6 : Sky : 87 : [\'BelowElev\']\n6-12 : Sky : 50 : [\'AboveElev\']\n6-12 : Sky : 50 : [\'BelowElev\']\n0-6 : PoP : 40 : [\'AboveElev\']\n0-6 : PoP : 40 : [\'BelowElev\']\n6-12 : PoP : 40 : [\'AboveElev\']\n6-12 : PoP : 80 : [\'BelowElev\']\n0-6 : Wx : NoWx : \'all\'\n0-6 : Wx : SChc:SW:-:<NoVis>:^Patchy:F:<NoInten>:<NoVis>:^Lkly:RW:-:<NoVis>:^Chc:RW:-:<NoVis>: : [\'AboveElev\']\n0-6 : Wx : Lkly:SW:-:<NoVis>:^Areas:F:<NoInten>:<NoVis>: : [\'BelowElev\']\n6-12 : Wx : NoWx : \'all\'\n6-12 : Wx : Patchy:F:<NoInten>:<NoVis>: : [\'AboveElev\']\n6-12 : Wx : Patchy:F:<NoInten>:<NoVis>:^Lkly:RW:-:<NoVis>:^Chc:RW:-:<NoVis>: : [\'BelowElev\']\n"""',
     'createGrids':[
       ('Fcst', 'Sky', 'SCALAR', 0, 6, 50, ['AboveElev']),
       ('Fcst', 'Sky', 'SCALAR', 0, 6, 87, ['BelowElev']),
       ('Fcst', 'Sky', 'SCALAR', 6, 12, 50, ['AboveElev']),
       ('Fcst', 'Sky', 'SCALAR', 6, 12, 50, ['BelowElev']),
       ('Fcst', 'PoP', 'SCALAR', 0, 6, 40, ['AboveElev']),
       ('Fcst', 'PoP', 'SCALAR', 0, 6, 40, ['BelowElev']),
       ('Fcst', 'PoP', 'SCALAR', 6, 12, 40, ['AboveElev']),
       ('Fcst', 'PoP', 'SCALAR', 6, 12, 80, ['BelowElev']),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'NoWx', 'all'),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'SChc:SW:-:<NoVis>:^Patchy:F:<NoInten>:<NoVis>:^Lkly:RW:-:<NoVis>:^Chc:RW:-:<NoVis>:', ['AboveElev']),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'Lkly:SW:-:<NoVis>:^Areas:F:<NoInten>:<NoVis>:', ['BelowElev']),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'NoWx', 'all'),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'Patchy:F:<NoInten>:<NoVis>:', ['AboveElev']),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'Patchy:F:<NoInten>:<NoVis>:^Lkly:RW:-:<NoVis>:^Chc:RW:-:<NoVis>:', ['BelowElev']),
     ],
     'name':'SPW_1_1735',
     'checkStrings':[
         "WINDWARD...MOSTLY SUNNY...SHOWERS LIKELY AND SLIGHT CHANCE OF SNOW SHOWERS IN THE MORNING...PATCHY FOG THROUGH THE DAY.",
         "LEEWARD...MOSTLY CLOUDY WITH SNOW SHOWERS LIKELY IN THE MORNING...THEN MOSTLY SUNNY WITH SHOWERS LIKELY IN THE AFTERNOON...AREAS OF FOG IN THE MORNING...THEN PATCHY FOG IN THE AFTERNOON.",
         "CHANCE OF PRECIPITATION 70 PERCENT.",
         ],
   },
   {
     'commentary':'"""\nPrecip:LE\nSky:LE\nNonPrecip:null\nPoP:noLE\nConsolidation:noLE\n\n0-6 : Sky : 50 : [\'AboveElev\']\n0-6 : Sky : 87 : [\'BelowElev\']\n6-12 : Sky : 50 : [\'AboveElev\']\n6-12 : Sky : 87 : [\'BelowElev\']\n0-6 : PoP : 40 : [\'AboveElev\']\n0-6 : PoP : 40 : [\'BelowElev\']\n6-12 : PoP : 40 : [\'AboveElev\']\n6-12 : PoP : 40 : [\'BelowElev\']\n0-6 : Wx : NoWx : \'all\'\n0-6 : Wx : SChc:SW:-:<NoVis>:^Lkly:RW:-:<NoVis>:^Chc:RW:-:<NoVis>: : [\'AboveElev\']\n0-6 : Wx : SChc:SW:-:<NoVis>: : [\'BelowElev\']\n6-12 : Wx : NoWx : \'all\'\n6-12 : Wx : Lkly:RW:-:<NoVis>:^Chc:RW:-:<NoVis>: : [\'BelowElev\']\n"""',
     'createGrids':[
       ('Fcst', 'Sky', 'SCALAR', 0, 6, 50, ['AboveElev']),
       ('Fcst', 'Sky', 'SCALAR', 0, 6, 87, ['BelowElev']),
       ('Fcst', 'Sky', 'SCALAR', 6, 12, 50, ['AboveElev']),
       ('Fcst', 'Sky', 'SCALAR', 6, 12, 87, ['BelowElev']),
       ('Fcst', 'PoP', 'SCALAR', 0, 6, 40, ['AboveElev']),
       ('Fcst', 'PoP', 'SCALAR', 0, 6, 40, ['BelowElev']),
       ('Fcst', 'PoP', 'SCALAR', 6, 12, 40, ['AboveElev']),
       ('Fcst', 'PoP', 'SCALAR', 6, 12, 40, ['BelowElev']),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'NoWx', 'all'),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'SChc:SW:-:<NoVis>:^Lkly:RW:-:<NoVis>:^Chc:RW:-:<NoVis>:', ['AboveElev']),
       ('Fcst', 'Wx', 'WEATHER', 0, 6, 'SChc:SW:-:<NoVis>:', ['BelowElev']),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'NoWx', 'all'),
       ('Fcst', 'Wx', 'WEATHER', 6, 12, 'Lkly:RW:-:<NoVis>:^Chc:RW:-:<NoVis>:', ['BelowElev']),
     ],
     'name':'SPW_1_1961',
     'checkStrings':[
         "WINDWARD...MOSTLY SUNNY...SHOWERS LIKELY AND SLIGHT CHANCE OF SNOW SHOWERS IN THE MORNING.", 
         "LEEWARD...MOSTLY CLOUDY...SLIGHT CHANCE OF SNOW SHOWERS IN THE MORNING...THEN SHOWERS LIKELY IN THE AFTERNOON.",
         "CHANCE OF PRECIPITATION 40 PERCENT.",
     ],
   },
]



import TestScript
def testScript(self, dataMgr):
    defaults = {
        "cmdLineVars" :"{('Product Issuance', 'productIssuance'): 'Morning', ('Issuance Type', 'issuanceType'): 'ROUTINE', ('Issued By', 'issuedBy'): None}",
        "productType": "Phrase_Test_Local",
        "fileChanges" : [
           ("Phrase_Test_Local", "TextProduct", "replace", periodVer2, "undo")
           ],
        }
    return TestScript.generalTestScript(self, dataMgr, scripts, defaults)

