C MEMBER GRUNOF
C  (from old member PPGRUNOF)
C
      SUBROUTINE GRUNOF(W, A, WN, WX, BI, SK, SM, E1, E2, CP, POW,
     * G1, G2, NRELN, C, Y, B, C2, DUR, API, RAIN, RI1, RI2, RO)
C
C.....THIS IS THE RUNOFF COMPUTATION DRIVER ROUTINE FOR THE NWSRFS
C.....VERSION 5.0 WGRFC FT. WORTH MARO FUNCTION.
C
C.....GIVEN THE RAINFALL-RUNOFF RELATION CONSTANTS...THE SEASON...THE
C.....SOIL MOISTURE...AND THE PRECIPITATION AT THE GRID POINT...A POINT
C.....VALUE OF RUNOFF IS COMPUTED.
C
C.....THE SUBROUTINE COMPUTES ONE VALUE OF RUNOFF FOR ONE GRID POINT
C.....EACH TIME IT IS CALLED.
C
C.....HERE IS THE ARGUMENT LIST.
C
C.....W      - THE WEEK NUMBER.
C.....A      - RAINFALL-RUNOFF RELATION CONSTANT (SEE NWSRFS IX.3.4C).
C.....WN     - RAINFALL-RUNOFF RELATION CONSTANT.
C.....WX     - RAINFALL-RUNOFF RELATION CONSTANT.
C.....BI     - RAINFALL-RUNOFF RELATION CONSTANT.
C.....SK     - RAINFALL-RUNOFF RELATION CONSTANT.
C.....SM     - RAINFALL-RUNOFF RELATION CONSTANT.
C.....E1     - RAINFALL-RUNOFF RELATION CONSTANT.
C.....E2     - RAINFALL-RUNOFF RELATION CONSTANT.
C.....CP     - RAINFALL-RUNOFF RELATION CONSTANT.
C.....POW    - RAINFALL-RUNOFF RELATION CONSTANT.
C.....G1     - RAINFALL-RUNOFF RELATION CONSTANT.
C.....G2     - RAINFALL-RUNOFF RELATION CONSTANT.
C.....NRELN  - RAINFALL-RUNOFF RELATION NUMBER.
C.....C      - RAINFALL-RUNOFF EQUATION INTERIM RESULT.
C.....Y      - RAINFALL-RUNOFF EQUATION INTERIM RESULT.
C.....B      - RAINFALL-RUNOFF EQUATION INTERIM RESULT.
C.....C2     - RAINFALL-RUNOFF EQUATION INTERIM RESULT.
C.....DUR    - RAINFALL DURATION.
C.....API    - GRID POINT API.
C.....RAIN   - GRID POINT RAINFALL.
C.....RI1    - RAINFALL-RUNOFF EQUATION INTERIM RESULT.
C.....RI2    - RAINFALL-RUNOFF EQUATION INTERIM RESULT.
C.....RO     - GRID POINT RUNOFF COMPUTED.
C
C.....NOTE:  THE RAINFALL-RUNOFF EQUATION INTERIM RESULTS IN THE
C.....ARGUMENT LIST ARE PASSED BACK TO THE CALLING ROUTINE FOR THE
C.....PURPOSES OF DEBUG OUTPUT.
C
C
C.....THIS ROUTINE WAS DEVELOPED FROM SUBROUTINE RUNOF IN WGRFC
C.....RUNOFF COMPUTATION PROGRAM ONECL (ONE CALL).
C
C.....GRUNOF ORIGINALLY WRITTEN BY:
C
C.....JERRY M. NUNN       WGRFC FT. WORTH, TEXAS       NOVEMBER 1986
C
      DIMENSION SNAME(2)
C
      INCLUDE 'common/pudbug'
      INCLUDE 'common/where'
      INCLUDE 'gcommon/gsize'
      INCLUDE 'common/ionum'
C
C    ================================= RCS keyword statements ==========
      CHARACTER*68     RCSKW1,RCSKW2
      DATA             RCSKW1,RCSKW2 /                                 '
     .$Source: /fs/hseb/ob72/rfc/ofs/src/fcst_maro/RCS/grunof.f,v $
     . $',                                                             '
     .$Id: grunof.f,v 1.1 1995/09/17 19:02:32 dws Exp $
     . $' /
C    ===================================================================
C
C
      DATA SNAME /4hGRUN, 4hOF  /
C
  902 FORMAT(1H0, '*** ENTER GRUNOF ***')
  903 FORMAT(1X, '*** EXIT GRUNOF ***')
      INCLUDE 'gcommon/setwhere'
C
C.....BEGIN THE COMPUTATIONS...INITIALIZE RUNOFF.
C
      IF(IPTRCE .GE. 8) WRITE(IOPDBG,902)
      RO = 0.0
C
C.....IF NO RAINFALL OCCURRED...THERE WAS OBVIOUSLY NO RUNOFF.
C
      IF(RAIN .LT. 0.01) GOTO 999
C
C.....IF THE API IS NEGATIVE...COMPARE ITS ABSOLUTE VALUE TO THE RAIN.
C
      IF(API .GE. 0.0) GOTO 100
      API2 = ABS(API)
C
C.....IF THE ABSOLUTE VALUE OF THE (NEGATIVE) API EXCEEDS THE RAIN,
C.....THERE WAS NO RUNOFF.
C
      IF(API2 .GT. RAIN) GOTO 999
C
C.....NOW THAT Y AND C HAVE BEEN COMPUTED...GO INTO THE FINAL STAGES OF
C.....THE RAINFALL - RUNOFF COMPUTATIONS.
C
  100 CALL GROCMP(A, DUR, B, C, C2, Y, BI, SM, SK, POW, NRELN, API,
     * RAIN, RI1, RI2, RO)
C
  999 IF(IPTRCE .GE. 8) WRITE(IOPDBG,903)
      RETURN
      END

