C MEMBER GTITLE
C  (from old member PPGTITLE)
C-----------------------------------------------------------------------
C
C                             LAST UPDATE: 07/01/94.15:33:28 BY $WC20SV
C
C @PROCESS LVL(77)
C
      SUBROUTINE GTITLE
C
C.....THIS IS DOCUMENT GTITLE. THIS PRODUCES A TITLE PAGE FOR THE
C.....MARO FUNCTION.
C
C.....ORIGINALLY WRITTEN BY:
C
C.....JERRY M. NUNN     WGRFC FT. WORTH, TEXAS     FEBRUARY 10, 1988
C
      DIMENSION SNAME(2), ANS(2), UNITS(4), MEAS(6), NTECH(100)
      DIMENSION IPCT(4)
C
      INCLUDE 'common/where'
      INCLUDE 'common/ionum'
      INCLUDE 'gcommon/gopt'
      INCLUDE 'gcommon/gdispl'
      INCLUDE 'gcommon/gsize'
      INCLUDE 'gcommon/gmdr'
      INCLUDE 'gcommon/gdate'
      INCLUDE 'common/fctime'
      INCLUDE 'gcommon/gboxot'
      INCLUDE 'gcommon/boxtrc'
      INCLUDE 'common/pudbug'
      INCLUDE 'udsi'
      INCLUDE 'common/errdat'
C
C    ================================= RCS keyword statements ==========
      CHARACTER*68     RCSKW1,RCSKW2
      DATA             RCSKW1,RCSKW2 /                                 '
     .$Source: /fs/hseb/ob72/rfc/ofs/src/fcst_maro/RCS/gtitle.f,v $
     . $',                                                             '
     .$Id: gtitle.f,v 1.1 1995/09/17 19:02:47 dws Exp $
     . $' /
C    ===================================================================
C
C
      DATA SNAME, ANS, GOPT /4HGTIT,4HLE  ,4HYES ,4HNO  ,4HGOPT/
      DATA UNITS, ZTIME /4HMETR,4HIC  ,4HENGL,4HISH ,4HZ   /
      DATA MEAS /4HMILL,4HIMET,4HERS.,4HINCH,4HES. ,4H    /
      DATA NTECH /4HAPIM,4HAX  ,4HAPIM,4HIN  ,4HAPIR,4HCMIN,
     * 4HAPIR,4HEC  ,4HAPIS,4HCON ,4HBOXD,4HEBUG,4HBOXD,4HKEY ,
     * 4HBOXD,4HUMP ,4HCONV,4HEC  ,4HDEBU,4HGPR ,4HDUR ,4H    ,
     * 4HENDR,4HUN  ,4HERRO,4HRPR ,4HESTF,4HTW  ,4HLSTC,4HMPDY,
     * 4HFTWM,4HDRDS,4HMDRE,4HST6 ,4HMDRE,4HST24,4HMETR,4HIC  ,
     * 4HMODT,4HZC  ,4HMODU,4HNITS,4HMODW,4HARN ,4HMDRT,4HABLE,
     * 4HNOES,4HT6HR,4HNOUT,4HDS  ,4HNOUT,4HZ   ,4HNUMQ,4HDT  ,
     * 4HPAGE,4HSIZE,4HPGSZ,4HMARO,4HPLOT,4HPP24,4HPP24,4HMAX ,
     * 4HPP24,4HTIME,4HPPDE,4HBUG ,4HPPPR,4HINT ,4HPPTR,4HACE ,
     * 4HPRTM,4HARO ,4HPRTM,4HDR  ,4HPRTM,4HDR6 ,4HPRTP,4HP6  ,
     * 4HPRTP,4HP24 ,4HPRTP,4HPZRO,4HPUNC,4HH   ,4HRWWA,4HRN  ,
     * 4HSTAR,4HTRUN,4HWKLA,4HG   ,4HWTES,4HT24 ,4HFTWQ,4HPF  ,
     * 6*4H    /
C
  897 FORMAT(1H0, '*** WARNING ***  THE USER HAS REQUESTED SIX-HOURLY DI
     *STRIBUTIONS TO BE DETERMINED BY MDR IN A QPF RUN.', /, 5X, 'IN A Q
     *PF RUN...THE SIX-HOURLY DISTRIBUTIONS ARE DETERMINED', /, 5X, 'BY
     *A SET OF FOUR DISTRIBUTION CONSTANTS ENTERED WITH THE ''FTWQPF'' T
     *ECHNIQUE.', /, 5X, 'THE MDR SIX-HOURLY DISTRIBUTION FLAG IS BEING
     *RE-SET TO ', I4, '. PROCESSING CONTINUES.')
  898 FORMAT(1H0, 9X, 2A4, 5X, I2, 4X, 'THIS IS NOT A QPF RUN OF THE MAR
     *O FUNCTION.')
  899 FORMAT(1H0, 9X, 2A4, 5X, I2, 4X, 'THIS IS A QPF RUN OF THE MARO FU
     *NCTION.', /, 29X, 'THE DISTRIBUTION CONSTANTS AND PERCENTAGES FOR
     *THE FOUR SIX-HOURLY PERIODS ARE', /, 29X, I5, 1X, '(', I3, ')',
     * 1X, I5, '(', I3, ')', 1X, I5, '(', I3, ')', 1X, I5, '(', I3, ')')
  903 FORMAT(1H1,  40X, 'WGRFC MARO FUNCTION ')
  904 FORMAT(10X,  16X, 'RUN PERIOD  ', I2, '/', I2, '/', I4,
     * ' - ', I2, A4, '  THRU ', I2, '/', I2, '/', I4, ' - ', I2, A4)
  905 FORMAT(10X,  16X, 'TIME OF RUN   ', 2A4, I2, ', ', I4,
     * ' -- ', I2, ':', I2, A4)
  907 FORMAT(1H0, 130('.'))
  908 FORMAT(1H0, 'DATE-TIME OPTIONS IN EFFECT:')
  909 FORMAT(1H0, 'BEGINNING RUNDATE IS:  WEEKDAY NO. ', I1, ' -- ',
     * A3, 1X, A3, 1X, I2, ', ', I4, ' AT ', I2, A3, '   (WEEK NO. OF YE
     *AR = ', I2, ')', 5X, 'NWSRFS JULIAN DATE IS:  ', I5, 2X, I2)
  910 FORMAT(1H0, 'ENDING RUNDATE IS:     WEEKDAY NO. ', I1, ' -- ',
     * A3, 1X, A3, 1X, I2, ', ', I4, ' AT ', I2, A3, '   (WEEK NO. OF YE
     *AR = ', I2, ')', 5X, 'NWSRFS JULIAN DATE IS:  ', I5, 2X, I2)
  911 FORMAT(1H0, '*** NOTE ***   THE LAST SIX-HOURLY TIME SLOT CONTAINI
     *NG OBSERVED DATA IS ', A3, 1X, A3, 1X, I2, ', ', I4, ' AT ', I2,
     * A3, '.', /, 16X, 'ALL SIX-HOURLY TIME SERIES AFTER THIS TIME WILL
     * CONTAIN A DATA VALUE OF ZERO.')
  912 FORMAT(1H0, 'DISPLAY OPTIONS IN EFFECT:')
  913 FORMAT(1H0, 'PRINT OBSERVED 24-HOUR PRECIP:  ', A3, 9X, 'PRINT EST
     *IMATED 24-HOUR PRECIP:  ', A3, 9X, 'PRINT ZERO VALUES OF 24-HOUR P
     *RECIP:  ', A3)
  914 FORMAT(1H0, 'PRINT OBSERVED  6-HOUR PRECIP:  ', A3, 9X, 'PRINT EST
     *IMATED  6-HOUR PRECIP:  ', A3, 9X, 'PRINT ZERO VALUES OF  6-HOUR P
     *RECIP:  ', A3)
  915 FORMAT(1H0, 'PRINT MARO/MAPG/MAPE TABULAR SUMMARY:  ', A3, 28X,
     * 'MAXIMUM NUMBER OF MARO AREAS TO PLACE ON A SINGLE PAGE = ', I2)
  916 FORMAT(1H0, 'DISPLAY MDR:  ', A3, 9X, 'DISPLAY MDR DATA AND MDR DE
     *RIVED PRECIPITATION:  ', A3, 9X, 'DISPLAY GAGE/RADAR RATIOS OF STA
     *TIONS:  ', A3)
  917 FORMAT(1H0, 'CREATE AFOS GRAPHIC PLOT OF PRECIP:  ', A3, 49X, 'INC
     *LUDE ESTIMATIONS IN GRAPHIC PLOT:  ', A3)
  918 FORMAT(1H0, 'PRINT GRID POINT DATA ON DEGREE BOX BACKGROUND:  ',
     * A3, 9X, 'CREATE AFOS GRAPHIC OF GRID POINT DATA ON DEGREE BOX BAC
     *KGROUND:  ', A3)
  919 FORMAT(1H0, 'DISPLAY THE FOLLOWING:  PG24 (24-HR GRID POINT PRECIP
     *):  ', A3, 6X, 'APIG (GRID POINT API):  ', A3, 7X, 'RNFG (GRID POI
     *NT RUNOFF):  ', A3)
  920 FORMAT(1H0, 'DISPLAY OF GRID POINT DATA WILL BE FOR THE FOLLOWING
     *GRID BOXES:', /, 1H0, 20I5)
  921 FORMAT(1H0, '*** NOTE ***   DATA WILL BE DISPLAYED IN ', A4, A3,
     * ' UNITS')
  922 FORMAT(1H0, 'MDR USAGE OPTIONS IN EFFECT:')
  923 FORMAT(1H0, 'MDR DATA IS AVAILABLE AND MAY BE USED IN THIS RUN OF
     *MARO.')
  924 FORMAT(1H0, 'MDR DATA IS NOT AVAILABLE OR MAY NOT BE USED IN THIS
     *RUN OF MARO.')
  925 FORMAT(1H0, 'MDR USAGE LEVEL CODE FOR 24-HOUR PRECIPITATION...PREC
     *IPITATION ESTIMATES WILL BE PLACED IN THE CENTROID GRID POINT', /,
     * 5X, 'OF EACH MDR BOX, PROVIDED NO OBSERVED AMOUNT IS PRESENT THER
     *E ALREADY.')
  926 FORMAT(1H0, 'MDR USAGE LEVEL IS 0.  MDR WILL NOT BE USED TO MAKE A
     *NY PRECIPITATION ESTIMATES.')
  927 FORMAT(1H0, 'MDR USAGE LEVEL IS 1.  MDR WILL BE USED ONLY TO ESTIM
     *ATE ZERO PRECIPITATION AMOUNTS.')
  928 FORMAT(1H0, 'MDR USAGE LEVEL IS 2.  MDR WILL BE USED ONLY TO ESTIM
     *ATE PRECIPITATION UP TO THE SPECIFIED AMOUNT OF ', F5.2, ' IN.')
  929 FORMAT(1H0, 'MDR USAGE LEVEL IS 3.  MDR WILL BE USED TO ESTIMATE A
     *NY PRECIPITATION AMOUNT.')
  930 FORMAT(1H0, 'MDR USAGE CODE FOR 6-HOUR PRECIPITATION IS 1...DISTRI
     *BUTION PERCENTAGES WILL BE COMPUTED FOR THE CENTROID GRID POINTS.'
     *)
  931 FORMAT(1H0, 'MDR USAGE CODE FOR 6-HOUR PRECIPITATION IS 0...DISTRI
     *BUTION PERCENTAGES WILL NOT BE COMPUTED FOR THE CENTROID GRID POIN
     *TS.')
  932 FORMAT(1H0, 'MDR PRECIPITATION CONVERSION TABLE TO USE IS THE ',
     * I2, ' PERCENT PROBABILITY LEVEL TABLE.')
  933 FORMAT(1H0, 'NO CONVERSION TABLE VALUE WAS INPUT BY THE USER...THE
     * CONVERSION TABLE IS THE DEFAULT VALUE.', /, 1X, 'THE CONVERSION T
     *ABLE VALUE MAY BE LATER ALTERED BY CALIBRATION OF THE FIRST ORDER
     *PRECIPITATION DATA.')
  934 FORMAT(1H0, 'THE CONVERSION TABLE VALUE WAS INPUT BY THE USER...TH
     *IS CONVERSION TABLE VALUE', /, 1X, 'WILL REMAIN IN EFFECT THROUGHO
     *UT THIS RUN OF THE MARO FUNCTION.')
  935 FORMAT(1H0, 'PRECIPITATION ESTIMATION, API COMPUTATION, AND RUNOFF
     * COMPUTATION OPTIONS IN EFFECT:')
  936 FORMAT(1H0, 'THE CONVECTIVE PRECIPITATION ESTIMATION OPTION IS IN
     *EFFECT...THE ESTIMATION DISTANCE IS ', F5.2, ' MI.')
  937 FORMAT(1H0, 'THE CONVECTIVE PRECIPITATION ESTIMATION OPTION IS NOT
     * IN EFFECT.')
  938 FORMAT(1H0, 'THE ADJACENT QUADRANT PROCEDURE PROCESS CODE IS ',
     * I2, '.')
  939 FORMAT(1H0, 'SIX-HOURLY PRECIPITATION AMOUNTS WILL BE ESTIMATED FR
     *OM SURROUNDING SIX-HOURLY PRECIPITATION REPORTING STATIONS.')
  940 FORMAT(1H0, 'SIX-HOURLY PRECIPITATION AMOUNTS WILL NOT BE ESTIMATE
     *D FROM SURROUNDING SIX-HOURLY PRECIPITATION REPORTING STATIONS.')
  941 FORMAT(1H0, 'THE NUMBER OF OBSERVED PRECIPITATION REPORTS TO BE US
     *ED PER QUADRANT IS ', I2, '.  THE UPPER LIMIT FOR THIS NUMBER IS',
     * 1X, I2, '.')
  942 FORMAT(1H0, 'THE PRECIPITATION DURATION FACTOR IS ', F5.2, ' HOURS
     *. THIS FACTOR WAS INPUT BY THE USER.')
  943 FORMAT(1H0, 'THE PRECIPITATION DURATION FACTOR IS ', F5.2, ' HOURS
     *. THIS FACTOR WAS DETERMINED BY MARO.')
  944 FORMAT(1H0, 'THE API RECESSION FACTOR IS ', F5.2, '. THIS FACTOR W
     *S INPUT BY THE USER.')
  945 FORMAT(1H0, 'THE API RECESSION FACTOR IS ', F5.2, '. THIS FACTOR W
     *AS DETERMINED BY MARO.')
  946 FORMAT(1H0, 'MINIMUM VALUE FOR WHICH THE API RECESSION FACTOR CAN
     *BE USED IS ', F5.2, ' IN.')
  947 FORMAT(1H0, 'FOR APIS BELOW THE MINIMUM VALUE, THE NEW API IS DETE
     *RMINED BY SUBTRACTING ', F5.2, ' IN FROM THE CURRENT API VALUE.')
  948 FORMAT(1H0, 'APIS WILL NOT BE ALLOWED TO GO ABOVE ', F5.2, ' IN OR
     * TO GO BELOW ', F5.2, ' IN.')
  949 FORMAT(1H0, 'TRACE/DEBUG OPTIONS IN EFFECT')
  950 FORMAT(1H0, 'TRACE LEVEL = ', I2, 10X, 'NOBUG CODE = ', I2)
  951 FORMAT(1H0, 'DEBUG IS TURNED ON FOR ALL DEBUG CODES')
  952 FORMAT(1H0, 'DEBUG IS TURNED ON FOR THE FOLLOWING DEBUG CODES:',
     * /, 1H0, 20(1X, A4))
  953 FORMAT(1H0, 'DEBUG IS TURNED ON FOR ALL DEGREE BOXES.')
  954 FORMAT(1H0, 'DEBUG IS TURNED ON FOR THE FOLLOWING DEGREE BOXES:',
     * /, 1H0, 20I5)
  955 FORMAT(1H0, '*** GTITLE ENTERED ***')
  956 FORMAT(1H0, '*** EXIT GTITLE ***')
  957 FORMAT(1H0, 'THE 24-HOUR PRECIPITATION ESTIMATION FLAG IS ON.',
     * /, 1H0, 'MISSING 24-HOUR PRECIPITATION WILL BE ESTIMATED FROM THE
     * ESTIMATION ROUTINES.')
  958 FORMAT(1H0, 'THE 24-HOUR PRECIPITATION ESTIMATION FLAG IS OFF.',
     * /, 1H0, 'MISSING 24-HOUR PRECIPITATION WILL BE SET TO ZERO.')
  959 FORMAT(//)
  961 FORMAT(1H0, 9X, 'THE TABLE BELOW IS A STATUS TABLE FOR THE MORE IM
     *PORTANT RUN-TIME OPTIONS AVAILABLE WITH THE WGRFC MARO FUNCTION.',
     * /, 1H0, 9X, 'TECHNIQUE   VALUE  DESCRIPTION', /, 10X, '---------
     *  -----  -----------')
  962 FORMAT(1H0, 9X, 2A4, 5X, I2, 4X, 'PARTIAL DAY PRECIPITATION REPORT
     * WILL BE USED AS FULL DAY TOTALS.')
  963 FORMAT(1H0, 9X, 2A4, 5X, I2, 4X, 'ONLY FULL DAY PRECIPITATION TOTA
     *LS WILL BE USED.')
  964 FORMAT(1H0, 9X, 2A4, 5X, I2, 4X, 'MISSING SIX-HOURLY PRECIPITATION
     * AT A FIRST ORDER GRID POINT WILL NOT BE ESTIMATED.')
  965 FORMAT(1H0, 9X, 2A4, 5X, I2, 4X, 'MISSING SIX-HOURLY PRECIPITATION
     * AT A FIRST ORDER GRID POINT WILL BE ESTIMATED.')
  966 FORMAT(1H0, 9X, 2A4, 5X, I2, 4X, 'DAILY PRECIPITATION TOTALS EXCEE
     *DING ', F6.2, ' INCHES WILL NOT BE USED.')
  967 FORMAT(1H0, 9X, 2A4, 5X, I2, 4X, 'CONVECTIVE ESTIMATION OPTION IS
     *IN EFFECT. CONVECTIVE RADIUS = ', F5.0, ' MILES.')
  968 FORMAT(1H0, 9X, 2A4, 5X, I2, 4X, 'CONVECTIVE ESTIMATION OPTION IS
     *NOT IN EFFECT.')
  969 FORMAT(1H0, 9X, 2A4, 5X, I2, 4X, 'WGRFC FT. WORTH ESTIMATION PROCE
     *DURE NO. ', I2, ' WILL BE USED TO ESTIMATE MISSING PRECIPITATION.'
     *)
  970 FORMAT(1H0, 9X, 2A4, 5X, I2, 4X, 'STANDARD ESTIMATION PROCEDURE WI
     *LL BE USED TO ESTIMATE MISSING PRECIPITATION.')
  971 FORMAT(1H0, 9X, 2A4, 5X, I2, 4X, 'MAXIMUM OF ', I2, ' OBSERVATIONS
     * PER QUADRANT USED TO DEVELOP PRECIPITATION ESTIMATIONS.')
  972 FORMAT(1H0, 9X, 2A4, 5X, I2, 4X, 'MDR WILL BE USED TO ESTIMATE SIX
     *-HOURLY DISTRIBUTION PERCENTAGES.')
  973 FORMAT(1H0, 9X, 2A4, 5X, I2, 4X, 'MDR WILL BE USED TO ESTIMATE ZER
     *O 24-HOUR PRECIPITATION TOTALS.')
  974 FORMAT(1H0, 9X, 2A4, 5X, I2, 4X, 'MDR WILL BE USED TO ESTIMATE A 2
     *4-HOUR PRECIPITATION TOTAL UP TO ', F6.2, ' INCHES.')
  975 FORMAT(1H0, 9X, 2A4, 5X, I2, 4X, 'MDR WILL BE USED TO ESTIMATE ANY
     * 24-HOUR PRECIPITATION TOTAL.')
  976 FORMAT(1H0, 9X, 2A4, 5X, I2, 4X, 'A USER-SPECIFIED MDR PROBABILITY
     * TABLE OF ', I2, ' PERCENT WILL BE USED.')
  977 FORMAT(1H0, 9X, 2A4, 5X, I2, 4X, 'THE DEFAULT MDR PROBABILITY TABL
     *E OF ', I2, ' PERCENT WILL BE USED,', /, 29X, 'OR AN MDR PROBABILI
     *TY TABLE WILL BE DETERMINED FROM CALIBRATION', /, 29X, 'OF AVAILAB
     *LE SIX-HOURLY PRECIPITATION AND MDR ACCUMULATIONS.')
  978 FORMAT(1H0, 9X, 2A4, 5X, I2, 4X, 'STATION, MAPG, MARO, AND MAPI TI
     *ME SERIES ARE DISPLAYED IN ', 3A4)
  979 FORMAT(1H0, 9X, 2A4, 5X, I2, 4X, 'DISPLAY ONLY OBSERVED 24-HOUR PR
     *ECIPITATION.')
  980 FORMAT(1H0, 9X, 2A4, 5X, I2, 4X, 'DISPLAY BOTH OBSERVED AND ESTIMA
     *TED 24-HOUR PRECIPITATION.')
  981 FORMAT(1H0, 9X, 2A4, 5X, I2, 4X, 'DISPLAY SIX-HOURLY PRECIPITATION
     * AND PERCENTAGE DISTRIBUTIONS.')
  982 FORMAT(1H0, 9X, 2A4, 5X, I2, 4X, 'DISPLAY ZERO PRECIPITATION AMOUN
     *TS IN BOTH 24-HOUR AND SIX-HOURLY DISPLAYS.')
  983 FORMAT(1H0, 9X, 2A4, 5X, I2, 4X, 'DISPLAY THE MDR-FIRST ORDER PREC
     *IPITATION CALIBRATION SUMMARY.')
  984 FORMAT(1H0, 9X, 2A4, 5X, I2, 4X, 'DISPLAY THE MDR ACCUMULATION SIX
     *-HOURLY COMPARISON TABLE.')
  985 FORMAT(1H0, 9X, 2A4, 5X, I2, 4X, 'DISPLAY MARO, MAPG, AND MAPI TIM
     *E SERIES FOR EACH MARO AREA.')
  986 FORMAT(1H0, 9X, 2A4, 5X, I2, 4X, 'DISPLAY A MAXIMUM OF ', I2, ' MA
     *RO AREAS PER PAGE.')
  987 FORMAT(1H0, 9X, 2A4, 5X, I2, 4X, 'DISPLAY HYDROLOGIC GRID POINT DA
     *TA FOR ALL DEGREE BOXES.')
  988 FORMAT(1H0, 9X, 2A4, 5X, I2, 4X, 'DISPLAY HYDROLOGIC GRID POINT DA
     *TA FOR THE FOLLOWING DEGREE BOXES:', /, 29X, 20I3)
  989 FORMAT(29X, 'DISPLAY APIG (GRID POINT API)')
  990 FORMAT(29X, 'DISPLAY GRNF (GRID POINT RUNOFF)')
  991 FORMAT(29X, 'DISPLAY PG24 (GRID POINT 24-HOUR PRECIPITATION)')
  992 FORMAT(1H0, 9X, 2A4, 5X, I2, 4X, 'THE FOLLOWING DEBUG CODES ARE SP
     *ECIFIED:', /, 29X, A4, 1X, A4, 1X, A4, 1X, A4, 1X, A4, 1X, A4, 1X,
     * A4, 1X, A4, 1X, A4, 1X, A4, 1X, /, 29X, A4, 1X, A4, 1X, A4, 1X,
     * A4, 1X, A4, 1X, A4, 1X, A4, 1X, A4, 1X, A4, 1X, A4, 1X)
  993 FORMAT(1H0, 9X, 2A4, 5X, I2, 4X, 'FOR THOSE DEBUG CODES ACTIVATED
     *BY DEGREE BOX...DEBUG IS ON FOR ALL DEGREE BOXES.')
  994 FORMAT(1H0, 9X, 2A4, 5X, I2, 4X, 'FOR THOSE DEBUG CODES ACTIVATED
     *BY DEGREE BOX...DEBUG IS ON FOR THE FOLLOWING DEGREE BOXES:',
     * /, 29X, 20I3)
  995 FORMAT(1H0, 9X, 2A4, 5X, I2, 4X, 'ALL DEBUG CODES ARE TURNED ON.')
  996 FORMAT(1H0, 9X, 2A4, 5X, I2, 4X, 'THE TRACE LEVEL IS ', I2, '.')
C
      INCLUDE 'gcommon/setwhere'
C
      IF(IPTRCE .GE. 3) WRITE(IOPDBG,955)
C
      IBUG = IPBUG(GOPT)
C
C.....COMPUTE SMALL PRECIP FOR MDR.
C
      SPRECP = ISMALL
      SPRECP = SPRECP/100.
C
C.....WRITE OUT MARO TITLE BOX.
C
      WRITE(IPR,903)
      WRITE(IPR,904) IHBMO, IHBDAT, IHBYR, IHBHRS, ZTIME, IHYMO, IHYDAT,
     * IHYYR, IHYHRS, ZTIME
      WRITE(IPR,905) NWKDAY, MONTH, NDATE, NYEAR, ICHRS, ICMINS, ZTIME
      WRITE(IPR,959)
C
C.....NOW PRINT OUT THE VALUES OF THE TECHNIQUES BELOW THE MARO TITLE
C.....BOX. WE WILL PRINT OUT THE VALUES OF ONLY THE MORE SIGNIFICANT
C.....MARO RUN-TIME OPTIONS.
C
      WRITE(IPR,961)
C
C.....PP24TIME TECHNIQUE.
C
      JP = 63
      KP = 64
C
      IF(IPTCHK .EQ. 1) GOTO 110
      WRITE(IPR,962) NTECH(JP), NTECH(KP), IPTCHK
      GOTO 120
C
  110 WRITE(IPR,963) NTECH(JP), NTECH(KP), IPTCHK
C
C.....NOEST6HR TECHNIQUE.
C
  120 JP = 47
      KP = 48
C
      IF(NOEST6 .EQ. 0) GOTO 130
      WRITE(IPR,964) NTECH(JP), NTECH(KP), NOEST6
      GOTO 140
C
  130 WRITE(IPR,965) NTECH(JP), NTECH(KP), NOEST6
C
C.....PP24MAX TECHNIQUE.
C
  140 CALL HPAST('PP24MAX ', JPPMAX, ISTATC)
      IF(JPPMAX .EQ. 0) GOTO 150
C
      PCMAX = MAXPCP
      PCMAX = PCMAX/100.
C
      JP = 61
      KP = 62
      WRITE(IPR,966) NTECH(JP), NTECH(KP), JPPMAX, PCMAX
C
C.....CONVEC TECHNIQUE.
C
  150 JP = 17
      KP = 18
C
      IF(ICONVC .EQ. 0) GOTO 160
      WRITE(IPR,967) NTECH(JP), NTECH(KP), ICONVC, CNVDIS
      GOTO 170
C
  160 WRITE(IPR,968) NTECH(JP), NTECH(KP), ICONVC
C
C.....ESTFTW TECHNIQUE.
C
  170 JP = 27
      KP = 28
C
      IF(IADJQP .EQ. 0) GOTO 180
      WRITE(IPR,969) NTECH(JP), NTECH(KP), IADJQP, IADJQP
      GOTO 190
C
  180 WRITE(IPR,970) NTECH(JP), NTECH(KP), IADJQP
C
C.....NUMQDT TECHNIQUE.
C
  190 JP = 53
      KP = 54
C
      WRITE(IPR,971) NTECH(JP), NTECH(KP), NUMQDT, NUMQDT
C
C.....FTWQPF TECHNIQUE.
C
      JP = 93
      KP = 94
      IF(KQPFRN .EQ. 0) GOTO 196
C
C.....IN A QPF RUN...DON'T ATTEMPT TO USE MDR TO DISTRIBUTE THE
C.....PRECIPITATION.
C
      IF(MDRST6 .EQ. 0) GOTO 188
      MDRST6 = 0
      WRITE(IPR,897) MDRST6
      CALL WARN
C
  188 ISUM = 0
C
      DO 191 NP = 1, 4
      IF(KQPFD(NP) .LT. 0) KQPFD(NP) = 0
      ISUM = ISUM + KQPFD(NP)
  191 CONTINUE
C
C.....CHECK THE SUM TOTAL OF THE DISTRIBUTION FACTORS...TO SEE IF ANY
C.....WERE EVEN ENTERED.
C
      IF(ISUM .GT. 0) GOTO 193
C
C.....NO DISTRIBUTION FACTORS WERE ENTERED. SET AN EVEN DISTRIBUTION
C.....FOR NOW (MARO SUBROUTINE WILL LATER RE-COMPUTE IT).
C
      DO 192 NP = 1, 4
      IPCT(NP) = 25
  192 CONTINUE
      GOTO 195
C
C.....DISTRIBUTION FACTORS WERE ENTERED. NORMALIZE ALL FACTORS OVER
C.....FOUR SIX-HOURLY PERIODS FOR NOW (MARO SUBROUTINE WILL LATER
C.....RE-COMPUTE IT).
C
  193 X = ISUM
C
      DO 194 NP = 1, 4
      F = KQPFD(NP)
      IPCT(NP) = (F/X)*100. + 0.5
  194 CONTINUE
C
  195 WRITE(IPR,899) NTECH(JP), NTECH(KP), KQPFRN, (KQPFD(NP), IPCT(NP),
     * NP = 1, 4)
      GOTO 197
C
C.....WRITE MESSAGE WHICH SAYS THIS IS NOT A QPF RUN.
C
  196 WRITE(IPR,898) NTECH(JP), NTECH(KP), KQPFRN
C
C.....TEST MDR. IF MDR = 0...THEN SKIP THE NEXT BLOCK OF SEVERAL
C.....MDR-RELATED TECHNIQUES.
C
  197 IF(MDR .EQ. 0) GOTO 250
C
C.....MDRDIST TECHNIQUE. VALID ONLY IF MDR = 1.
C
      IF(MDRST6 .EQ. 0) GOTO 200
C
      JP = 31
      KP = 32
C
      WRITE(IPR,972) NTECH(JP), NTECH(KP), MDRST6
C
C.....MDREST24 TECHNIQUE.
C
  200 IF(MDRSTA .EQ. 0) GOTO 230
C
      JP = 35
      KP = 36
C
      IF(MDRSTA .EQ. 3) GOTO 220
      IF(MDRSTA .EQ. 2) GOTO 210
C
      WRITE(IPR,973) NTECH(JP), NTECH(KP), MDRSTA
      GOTO 230
C
  210 PSMALL = ISMALL
      PSMALL = PSMALL/100.
C
      WRITE(IPR,974) NTECH(JP), NTECH(KP), MDRSTA, PSMALL
      GOTO 230
C
  220 WRITE(IPR,975) NTECH(JP), NTECH(KP), MDRSTA
C
C.....NTABLE TECHNIQUE.
C
  230 JP = 45
      KP = 46
C
      IF(MDRUST .EQ. 0) GOTO 240
C
      WRITE(IPR,976) NTECH(JP), NTECH(KP), MDRUST, IUSTBL
      GOTO 250
C
  240 WRITE(IPR,977) NTECH(JP), NTECH(KP), MDRUST, NTABLE
C
C.....METRIC TECHNIQUE.
C
  250 JP = 37
      KP = 38
C
      NP = IANSW(METRIC)
      IP = (NP-1)*3 + 1
      LP = NP*3
C
      WRITE(IPR,978) NTECH(JP), NTECH(KP), METRIC, (MEAS(MP),MP=IP,LP)
C
C.....PRTPP24 TECHNIQUE.
C
      IF(IPRT24 .EQ. 0) GOTO 280
C
      JP = 79
      KP = 80
C
      IF(IPRT24 .EQ. 2) GOTO 270
      WRITE(IPR,979) NTECH(JP), NTECH(KP), IPRT24
      GOTO 280
C
  270 WRITE(IPR,980) NTECH(JP), NTECH(KP), IPRT24
C
C.....PRTPP6 TECHNIQUE.
C
  280 IF(IPRT6 .EQ. 0) GOTO 290
C
      JP = 77
      KP = 78
C
      WRITE(IPR,981) NTECH(JP), NTECH(KP), IPRT6
C
C.....PRTPPZRO TECHNIQUE. VALID ONLY IF IPRT24 > 0 OR IPRT6> 0.
C
  290 IF(IPRT24 .GT. 0) GOTO 300
      IF(IPRT6 .GT. 0) GOTO 300
      GOTO 310
C
  300 IF(IPRZRO .EQ. 0) GOTO 310
C
      JP = 81
      KP = 82
C
      WRITE(IPR,982) NTECH(JP), NTECH(KP), IPRZRO
C
C.....PRTMDR TECHNIQUE. VALID ONLY IF MDR = 1.
C
  310 IF(MDR .LT. 1) GOTO 330
      MDRPR6 = MDRPRT
      IF(MDRPRT .EQ. 0) GOTO 320
C
      JP = 73
      KP = 74
C
      WRITE(IPR,983) NTECH(JP), NTECH(KP), MDRPRT
C
C.....PRTMDR6 TECHNIQUE. VALID ONLY IF MDR = 1. NOT CURRENTLY IN USE.
C
  320 IF(MDRPR6 .EQ. 0) GOTO 330
C
      JP = 75
      KP = 76
C
      WRITE(IPR,984) NTECH(JP), NTECH(KP), MDRPR6
C
C.....PRTMARO TECHNIQUE.
C
  330 IF(MAROPT .EQ. 0) GOTO 340
C
      JP = 71
      KP = 72
C
      WRITE(IPR,985) NTECH(JP), NTECH(KP), MAROPT
C
C.....TECHNIQUE PGSZMARO. VALID ONLY IF MAROPT > 0.
C
      JP = 57
      KP = 58
C
      WRITE(IPR,986) NTECH(JP), NTECH(KP), NPAGE, NPAGE
C
C.....TECHNIQUE BOXDUMP.
C
  340 CALL HPAST('BOXDUMP ', IBXDSP, ISTATC)
      IF(IBXDSP .EQ. 0) GOTO 370
C
      JP = 15
      KP = 16
C
      IF(IBXDSP .EQ. 2) GOTO 350
      IF(NBXDSP .EQ. 0) IBXDSP = 0
      IF(IBXDSP .EQ. 0) GOTO 370
C
      WRITE(IPR,988) NTECH(JP), NTECH(KP), IBXDSP,
     * (MPTBOX(NP), NP = 1, NBXDSP)
      GOTO 360
C
  350 WRITE(IPR,987) NTECH(JP), NTECH(KP), IBXDSP
C
C.....TECHNIQUE BOXDKEY. VALID ONLY IF IBXDSP > 0.
C
  360 CALL HPAST('BOXDKEY ', JBXKEY, ISTATC)
      IF(JBXKEY .EQ. 0) GOTO 370
C
      IF(NUMAPI .GT. 0) WRITE(IPR,989)
      IF(NURNOF .GT. 0) WRITE(IPR,990)
      IF(NUPCPN .GT. 0) WRITE(IPR,991)
C
C.....PPDEBUG TECHNIQUE.
C
  370 CALL HPAST('PPDEBUG ', IPDBG, ISTATC)
      IF(IPDBG .EQ. 0) GOTO 410
C
      JP = 65
      KP = 66
C
      IF(IPDBG .EQ. 2) GOTO 380
      IF(NDBUG .EQ. 0) IPDBG = 0
      IF(IPDBG .EQ. 0) GOTO 390
C
      WRITE(IPR,992) NTECH(JP), NTECH(KP), IPDBG,
     * (PDBUG(NP), NP = 1, NDBUG)
      GOTO 390
C
  380 WRITE(IPR,995) NTECH(JP), NTECH(KP), IPDBG
C
C.....TECHNIQUE BOXDEBUG. VALID ONLY IF IPDBG > 0.
C
  390 CALL HPAST('BOXDEBUG', IBXDB, ISTATC)
      IF(IBXDB .EQ. 0) GOTO 410
C
      JP = 11
      KP = 12
C
      IF(IBXDB .EQ. 2) GOTO 400
      IF(NBXDBG .EQ. 0) IBXDB = 0
      IF(IBXDB  .EQ. 0) GOTO 410
C
      WRITE(IPR,994) NTECH(JP), NTECH(KP), IBXDB,
     * (NTRBOX(NP), NP = 1, NBXDBG)
      GOTO 410
C
  400 WRITE(IPR,993) NTECH(JP), NTECH(KP), IBXDB
C
C.....TECHNIQUE PPTRACE.
C
  410 JP = 69
      KP = 70
C
      WRITE(IPR,996) NTECH(JP), NTECH(KP), IPTRCE, IPTRCE
C
C.....NOW TEST IF DEBUG OUTPUT IS DESIRED.
C
      IF(IBUG .EQ. 1) GOTO 800
      GOTO 999
C
C
C.....WRITE OUT MARO DATE-TIME INFORMATION.
C
  800 WRITE(IOPDBG,907)
      WRITE(IOPDBG,908)
      WRITE(IOPDBG,909) IHBDA, IHBDAY, IHBMON, IHBDAT,
     * IHBYR, ITIME6(NUMPD1), ZTIME, IHBWK, IBEGDA, IHRRUN
      WRITE(IOPDBG,910) IHYDA, IHYDAY, IHYMON, IHYDAT,
     * IHYYR, ITIME6(NUMPD1), ZTIME, IHYWK, ICURDA, LHRRUN
      IF(IATSA .EQ. 0) WRITE(IOPDBG,911) NWKDAY, MONTH, NDATE, NYEAR,
     * LTSLOT, ZTIME
      WRITE(IOPDBG,907)
C
C.....NOW WRITE OUT THE DISPLAY OPTIONS.
C
      WRITE(IOPDBG,907)
C
      NP = IANSW(METRIC)
      WRITE(IOPDBG,921) UNITS(NP*2-1), UNITS(NP*2)
      WRITE(IOPDBG,912)
C
      JP = IANSW(IPRT24)
      KP = IANSW(IPREST)
      NP = IANSW(IPRZRO)
      WRITE(IOPDBG,913) ANS(JP), ANS(KP), ANS(NP)
C
      JP = IANSW(IPRT6)
      WRITE(IOPDBG,914) ANS(JP), ANS(KP), ANS(NP)
C
      NP = IANSW(MAROPT)
      WRITE(IOPDBG,915) ANS(NP), NPAGE
C
      IP = MDRPRT
      IF(IP .GT. 1) IP = 1
      JP = IANSW(IP)
      IF(JP .EQ. 2) GOTO 810
      KP = 1
      NP = 2
      IF(MDRPRT .EQ. 2) NP = 1
      GOTO 820
C
  810 KP = 2
      NP = 2
  820 WRITE(IOPDBG,916) ANS(JP), ANS(KP), ANS(NP)
C
      KP = IANSW(IPLT24)
      NP = 2
      IF(KP .EQ. 2) GOTO 830
      NP = IANSW(IPLEST)
  830 WRITE(IOPDBG,917) ANS(KP), ANS(NP)
C
      KP = IANSW(IPRTBX)
      NP = IANSW(IPLTBX)
      WRITE(IOPDBG,918) ANS(KP), ANS(NP)
C
      IP = 2
      LP = 2
      MP = 2
      IF((KP .EQ. 2) .AND. (NP .EQ. 2)) GOTO 840
      IF(NUPCPN .GT. 0) IP = 1
      IF(NUMAPI .GT. 0) LP = 1
      IF(NURNOF .GT. 0) MP = 1
  840 WRITE(IOPDBG,919) ANS(IP), ANS(LP), ANS(MP)
      IF((IP .EQ. 1) .OR. (LP .EQ. 1) .OR. (MP .EQ. 1))
     * WRITE(IOPDBG,920) (MPTBOX(NP), NP = 1, 20)
      WRITE(IOPDBG,907)
C
C.....WRITE OUT THE MDR USAGE OPTIONS.
C
      WRITE(IOPDBG,907)
      WRITE(IOPDBG,922)
      IF(MDR .EQ. 1) WRITE(IOPDBG,923)
      IF(MDR .EQ. 0) WRITE(IOPDBG,924)
      WRITE(IOPDBG,925)
      IF(MDRSTA .EQ. 0) WRITE(IOPDBG,926)
      IF(MDRSTA .EQ. 1) WRITE(IOPDBG,927)
      IF(MDRSTA .EQ. 2) WRITE(IOPDBG,928) SPRECP
      IF(MDRSTA .EQ. 3) WRITE(IOPDBG,929)
      IF(MDRST6 .EQ. 1) WRITE(IOPDBG,930)
      IF(MDRST6 .EQ. 0) WRITE(IOPDBG,931)
      IF(MDRUST .EQ. 0) WRITE(IOPDBG,932) NTABLE
      IF(MDRUST .EQ. 1) WRITE(IOPDBG,932) IUSTBL
      IF(MDRUST .EQ. 0) WRITE(IOPDBG,933)
      IF(MDRUST .EQ. 1) WRITE(IOPDBG,934)
      WRITE(IOPDBG,907)
C
C.....WRITE OUT THE PRECIPITATION, API, AND RUNOFF-RELATED OPTIONS
C.....THAT ARE IN EFFECT.
C
      WRITE(IOPDBG,907)
      WRITE(IOPDBG,935)
      IF(IESTPX .EQ. 1) WRITE(IOPDBG,957)
      IF(IESTPX .EQ. 0) WRITE(IOPDBG,958)
      IF(ICONVC .EQ. 0) WRITE(IOPDBG,937)
      IF(ICONVC .EQ. 1) WRITE (IOPDBG,936) CNVDIS
      WRITE(IOPDBG,938) IADJQP
      IF(NOEST6 .EQ. 0) WRITE(IOPDBG,939)
      IF(NOEST6 .EQ. 1) WRITE(IOPDBG,940)
      WRITE(IOPDBG,941) NUMQDT, NQSET
      IF(NDRSET .EQ. 1) WRITE(IOPDBG,942) DUR
      IF(NDRSET .EQ. 0) WRITE(IOPDBG,943) DUR
      IF(NRCSET .EQ. 1) WRITE(IOPDBG,944) REC
      IF(NRCSET .EQ. 0) WRITE(IOPDBG,945) REC
      WRITE(IOPDBG,946) APIMNR
      WRITE(IOPDBG,947) APIDEC
      WRITE(IOPDBG,948) APIMAX, APIMIN
      WRITE(IOPDBG,907)
C
C.....PRINT OUT THE MARO TRACE/DEBUG CODES.
C
      WRITE(IOPDBG,907)
      WRITE(IOPDBG,949)
      WRITE(IOPDBG,950) IPTRCE, NOBUG
      IF(IPALL .EQ. 1) WRITE(IOPDBG,951)
      IF(IPALL .NE. 1) WRITE(IOPDBG,952) (PDBUG(NP), NP = 1, NDBUG)
      IF(IPBOXA .EQ. 1) WRITE(IOPDBG,953)
      IF(IPBOXA .NE. 1) WRITE(IOPDBG,954) (NTRBOX(NP), NP = 1, NBXDBG)
      WRITE(IOPDBG,907)
C
  999 IF(IPTRCE .GE. 3) WRITE(IOPDBG,956)
C
      RETURN
      END
