/*
** Generated by X-Designer
*/
/*
**LIBS: -lXm -lXt -lX11
*/

#include <stdlib.h>
#include <X11/Xatom.h>
#include <X11/Intrinsic.h>
#include <X11/Shell.h>

#include <Xm/Xm.h>
#include <X11/StringDefs.h>
#include <Xm/DialogS.h>
#include <Xm/Form.h>
#include <Xm/Label.h>
#include <Xm/PushB.h>
#include <Xm/RowColumn.h>
#include <Xm/Scale.h>
#include <Xm/Separator.h>
#include <Xm/ToggleB.h>
#include <Xm/ToggleBG.h>


Widget display_edit_precip_polyDS = (Widget) NULL;
Widget display_edit_precip_polyFO = (Widget) NULL;
Widget edit_precip_polySubLB = (Widget) NULL;
Widget edit_precip_polySubPB = (Widget) NULL;
Widget edit_precip_polySP = (Widget) NULL;
Widget edit_precip_polyClosePB = (Widget) NULL;
Widget precipModeRB = (Widget) NULL;
Widget rMosaicTB = (Widget) NULL;
Widget avgRMosaicTB = (Widget) NULL;
Widget maxRMosaicTB = (Widget) NULL;
Widget bMosaicTB = (Widget) NULL;
Widget lMosaicTB = (Widget) NULL;
Widget gageOnlyTB = (Widget) NULL;
Widget mMosaicTB = (Widget) NULL;
Widget locMMosaicTB = (Widget) NULL;
Widget satPrecipTB = (Widget) NULL;
Widget locSatPrecipTB = (Widget) NULL;
Widget srMosaicTB = (Widget) NULL;
Widget sgMosaicTB = (Widget) NULL;
Widget srgMosaicTB = (Widget) NULL;
Widget p3LMosaicTB = (Widget) NULL;
Widget xmrgTB = (Widget) NULL;
Widget rfcBMosaicTB = (Widget) NULL;
Widget rfcMMosaicTB = (Widget) NULL;
Widget rfcMosaicTB = (Widget) NULL;
Widget adjust_precip_valLB = (Widget) NULL;
Widget adjust_precip_valSC = (Widget) NULL;
Widget adjust_setPB = (Widget) NULL;
Widget adjust_raisePB = (Widget) NULL;
Widget adjust_lowerPB = (Widget) NULL;
Widget adjust_scalePB = (Widget) NULL;
Widget adjust_precip_valSP = (Widget) NULL;
Widget persistentTB = (Widget) NULL;
Widget adjust_snowPB = (Widget) NULL;


static int _xd_initialised = 0 ;

typedef struct PixelResources_s { 
	Pixel blue;
} PixelResources_t, *PixelResources_p;

static PixelResources_t pixel_resources;


static void initialise_objects(Widget parent)
{
	XrmValue     from_value, to_value; /* For resource conversions */

	if (_xd_initialised) {
		return ;
	}

	_xd_initialised = 1;

	while (XtParent(parent)) {
		parent = XtParent(parent);
	}


	if (DefaultDepthOfScreen(DefaultScreenOfDisplay(XtDisplay(parent))) != 1) {
		from_value.addr = "#c4c4c4c4c4c4";
		from_value.size = strlen(from_value.addr)+1;

		pixel_resources.blue = XmUNSPECIFIED_PIXEL;

		to_value.size = sizeof(Pixel);
		to_value.addr = (XPointer) &pixel_resources.blue;
		XtConvertAndStore( parent, XmRString, &from_value, XmRPixel, &to_value);
	}
}


void create_display_edit_precip_polyDS (Widget parent)
{
	Widget children[18];      /* Children to manage */
	Display *display = XtDisplay ( parent );
	Arg al[64];                    /* Arg List */
	register int ac = 0;           /* Arg Count */
	XrmValue from_value, to_value; /* For resource conversion */
	XPointer to_address; /* For Thread-safe resource conversion */ 
	Pixel to_pixel; /* For Thread-safe resource conversion */ 
	XmFontList to_fontlist; /* For Thread-safe resource conversion */ 
	XtPointer tmp_value;             /* ditto */
	XmString xmstrings[16];    /* temporary storage for XmStrings */

	XtSetArg(al[ac], XmNwidth, 300); ac++;
	XtSetArg(al[ac], XmNheight, 770); ac++;
	XtSetArg(al[ac], XmNallowShellResize, FALSE); ac++;
	XtSetArg(al[ac], XmNtitle, "Edit Precipitation"); ac++;
	XtSetArg(al[ac], XmNminWidth, 300); ac++;
	XtSetArg(al[ac], XmNminHeight, 770); ac++;
	XtSetArg(al[ac], XmNmaxWidth, 300); ac++;
	XtSetArg(al[ac], XmNmaxHeight, 770); ac++;
	XtSetArg(al[ac], XmNbaseWidth, 300); ac++;
	XtSetArg(al[ac], XmNbaseHeight, 770); ac++;
	display_edit_precip_polyDS = XmCreateDialogShell ( parent, (char *) "display_edit_precip_polyDS", al, ac );
	ac = 0;
	initialise_objects ( display_edit_precip_polyDS );
	XtSetArg(al[ac], XmNx, 166); ac++;
	XtSetArg(al[ac], XmNwidth, 300); ac++;
	XtSetArg(al[ac], XmNheight, 770); ac++;
	XtSetArg(al[ac], XmNnoResize, TRUE); ac++;
	XtSetArg(al[ac], XmNresizePolicy, XmRESIZE_NONE); ac++;
	XtSetArg(al[ac], XmNautoUnmanage, FALSE); ac++;
	display_edit_precip_polyFO = XmCreateForm ( display_edit_precip_polyDS, (char *) "display_edit_precip_polyFO", al, ac );
	ac = 0;
	XtSetArg(al[ac], XmNwidth, 165); ac++;
	if (DefaultDepthOfScreen(DefaultScreenOfDisplay(display)) != 1) {

		from_value.addr = "#ffff00000000" ;
		from_value.size = strlen( from_value.addr ) + 1;
		to_value.size = sizeof(Pixel);
		to_value.addr = (XPointer) &to_pixel;
		XtConvertAndStore (display_edit_precip_polyFO, XmRString, &from_value, XmRPixel, &to_value);

		if ( to_value.addr ) {
			XtSetArg(al[ac], XmNforeground, (*((Pixel*) to_value.addr))); ac++;
		}
	}
	xmstrings[0] = XmStringGenerate ( (XtPointer) "Select Field To Substitute", XmFONTLIST_DEFAULT_TAG, XmCHARSET_TEXT, NULL );
	XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;

	from_value.addr = "-misc-fixed-bold-r-normal--13-120-75-75-c-70-iso8859-1" ;
	from_value.size = strlen( from_value.addr ) + 1;
	to_value.size = sizeof(XmFontList);
	to_value.addr = (XPointer) &to_fontlist;
	XtConvertAndStore (display_edit_precip_polyFO, XmRString, &from_value, XmRFontList, &to_value);

	if ( to_value.addr ) {
		XtSetArg(al[ac], XmNfontList, (*((XmFontList*) to_value.addr))); ac++;
	}
	edit_precip_polySubLB = XmCreateLabel ( display_edit_precip_polyFO, (char *) "edit_precip_polySubLB", al, ac );
	ac = 0;
	XmStringFree ( xmstrings [ 0 ] );
	XtSetArg(al[ac], XmNwidth, 80); ac++;
	if (DefaultDepthOfScreen(DefaultScreenOfDisplay(display)) != 1) {

		from_value.addr = "snow" ;
		from_value.size = strlen( from_value.addr ) + 1;
		to_value.size = sizeof(Pixel);
		to_value.addr = (XPointer) &to_pixel;
		XtConvertAndStore (display_edit_precip_polyFO, XmRString, &from_value, XmRPixel, &to_value);

		if ( to_value.addr ) {
			XtSetArg(al[ac], XmNforeground, (*((Pixel*) to_value.addr))); ac++;
		}
	}
	if (DefaultDepthOfScreen(DefaultScreenOfDisplay(display)) != 1) {

		from_value.addr = "blue3" ;
		from_value.size = strlen( from_value.addr ) + 1;
		to_value.size = sizeof(Pixel);
		to_value.addr = (XPointer) &to_pixel;
		XtConvertAndStore (display_edit_precip_polyFO, XmRString, &from_value, XmRPixel, &to_value);

		if ( to_value.addr ) {
			XtSetArg(al[ac], XmNbackground, (*((Pixel*) to_value.addr))); ac++;
		}
	}
	xmstrings[0] = XmStringGenerate ( (XtPointer) "Substitute", XmFONTLIST_DEFAULT_TAG, XmCHARSET_TEXT, NULL );
	XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
	edit_precip_polySubPB = XmCreatePushButton ( display_edit_precip_polyFO, (char *) "edit_precip_polySubPB", al, ac );
	ac = 0;
	XmStringFree ( xmstrings [ 0 ] );
	if (DefaultDepthOfScreen(DefaultScreenOfDisplay(display)) != 1) {

		from_value.addr = "coral" ;
		from_value.size = strlen( from_value.addr ) + 1;
		to_value.size = sizeof(Pixel);
		to_value.addr = (XPointer) &to_pixel;
		XtConvertAndStore (display_edit_precip_polyFO, XmRString, &from_value, XmRPixel, &to_value);

		if ( to_value.addr ) {
			XtSetArg(al[ac], XmNforeground, (*((Pixel*) to_value.addr))); ac++;
		}
	}
	edit_precip_polySP = XmCreateSeparator ( display_edit_precip_polyFO, (char *) "edit_precip_polySP", al, ac );
	ac = 0;
	if (DefaultDepthOfScreen(DefaultScreenOfDisplay(display)) != 1) {

		from_value.addr = "snow" ;
		from_value.size = strlen( from_value.addr ) + 1;
		to_value.size = sizeof(Pixel);
		to_value.addr = (XPointer) &to_pixel;
		XtConvertAndStore (display_edit_precip_polyFO, XmRString, &from_value, XmRPixel, &to_value);

		if ( to_value.addr ) {
			XtSetArg(al[ac], XmNforeground, (*((Pixel*) to_value.addr))); ac++;
		}
	}
	if (DefaultDepthOfScreen(DefaultScreenOfDisplay(display)) != 1) {

		from_value.addr = "dark red" ;
		from_value.size = strlen( from_value.addr ) + 1;
		to_value.size = sizeof(Pixel);
		to_value.addr = (XPointer) &to_pixel;
		XtConvertAndStore (display_edit_precip_polyFO, XmRString, &from_value, XmRPixel, &to_value);

		if ( to_value.addr ) {
			XtSetArg(al[ac], XmNbackground, (*((Pixel*) to_value.addr))); ac++;
		}
	}
	xmstrings[0] = XmStringGenerate ( (XtPointer) "Close", XmFONTLIST_DEFAULT_TAG, XmCHARSET_TEXT, NULL );
	XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
	XtSetArg(al[ac], XmNrecomputeSize, FALSE); ac++;
	edit_precip_polyClosePB = XmCreatePushButton ( display_edit_precip_polyFO, (char *) "edit_precip_polyClosePB", al, ac );
	ac = 0;
	XmStringFree ( xmstrings [ 0 ] );
	XtSetArg(al[ac], XmNheight, 660); ac++;
	precipModeRB = XmCreateRadioBox ( display_edit_precip_polyFO, (char *) "precipModeRB", al, ac );
	ac = 0;
	XtSetArg(al[ac], XmNx, 3); ac++;
	XtSetArg(al[ac], XmNy, 3); ac++;
	xmstrings[0] = XmStringGenerate ( (XtPointer) "Radar Mosaic", XmFONTLIST_DEFAULT_TAG, XmCHARSET_TEXT, NULL );
	XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
	XtSetArg(al[ac], XmNrecomputeSize, FALSE); ac++;
	rMosaicTB = XmCreateToggleButtonGadget ( precipModeRB, (char *) "rMosaicTB", al, ac );
	ac = 0;
	XmStringFree ( xmstrings [ 0 ] );
	XtSetArg(al[ac], XmNx, 3); ac++;
	XtSetArg(al[ac], XmNy, 30); ac++;
	xmstrings[0] = XmStringGenerate ( (XtPointer) "Average Radar Mosaic", XmFONTLIST_DEFAULT_TAG, XmCHARSET_TEXT, NULL );
	XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
	avgRMosaicTB = XmCreateToggleButtonGadget ( precipModeRB, (char *) "avgRMosaicTB", al, ac );
	ac = 0;
	XmStringFree ( xmstrings [ 0 ] );
	XtSetArg(al[ac], XmNx, 3); ac++;
	XtSetArg(al[ac], XmNy, 57); ac++;
	xmstrings[0] = XmStringGenerate ( (XtPointer) "Max Radar Mosaic", XmFONTLIST_DEFAULT_TAG, XmCHARSET_TEXT, NULL );
	XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
	maxRMosaicTB = XmCreateToggleButtonGadget ( precipModeRB, (char *) "maxRMosaicTB", al, ac );
	ac = 0;
	XmStringFree ( xmstrings [ 0 ] );
	xmstrings[0] = XmStringGenerate ( (XtPointer) "Field Bias Radar Mosaic", XmFONTLIST_DEFAULT_TAG, XmCHARSET_TEXT, NULL );
	XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
	bMosaicTB = XmCreateToggleButtonGadget ( precipModeRB, (char *) "bMosaicTB", al, ac );
	ac = 0;
	XmStringFree ( xmstrings [ 0 ] );
	XtSetArg(al[ac], XmNx, 3); ac++;
	XtSetArg(al[ac], XmNy, 111); ac++;
	xmstrings[0] = XmStringGenerate ( (XtPointer) "Local Bias Radar Mosaic", XmFONTLIST_DEFAULT_TAG, XmCHARSET_TEXT, NULL );
	XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
	lMosaicTB = XmCreateToggleButtonGadget ( precipModeRB, (char *) "lMosaicTB", al, ac );
	ac = 0;
	XmStringFree ( xmstrings [ 0 ] );
	XtSetArg(al[ac], XmNx, 3); ac++;
	XtSetArg(al[ac], XmNy, 138); ac++;
	XtSetArg(al[ac], XmNwidth, 221); ac++;
	XtSetArg(al[ac], XmNheight, 1); ac++;
	xmstrings[0] = XmStringGenerate ( (XtPointer) "Gage Only Analysis", XmFONTLIST_DEFAULT_TAG, XmCHARSET_TEXT, NULL );
	XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
	gageOnlyTB = XmCreateToggleButtonGadget ( precipModeRB, (char *) "gageOnlyTB", al, ac );
	ac = 0;
	XmStringFree ( xmstrings [ 0 ] );
	XtSetArg(al[ac], XmNx, 3); ac++;
	XtSetArg(al[ac], XmNy, 165); ac++;
	xmstrings[0] = XmStringGenerate ( (XtPointer) "Multisensor Mosaic", XmFONTLIST_DEFAULT_TAG, XmCHARSET_TEXT, NULL );
	XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
	mMosaicTB = XmCreateToggleButtonGadget ( precipModeRB, (char *) "mMosaicTB", al, ac );
	ac = 0;
	XmStringFree ( xmstrings [ 0 ] );
	XtSetArg(al[ac], XmNx, 3); ac++;
	XtSetArg(al[ac], XmNy, 192); ac++;
	xmstrings[0] = XmStringGenerate ( (XtPointer) "Local Bias Multisensor Mosaic", XmFONTLIST_DEFAULT_TAG, XmCHARSET_TEXT, NULL );
	XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
	locMMosaicTB = XmCreateToggleButtonGadget ( precipModeRB, (char *) "locMMosaicTB", al, ac );
	ac = 0;
	XmStringFree ( xmstrings [ 0 ] );
	xmstrings[0] = XmStringGenerate ( (XtPointer) "Satellite Precip", XmFONTLIST_DEFAULT_TAG, XmCHARSET_TEXT, NULL );
	XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
	satPrecipTB = XmCreateToggleButtonGadget ( precipModeRB, (char *) "satPrecipTB", al, ac );
	ac = 0;
	XmStringFree ( xmstrings [ 0 ] );
	xmstrings[0] = XmStringGenerate ( (XtPointer) "Local Bias Satellite Precip", XmFONTLIST_DEFAULT_TAG, XmCHARSET_TEXT, NULL );
	XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
	locSatPrecipTB = XmCreateToggleButtonGadget ( precipModeRB, (char *) "locSatPrecipTB", al, ac );
	ac = 0;
	XmStringFree ( xmstrings [ 0 ] );
	XtSetArg(al[ac], XmNx, 3); ac++;
	XtSetArg(al[ac], XmNy, 273); ac++;
	xmstrings[0] = XmStringGenerate ( (XtPointer) "Satellite Radar Mosaic", XmFONTLIST_DEFAULT_TAG, XmCHARSET_TEXT, NULL );
	XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
	srMosaicTB = XmCreateToggleButtonGadget ( precipModeRB, (char *) "srMosaicTB", al, ac );
	ac = 0;
	XmStringFree ( xmstrings [ 0 ] );
	xmstrings[0] = XmStringGenerate ( (XtPointer) "Satellite Gage Mosaic", XmFONTLIST_DEFAULT_TAG, XmCHARSET_TEXT, NULL );
	XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
	sgMosaicTB = XmCreateToggleButtonGadget ( precipModeRB, (char *) "sgMosaicTB", al, ac );
	ac = 0;
	XmStringFree ( xmstrings [ 0 ] );
	xmstrings[0] = XmStringGenerate ( (XtPointer) "Satellite Radar Gage Mosaic", XmFONTLIST_DEFAULT_TAG, XmCHARSET_TEXT, NULL );
	XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
	srgMosaicTB = XmCreateToggleButtonGadget ( precipModeRB, (char *) "srgMosaicTB", al, ac );
	ac = 0;
	XmStringFree ( xmstrings [ 0 ] );
	XtSetArg(al[ac], XmNx, 3); ac++;
	XtSetArg(al[ac], XmNy, 354); ac++;
	xmstrings[0] = XmStringGenerate ( (XtPointer) "Triangulated Local Bias Mosaic", XmFONTLIST_DEFAULT_TAG, XmCHARSET_TEXT, NULL );
	XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
	p3LMosaicTB = XmCreateToggleButtonGadget ( precipModeRB, (char *) "p3LMosaicTB", al, ac );
	ac = 0;
	XmStringFree ( xmstrings [ 0 ] );
	xmstrings[0] = XmStringGenerate ( (XtPointer) "Best Estimate QPE", XmFONTLIST_DEFAULT_TAG, XmCHARSET_TEXT, NULL );
	XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
	xmrgTB = XmCreateToggleButtonGadget ( precipModeRB, (char *) "xmrgTB", al, ac );
	ac = 0;
	XmStringFree ( xmstrings [ 0 ] );
	xmstrings[0] = XmStringGenerate ( (XtPointer) "RFC Field Bias Mosaic", XmFONTLIST_DEFAULT_TAG, XmCHARSET_TEXT, NULL );
	XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
	rfcBMosaicTB = XmCreateToggleButtonGadget ( precipModeRB, (char *) "rfcBMosaicTB", al, ac );
	ac = 0;
	XmStringFree ( xmstrings [ 0 ] );
	xmstrings[0] = XmStringGenerate ( (XtPointer) "RFC Multisensor Mosaic", XmFONTLIST_DEFAULT_TAG, XmCHARSET_TEXT, NULL );
	XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
	rfcMMosaicTB = XmCreateToggleButtonGadget ( precipModeRB, (char *) "rfcMMosaicTB", al, ac );
	ac = 0;
	XmStringFree ( xmstrings [ 0 ] );
	xmstrings[0] = XmStringGenerate ( (XtPointer) "RFC QPE Mosaic", XmFONTLIST_DEFAULT_TAG, XmCHARSET_TEXT, NULL );
	XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
	rfcMosaicTB = XmCreateToggleButtonGadget ( precipModeRB, (char *) "rfcMosaicTB", al, ac );
	ac = 0;
	XmStringFree ( xmstrings [ 0 ] );
	if (DefaultDepthOfScreen(DefaultScreenOfDisplay(display)) != 1) {

		from_value.addr = "#ffff00000000" ;
		from_value.size = strlen( from_value.addr ) + 1;
		to_value.size = sizeof(Pixel);
		to_value.addr = (XPointer) &to_pixel;
		XtConvertAndStore (display_edit_precip_polyFO, XmRString, &from_value, XmRPixel, &to_value);

		if ( to_value.addr ) {
			XtSetArg(al[ac], XmNforeground, (*((Pixel*) to_value.addr))); ac++;
		}
	}
	xmstrings[0] = XmStringGenerate ( (XtPointer) "Adjust Precipitation Value", XmFONTLIST_DEFAULT_TAG, XmCHARSET_TEXT, NULL );
	XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;

	from_value.addr = "-misc-fixed-bold-r-normal--13-120-75-75-c-70-iso8859-8" ;
	from_value.size = strlen( from_value.addr ) + 1;
	to_value.size = sizeof(XmFontList);
	to_value.addr = (XPointer) &to_fontlist;
	XtConvertAndStore (display_edit_precip_polyFO, XmRString, &from_value, XmRFontList, &to_value);

	if ( to_value.addr ) {
		XtSetArg(al[ac], XmNfontList, (*((XmFontList*) to_value.addr))); ac++;
	}
	adjust_precip_valLB = XmCreateLabel ( display_edit_precip_polyFO, (char *) "adjust_precip_valLB", al, ac );
	ac = 0;
	XmStringFree ( xmstrings [ 0 ] );
	xmstrings[0] = XmStringGenerate ( (XtPointer) " ", XmFONTLIST_DEFAULT_TAG, XmCHARSET_TEXT, NULL );
	XtSetArg(al[ac], XmNtitleString, xmstrings[0]); ac++;
	XtSetArg(al[ac], XmNshowValue, TRUE); ac++;
	XtSetArg(al[ac], XmNminimum, 0); ac++;
	XtSetArg(al[ac], XmNmaximum, 500); ac++;
	XtSetArg(al[ac], XmNvalue, 0); ac++;
	XtSetArg(al[ac], XmNorientation, XmHORIZONTAL); ac++;
	XtSetArg(al[ac], XmNprocessingDirection, XmMAX_ON_RIGHT); ac++;
	XtSetArg(al[ac], XmNdecimalPoints, 2); ac++;
	XtSetArg(al[ac], XmNscaleMultiple, 1); ac++;
	adjust_precip_valSC = XmCreateScale ( display_edit_precip_polyFO, (char *) "adujst_precip_valSC", al, ac );
	ac = 0;
	XmStringFree ( xmstrings [ 0 ] );
	if (DefaultDepthOfScreen(DefaultScreenOfDisplay(display)) != 1) {

		from_value.addr = "snow" ;
		from_value.size = strlen( from_value.addr ) + 1;
		to_value.size = sizeof(Pixel);
		to_value.addr = (XPointer) &to_pixel;
		XtConvertAndStore (display_edit_precip_polyFO, XmRString, &from_value, XmRPixel, &to_value);

		if ( to_value.addr ) {
			XtSetArg(al[ac], XmNforeground, (*((Pixel*) to_value.addr))); ac++;
		}
	}
	if (DefaultDepthOfScreen(DefaultScreenOfDisplay(display)) != 1) {

		from_value.addr = "blue3" ;
		from_value.size = strlen( from_value.addr ) + 1;
		to_value.size = sizeof(Pixel);
		to_value.addr = (XPointer) &to_pixel;
		XtConvertAndStore (display_edit_precip_polyFO, XmRString, &from_value, XmRPixel, &to_value);

		if ( to_value.addr ) {
			XtSetArg(al[ac], XmNbackground, (*((Pixel*) to_value.addr))); ac++;
		}
	}
	xmstrings[0] = XmStringGenerate ( (XtPointer) "Set", XmFONTLIST_DEFAULT_TAG, XmCHARSET_TEXT, NULL );
	XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
	XtSetArg(al[ac], XmNrecomputeSize, FALSE); ac++;
	adjust_setPB = XmCreatePushButton ( display_edit_precip_polyFO, (char *) "adjust_setPB", al, ac );
	ac = 0;
	XmStringFree ( xmstrings [ 0 ] );
	if (DefaultDepthOfScreen(DefaultScreenOfDisplay(display)) != 1) {

		from_value.addr = "snow" ;
		from_value.size = strlen( from_value.addr ) + 1;
		to_value.size = sizeof(Pixel);
		to_value.addr = (XPointer) &to_pixel;
		XtConvertAndStore (display_edit_precip_polyFO, XmRString, &from_value, XmRPixel, &to_value);

		if ( to_value.addr ) {
			XtSetArg(al[ac], XmNforeground, (*((Pixel*) to_value.addr))); ac++;
		}
	}
	if (DefaultDepthOfScreen(DefaultScreenOfDisplay(display)) != 1) {

		from_value.addr = "blue3" ;
		from_value.size = strlen( from_value.addr ) + 1;
		to_value.size = sizeof(Pixel);
		to_value.addr = (XPointer) &to_pixel;
		XtConvertAndStore (display_edit_precip_polyFO, XmRString, &from_value, XmRPixel, &to_value);

		if ( to_value.addr ) {
			XtSetArg(al[ac], XmNbackground, (*((Pixel*) to_value.addr))); ac++;
		}
	}
	xmstrings[0] = XmStringGenerate ( (XtPointer) "Raise", XmFONTLIST_DEFAULT_TAG, XmCHARSET_TEXT, NULL );
	XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
	adjust_raisePB = XmCreatePushButton ( display_edit_precip_polyFO, (char *) "adjust_raisePB", al, ac );
	ac = 0;
	XmStringFree ( xmstrings [ 0 ] );
	if (DefaultDepthOfScreen(DefaultScreenOfDisplay(display)) != 1) {

		from_value.addr = "snow" ;
		from_value.size = strlen( from_value.addr ) + 1;
		to_value.size = sizeof(Pixel);
		to_value.addr = (XPointer) &to_pixel;
		XtConvertAndStore (display_edit_precip_polyFO, XmRString, &from_value, XmRPixel, &to_value);

		if ( to_value.addr ) {
			XtSetArg(al[ac], XmNforeground, (*((Pixel*) to_value.addr))); ac++;
		}
	}
	if (DefaultDepthOfScreen(DefaultScreenOfDisplay(display)) != 1) {

		from_value.addr = "blue3" ;
		from_value.size = strlen( from_value.addr ) + 1;
		to_value.size = sizeof(Pixel);
		to_value.addr = (XPointer) &to_pixel;
		XtConvertAndStore (display_edit_precip_polyFO, XmRString, &from_value, XmRPixel, &to_value);

		if ( to_value.addr ) {
			XtSetArg(al[ac], XmNbackground, (*((Pixel*) to_value.addr))); ac++;
		}
	}
	xmstrings[0] = XmStringGenerate ( (XtPointer) "Lower", XmFONTLIST_DEFAULT_TAG, XmCHARSET_TEXT, NULL );
	XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
	adjust_lowerPB = XmCreatePushButton ( display_edit_precip_polyFO, (char *) "adjust_lowerPB", al, ac );
	ac = 0;
	XmStringFree ( xmstrings [ 0 ] );
	if (DefaultDepthOfScreen(DefaultScreenOfDisplay(display)) != 1) {

		from_value.addr = "snow" ;
		from_value.size = strlen( from_value.addr ) + 1;
		to_value.size = sizeof(Pixel);
		to_value.addr = (XPointer) &to_pixel;
		XtConvertAndStore (display_edit_precip_polyFO, XmRString, &from_value, XmRPixel, &to_value);

		if ( to_value.addr ) {
			XtSetArg(al[ac], XmNforeground, (*((Pixel*) to_value.addr))); ac++;
		}
	}
	if (DefaultDepthOfScreen(DefaultScreenOfDisplay(display)) != 1) {

		from_value.addr = "blue3" ;
		from_value.size = strlen( from_value.addr ) + 1;
		to_value.size = sizeof(Pixel);
		to_value.addr = (XPointer) &to_pixel;
		XtConvertAndStore (display_edit_precip_polyFO, XmRString, &from_value, XmRPixel, &to_value);

		if ( to_value.addr ) {
			XtSetArg(al[ac], XmNbackground, (*((Pixel*) to_value.addr))); ac++;
		}
	}
	xmstrings[0] = XmStringGenerate ( (XtPointer) "Scale", XmFONTLIST_DEFAULT_TAG, XmCHARSET_TEXT, NULL );
	XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
	adjust_scalePB = XmCreatePushButton ( display_edit_precip_polyFO, (char *) "adjust_scalePB", al, ac );
	ac = 0;
	XmStringFree ( xmstrings [ 0 ] );
	if (DefaultDepthOfScreen(DefaultScreenOfDisplay(display)) != 1) {

		from_value.addr = "#00000000ffff" ;
		from_value.size = strlen( from_value.addr ) + 1;
		to_value.size = sizeof(Pixel);
		to_value.addr = (XPointer) &to_pixel;
		XtConvertAndStore (display_edit_precip_polyFO, XmRString, &from_value, XmRPixel, &to_value);

		if ( to_value.addr ) {
			XtSetArg(al[ac], XmNforeground, (*((Pixel*) to_value.addr))); ac++;
		}
	}
	adjust_precip_valSP = XmCreateSeparator ( display_edit_precip_polyFO, (char *) "adjust_precip_valSP", al, ac );
	ac = 0;
	xmstrings[0] = XmStringGenerate ( (XtPointer) "Make Persistent", XmFONTLIST_DEFAULT_TAG, XmCHARSET_TEXT, NULL );
	XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
	XtSetArg(al[ac], XmNrecomputeSize, FALSE); ac++;
	XtSetArg(al[ac], XmNset, XmUNSET); ac++;
	persistentTB = XmCreateToggleButton ( display_edit_precip_polyFO, (char *) "persistentTB", al, ac );
	ac = 0;
	XmStringFree ( xmstrings [ 0 ] );
	if (DefaultDepthOfScreen(DefaultScreenOfDisplay(display)) != 1) {

		from_value.addr = "snow" ;
		from_value.size = strlen( from_value.addr ) + 1;
		to_value.size = sizeof(Pixel);
		to_value.addr = (XPointer) &to_pixel;
		XtConvertAndStore (display_edit_precip_polyFO, XmRString, &from_value, XmRPixel, &to_value);

		if ( to_value.addr ) {
			XtSetArg(al[ac], XmNforeground, (*((Pixel*) to_value.addr))); ac++;
		}
	}
	if (DefaultDepthOfScreen(DefaultScreenOfDisplay(display)) != 1) {

		from_value.addr = "blue3" ;
		from_value.size = strlen( from_value.addr ) + 1;
		to_value.size = sizeof(Pixel);
		to_value.addr = (XPointer) &to_pixel;
		XtConvertAndStore (display_edit_precip_polyFO, XmRString, &from_value, XmRPixel, &to_value);

		if ( to_value.addr ) {
			XtSetArg(al[ac], XmNbackground, (*((Pixel*) to_value.addr))); ac++;
		}
	}
	xmstrings[0] = XmStringGenerate ( (XtPointer) "Snow", XmFONTLIST_DEFAULT_TAG, XmCHARSET_TEXT, NULL );
	XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
	adjust_snowPB = XmCreatePushButton ( display_edit_precip_polyFO, (char *) "adjust_snowPB", al, ac );
	ac = 0;
	XmStringFree ( xmstrings [ 0 ] );


	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNtopOffset, 164); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_OPPOSITE_FORM); ac++;
	XtSetArg(al[ac], XmNbottomOffset, -184); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNleftOffset, 41); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_OPPOSITE_FORM); ac++;
	XtSetArg(al[ac], XmNrightOffset, -241); ac++;
	XtSetValues ( edit_precip_polySubLB, al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNtopOffset, 691); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_OPPOSITE_FORM); ac++;
	XtSetArg(al[ac], XmNbottomOffset, -721); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNleftOffset, 4); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_OPPOSITE_FORM); ac++;
	XtSetArg(al[ac], XmNrightOffset, -84); ac++;
	XtSetValues ( edit_precip_polySubPB, al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNtopOffset, 722); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_OPPOSITE_FORM); ac++;
	XtSetArg(al[ac], XmNbottomOffset, -733); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNleftOffset, 8); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_OPPOSITE_FORM); ac++;
	XtSetArg(al[ac], XmNrightOffset, -295); ac++;
	XtSetValues ( edit_precip_polySP, al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNtopOffset, 735); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_OPPOSITE_FORM); ac++;
	XtSetArg(al[ac], XmNbottomOffset, -768); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNleftOffset, 184); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_OPPOSITE_FORM); ac++;
	XtSetArg(al[ac], XmNrightOffset, -296); ac++;
	XtSetValues ( edit_precip_polyClosePB, al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNtopOffset, 183); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_OPPOSITE_FORM); ac++;
	XtSetArg(al[ac], XmNbottomOffset, -691); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNleftOffset, 35); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_OPPOSITE_FORM); ac++;
	XtSetArg(al[ac], XmNrightOffset, -260); ac++;
	XtSetValues ( precipModeRB, al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNtopOffset, 6); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_OPPOSITE_FORM); ac++;
	XtSetArg(al[ac], XmNbottomOffset, -31); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNleftOffset, 40); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_OPPOSITE_FORM); ac++;
	XtSetArg(al[ac], XmNrightOffset, -240); ac++;
	XtSetValues ( adjust_precip_valLB, al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNtopOffset, 60); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_OPPOSITE_FORM); ac++;
	XtSetArg(al[ac], XmNbottomOffset, -95); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNleftOffset, 25); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_OPPOSITE_FORM); ac++;
	XtSetArg(al[ac], XmNrightOffset, -260); ac++;
	XtSetValues ( adjust_precip_valSC, al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNtopOffset, 102); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_OPPOSITE_FORM); ac++;
	XtSetArg(al[ac], XmNbottomOffset, -132); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNleftOffset, 4); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_OPPOSITE_FORM); ac++;
	XtSetArg(al[ac], XmNrightOffset, -59); ac++;
	XtSetValues ( adjust_setPB, al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNtopOffset, 102); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_OPPOSITE_FORM); ac++;
	XtSetArg(al[ac], XmNbottomOffset, -132); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNleftOffset, 64); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_OPPOSITE_FORM); ac++;
	XtSetArg(al[ac], XmNrightOffset, -119); ac++;
	XtSetValues ( adjust_raisePB, al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNtopOffset, 102); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_OPPOSITE_FORM); ac++;
	XtSetArg(al[ac], XmNbottomOffset, -132); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNleftOffset, 124); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_OPPOSITE_FORM); ac++;
	XtSetArg(al[ac], XmNrightOffset, -179); ac++;
	XtSetValues ( adjust_lowerPB, al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNtopOffset, 102); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_OPPOSITE_FORM); ac++;
	XtSetArg(al[ac], XmNbottomOffset, -132); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNleftOffset, 185); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_OPPOSITE_FORM); ac++;
	XtSetArg(al[ac], XmNrightOffset, -240); ac++;
	XtSetValues ( adjust_scalePB, al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNtopOffset, 145); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_OPPOSITE_FORM); ac++;
	XtSetArg(al[ac], XmNbottomOffset, -155); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNleftOffset, 17); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_OPPOSITE_FORM); ac++;
	XtSetArg(al[ac], XmNrightOffset, -277); ac++;
	XtSetValues ( adjust_precip_valSP, al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNtopOffset, 33); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_OPPOSITE_FORM); ac++;
	XtSetArg(al[ac], XmNbottomOffset, -57); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNleftOffset, 69); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_OPPOSITE_FORM); ac++;
	XtSetArg(al[ac], XmNrightOffset, -197); ac++;
	XtSetValues ( persistentTB, al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNtopOffset, 102); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_OPPOSITE_FORM); ac++;
	XtSetArg(al[ac], XmNbottomOffset, -133); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNleftOffset, 244); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_OPPOSITE_FORM); ac++;
	XtSetArg(al[ac], XmNrightOffset, -294); ac++;
	XtSetValues ( adjust_snowPB, al, ac );
	ac = 0;
	if ((children[ac] = rMosaicTB) != (Widget) 0) { ac++; }
	if ((children[ac] = avgRMosaicTB) != (Widget) 0) { ac++; }
	if ((children[ac] = maxRMosaicTB) != (Widget) 0) { ac++; }
	if ((children[ac] = bMosaicTB) != (Widget) 0) { ac++; }
	if ((children[ac] = lMosaicTB) != (Widget) 0) { ac++; }
	if ((children[ac] = gageOnlyTB) != (Widget) 0) { ac++; }
	if ((children[ac] = mMosaicTB) != (Widget) 0) { ac++; }
	if ((children[ac] = locMMosaicTB) != (Widget) 0) { ac++; }
	if ((children[ac] = satPrecipTB) != (Widget) 0) { ac++; }
	if ((children[ac] = locSatPrecipTB) != (Widget) 0) { ac++; }
	if ((children[ac] = srMosaicTB) != (Widget) 0) { ac++; }
	if ((children[ac] = sgMosaicTB) != (Widget) 0) { ac++; }
	if ((children[ac] = srgMosaicTB) != (Widget) 0) { ac++; }
	if ((children[ac] = p3LMosaicTB) != (Widget) 0) { ac++; }
	if ((children[ac] = xmrgTB) != (Widget) 0) { ac++; }
	if ((children[ac] = rfcBMosaicTB) != (Widget) 0) { ac++; }
	if ((children[ac] = rfcMMosaicTB) != (Widget) 0) { ac++; }
	if ((children[ac] = rfcMosaicTB) != (Widget) 0) { ac++; }
	if (ac > 0) { XtManageChildren(children, ac); }
	ac = 0;
	if ((children[ac] = edit_precip_polySubLB) != (Widget) 0) { ac++; }
	if ((children[ac] = edit_precip_polySubPB) != (Widget) 0) { ac++; }
	if ((children[ac] = edit_precip_polySP) != (Widget) 0) { ac++; }
	if ((children[ac] = edit_precip_polyClosePB) != (Widget) 0) { ac++; }
	if ((children[ac] = precipModeRB) != (Widget) 0) { ac++; }
	if ((children[ac] = adjust_precip_valLB) != (Widget) 0) { ac++; }
	if ((children[ac] = adjust_precip_valSC) != (Widget) 0) { ac++; }
	if ((children[ac] = adjust_setPB) != (Widget) 0) { ac++; }
	if ((children[ac] = adjust_raisePB) != (Widget) 0) { ac++; }
	if ((children[ac] = adjust_lowerPB) != (Widget) 0) { ac++; }
	if ((children[ac] = adjust_scalePB) != (Widget) 0) { ac++; }
	if ((children[ac] = adjust_precip_valSP) != (Widget) 0) { ac++; }
	if ((children[ac] = persistentTB) != (Widget) 0) { ac++; }
	if ((children[ac] = adjust_snowPB) != (Widget) 0) { ac++; }
	if (ac > 0) { XtManageChildren(children, ac); }
	ac = 0;

/*  ==============  Statements containing RCS keywords:  */
{static char rcs_id1[] = "$Source$";
 static char rcs_id2[] = "$Id$";}
/*  ===================================================  */

}

