/*
** Generated by X-Designer
*/
#ifndef _latestrep_h
#define _latestrep_h

#define XD_MOTIF



extern Widget latestrepDS;
extern Widget latestrepFO;
extern Widget latest_filterOM;
extern Widget latest_filterLB;
extern Widget latest_filterCB;
extern Widget latest_filterPDM;
extern Widget filter_allPB;
extern Widget filter_olderthanPB;
extern Widget filter_neverPB;
extern Widget latest_sortOM;
extern Widget latest_sortLB;
extern Widget latest_sortCB;
extern Widget latest_sortPDM;
extern Widget sort_locationPB;
extern Widget sort_timePB;
extern Widget latestrepLB;
extern Widget latestlistSL;
extern Widget latestlistHSB;
extern Widget latestlistVSB;
extern Widget latestlistLS;
extern Widget latestlocFR;
extern Widget latestlocFO;
extern Widget latestlocSL;
extern Widget latestlocHSB;
extern Widget latestlocVSB;
extern Widget latestlocLS;
extern Widget latestlocLB1;
extern Widget latestlocLB2;
extern Widget cutimeLB;
extern Widget curtimeTX;
extern Widget dcpfreqLB;
extern Widget dcpfreqTX;
extern Widget dcprepLB;
extern Widget dcprepTX;
extern Widget telemfreqLB;
extern Widget telemfreqTX;
extern Widget telemrepLB;
extern Widget latestlocLB;
extern Widget latestrep_okPB;
extern Widget durationTX;
extern Widget hoursLB;

extern void create_latestrepDS ();


#endif
