/*
** Generated by X-Designer
*/
#ifndef _lwstmt_h
#define _lwstmt_h

#define XD_MOTIF



extern Widget lwstmtDS;
extern Widget lwstmtFM;
extern Widget lwstmtSLB;
extern Widget lwstmt_horizSB;
extern Widget lwstmt_vertSB;
extern Widget lwstmtLB;
extern Widget lwstmt_infoFrm;
extern Widget lwstmt_infoFM;
extern Widget lwvalLbl;
extern Widget lwvalTxt;
extern Widget upvalLbl;
extern Widget upvalTxt;
extern Widget crtrankLbl;
extern Widget crtrankTxt;
extern Widget crtLbl;
extern Widget crtTxt;
extern Widget srcLbl;
extern Widget srcTxt;
extern Widget stmtLbl;
extern Widget stmtTxt;
extern Widget peLbl;
extern Widget peTxt;
extern Widget lwstmt_infoLbl;
extern Widget lwstmtSP;
extern Widget lwstmtokPB;
extern Widget lwstmtapplyPB;
extern Widget lwstmtcancelPB;
extern Widget lwstmtnewPB;
extern Widget lwstmtdelPB;
extern Widget lwstmt_lwvalLbl;
extern Widget lwstmt_upvalLbl;
extern Widget lwstmt_crtrankLbl;
extern Widget lwstmt_peLbl;

extern void create_lwstmtDS (Widget);


#endif
