/*
** Generated by X-Designer
*/
#ifndef _pointservice_backup_h
#define _pointservice_backup_h

#define XD_MOTIF



extern Widget hbsbfilterDS;
extern Widget hbsbfilterFO;
extern Widget hbsbfhsaSL;
extern Widget hbsbfhsaHSB;
extern Widget hbsbfhsaVSB;
extern Widget hbsbfhsaLI;
extern Widget hbsbfapplyPB;
extern Widget hbsbfcancelPB;

extern void create_hbsbfilterDS (Widget);


#endif
