/*
** Generated by X-Designer
*/
#ifndef _prodview_h
#define _prodview_h

#define XD_MOTIF



extern Widget prodviewDS;
extern Widget prodviewFM;
extern Widget prodviewPW;
extern Widget prodviewFO;
extern Widget prodviewFR;
extern Widget prodinfoFO;
extern Widget prodlistSL;
extern Widget prodlistHSB;
extern Widget prodlistVSB;
extern Widget prodlistLS;
extern Widget prodlistLB;
extern Widget prodfilterTX;
extern Widget prodsortLB;
extern Widget prodsortOM;
extern Widget prodsortLB2;
extern Widget prodsortCB;
extern Widget prodsortPDM;
extern Widget prodsort_loc_PB;
extern Widget prodsort_prodtime_PB;
extern Widget prodsort_posttime_PB;
extern Widget prodlocLB;
extern Widget prodlocTX;
extern Widget prodselOM;
extern Widget prodselLbl;
extern Widget prodselCB;
extern Widget prodselPDM;
extern Widget prodsel_loc_PB;
extern Widget prodsel_latest_PB;
extern Widget prodsel_all_PB;
extern Widget prodlistLB2;
extern Widget prodSP;
extern Widget prodfilterLB;
extern Widget prodinfoLB;
extern Widget prodtxtFM;
extern Widget productST;
extern Widget prodtxtHSB;
extern Widget prodtxtVSB;
extern Widget productTxt;
extern Widget ok_prodviewPB;

extern void create_prodviewDS (Widget);


#endif
