#!/bin/ksh
#==========================================================================
#  Create input file directories for OFS
#
USAGE="Usage: create_input_group group_name"
#
# The script create_input_group will create a new branch in the ofs input
# directory structure.  The command usage is:
#
#  create_input_group group_name
#
# The group_name parameter is required.  The top-level of the input group 
# branch is created directly under the "ofs_dir"/input directory ("" 
# indicating the use of a gad token).  The names of the 
# sub-directories created under group_name correspond to the collection of 
# batch ofs programs that exist on the scientific workstations.  A list of
# those programs is held in the file ofs.program.list in the "rfs_sys_dir"
# directory.  All directories in the chain are tested for existence and are
# created if they don't exist.  Permissions are read for all users and write
# for the user and group.
#==========================================================================

if [[ -z $1 ]]
   then
      print $USAGE
      exit
   fi

# returns a fully resolved path
get_full_path() {
    cd "$1"
    echo $(pwd)
}

script_dir=$(get_full_path $(dirname $0))

. $script_dir/include_hydro_env.sh

print Creating OFS input directories for $1 group 
print '  'at `date -u +"%T %Z"` on `date -u +"%a %b %d %Y"`
print ""

# First create default input directories

List_dir=$(gad rfs_sys_dir)
List_file=$List_dir/ofs.program.list
Inpt_dir=$(gad ofs_dir)/input

print " Check to create: $Inpt_dir"

if [[ ! -a $Inpt_dir ]]
  then
    mkdir $Inpt_dir
    chmod ug+rwx $Inpt_dir
    print "  Directory $Inpt_dir created."
fi

Inpt_dir=$Inpt_dir/$1
print "  Check to create: $Inpt_dir"

if [[ ! -a $Inpt_dir ]]
  then
    mkdir $Inpt_dir
    chmod ug+rwx $Inpt_dir
    print "   Directory $Inpt_dir created."
fi

if [[ -a $List_dir && -d $List_dir && -a $List_file ]]
  then
    while read -r pgm_name
      do
	print "   Check to create: $Inpt_dir/$pgm_name"

	if [[ ! -a $Inpt_dir/$pgm_name ]]
	  then
	    mkdir $Inpt_dir/$pgm_name
	    chmod ug+rwx $Inpt_dir/$pgm_name
	    print "    Directory $Inpt_dir/$pgm_name created."
	fi
      done < $List_file
  fi


