//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.10 at 10:31:03 AM CST 
//


package org.isotc211._2005.gfc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import org.isotc211._2005.gco.CharacterStringPropertyType;
import org.isotc211._2005.gco.LocalNamePropertyType;
import org.isotc211._2005.gco.MultiplicityPropertyType;


/**
 * Abstract class for local and global feature properties.
 * 
 * <p>Java class for AbstractFC_PropertyType_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AbstractFC_PropertyType_Type">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.isotc211.org/2005/gfc}AbstractFC_CarrierOfCharacteristics_Type">
 *       &lt;sequence>
 *         &lt;element name="memberName" type="{http://www.isotc211.org/2005/gco}LocalName_PropertyType"/>
 *         &lt;element name="definition" type="{http://www.isotc211.org/2005/gco}CharacterString_PropertyType" minOccurs="0"/>
 *         &lt;element name="cardinality" type="{http://www.isotc211.org/2005/gco}Multiplicity_PropertyType"/>
 *         &lt;element name="definitionReference" type="{http://www.isotc211.org/2005/gfc}FC_DefinitionReference_PropertyType" minOccurs="0"/>
 *         &lt;element name="featureCatalogue" type="{http://www.isotc211.org/2005/gfc}FC_FeatureCatalogue_PropertyType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbstractFC_PropertyType_Type", propOrder = {
    "memberName",
    "definition",
    "cardinality",
    "definitionReference",
    "featureCatalogue"
})
@XmlSeeAlso({
    FCFeatureAttributeType.class,
    FCFeatureOperationType.class,
    FCAssociationRoleType.class
})
public abstract class AbstractFCPropertyTypeType
    extends AbstractFCCarrierOfCharacteristicsType
{

    @XmlElement(required = true)
    protected LocalNamePropertyType memberName;
    protected CharacterStringPropertyType definition;
    @XmlElement(required = true)
    protected MultiplicityPropertyType cardinality;
    protected FCDefinitionReferencePropertyType definitionReference;
    protected FCFeatureCataloguePropertyType featureCatalogue;

    /**
     * Gets the value of the memberName property.
     * 
     * @return
     *     possible object is
     *     {@link LocalNamePropertyType }
     *     
     */
    public LocalNamePropertyType getMemberName() {
        return memberName;
    }

    /**
     * Sets the value of the memberName property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocalNamePropertyType }
     *     
     */
    public void setMemberName(LocalNamePropertyType value) {
        this.memberName = value;
    }

    /**
     * Gets the value of the definition property.
     * 
     * @return
     *     possible object is
     *     {@link CharacterStringPropertyType }
     *     
     */
    public CharacterStringPropertyType getDefinition() {
        return definition;
    }

    /**
     * Sets the value of the definition property.
     * 
     * @param value
     *     allowed object is
     *     {@link CharacterStringPropertyType }
     *     
     */
    public void setDefinition(CharacterStringPropertyType value) {
        this.definition = value;
    }

    /**
     * Gets the value of the cardinality property.
     * 
     * @return
     *     possible object is
     *     {@link MultiplicityPropertyType }
     *     
     */
    public MultiplicityPropertyType getCardinality() {
        return cardinality;
    }

    /**
     * Sets the value of the cardinality property.
     * 
     * @param value
     *     allowed object is
     *     {@link MultiplicityPropertyType }
     *     
     */
    public void setCardinality(MultiplicityPropertyType value) {
        this.cardinality = value;
    }

    /**
     * Gets the value of the definitionReference property.
     * 
     * @return
     *     possible object is
     *     {@link FCDefinitionReferencePropertyType }
     *     
     */
    public FCDefinitionReferencePropertyType getDefinitionReference() {
        return definitionReference;
    }

    /**
     * Sets the value of the definitionReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link FCDefinitionReferencePropertyType }
     *     
     */
    public void setDefinitionReference(FCDefinitionReferencePropertyType value) {
        this.definitionReference = value;
    }

    /**
     * Gets the value of the featureCatalogue property.
     * 
     * @return
     *     possible object is
     *     {@link FCFeatureCataloguePropertyType }
     *     
     */
    public FCFeatureCataloguePropertyType getFeatureCatalogue() {
        return featureCatalogue;
    }

    /**
     * Sets the value of the featureCatalogue property.
     * 
     * @param value
     *     allowed object is
     *     {@link FCFeatureCataloguePropertyType }
     *     
     */
    public void setFeatureCatalogue(FCFeatureCataloguePropertyType value) {
        this.featureCatalogue = value;
    }

}
