//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.10 at 10:31:03 AM CST 
//


package org.isotc211._2005.gfc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.isotc211._2005.gco.BooleanPropertyType;


/**
 * A role of the association FC_AssociationRole::relation.  - [ocl] - roleName = FC_Member::memberName; - FC_PropertyType::cardinality realizes GF_AssociationRole::cardinality - [/ocl]
 * 
 * <p>Java class for FC_AssociationRole_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FC_AssociationRole_Type">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.isotc211.org/2005/gfc}AbstractFC_PropertyType_Type">
 *       &lt;sequence>
 *         &lt;element name="type" type="{http://www.isotc211.org/2005/gfc}FC_RoleType_PropertyType"/>
 *         &lt;element name="isOrdered" type="{http://www.isotc211.org/2005/gco}Boolean_PropertyType"/>
 *         &lt;element name="isNavigable" type="{http://www.isotc211.org/2005/gco}Boolean_PropertyType"/>
 *         &lt;element name="relation" type="{http://www.isotc211.org/2005/gfc}FC_FeatureAssociation_PropertyType"/>
 *         &lt;element name="rolePlayer" type="{http://www.isotc211.org/2005/gfc}FC_FeatureType_PropertyType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FC_AssociationRole_Type", propOrder = {
    "type",
    "isOrdered",
    "isNavigable",
    "relation",
    "rolePlayer"
})
public class FCAssociationRoleType
    extends AbstractFCPropertyTypeType
{

    @XmlElement(required = true)
    protected FCRoleTypePropertyType type;
    @XmlElement(required = true)
    protected BooleanPropertyType isOrdered;
    @XmlElement(required = true)
    protected BooleanPropertyType isNavigable;
    @XmlElement(required = true)
    protected FCFeatureAssociationPropertyType relation;
    protected FCFeatureTypePropertyType rolePlayer;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link FCRoleTypePropertyType }
     *     
     */
    public FCRoleTypePropertyType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link FCRoleTypePropertyType }
     *     
     */
    public void setType(FCRoleTypePropertyType value) {
        this.type = value;
    }

    /**
     * Gets the value of the isOrdered property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanPropertyType }
     *     
     */
    public BooleanPropertyType getIsOrdered() {
        return isOrdered;
    }

    /**
     * Sets the value of the isOrdered property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanPropertyType }
     *     
     */
    public void setIsOrdered(BooleanPropertyType value) {
        this.isOrdered = value;
    }

    /**
     * Gets the value of the isNavigable property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanPropertyType }
     *     
     */
    public BooleanPropertyType getIsNavigable() {
        return isNavigable;
    }

    /**
     * Sets the value of the isNavigable property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanPropertyType }
     *     
     */
    public void setIsNavigable(BooleanPropertyType value) {
        this.isNavigable = value;
    }

    /**
     * Gets the value of the relation property.
     * 
     * @return
     *     possible object is
     *     {@link FCFeatureAssociationPropertyType }
     *     
     */
    public FCFeatureAssociationPropertyType getRelation() {
        return relation;
    }

    /**
     * Sets the value of the relation property.
     * 
     * @param value
     *     allowed object is
     *     {@link FCFeatureAssociationPropertyType }
     *     
     */
    public void setRelation(FCFeatureAssociationPropertyType value) {
        this.relation = value;
    }

    /**
     * Gets the value of the rolePlayer property.
     * 
     * @return
     *     possible object is
     *     {@link FCFeatureTypePropertyType }
     *     
     */
    public FCFeatureTypePropertyType getRolePlayer() {
        return rolePlayer;
    }

    /**
     * Sets the value of the rolePlayer property.
     * 
     * @param value
     *     allowed object is
     *     {@link FCFeatureTypePropertyType }
     *     
     */
    public void setRolePlayer(FCFeatureTypePropertyType value) {
        this.rolePlayer = value;
    }

}
