#!/bin/ksh
# file name: run_SSHP_SAC_state_update
# Created: 12/15/2003

# This allows you to run this script from outside of ./bin
RUN_FROM_DIR=`dirname $0`

# set up SOME environment variables for WHFS applications
. $RUN_FROM_DIR/../../set_hydro_env

# set initial lid to the first command line argument passed into the script
LID_PASSED_IN=$1

export CLASSPATH=.
CLASSPATH=$CLASSPATH:$DB_DRIVER_PATH
# need to add a path to the jar file for this application
CLASSPATH=$CLASSPATH:$WHFS_BIN_DIR/SiteSpecific.jar

export WHFS_LOCAL_DATA_SSHP_DIR=$WHFS_BIN_DIR/../local/data/app/sshp


EXPIRATION_HOURS=$($GAD_DIR/get_apps_defaults$OS_SUFFIX sshp_sac_update_expiration_hours)
if [ -z "$EXPIRATION_HOURS" ] 
then
   EXPIRATION_HOURS=25
fi

HOURS_FORWARD=$($GAD_DIR/get_apps_defaults$OS_SUFFIX sshp_sac_update_hours_forward)
if [ -z "$HOURS_FORWARD" ] 
then
   HOURS_FORWARD=-2
fi

# Java bin directory
JBINDIR=$SYS_JAVA_DIR/bin

# Keeps the last 1200 lines of the log file

LOGFILE=$SSHP_LOG_DIR/SacStateUpdate.log
STDLOGFILE=$SSHP_LOG_DIR/SacStateUpdate.stdout.log
TMPFILE=$SSHP_LOG_DIR/SacStateUpdate.tmp

tail -1200 $LOGFILE > $TMPFILE
mv $TMPFILE $LOGFILE

tail -1200 $STDLOGFILE > $TMPFILE
mv $TMPFILE $STDLOGFILE
# run the SacStateUpdater if on Linux or ssh to a linux machine if not.

if [[ `uname` = "Linux" ]]
then
     $JBINDIR/java ohd.hseb.sshp.SacStateUpdater $JDBCURL $EXPIRATION_HOURS $HOURS_FORWARD $LOGFILE >>$STDLOGFILE 2>>$STDLOGFILE
elif [[ `uname` = "HP-UX" ]]
then
     ssh -oBatchMode=yes $SSHP_JAVA_PROCESS_HOST $WHFS_BIN_DIR/run_SSHP_SAC_state_update >>$STDLOGFILE 2>>$STDLOGFILE
fi
