#!/bin/ksh

export DRIVERPATH=/usr/lib/postgresql-8.2-506.jdbc3.jar
export RUN_FROM_DIR=`dirname $0`
export PROJECTS_DIR=$RUN_FROM_DIR/../..

export IHFSDB_DIR=$PROJECTS_DIR/ihfsdb
export DB_DIR=$PROJECTS_DIR/db

export BASEPATH=$DB_DIR/classes

export CLASSPATH=./:$BASEPATH/:$DRIVERPATH
echo "CLASSPATH =" $CLASSPATH

#The connection string
connecturl="jdbc:postgresql://genessee:5432/hd_${DS_BUILD}empty?user=pguser"

#The location of the PreferredTableNames.txt file.
namingfile=$IHFSDB_DIR/scripts/PreferredTableNames.txt

#The destination of the generated source files 
targetdir=$IHFSDB_DIR/src/ohd/hseb/ihfsdb/generated

#db name
dbname=hd_${DS_BUILD}empty

#package name -- NONE means no packaging
# Note: this does NOT affect directly in which the generated class is placed
package=ohd.hseb.ihfsdb.generated

db_driver_class_name=org.postgresql.Driver

$JAVADIR/bin/java ohd.hseb.dbgen.JDbGen $connecturl $namingfile $dbname $package $targetdir $db_driver_class_name

return $?
