# ----------------------------------------------------------------------------
#
# SOFTWARE HISTORY
#
# Date          Ticket#  Engineer  Description
# ------------- -------- --------- --------------------------------------------
# Jun 30, 2021  8572     randerso  Moved svcbu path properties out of 
#                                  svcbu.properties since those should never
#                                  need to be overridden by sites
#################################################################


# Directories used by Service Backup
#
# AWIPS_HOME:           The AWIPS II installation directory.
#
# GFESUITE_HOME:        The server directory containing files and programs
#                       used by GFE during Service Backup
#
# GFESUITE_BIN:         Directory containing GFE server side utility 
#                       programs including ifpnetCDF and iscMosaic
#
# SVCBU_HOME:           Directory used by service backup as a sandbox for 
#                       constructing files to be sent and for processing 
#                       received files.
#
# LOCALIZATION_PATH:    This is the path to the root of the localization
#                       directory.  This path is used for properly importing
#                       and exporting configuration data
#       
# IFPS_LOG:             Directory containing logs for the service backup 
#                       operations.
#
# IFPS_DATA:            Directory containing the svcbu_export_elements file.  
#                       This file is used to specify which weather elements are
#                       packaged and sent when exporting digital data for a 
#                       site.
#       
# LOCK_DIR:             Directory used for lock files.  Each Service Backup 
#                       operation maintains a lock file during its execution.  
#                       The lock remains for the duration of the operation and 
#                       is erased upon completion to prevent simultaneous 
#                       operations from occurring.
#
# SCRIPTS_DIR:          Directory containing the scripts used by service 
#                       backup
#
# CAVE_LAUNCH_SCRIPT:   This path points to the script which starts GFE.  This 
#                       variable is read when the user hits the 'Enable' button
#                       On the service backup GUI.  
#
# NCDUMP_PATH:          Directory containing the ncdump executable
#

GFESUITE_HOME=/awips2/GFESuite
GFESUITE_BIN=/awips2/GFESuite/bin
SVCBU_HOME=/awips2/GFESuite/ServiceBackup/svcbu
LOCALIZATION_PATH=/awips2/edex/data/utility
IFPS_LOG=/awips2/GFESuite/ServiceBackup/logs
IFPS_DATA=/awips2/GFESuite/ServiceBackup/data
LOCK_DIR=/awips2/GFESuite/ServiceBackup/locks
SCRIPTS_DIR=/awips2/GFESuite/ServiceBackup/scripts
CAVE_LAUNCH_SCRIPT=/awips2/cave/cave.sh
NCDUMP_PATH=/awips2/netcdf/bin/
