#!/bin/sh

# $1 = file to copy
# $2 = bin directory
# $3 = site name
# $4 = central server directory

cd $2
cp $1 $2

echo ${3} > siteID.txt
tar cvf ${3}Grd.tar ${3}Grd.netcdf siteID.txt
mv ${3}Grd.tar ${3}Grd
cp ${3}Grd $4
rm -f siteID.txt *.netcdf *.tar


