#!/bin/sh
# chkconfig: - 99 10
# description: AWIPS II IRT Component.

# Source function library.
. /etc/rc.d/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

# Check that networking is up.
[ ${NETWORKING} = "no" ] && exit 0

EDEXUSER=awips
export LD_LIBRARY_PATH=%{PYTHON_INSTALL}%/lib
export LD_PRELOAD=%{PYTHON_INSTALL}%/lib/libpython2.7.so 

IRT_DIR=%{IRT_INSTALL}%/IRT-operational/server/
PID_FILE=$IRT_DIR/tmp.pid

# Verify root user
checkUser() {
   REQUIREDUSER="root"
   CURUSER=`whoami`
   if [ "$CURUSER" != "$REQUIREDUSER" ]; then
      echo "Insufficient privileges: must run script as $REQUIREDUSER"
      exit 1
   fi
}

start(){
	cd $IRT_DIR
	su $EDEXUSER -c "%{PYTHON_INSTALL}%/bin/python RoutingTableSvc.py &" > /dev/null 2>&1
	routingSvcName=RoutingTableSvc.py
	ps ax | grep "$routingSvcName$" | awk '{print $1;}' > $PID_FILE
}

stop(){
	cd $IRT_DIR
	cat $PID_FILE | while read pid
	do
	su $EDEXUSER -c "kill -9 $pid"
	done
	rm $PID_FILE
}

restart(){
	stop
	sleep 3
	start
}

# See how we were called
case $1 in
  start)
        checkUser
        echo "Starting IRT Server..."
        start
        RETVAL=$?
        ;;
  stop)
        checkUser
        echo "Stopping IRT Server..."
        stop
        RETVAL=$?
        ;;
  restart)
        checkUser
        echo "Restarting IRT Server..."
        restart
        RETVAL=$?
        ;;
  *)
        #Print help
        echo "Usage: $0 {start|stop|restart}" 1>&2
        exit 1
        ;;
esac

exit $RETVAL