//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.10 at 12:21:12 PM EDT 
//


package gov.noaa.nws.ncep.ui.pgen.file;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Color"/>
 *         &lt;element ref="{}DrawableElement" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="outputFile" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="inputFile" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="filled" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="monoColor" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="onOff" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "color",
    "drawableElement"
})
@XmlRootElement(name = "Layer")
public class Layer {

    @XmlElement(name = "Color", required = true)
    protected Color color;
    @XmlElement(name = "DrawableElement")
    protected DrawableElement drawableElement;
    @XmlAttribute
    protected String outputFile;
    @XmlAttribute
    protected String inputFile;
    @XmlAttribute
    protected Boolean filled;
    @XmlAttribute
    protected Boolean monoColor;
    @XmlAttribute
    protected Boolean onOff;
    @XmlAttribute
    protected String name;
    @XmlAttribute
    protected String metaInfo;
    
    /**
     * Gets the value of the color property.
     * 
     * @return
     *     possible object is
     *     {@link Color }
     *     
     */
    public Color getColor() {
        return color;
    }

    /**
     * Sets the value of the color property.
     * 
     * @param value
     *     allowed object is
     *     {@link Color }
     *     
     */
    public void setColor(Color value) {
        this.color = value;
    }

    /**
     * Gets the value of the drawableElement property.
     * 
     * @return
     *     possible object is
     *     {@link DrawableElement }
     *     
     */
    public DrawableElement getDrawableElement() {
        return drawableElement;
    }

    /**
     * Sets the value of the drawableElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link DrawableElement }
     *     
     */
    public void setDrawableElement(DrawableElement value) {
        this.drawableElement = value;
    }

    /**
     * Gets the value of the outputFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutputFile() {
        return outputFile;
    }

    /**
     * Sets the value of the outputFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutputFile(String value) {
        this.outputFile = value;
    }

    /**
     * Gets the value of the inputFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInputFile() {
        return inputFile;
    }

    /**
     * Sets the value of the inputFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInputFile(String value) {
        this.inputFile = value;
    }

    /**
     * Gets the value of the filled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFilled() {
        return filled;
    }

    /**
     * Sets the value of the filled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFilled(Boolean value) {
        this.filled = value;
    }

    /**
     * Gets the value of the monoColor property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isMonoColor() {
        return monoColor;
    }

    /**
     * Sets the value of the monoColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMonoColor(Boolean value) {
        this.monoColor = value;
    }

    /**
     * Gets the value of the onOff property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isOnOff() {
        return onOff;
    }

    /**
     * Sets the value of the onOff property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOnOff(Boolean value) {
        this.onOff = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

	public String getMetaInfo() {
		return metaInfo;
	}

	public void setMetaInfo(String metaInfo) {
		this.metaInfo = metaInfo;
	}

}
