//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.05.07 at 03:21:18 PM EDT 
//

package gov.noaa.nws.ncep.ui.pgen.file;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Color" maxOccurs="unbounded"/>
 *         &lt;element ref="{}Point" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="pgenType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="fillPattern" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="filled" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="closed" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="smoothFactor" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="sizeScale" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="lineWidth" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="pgenCategory" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "color", "point" })
@XmlRootElement(name = "Line")
public class Line {

    @XmlElement(name = "Color", required = true)
    protected List<Color> color;

    @XmlElement(name = "Point", required = true)
    protected List<Point> point;

    @XmlAttribute
    protected Double kinkPosition;

    @XmlAttribute
    protected String arrowHeadType;

    @XmlAttribute
    protected boolean flipSide = false;

    @XmlAttribute
    protected String fillPattern;

    @XmlAttribute
    protected Boolean filled;

    @XmlAttribute
    protected Boolean closed;

    @XmlAttribute
    protected Integer smoothFactor;

    @XmlAttribute
    protected Double sizeScale;

    @XmlAttribute
    protected Float lineWidth;

    @XmlAttribute
    protected String pgenCategory;

    @XmlAttribute
    protected String pgenType;

    /**
     * Gets the value of the color property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the color property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getColor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Color }
     * 
     * 
     */
    public List<Color> getColor() {
        if (color == null) {
            color = new ArrayList<Color>();
        }
        return this.color;
    }

    /**
     * Gets the value of the point property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the point property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getPoint().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Point }
     * 
     * 
     */
    public List<Point> getPoint() {
        if (point == null) {
            point = new ArrayList<Point>();
        }
        return this.point;
    }

    /**
     * Gets the value of the pgenType property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPgenType() {
        return pgenType;
    }

    /**
     * Sets the value of the pgenType property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setPgenType(String value) {
        this.pgenType = value;
    }

    /**
     * Gets the value of the fillPattern property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getFillPattern() {
        return fillPattern;
    }

    /**
     * Sets the value of the fillPattern property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setFillPattern(String value) {
        this.fillPattern = value;
    }

    /**
     * Gets the value of the filled property.
     * 
     * @return possible object is {@link Boolean }
     * 
     */
    public Boolean isFilled() {
        return filled;
    }

    /**
     * Sets the value of the filled property.
     * 
     * @param value
     *            allowed object is {@link Boolean }
     * 
     */
    public void setFilled(Boolean value) {
        this.filled = value;
    }

    /**
     * Gets the value of the closed property.
     * 
     * @return possible object is {@link Boolean }
     * 
     */
    public Boolean isClosed() {
        return closed;
    }

    /**
     * Sets the value of the closed property.
     * 
     * @param value
     *            allowed object is {@link Boolean }
     * 
     */
    public void setClosed(Boolean value) {
        this.closed = value;
    }

    /**
     * Gets the value of the smoothFactor property.
     * 
     * @return possible object is {@link Integer }
     * 
     */
    public Integer getSmoothFactor() {
        return smoothFactor;
    }

    /**
     * Sets the value of the smoothFactor property.
     * 
     * @param value
     *            allowed object is {@link Integer }
     * 
     */
    public void setSmoothFactor(Integer value) {
        this.smoothFactor = value;
    }

    /**
     * Gets the value of the sizeScale property.
     * 
     * @return possible object is {@link Double }
     * 
     */
    public Double getSizeScale() {
        return sizeScale;
    }

    /**
     * Sets the value of the sizeScale property.
     * 
     * @param value
     *            allowed object is {@link Double }
     * 
     */
    public void setSizeScale(Double value) {
        this.sizeScale = value;
    }

    /**
     * Gets the value of the lineWidth property.
     * 
     * @return possible object is {@link Float }
     * 
     */
    public Float getLineWidth() {
        return lineWidth;
    }

    /**
     * Sets the value of the lineWidth property.
     * 
     * @param value
     *            allowed object is {@link Float }
     * 
     */
    public void setLineWidth(Float value) {
        this.lineWidth = value;
    }

    /**
     * Gets the value of the pgenCategory property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPgenCategory() {
        return pgenCategory;
    }

    /**
     * Sets the value of the pgenCategory property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setPgenCategory(String value) {
        this.pgenCategory = value;
    }

    /**
     * @return the flipSide
     */
    public boolean isFlipSide() {
        return flipSide;
    }

    /**
     * @param flipSide
     *            the flipSide to set
     */
    public void setFlipSide(boolean flipSide) {
        this.flipSide = flipSide;
    }

    /**
     * Gets the value of the arrowHeadType property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getArrowHeadType() {
        return arrowHeadType;
    }

    /**
     * Sets the value of the arrowHeadTYpe property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setArrowHeadType(String value) {
        this.arrowHeadType = value;
    }

    /**
     * Gets the value of the kinkPosition property.
     * 
     * @return possible object is {@link Double }
     * 
     */
    public Double getKinkPosition() {
        return kinkPosition;
    }

    /*
     * y Sets the value of the kinkPosition property.
     * 
     * @param value allowed object is {@link Double }
     */
    public void setKinkPosition(Double value) {
        this.kinkPosition = value;
    }

}
