//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.10 at 10:31:13 AM CST 
//


package org.isotc211._2005.gmi;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.isotc211._2005.gco.AbstractObjectType;
import org.isotc211._2005.gco.CharacterStringPropertyType;
import org.isotc211._2005.gmd.CICitationPropertyType;
import org.isotc211._2005.gmd.MDIdentifierPropertyType;
import org.isotc211._2005.gmd.MDProgressCodePropertyType;


/**
 * Description: Designations for the operation used to acquire the dataset - shortName: MssnId
 * 
 * <p>Java class for MI_Operation_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MI_Operation_Type">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.isotc211.org/2005/gco}AbstractObject_Type">
 *       &lt;sequence>
 *         &lt;element name="description" type="{http://www.isotc211.org/2005/gco}CharacterString_PropertyType" minOccurs="0"/>
 *         &lt;element name="citation" type="{http://www.isotc211.org/2005/gmd}CI_Citation_PropertyType" minOccurs="0"/>
 *         &lt;element name="identifier" type="{http://www.isotc211.org/2005/gmd}MD_Identifier_PropertyType"/>
 *         &lt;element name="status" type="{http://www.isotc211.org/2005/gmd}MD_ProgressCode_PropertyType"/>
 *         &lt;element name="type" type="{http://www.isotc211.org/2005/gmi}MI_OperationTypeCode_PropertyType" minOccurs="0"/>
 *         &lt;element name="parentOperation" type="{http://www.isotc211.org/2005/gmi}MI_Operation_PropertyType"/>
 *         &lt;element name="childOperation" type="{http://www.isotc211.org/2005/gmi}MI_Operation_PropertyType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="platform" type="{http://www.isotc211.org/2005/gmi}MI_Platform_PropertyType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="objective" type="{http://www.isotc211.org/2005/gmi}MI_Objective_PropertyType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="plan" type="{http://www.isotc211.org/2005/gmi}MI_Plan_PropertyType" minOccurs="0"/>
 *         &lt;element name="significantEvent" type="{http://www.isotc211.org/2005/gmi}MI_Event_PropertyType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MI_Operation_Type", propOrder = {
    "description",
    "citation",
    "identifier",
    "status",
    "type",
    "parentOperation",
    "childOperation",
    "platform",
    "objective",
    "plan",
    "significantEvent"
})
public class MIOperationType
    extends AbstractObjectType
{

    protected CharacterStringPropertyType description;
    protected CICitationPropertyType citation;
    @XmlElement(required = true)
    protected MDIdentifierPropertyType identifier;
    @XmlElement(required = true)
    protected MDProgressCodePropertyType status;
    protected MIOperationTypeCodePropertyType type;
    @XmlElement(required = true)
    protected MIOperationPropertyType parentOperation;
    protected List<MIOperationPropertyType> childOperation;
    protected List<MIPlatformPropertyType> platform;
    protected List<MIObjectivePropertyType> objective;
    protected MIPlanPropertyType plan;
    protected List<MIEventPropertyType> significantEvent;

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link CharacterStringPropertyType }
     *     
     */
    public CharacterStringPropertyType getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link CharacterStringPropertyType }
     *     
     */
    public void setDescription(CharacterStringPropertyType value) {
        this.description = value;
    }

    /**
     * Gets the value of the citation property.
     * 
     * @return
     *     possible object is
     *     {@link CICitationPropertyType }
     *     
     */
    public CICitationPropertyType getCitation() {
        return citation;
    }

    /**
     * Sets the value of the citation property.
     * 
     * @param value
     *     allowed object is
     *     {@link CICitationPropertyType }
     *     
     */
    public void setCitation(CICitationPropertyType value) {
        this.citation = value;
    }

    /**
     * Gets the value of the identifier property.
     * 
     * @return
     *     possible object is
     *     {@link MDIdentifierPropertyType }
     *     
     */
    public MDIdentifierPropertyType getIdentifier() {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link MDIdentifierPropertyType }
     *     
     */
    public void setIdentifier(MDIdentifierPropertyType value) {
        this.identifier = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link MDProgressCodePropertyType }
     *     
     */
    public MDProgressCodePropertyType getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link MDProgressCodePropertyType }
     *     
     */
    public void setStatus(MDProgressCodePropertyType value) {
        this.status = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link MIOperationTypeCodePropertyType }
     *     
     */
    public MIOperationTypeCodePropertyType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link MIOperationTypeCodePropertyType }
     *     
     */
    public void setType(MIOperationTypeCodePropertyType value) {
        this.type = value;
    }

    /**
     * Gets the value of the parentOperation property.
     * 
     * @return
     *     possible object is
     *     {@link MIOperationPropertyType }
     *     
     */
    public MIOperationPropertyType getParentOperation() {
        return parentOperation;
    }

    /**
     * Sets the value of the parentOperation property.
     * 
     * @param value
     *     allowed object is
     *     {@link MIOperationPropertyType }
     *     
     */
    public void setParentOperation(MIOperationPropertyType value) {
        this.parentOperation = value;
    }

    /**
     * Gets the value of the childOperation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the childOperation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChildOperation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MIOperationPropertyType }
     * 
     * 
     */
    public List<MIOperationPropertyType> getChildOperation() {
        if (childOperation == null) {
            childOperation = new ArrayList<MIOperationPropertyType>();
        }
        return this.childOperation;
    }

    /**
     * Gets the value of the platform property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the platform property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPlatform().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MIPlatformPropertyType }
     * 
     * 
     */
    public List<MIPlatformPropertyType> getPlatform() {
        if (platform == null) {
            platform = new ArrayList<MIPlatformPropertyType>();
        }
        return this.platform;
    }

    /**
     * Gets the value of the objective property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the objective property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getObjective().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MIObjectivePropertyType }
     * 
     * 
     */
    public List<MIObjectivePropertyType> getObjective() {
        if (objective == null) {
            objective = new ArrayList<MIObjectivePropertyType>();
        }
        return this.objective;
    }

    /**
     * Gets the value of the plan property.
     * 
     * @return
     *     possible object is
     *     {@link MIPlanPropertyType }
     *     
     */
    public MIPlanPropertyType getPlan() {
        return plan;
    }

    /**
     * Sets the value of the plan property.
     * 
     * @param value
     *     allowed object is
     *     {@link MIPlanPropertyType }
     *     
     */
    public void setPlan(MIPlanPropertyType value) {
        this.plan = value;
    }

    /**
     * Gets the value of the significantEvent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the significantEvent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSignificantEvent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MIEventPropertyType }
     * 
     * 
     */
    public List<MIEventPropertyType> getSignificantEvent() {
        if (significantEvent == null) {
            significantEvent = new ArrayList<MIEventPropertyType>();
        }
        return this.significantEvent;
    }

}
