//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.07.12 at 04:10:24 PM EDT
//

package gov.noaa.nws.mdl.viz.boundaryTool.boundaries.state.xml;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="UserName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TimeInfo">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="FileCreationTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                   &lt;element name="FileCreationUtime" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Boundary" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="BoundaryId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="BoundaryType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="BoundaryMode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="BoundaryLifeSpan" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="BoundaryCreationTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *                   &lt;element name="BoundaryCreationUtime" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *                   &lt;element name="BoundaryEditedTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *                   &lt;element name="BoundaryEditedUtime" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *                   &lt;element name="BoundaryExpirationTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *                   &lt;element name="BoundaryExpirationUtime" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *                   &lt;element name="NumberOfVertices" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="Vertex" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Latitude" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *                             &lt;element name="Longitude" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *                             &lt;element name="Azimuth" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *                             &lt;element name="Speed" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *                             &lt;element name="U" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *                             &lt;element name="V" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ForbiddenBoundaryIds" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ForbiddenId" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Log" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Comment" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "userName", "timeInfo", "boundary",
        "forbiddenBoundaryIds", "log" })
@XmlRootElement(name = "Boundaries")
public class Boundaries {

    @XmlElement(name = "UserName", required = true)
    protected String userName;
    @XmlElement(name = "TimeInfo", required = true)
    protected Boundaries.TimeInfo timeInfo;
    @XmlElement(name = "Boundary")
    protected List<Boundaries.Boundary> boundary;
    @XmlElement(name = "ForbiddenBoundaryIds")
    protected List<Boundaries.ForbiddenBoundaryIds> forbiddenBoundaryIds;
    @XmlElement(name = "Log")
    protected List<Boundaries.Log> log;

    /**
     * Gets the value of the userName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getUserName() {
        return userName;
    }

    /**
     * Sets the value of the userName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setUserName(String value) {
        this.userName = value;
    }

    /**
     * Gets the value of the timeInfo property.
     * 
     * @return possible object is {@link Boundaries.TimeInfo }
     * 
     */
    public Boundaries.TimeInfo getTimeInfo() {
        return timeInfo;
    }

    /**
     * Sets the value of the timeInfo property.
     * 
     * @param value
     *            allowed object is {@link Boundaries.TimeInfo }
     * 
     */
    public void setTimeInfo(Boundaries.TimeInfo value) {
        this.timeInfo = value;
    }

    /**
     * Gets the value of the boundary property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the boundary property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getBoundary().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Boundaries.Boundary }
     * 
     * 
     */
    public List<Boundaries.Boundary> getBoundary() {
        if (boundary == null) {
            boundary = new ArrayList<Boundaries.Boundary>();
        }
        return this.boundary;
    }

    /**
     * Gets the value of the forbiddenBoundaryIds property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the forbiddenBoundaryIds property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getForbiddenBoundaryIds().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Boundaries.ForbiddenBoundaryIds }
     * 
     * 
     */
    public List<Boundaries.ForbiddenBoundaryIds> getForbiddenBoundaryIds() {
        if (forbiddenBoundaryIds == null) {
            forbiddenBoundaryIds = new ArrayList<Boundaries.ForbiddenBoundaryIds>();
        }
        return this.forbiddenBoundaryIds;
    }

    /**
     * Gets the value of the log property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the log property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getLog().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Boundaries.Log }
     * 
     * 
     */
    public List<Boundaries.Log> getLog() {
        if (log == null) {
            log = new ArrayList<Boundaries.Log>();
        }
        return this.log;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="BoundaryId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="BoundaryType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="BoundaryMode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="BoundaryLifeSpan" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="BoundaryCreationTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
     *         &lt;element name="BoundaryCreationUtime" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
     *         &lt;element name="BoundaryEditedTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
     *         &lt;element name="BoundaryEditedUtime" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
     *         &lt;element name="BoundaryExpirationTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
     *         &lt;element name="BoundaryExpirationUtime" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
     *         &lt;element name="NumberOfVertices" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="Vertex" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Latitude" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
     *                   &lt;element name="Longitude" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
     *                   &lt;element name="Azimuth" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
     *                   &lt;element name="Speed" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
     *                   &lt;element name="U" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
     *                   &lt;element name="V" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "boundaryId", "boundaryType",
            "boundaryMode", "boundaryLifeSpan", "boundaryCreationTime",
            "boundaryCreationUtime", "boundaryEditedTime",
            "boundaryEditedUtime", "boundaryExpirationTime",
            "boundaryExpirationUtime", "numberOfVertices", "vertex" })
    public static class Boundary {

        @XmlElement(name = "BoundaryId")
        protected Integer boundaryId;
        @XmlElement(name = "BoundaryType")
        protected String boundaryType;
        @XmlElement(name = "BoundaryMode")
        protected String boundaryMode;
        @XmlElement(name = "BoundaryLifeSpan")
        protected Integer boundaryLifeSpan;
        @XmlElement(name = "BoundaryCreationTime")
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar boundaryCreationTime;
        @XmlElement(name = "BoundaryCreationUtime")
        protected Long boundaryCreationUtime;
        @XmlElement(name = "BoundaryEditedTime")
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar boundaryEditedTime;
        @XmlElement(name = "BoundaryEditedUtime")
        protected Long boundaryEditedUtime;
        @XmlElement(name = "BoundaryExpirationTime")
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar boundaryExpirationTime;
        @XmlElement(name = "BoundaryExpirationUtime")
        protected Long boundaryExpirationUtime;
        @XmlElement(name = "NumberOfVertices")
        protected Integer numberOfVertices;
        @XmlElement(name = "Vertex")
        protected List<Boundaries.Boundary.Vertex> vertex;

        /**
         * Gets the value of the boundaryId property.
         * 
         * @return possible object is {@link Integer }
         * 
         */
        public Integer getBoundaryId() {
            return boundaryId;
        }

        /**
         * Sets the value of the boundaryId property.
         * 
         * @param value
         *            allowed object is {@link Integer }
         * 
         */
        public void setBoundaryId(Integer value) {
            this.boundaryId = value;
        }

        /**
         * Gets the value of the boundaryType property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getBoundaryType() {
            return boundaryType;
        }

        /**
         * Sets the value of the boundaryType property.
         * 
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setBoundaryType(String value) {
            this.boundaryType = value;
        }

        /**
         * Gets the value of the boundaryMode property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getBoundaryMode() {
            return boundaryMode;
        }

        /**
         * Sets the value of the boundaryMode property.
         * 
         * @param value
         *            allowed object is {@link String }
         * 
         */
        public void setBoundaryMode(String value) {
            this.boundaryMode = value;
        }

        /**
         * Gets the value of the boundaryLifeSpan property.
         * 
         * @return possible object is {@link Integer }
         * 
         */
        public Integer getBoundaryLifeSpan() {
            return boundaryLifeSpan;
        }

        /**
         * Sets the value of the boundaryLifeSpan property.
         * 
         * @param value
         *            allowed object is {@link Integer }
         * 
         */
        public void setBoundaryLifeSpan(Integer value) {
            this.boundaryLifeSpan = value;
        }

        /**
         * Gets the value of the boundaryCreationTime property.
         * 
         * @return possible object is {@link XMLGregorianCalendar }
         * 
         */
        public XMLGregorianCalendar getBoundaryCreationTime() {
            return boundaryCreationTime;
        }

        /**
         * Sets the value of the boundaryCreationTime property.
         * 
         * @param value
         *            allowed object is {@link XMLGregorianCalendar }
         * 
         */
        public void setBoundaryCreationTime(XMLGregorianCalendar value) {
            this.boundaryCreationTime = value;
        }

        /**
         * Gets the value of the boundaryCreationUtime property.
         * 
         * @return possible object is {@link Long }
         * 
         */
        public Long getBoundaryCreationUtime() {
            return boundaryCreationUtime;
        }

        /**
         * Sets the value of the boundaryCreationUtime property.
         * 
         * @param value
         *            allowed object is {@link Long }
         * 
         */
        public void setBoundaryCreationUtime(Long value) {
            this.boundaryCreationUtime = value;
        }

        /**
         * Gets the value of the boundaryEditedTime property.
         * 
         * @return possible object is {@link XMLGregorianCalendar }
         * 
         */
        public XMLGregorianCalendar getBoundaryEditedTime() {
            return boundaryEditedTime;
        }

        /**
         * Sets the value of the boundaryEditedTime property.
         * 
         * @param value
         *            allowed object is {@link XMLGregorianCalendar }
         * 
         */
        public void setBoundaryEditedTime(XMLGregorianCalendar value) {
            this.boundaryEditedTime = value;
        }

        /**
         * Gets the value of the boundaryEditedUtime property.
         * 
         * @return possible object is {@link Long }
         * 
         */
        public Long getBoundaryEditedUtime() {
            return boundaryEditedUtime;
        }

        /**
         * Sets the value of the boundaryEditedUtime property.
         * 
         * @param value
         *            allowed object is {@link Long }
         * 
         */
        public void setBoundaryEditedUtime(Long value) {
            this.boundaryEditedUtime = value;
        }

        /**
         * Gets the value of the boundaryExpirationTime property.
         * 
         * @return possible object is {@link XMLGregorianCalendar }
         * 
         */
        public XMLGregorianCalendar getBoundaryExpirationTime() {
            return boundaryExpirationTime;
        }

        /**
         * Sets the value of the boundaryExpirationTime property.
         * 
         * @param value
         *            allowed object is {@link XMLGregorianCalendar }
         * 
         */
        public void setBoundaryExpirationTime(XMLGregorianCalendar value) {
            this.boundaryExpirationTime = value;
        }

        /**
         * Gets the value of the boundaryExpirationUtime property.
         * 
         * @return possible object is {@link Long }
         * 
         */
        public Long getBoundaryExpirationUtime() {
            return boundaryExpirationUtime;
        }

        /**
         * Sets the value of the boundaryExpirationUtime property.
         * 
         * @param value
         *            allowed object is {@link Long }
         * 
         */
        public void setBoundaryExpirationUtime(Long value) {
            this.boundaryExpirationUtime = value;
        }

        /**
         * Gets the value of the numberOfVertices property.
         * 
         * @return possible object is {@link Integer }
         * 
         */
        public Integer getNumberOfVertices() {
            return numberOfVertices;
        }

        /**
         * Sets the value of the numberOfVertices property.
         * 
         * @param value
         *            allowed object is {@link Integer }
         * 
         */
        public void setNumberOfVertices(Integer value) {
            this.numberOfVertices = value;
        }

        /**
         * Gets the value of the vertex property.
         * 
         * <p>
         * This accessor method returns a reference to the live list, not a
         * snapshot. Therefore any modification you make to the returned list
         * will be present inside the JAXB object. This is why there is not a
         * <CODE>set</CODE> method for the vertex property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * 
         * <pre>
         * getVertex().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Boundaries.Boundary.Vertex }
         * 
         * 
         */
        public List<Boundaries.Boundary.Vertex> getVertex() {
            if (vertex == null) {
                vertex = new ArrayList<Boundaries.Boundary.Vertex>();
            }
            return this.vertex;
        }

        /**
         * <p>
         * Java class for anonymous complex type.
         * 
         * <p>
         * The following schema fragment specifies the expected content
         * contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Latitude" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
         *         &lt;element name="Longitude" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
         *         &lt;element name="Azimuth" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
         *         &lt;element name="Speed" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
         *         &lt;element name="U" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
         *         &lt;element name="V" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = { "latitude", "longitude", "azimuth",
                "speed", "u", "v" })
        public static class Vertex {

            @XmlElement(name = "Latitude")
            protected Float latitude;
            @XmlElement(name = "Longitude")
            protected Float longitude;
            @XmlElement(name = "Azimuth")
            protected Float azimuth;
            @XmlElement(name = "Speed")
            protected Float speed;
            @XmlElement(name = "U")
            protected Float u;
            @XmlElement(name = "V")
            protected Float v;

            /**
             * Gets the value of the latitude property.
             * 
             * @return possible object is {@link Float }
             * 
             */
            public Float getLatitude() {
                return latitude;
            }

            /**
             * Sets the value of the latitude property.
             * 
             * @param value
             *            allowed object is {@link Float }
             * 
             */
            public void setLatitude(Float value) {
                this.latitude = value;
            }

            /**
             * Gets the value of the longitude property.
             * 
             * @return possible object is {@link Float }
             * 
             */
            public Float getLongitude() {
                return longitude;
            }

            /**
             * Sets the value of the longitude property.
             * 
             * @param value
             *            allowed object is {@link Float }
             * 
             */
            public void setLongitude(Float value) {
                this.longitude = value;
            }

            /**
             * Gets the value of the azimuth property.
             * 
             * @return possible object is {@link Float }
             * 
             */
            public Float getAzimuth() {
                return azimuth;
            }

            /**
             * Sets the value of the azimuth property.
             * 
             * @param value
             *            allowed object is {@link Float }
             * 
             */
            public void setAzimuth(Float value) {
                this.azimuth = value;
            }

            /**
             * Gets the value of the speed property.
             * 
             * @return possible object is {@link Float }
             * 
             */
            public Float getSpeed() {
                return speed;
            }

            /**
             * Sets the value of the speed property.
             * 
             * @param value
             *            allowed object is {@link Float }
             * 
             */
            public void setSpeed(Float value) {
                this.speed = value;
            }

            /**
             * Gets the value of the u property.
             * 
             * @return possible object is {@link Float }
             * 
             */
            public Float getU() {
                return u;
            }

            /**
             * Sets the value of the u property.
             * 
             * @param value
             *            allowed object is {@link Float }
             * 
             */
            public void setU(Float value) {
                this.u = value;
            }

            /**
             * Gets the value of the v property.
             * 
             * @return possible object is {@link Float }
             * 
             */
            public Float getV() {
                return v;
            }

            /**
             * Sets the value of the v property.
             * 
             * @param value
             *            allowed object is {@link Float }
             * 
             */
            public void setV(Float value) {
                this.v = value;
            }

        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ForbiddenId" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "forbiddenId" })
    public static class ForbiddenBoundaryIds {

        @XmlElement(name = "ForbiddenId")
        protected List<String> forbiddenId;

        /**
         * Gets the value of the forbiddenId property.
         * 
         * <p>
         * This accessor method returns a reference to the live list, not a
         * snapshot. Therefore any modification you make to the returned list
         * will be present inside the JAXB object. This is why there is not a
         * <CODE>set</CODE> method for the forbiddenId property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * 
         * <pre>
         * getForbiddenId().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getForbiddenId() {
            if (forbiddenId == null) {
                forbiddenId = new ArrayList<String>();
            }
            return this.forbiddenId;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Comment" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "comment" })
    public static class Log {

        @XmlElement(name = "Comment")
        protected List<String> comment;

        /**
         * Gets the value of the comment property.
         * 
         * <p>
         * This accessor method returns a reference to the live list, not a
         * snapshot. Therefore any modification you make to the returned list
         * will be present inside the JAXB object. This is why there is not a
         * <CODE>set</CODE> method for the comment property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * 
         * <pre>
         * getComment().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getComment() {
            if (comment == null) {
                comment = new ArrayList<String>();
            }
            return this.comment;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="FileCreationTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *         &lt;element name="FileCreationUtime" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "fileCreationTime", "fileCreationUtime" })
    public static class TimeInfo {

        @XmlElement(name = "FileCreationTime", required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar fileCreationTime;
        @XmlElement(name = "FileCreationUtime")
        protected long fileCreationUtime;

        /**
         * Gets the value of the fileCreationTime property.
         * 
         * @return possible object is {@link XMLGregorianCalendar }
         * 
         */
        public XMLGregorianCalendar getFileCreationTime() {
            return fileCreationTime;
        }

        /**
         * Sets the value of the fileCreationTime property.
         * 
         * @param value
         *            allowed object is {@link XMLGregorianCalendar }
         * 
         */
        public void setFileCreationTime(XMLGregorianCalendar value) {
            this.fileCreationTime = value;
        }

        /**
         * Gets the value of the fileCreationUtime property.
         * 
         */
        public long getFileCreationUtime() {
            return fileCreationUtime;
        }

        /**
         * Sets the value of the fileCreationUtime property.
         * 
         */
        public void setFileCreationUtime(long value) {
            this.fileCreationUtime = value;
        }

    }

}
