name: update station info

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *" 

jobs:
  update_ndm:
    runs-on: ubuntu-latest
    environment:
      name: VLAB
    steps:
      # Checkout this repo
      # this gets the latest code (and is run on the default branch)
      - name: Checkout awips2
        uses: actions/checkout@v3
      # Do individual pulls for all the files in the ndm directory
      - name: Pull latest from vlab svn repo
        run: |
          cd rpms/awips2.edex/Installer.edex/ndm/
          for file in *; do
            svn export --force https://vlab.noaa.gov/svn/awips-ndm/trunk/"$file" --username ${{ secrets.VLAB_UNAME }} --password ${{ secrets.VLAB_PASS }}
          done
      # Check in all the new files
      # Do we need to check for a change or can we just run a git add?
      - name: Update existing NDM files for awips2 repo
        run: |
          date=`date +%Y%m%d-%H:%M:%S`
          git config user.name $GITHUB_ACTOR
          git config user.email $GITHUB_ACTOR@users.noreply.github.com
          git add --all
          git commit -m "New NDM updates on $date - autogenerated" 
          git push
