#!/bin/sh

# This software was developed and / or modified by Raytheon Company,
# pursuant to Contract DG133W-05-CQ-1067 with the US Government.
# 
# U.S. EXPORT CONTROLLED TECHNICAL DATA
# This software product contains export-restricted data whose
# export/transfer/disclosure is restricted by U.S. law. Dissemination
# to non-U.S. persons whether in the United States or abroad requires
# an export license or other authorization.
# 
# Contractor Name:        Raytheon Company
# Contractor Address:     6825 Pine Street, Suite 340
#                         Mail Stop B8
#                         Omaha, NE 68106
#                         402.291.0100
# 
# See the AWIPS II Master Rights File ("Master Rights File.pdf") for
# further licensing information.
#
#
# SOFTWARE HISTORY
# Date         Ticket#    Engineer    Description
# ------------ ---------- ----------- --------------------------
# Feb 07, 2014  #2509     dgilling    Fix baseline merge issue.
#
#


# get path to cave
path_to_script=`readlink -f $0`
RUN_FROM_DIR=`dirname $path_to_script`

# cave directory
CAVE_DIR=/awips2/cave

# execute the runProcedure module
_GFECLI="${RUN_FROM_DIR}/gfeclient.sh"
_MODULE="${RUN_FROM_DIR}/src/ifpimage/PngWriter.py"

# quoting of '$@' is used to prevent command line interpretation
if [ ! -f $_GFECLI ] || [ ! -d $CAVE_DIR ]
then
  echo "CAVE and/or gfeclient not installed on this workstation ..exiting"
  exit 1
else
  $_GFECLI $_MODULE "$@"
fi

