#!/bin/sh
#****************************************************************************
#* NCSA HDF                                                                 *
#* National Comptational Science Alliance                                   *
#* University of Illinois at Urbana-Champaign                               *
#* 605 E. Springfield, Champaign IL 61820                                   *
#*                                                                          *
#* For conditions of distribution and use, see the accompanying             *
#* java-hdf5/COPYING file.                                                  *
#*                                                                          *
#****************************************************************************/

##  These paths are taken from the configure for the Make
##  This program checks that the libraries are installed
##  in these paths.
##
##  Edit these paths to debug
##

RM=/bin/rm
JHVINSTALLDIR=.

LIBDIR=$JHVINSTALLDIR"/lib"

CLASSPATH=".:"$LIBDIR"/jhdf.jar"

LD_LIBRARY_PATH=$LIBDIR"/linux"

export CLASSPATH
export LD_LIBRARY_PATH

$RM -f test.hdf
/common/awips/jdk1.6.0_05/bin/java -Djava.library.path=$LD_LIBRARY_PATH TestHDF4Link
$RM -f test.hdf
